### ISSUE TITLE
SassError: SassError: Undefined variable.

### ISSUE THREAD

**Issue by telangY** [jdf2e/nutui-react#1005]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.5.4

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.19.1

### Browser and its version（浏览器及其版本）
chrome(113.0.5672.93)

### System and its version（系统及其版本）
windows11

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.6

  Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.19.1 - D:\Program Files\nodejs\node.EXE
      npm: 8.19.3 - D:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6 
      @tarojs/components: 3.6.6 => 3.6.6 
      @tarojs/helper: 3.6.6 => 3.6.6 
      @tarojs/plugin-framework-react: 3.6.6 => 3.6.6 
      @tarojs/plugin-html: ^3.6.6 => 3.6.6 
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6 
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6
      @tarojs/react: 3.6.6 => 3.6.6
      @tarojs/runtime: 3.6.6 => 3.6.6
      @tarojs/shared: 3.6.6 => 3.6.6
      @tarojs/taro: 3.6.6 => 3.6.6
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6
      babel-preset-taro: 3.6.6 => 3.6.6
      eslint-config-taro: 3.6.6 => 3.6.6
      react: ^18.0.0 => 18.0.0

### Reproduction link（重现链接）
[stackblitz.com](https://stackblitz.com/edit/webpack-webpack-js-org-bmddyc?file=package.json)

### Steps to reproduce（重现步骤）
与官方例子显示一样的错误

### What is expected?（期望的结果是什么？）
引入成功

### What is actually happening?（实际的结果是什么？）
引入错误  官网 babel 按需加载例子缺少 引入 sass varibale

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-demo/tree/master/react-taro

用这个例子 试试。
或者 taro cli 选 nutui-react 模板。

**Comment by oasis-cloud** [comment]
<img width="1725" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/8a428f29-c911-4f8b-8b45-75ea387594cb">

**Comment by auroramy** [comment]
好的

>

**Comment by telangY** [comment]
> https://github.com/jdf2e/nutui-demo/tree/master/react-taro
> 
> 用这个例子 试试。 或者 taro cli 选 nutui-react 模板。

好的  目前已经解决了
