### ISSUE TITLE
AvatarGroup 组件使用报错

### ISSUE THREAD

**Issue by lpfdazr** [jdf2e/nutui-react#1010]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.5.4

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
v20.1.0

### Browser and its version（浏览器及其版本）
 Chrome(111.0.5563.64（正式版本） （64 位）)

### System and its version（系统及其版本）
Window10 pro(Windows 10 专业版)

### Taro environmental information（taro 环境信息）
 Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 20.1.0 - D:\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.4 - D:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6
      @tarojs/components: 3.6.6 => 3.6.6
      @tarojs/helper: 3.6.6 => 3.6.6
      @tarojs/plugin-framework-react: 3.6.6 => 3.6.6
      @tarojs/plugin-html: ^3.6.6 => 3.6.6
      @tarojs/plugin-platform-alipay: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-jd: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-qq: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-swan: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-tt: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6
      @tarojs/react: 3.6.6 => 3.6.6
      @tarojs/runtime: 3.6.6 => 3.6.6
      @tarojs/shared: 3.6.6 => 3.6.6
      @tarojs/taro: 3.6.6 => 3.6.6
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6
      babel-preset-taro: 3.6.6 => 3.6.6
      eslint-config-taro: 3.6.6 => 3.6.6
      react: ^18.0.0 => 18.2.0

### Reproduction link（重现链接）
[gitee.com](https://gitee.com/zhaoruixiaogongzhu/app.git)

### Steps to reproduce（重现步骤）
运行工程就会报错,一个是添加组件报错，一个是工程启动时报错。
![0bcd80b9737c3a4f9306e611cc2f285](https://github.com/jdf2e/nutui-react/assets/129744500/f5f61d4e-48d2-483b-9d01-40833d7c56d2)
![37a59c05e4d1200a2d3bfc16ca7700b](https://github.com/jdf2e/nutui-react/assets/129744500/77d4b65f-5ab4-4e7d-beee-59a3d449f26d)
### What is expected?（期望的结果是什么？）
能够找出问题所在并解决

**Comment by oasis-cloud** [comment]
重现链接访问受限

**Comment by lpfdazr** [comment]
公开了

**Comment by lpfdazr** [comment]
> 重现链接访问受限

公开了

**Comment by lpfdazr** [comment]
![image](https://github.com/jdf2e/nutui-react/assets/129744500/845cf225-8047-4b94-bf23-1d22638b8d9a)
![image](https://github.com/jdf2e/nutui-react/assets/129744500/c4116c26-0c8d-4bba-a063-f867d91da93b)

**Comment by oasis-cloud** [comment]
可以参考 taro 的 issue：https://github.com/NervJS/taro/issues/13767。降级 taro 相关内容到 3.6.5。

{
  "name": "App",
  "version": "1.0.0",
  "private": true,
  "description": "",
  "templateInfo": {
    "name": "redux",
    "typescript": true,
    "css": "sass"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:jd": "taro build --type jd",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:jd": "npm run build:jd -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch"
  },
  "browserslist": [
    "last 3 versions",
    "Android >= 4.1",
    "ios >= 8"
  ],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@nutui/nutui-react-taro": "^1.5.4",
    "@tarojs/components": "3.6.5",
    "@tarojs/helper": "3.6.5",
    "@tarojs/plugin-framework-react": "3.6.5",
    "@tarojs/plugin-html": "^3.6.5",
    "@tarojs/plugin-platform-alipay": "3.6.5",
    "@tarojs/plugin-platform-h5": "3.6.5",
    "@tarojs/plugin-platform-jd": "3.6.5",
    "@tarojs/plugin-platform-qq": "3.6.5",
    "@tarojs/plugin-platform-swan": "3.6.5",
    "@tarojs/plugin-platform-tt": "3.6.5",
    "@tarojs/plugin-platform-weapp": "3.6.5",
    "@tarojs/react": "3.6.5",
    "@tarojs/runtime": "3.6.5",
    "@tarojs/shared": "3.6.5",
    "@tarojs/taro": "3.6.5",
    "babel-plugin-import": "^1.13.6",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
    "@tarojs/cli": "3.6.5",
    "@tarojs/webpack5-runner": "3.6.5",
    "@types/node": "^18.15.11",
    "@types/react": "^18.0.0",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "@typescript-eslint/parser": "^5.20.0",
    "babel-preset-taro": "3.6.5",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.6.5",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "postcss": "^8.4.18",
    "react-refresh": "^0.11.0",
    "stylelint": "9.3.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.1.0",
    "webpack": "^5.78.0"
  },
  "resolutions": {
    "@types/react": "^17.0.2",
    "@swc/core": "1.3.42"
  }
}
，通过 yarn install，测试无报错

**Comment by lpfdazr** [comment]
> 可以参考 taro 的 issue：[https://github.com/NervJS/taro/issues/13767。降级](https://github.com/NervJS/taro/issues/13767%E3%80%82%E9%99%8D%E7%BA%A7) taro 相关内容到 3.6.5。
> 
> {“名称”： “应用程序”， “版本”： “1.0.0”， “私有”： true， “描述”： “”， “模板信息”： { “名称”： “redux”， “typescript”： true， “css”： “sass” }， “scripts”： { “build：weapp”： “taro build --type weapp”， “build：swan”： “taro build --type swan”， “build：支付宝”： “taro build --type alipay”， “build：tt”： “taro build --type tt”， “build：h5”： “taro build --type H5”， “build：rn”： “taro build --type rn”， “build：qq”： “taro build --type qq”， “build：jd”： “taro build --type jd”， “build：quickapp”： “taro build --type quickapp”， “dev：weapp”： “npm run build：weapp -- --watch”， “dev：swan”： “npm run build：swan -- --watch”， “dev：alipay”： “npm run build：支付宝-- --watch”， “dev：tt”： “npm run build：TT -- --watch“， ”dev：h5“： ”npm run build：h5 -- --watch“， ”dev：rn“： ”npm run build：rn -- --watch“， ”dev：qq“： ”npm run build：qq -- --watch“， ”dev：jd“： ”npm run build：jd -- --watch“， ”dev：quickapp“： ”npm run build：quickapp -- --watch“ }， ”browserslist“： [ ”最近 3 个版本“， ”Android >= 4.1“， ”iOS >= 8“ ]， ”作者“： ”“， “license”： “MIT”， “dependencies”： { “@babel/runtime”： “^7.7.7”， “@nutui/nutui-react-taro”： “^1.5.4”， “@tarojs/components”： “3.6.5”， “@tarojs/helper”： “3.6.5”， “@tarojs/plugin-framework-react”： “3.6.5”， “@tarojs/plugin-html”： “^3.6.5”， “@tarojs/plugin-platform-alipay”： “3.6.5”， “@tarojs/plugin-platform-h5”： “3.6.5”， “@tarojs/plugin-platform-jd“： ”3.6.5“， ”@tarojs/plugin-platform-qq“： ”3.6.5“， ”@tarojs/plugin-platform-swan“： ”3.6.5“， ”@tarojs/plugin-platform-tt“： ”3.6.5“， ”@tarojs/plugin-platform-weapp“： ”3.6.5“， ”@tarojs/react“： ”3.6.5“， ”@tarojs/运行时“： ”3.6.5“， ”@tarojs/共享“： ”3.6.5“， ”@tarojs/taro“： ”3.6.5“， ”babel-plugin-import“： ”^1.13.6“， ”反应“： ”^18.0.0“， ”react-dom“： ”^18.0.0“， ”react-redux“： ”^7.2.0“， ”redux“： ”^4.0.0“， ”redux-logger“： ”^3.0.6“， ”redux-thunk“： ”^2.3.0“ }， ”devDependencies“： { ”@babel/core“： ”^7.8.0“， ”@pmmmwh/react-refresh-webpack-plugin“： ”^0.5.5“， ”@tarojs/cli“： ”3.6.5“， ”@tarojs/webpack5-runner“： ”3.6.5“， ”@types/节点“： ”^18.15.11“， “@types/react”： “^18.0.0”， “@types/webpack-env”： “^1.13.6”， “@typescript-eslint/eslint-plugin”： “^5.20.0”， “@typescript-eslint/parser”： “^5.20.0”， “babel-preset-taro”： “3.6.5”， “eslint”： “^8.12.0”， “eslint-config-taro”： “3.6.5”， “eslint-plugin-import”： “^2.12.0”， “eslint-plugin-react”： “^7.8.2”， “eslint-plugin-react-hooks”： “^4.2.0”， “postcss”： “^8.4.18”， “react-refresh”： “^0.11.0”， “stylelint”： “9.3.0”， “ts-node”： “^10.9.1”， “typescript”： “^4.1.0”， “webpack”： “^5.78.0” }， “resolution”： { “@types/react”： “^17.0.2”， “@swc/core”： “1.3.42” } } ，通过 yarn install，测试无报错

谢谢咯
