### ISSUE TITLE
Cell组件的desc属性支持布局，left center right

### ISSUE THREAD

**Issue by wangyuan0108** [jdf2e/nutui-react#1016]
### What problem does this feature solve?（这个功能解决的问题）
和Input合用的时候值对齐

### What does the proposed API look like?（期望的 API）
descAlign = left center right

**Comment by xiaoyatong** [comment]
辛苦截图、demo

**Comment by wangyuan0108** [comment]
<img width="364" alt="image" src="https://github.com/jdf2e/nutui-react/assets/22407253/17a34a32-f216-4f0e-ba66-53a6824005fa">

右侧的描述能在左侧，可以和input的提示对其布局

**Comment by xiaoyatong** [comment]
这个看了下，目前不会考虑添加 align，目前左侧标题部分 有一个最大宽度的设置。
我觉得我们会增加一个list 这样的组件，来实现你的这个功能。
还在盘点中。
