### ISSUE TITLE
Cell支持嵌入Input，但是padding值和下边都不可更改

### ISSUE THREAD

**Issue by wangyuan0108** [jdf2e/nutui-react#1017]
### What problem does this feature solve?（这个功能解决的问题）
组合使用

### What does the proposed API look like?（期望的 API）
支持合用

**Comment by xiaoyatong** [comment]
辛苦截图 demo

**Comment by wangyuan0108** [comment]
<img width="364" alt="image" src="https://github.com/jdf2e/nutui-react/assets/22407253/419e13cb-11c1-427a-9688-2f63833951ac">

padding和下边线不好处理，其实等于就是Form组件差不多

**Comment by oasis-cloud** [comment]
可直接自定义 className 来进行处理
