### ISSUE TITLE
Calendar 日历组件上下滑动回弹(你们的组件库文档写的示例上下滑动回弹都会回弹)

### ISSUE THREAD

**Issue by hy916** [jdf2e/nutui-react#1025]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-react version（nutui-react 版本）
1.5.4

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.0

### Browser and its version（浏览器及其版本）
Chrome 版本 113.0.5672.63（正式版本） (arm64)

### System and its version（系统及其版本）
macOS(13.3.1)

### Taro environmental information（taro 环境信息）
3.6.6

### Reproduction link（重现链接）
[nutui.jd.com/taro/react/1x/](https://nutui.jd.com/taro/react/1x/#/zh-CN/component/calendar)

### Steps to reproduce（重现步骤）
最简洁的方式：打开你们的文档网站：https://nutui.jd.com/taro/react/1x/#/zh-CN/component/calendar
随便点一个日历示例上下滚动日历（往上翻动月份或者往下翻动月份），你会发现都会弹回当前月份。

### What is expected?（期望的结果是什么？）
上下滚动日历不会回弹到当前月份

### What is actually happening?（实际的结果是什么？）
上下滚动日历会回弹到当前月份

### Remarks（补充说明）
所有开发的小伙伴都测试了 都会有这个问题。。

**Comment by hy916** [comment]
<img width="620" alt="image" src="https://github.com/jdf2e/nutui-react/assets/32630937/9ea874f0-7fc2-4cfb-8741-056f7b64e6e2">


你们的文档示例一样会回弹。不管你怎么滚动 一直回弹停留在5-6月份

**Comment by dongdongtian** [comment]
修复了么？ 我目前企业微信小程序用这个组件也遇到回弹了
