### ISSUE TITLE
react  nutui component textarea bind Value not work

### ISSUE THREAD

**Issue by linshuizhaoying** [jdf2e/nutui-react#103]
example:
  const [content, setContent] = useState('')
 <TextArea className='textarea' defaultValue={content} onChange={(e) => {
              console.log('e', e)
            }} limitShow maxlength='20' />

change value 123
console.log('content', content) => ''

**Comment by oasis-cloud** [comment]
可以提供完整的示例吗？

**Comment by vickyYE** [comment]
请注意下react版本的示例，
example:
const [content, setContent] = useState('')
const changeContent = (value: any, event: Event) => {
    console.log('content', value, content)
    setContent(value)
  }
<TextArea
          className="textarea"
          defaultValue={content}
          change={(value, e) => {
            console.log('e', e)
            changeContent(value, e)
          }}
          maxlength="20"
        />

**Comment by vickyYE** [comment]
后期会同步成onChange事件

**Comment by vickyYE** [comment]
目前change事件用的是change，
example:
const [content, setContent] = useState('')
const changeContent = (value: any, event: Event) => {
console.log('content', value, content)
setContent(value)
}
<TextArea
className="textarea"
defaultValue={content}
change={(value, e) => {
console.log('e', e)
changeContent(value, e)
}}
maxlength="20"
/>

 ## 1.1.5 版本会移除 change 更换为 onChange

**Comment by vickyYE** [comment]
> 

1.1.5 版本移除 change 更换为 onChange
