### ISSUE TITLE
datePicker卡死，不可交互

### ISSUE THREAD

**Issue by leij1ang** [jdf2e/nutui-react#1043]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-react version（nutui-react 版本）
2.0.0-alpha.10

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.20.0

### Browser and its version（浏览器及其版本）
chrome(113.0.5672.127)

### System and its version（系统及其版本）
window10

### Steps to reproduce（重现步骤）
有两种情况
一： minDate={new Date()}，无限触发onChange
二：如minDate为2000-2-1,首先滚动到2001-1-1，随后再滚动年份为2000就会卡死，月份未滚动到2月，无限触发onChange
猜测maxDate也会有类似情景，未测试

### What is expected?（期望的结果是什么？）
不会出现卡死，且滚动年/月，会判断当前日期是否低于minDate，如果是则自动调整日期

### What is actually happening?（实际的结果是什么？）
卡死

**Comment by xiaoyatong** [comment]
datepicker 2.0 在开发中。会关注您的问题。

**Comment by leij1ang** [comment]
@xiaoyatong 拉了代码到本地run dev，对应版本是`2.0.0-alpha.16`，设置了startDate 为 6.13，滚动到7月时，13日之前的日期仍然不可选择
<img width="396" alt="image" src="https://github.com/jdf2e/nutui-react/assets/20677914/f0341e53-51d7-4a39-ae92-0fb985a60760">
