### ISSUE TITLE
[WXML Runtime warning] 虚拟列表组件无法正确显示： ./base.wxml  Template `tmpl_0_div` not found

### ISSUE THREAD

**Issue by mdddj** [jdf2e/nutui-react#1081]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.0-alpha.13

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
19.8.1

### Browser and its version（浏览器及其版本）
 微信小程序浏览器

### System and its version（系统及其版本）
 Macos 13.4

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.5

  Taro CLI 3.6.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.8.1 - /usr/local/bin/node
      npm: 9.6.4 - ~/Library/pnpm/npm
    npmPackages:
      @tarojs/cli: 3.6.5 => 3.6.5 
      @tarojs/components: 3.6.5 => 3.6.5 
      @tarojs/helper: 3.6.5 => 3.6.5 
      @tarojs/plugin-framework-react: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-alipay: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-h5: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-jd: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-qq: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-swan: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-tt: 3.6.5 => 3.6.5 
      @tarojs/plugin-platform-weapp: 3.6.5 => 3.6.5 
      @tarojs/react: 3.6.5 => 3.6.5 
      @tarojs/runtime: 3.6.5 => 3.6.5 
      @tarojs/shared: 3.6.5 => 3.6.5 
      @tarojs/taro: 3.6.5 => 3.6.5 
      @tarojs/webpack5-runner: 3.6.5 => 3.6.5 
      babel-preset-taro: 3.6.5 => 3.6.5 
      eslint-config-taro: 3.6.5 => 3.6.5 
      react: ^18.0.0 => 18.0.0 

### Reproduction link（重现链接）
[github.com/mdddj/nutui-bug-01](https://github.com/mdddj/nutui-bug-01)

### Steps to reproduce（重现步骤）
pnpm run build:weapp

微信开发者工具打开 dist目录

查看console 控制台

相关代码在`pages/index/index.tsx`

### What is expected?（期望的结果是什么？）
正常显示组件内容

### What is actually happening?（实际的结果是什么？）
无法显示组件内容

截图：
<img width="1128" alt="image" src="https://github.com/jdf2e/nutui-react/assets/29020213/6f46e71a-0cee-4adb-9fa4-7cc073a1aa07">

`index.tsx`

```javascript
import { View, Text } from '@tarojs/components'
import { useLoad } from '@tarojs/taro'
import './index.less'
import React, {useCallback, useEffect, useState} from "react";
import {VirtualList} from "@nutui/nutui-react";

export default function Index() {
  const [sourceData, setsourceData] = useState([])
  const [pageNo, setPageNo] = useState(1)
  const getData = useCallback(() => {
    const datas = []
    const pageSize = 90
    for (let i = 10; i < pageSize; i++) {
      datas.push(`${i} Item`)
    }
    setsourceData((sourceData) => {
      return [...sourceData, ...datas]
    })
  }, [])
  const onScroll = () => {
    if (pageNo > 100) return
    setPageNo(pageNo + 1)
  }
  useEffect(() => {
    getData()
  }, [getData])
  const ItemVariable = ({ data, index }) => {
    return (
      <p className={index % 2 === 0 ? '' : 'nut-virtualList-demo-item'}>可变大小隔行展示-{data}</p>
    )
  }
  /** itemSize为首屏最大元素大小 */
  const ItemVariableDemo = React.memo(ItemVariable)
  useLoad(() => {
    console.log('Page loaded.')
  })

  return (
    <View className='index'>
      <Text>Hello world!</Text>
      <div className='nut-virtualList-demo-box  hideScrollbar heigh1'>
        <VirtualList
          sourceData={sourceData}
          ItemRender={ItemVariableDemo}
          itemSize={128}
          itemEqualSize={false}
          onScroll={onScroll}
        />
      </div>
    </View>
  )
}

```

报错内容
```
[WXML Runtime warning] ./base.wxml
 Template `tmpl_0_div` not found.
  143 | 
  144 | <template name="tmpl_1_container">
> 145 |   <template is="{{xs.a(1, i.nn, l)}}" data="{{i:i,cid:1,l:xs.f(l,i.nn)}}" />
      |                ^
  146 | </template>
  147 | 
  148 | <template name="tmpl_2_0">
```

**Comment by oasis-cloud** [comment]
从提供的 demo 来看，需要安装 @tarojs/plugin-html，并在 config/index.js 中添加配置：`plugins: ['@tarojs/plugin-html'],`。
如果需要使用 nutui-react-taro 的样式，可以通过 安装 babel-plugin-import 插件，在 babel.config.js 中增加配置：
```
  plugins: [
    [
      "import",
      {
        "libraryName": "@nutui/nutui-react-taro",
        "libraryDirectory": "dist/esm",
        "style": 'css',
        "camel2DashComponentName": false
      },
      'nutui-react-taro'
    ]
  ]
```

可以查看 nutui-react-taro 的文档，获得更多的说明信息

**Comment by mdddj** [comment]
感谢大佬回复，我试试

**Comment by CODEOrz** [comment]
> 从提供的 demo 来看，需要安装 @tarojs/plugin-html，并在 config/index.js 中添加配置：`plugins: ['@tarojs/plugin-html'],`。 如果需要使用 nutui-react-taro 的样式，可以通过 安装 babel-plugin-import 插件，在 babel.config.js 中增加配置：
> 
> ```
>   plugins: [
>     [
>       "import",
>       {
>         "libraryName": "@nutui/nutui-react-taro",
>         "libraryDirectory": "dist/esm",
>         "style": 'css',
>         "camel2DashComponentName": false
>       },
>       'nutui-react-taro'
>     ]
>   ]
> ```
> 
> 可以查看 nutui-react-taro 的文档，获得更多的说明信息

同样的问题，在使用Picker组件时遇到，添加@tarojs/plugin-html后无效。

**Comment by CODEOrz** [comment]
> 感谢大佬回复，我试试

请问这个问题有解决吗？

**Comment by cdx111** [comment]
已经使用了@tarojs/plugin-html还是不行

**Comment by cdx111** [comment]
@oasis-cloud

**Comment by VeejaLiu** [comment]
need reopen this issue

**Comment by ONE-0508** [comment]
> > 从提供的 demo 来看，需要安装 @tarojs/plugin-html，并在 config/index.js 中添加配置：`plugins: ['@tarojs/plugin-html'],`。 如果需要使用 nutui-react-taro 的样式，可以通过 安装 babel-plugin-import 插件，在 babel.config.js 中增加配置：
> > ```
> >   plugins: [
> >     [
> >       "import",
> >       {
> >         "libraryName": "@nutui/nutui-react-taro",
> >         "libraryDirectory": "dist/esm",
> >         "style": 'css',
> >         "camel2DashComponentName": false
> >       },
> >       'nutui-react-taro'
> >     ]
> >   ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以查看 nutui-react-taro 的文档，获得更多的说明信息
> 
> 同样的问题，在使用Picker组件时遇到，添加@tarojs/plugin-html后无效。

请问解决了吗， 我这边也是遇到这个问题， 添加babel-plugin-import后 并按照文档配置， 还是无法解决
