### ISSUE TITLE
dialog弹窗组件自定义的关闭按钮，关闭后页面还是被锁住

### ISSUE THREAD

**Issue by zhenyulei** [jdf2e/nutui-react#110]
`<Dialog title="" lockScroll={true} visible={dialogShow} closeOnClickOverlay={false}>
            <div className="close-btn" onClick={() => setVisible(false)}></div>
 </Dialog>`

解释一下，相当于关闭弹窗功能和页面的锁定class取消被分成了两个事件。导致关闭了弹窗但是消除锁定class没有生效。

**Comment by yangjinjun3** [comment]
已修复
