### ISSUE TITLE
在非组件文件使用Toast不会隐藏

### ISSUE THREAD

**Issue by Deuscx** [jdf2e/nutui-react#1101]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
2.0.0-alpha.15

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18.15.0

### Browser and its version（浏览器及其版本）
Chrome 100

### System and its version（系统及其版本）
Macos

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/p/sandbox/serene-euclid-nmvzcm?file=%2Fsrc%2Ftoast.ts%3A6%2C1)

### Steps to reproduce（重现步骤）
1.在非组件文件引入 toast
2. 显示toast，不会隐藏

### What is expected?（期望的结果是什么？）
Toast能够隐藏

### What is actually happening?（实际的结果是什么？）
Toast不会隐藏

**Comment by eiinu** [comment]
不应该在 React 函数组件的渲染函数中直接调用 show 方法，这样组件每次重新渲染时都会触发调用。
通过其他交互或者定时器操作中触发 show 方法后，是可以正常隐藏的，支持非组件文件调用。

**Comment by Deuscx** [comment]
@eiinu  你好，目前这边的场景是在useEffect有一个异步请求，然后会toast。此时toast会一直存在，这种应该怎么解决呢

**Comment by eiinu** [comment]
> @eiinu 你好，目前这边的场景是在useEffect有一个异步请求，然后会toast。此时toast会一直存在，这种应该怎么解决呢

1、在严格模式下，React 的 useEffect 方法会执行两次（属于设计 feature，不会在生产环境出现），其中的异步请求应该也执行了两次
2、连续调用两次 Toast.show 会使得 Toast 无法消失（这个是 bug，会尽快修复）

临时解决办法：
关闭严格模式，去掉最外层的 strictMode 组件
