### ISSUE TITLE
1.x Uploader组件 defaultFilelist有值时，文件上传按钮点击后无效，不能选择文件

### ISSUE THREAD

**Issue by bruceeelin** [jdf2e/nutui-react#1108]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.5.8

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(113.0.5672.126)

### System and its version（系统及其版本）
MaxOS(12.5)

### Reproduction link（重现链接）
[codepen.io](https://codepen.io/lin-Bruce/pen/eYQmPmd)

### Steps to reproduce（重现步骤）
属性：
listType: list

接入Uploader这个组件会有几个问题
1. defaultFileList 文档上的类型是 FileItem[], 但是 FileItem这个类没有export出来，无法引用。
  1.1 在项目中这个类型变成了 FileType<string>[]，同时 FileType也没有export出来，无法引用
2. 按照demo上的示例，给defaultFileList组装了一些值后，上传按钮点击后没有效果，当defaultFileList为空时，上传按钮点击就正常
3. 给defaultFileList赋值后，uploader组件能够能正常显示，但点击删除后，使用onChange和onRemove都没有回调
------------------
我看2.0版本上面更新了 defaultValue 和 value属性了，这个操作就是和antd类似，不知道是1.x版本存在问题还是我使用方式不对

### What is expected?（期望的结果是什么？）
传入defaultFileList一个默认值后，uploader组件会显示默认的值，然后，可以选择文件，选择文件后有回调；
删除文件后，能够收到回调

### What is actually happening?（实际的结果是什么？）
选择文件无反应；删除文件没有回调

**Comment by junjun666** [comment]
1.在1.0版本中类型确实没有暴露，只能在示例中先自行定义了。但在2.0版本中我们做了统一处理，会将一些类型声明会统一暴露出来（包括这个FileType）。
2.无论是列表类型还是图片类型，目前逻辑是只有为空时才可以上传，设置了defaultFileList就相当于默认上传了图片，只有先点击删除按钮，将其删除才可以再进行上传，这个是正常的交互逻辑。
3.刚在上传列表展示这一个demo配置了onRemove试了下，点击删除按钮是正常有回调的呢，不知道您那边是怎么配置不生效的呢？
<img width="1418" alt="image" src="https://github.com/jdf2e/nutui-react/assets/35680677/30cfe765-01d9-4abc-b5ad-bab8d91f6eb1">
