### ISSUE TITLE
tabs组件在抖音小程序下无法正常工作

### ISSUE THREAD

**Issue by l11180730** [jdf2e/nutui-react#1136]
版本："@nutui/nutui-react-taro": "^2.0.0-alpha.18"
scroll-view 的flex在抖音下无效

按照官方文档操作长这样
![image](https://github.com/jdf2e/nutui-react/assets/18589562/cb95aa46-293a-4450-aad2-be9a1fd04089)

**Comment by xiaoyatong** [comment]
给下demo
