### ISSUE TITLE
期望react版本日历组件也支持周选择

### ISSUE THREAD

**Issue by wqzwh** [jdf2e/nutui-react#1141]
### What problem does this feature solve?（这个功能解决的问题）
支持周选择

### What does the proposed API look like?（期望的 API）
api可以跟vue版本保持一致

<img width="412" alt="image" src="https://github.com/jdf2e/nutui-react/assets/16662470/bdb215ee-ed84-4eb0-9699-0d54ce416edc">

**Comment by xiaoyatong** [comment]
2.0 加入。
