### ISSUE TITLE
期望Icon图标官方支持使用 base64的方式引用

### ISSUE THREAD

**Issue by yaob421123** [jdf2e/nutui-react#1155]
### What problem does this feature solve?（这个功能解决的问题）
当项目包含多个子项目的时候打包后的生成的icon图标文件路径不对，如果使用base64方式则不会存在 路径问题。base64支持h5、小程序

### What does the proposed API look like?（期望的 API）
api 不变

```js
@font-face {  
  font-family: "iconfont";  
  src: url(data:font/truetype;charset=utf-8;base64,[base64]) format('truetype');  
}
```

**Comment by oasis-cloud** [comment]
2.0 版本仍然支持使用 base64 的方式引入 icon，可以查看官方文档，通过 @nutui/icons-react 或 @nutui/icons-react-taro 来使用
