### ISSUE TITLE
大佬们，2.x的正式版预计啥时候发布呢

### ISSUE THREAD

**Issue by Ruboyq** [jdf2e/nutui-react#1156]
### What problem does this feature solve?（这个功能解决的问题）
大佬们，2.x的正式版预计啥时候发布呢，现在用的2.0.0-beta.1，后续想在生产代码里用2.x的版本，想问下啥时候出正式版

### What does the proposed API look like?（期望的 API）
无

**Comment by Me-UserName** [comment]
群里的消息：这两天应该就发
