### ISSUE TITLE
【2.x】dist/types/index.d.ts 恢复组件 Props 相关类型申明导出

### ISSUE THREAD

**Issue by onlyling** [jdf2e/nutui-react#1181]
### What problem does this feature solve?（这个功能解决的问题）
```tsx
import type { ButtonProps } from '@nutui/nutui-react-taro'
```
在 `2.x` 版本报错，在 dist/types/index.d.ts 文件内未导出类型，升级后增加了许多不必要的更变

### What does the proposed API look like?（期望的 API）
与 1.x 大部分类型导出保持一致。

**Comment by oasis-cloud** [comment]
2.x 主要为了到处更多的类型，供开发者者使用。例如在 actionsheet 组件中提供了 ItemType，在 1.x 中是无法使用 props 中某个属性的类型的。
<img width="657" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/a1305c6b-f003-4d9e-aea1-920df1fa9ac1">

**Comment by onlyling** [comment]
> 2.x 主要为了到处更多的类型，供开发者者使用。例如在 actionsheet 组件中提供了 ItemType，在 1.x 中是无法使用 props 中某个属性的类型的。 <img alt="image" width="657" src="https://user-images.githubusercontent.com/12181600/251114178-a1305c6b-f003-4d9e-aea1-920df1fa9ac1.png">

```tsx
import type { ButtonProps } from '@nutui/nutui-react-taro'
import type { ItemType } from '@nutui/nutui-react-taro/dist/types/packages/actionsheet/actionsheet.taro.d.ts'
```

这两个方式都应当支持，入口文件可以导入组件级 Props，如果需要细节类型，就去某个组件对应的（子）文件导入。
