### ISSUE TITLE
[2.x] InfiniteLoading 滚动加载下滑无反应

### ISSUE THREAD

**Issue by yahuian** [jdf2e/nutui-react#1182]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.0

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.5.0

### Browser and its version（浏览器及其版本）
Version 114.0.5735.199 (Official Build) (64-bit)

### System and its version（系统及其版本）
Windows 10

### Taro environmental information（taro 环境信息）
```
👽 Taro v3.6.7


  Taro CLI 3.6.7 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 18.5.0 - ~/.nvm/versions/node/v18.5.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.5.0/bin/yarn
      npm: 8.12.1 - ~/.nvm/versions/node/v18.5.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.7 => 3.6.7 
      @tarojs/components: 3.6.7 => 3.6.7 
      @tarojs/helper: 3.6.7 => 3.6.7 
      @tarojs/plugin-framework-react: 3.6.7 => 3.6.7 
      @tarojs/plugin-html: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-alipay: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-h5: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-jd: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-qq: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-swan: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-tt: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-weapp: 3.6.7 => 3.6.7 
      @tarojs/react: 3.6.7 => 3.6.7 
      @tarojs/runtime: 3.6.7 => 3.6.7 
      @tarojs/shared: 3.6.7 => 3.6.7 
      @tarojs/taro: 3.6.7 => 3.6.7 
      @tarojs/taro-loader: 3.6.7 => 3.6.7 
      @tarojs/webpack5-runner: 3.6.7 => 3.6.7 
      babel-preset-taro: 3.6.7 => 3.6.7 
      eslint-config-taro: 3.6.7 => 3.6.7 
      react: ^18.0.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 5.0.2
```

### Reproduction link（重现链接）
[github.com](https://github.com/YahuiAn/Taro-NutUI-Demo/tree/master/InfiniteLoading)

### Steps to reproduce（重现步骤）
直接复制 https://nutui.jd.com/taro/react/2x/#/zh-CN/component/infiniteloading 的样例代码，然后测试时发现无法下划加载更多，但是官网上的演示效果是可以的

![chrome_ditJSilj34](https://github.com/jdf2e/nutui-react/assets/39142491/db364ef1-6186-409f-8447-88ce23556f4a)

### What is expected?（期望的结果是什么？）
下划可以加载更多

### What is actually happening?（实际的结果是什么？）
下划无任何反应

**Comment by hkhere** [comment]
still not working
