### ISSUE TITLE
taro小程序接入腾讯视频

### ISSUE THREAD

**Issue by Hanchengluo** [jdf2e/nutui-react#1197]
### What problem does this feature solve?（这个功能解决的问题）
小程序不允许直接使用视频要使用视频插件，但taro找不到正常的接入腾讯视频方式。

### What does the proposed API look like?（期望的 API）
taro小程序接入腾讯视频

**Comment by Hanchengluo** [comment]
nutui react里找不到app.confg.js和page.config.js
https://nervjs.github.io/taro-docs/docs/hybrid/#%E4%BD%BF%E7%94%A8%E5%B0%8F%E7%A8%8B%E5%BA%8F%E6%8F%92%E4%BB%B6

**Comment by eiinu** [comment]
建议到 [Taro](https://github.com/NervJS/taro) 仓库下讨论相关话题
