### ISSUE TITLE
官网 babel 按需加载例子缺少 引入 sass varibale

### ISSUE THREAD

**Issue by jeekdong** [jdf2e/nutui-react#120]
## 问题
nutui-react 官网「快速上手」一节介绍 WebPack 构建工具 通过 babel 使用按需加载 **有误**
仅配置 babel-plugin-import 无法正常运行
### 报错如下
```bash
Failed to compile.

SassError: Undefined variable.
  ╷
5 │   width: $icon-width;
  │          ^^^^^^^^^^^
  ╵
  node_modules/@nutui/nutui-react/dist/packages/icon/icon.scss 5:10  root stylesheet
ERROR in ./node_modules/@nutui/nutui-react/dist/packages/icon/icon.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./node_modules/@nutui/nutui-react/dist/packages/icon/icon.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
  ╷
5 │   width: $icon-width;
  │          ^^^^^^^^^^^
  ╵
  node_modules/@nutui/nutui-react/dist/packages/icon/icon.scss 5:10  root stylesheet

```

后续发现，@nutui/nutui-react 导出的 sass 文件包含 sass variable 但是未引入对应 sass variable 文件，实际配置还需要借助 sass-resources-loader 全局导入 sass variable 文件

## 可复现demo
https://stackblitz.com/edit/webpack-webpack-js-org-bmddyc

**Comment by Timson020** [comment]
同问

**Comment by oasis-cloud** [comment]
> ## 问题
> nutui-react 官网「快速上手」一节介绍 WebPack 构建工具 通过 babel 使用按需加载 **有误** 仅配置 babel-plugin-import 无法正常运行
> 
> ### 报错如下
> ```shell
> Failed to compile.
> 
> SassError: Undefined variable.
>   ╷
> 5 │   width: $icon-width;
>   │          ^^^^^^^^^^^
>   ╵
>   node_modules/@nutui/nutui-react/dist/packages/icon/icon.scss 5:10  root stylesheet
> ERROR in ./node_modules/@nutui/nutui-react/dist/packages/icon/icon.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[7].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[7].use[4]!./node_modules/@nutui/nutui-react/dist/packages/icon/icon.scss)
> Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> SassError: Undefined variable.
>   ╷
> 5 │   width: $icon-width;
>   │          ^^^^^^^^^^^
>   ╵
>   node_modules/@nutui/nutui-react/dist/packages/icon/icon.scss 5:10  root stylesheet
> ```
> 
> 后续发现，@nutui/nutui-react 导出的 sass 文件包含 sass variable 但是未引入对应 sass variable 文件，实际配置还需要借助 sass-resources-loader 全局导入 sass variable 文件
> 
> ## 可复现demo
> https://stackblitz.com/edit/webpack-webpack-js-org-bmddyc

文档已更新：https://nutui.jd.com/react/#/start-react
