### ISSUE TITLE
关于组件希望能支持RTL

### ISSUE THREAD

**Issue by Ruler1020730** [jdf2e/nutui-react#1210]
### What problem does this feature solve?（这个功能解决的问题）
在特殊语言下能支持组件的RTL

### What does the proposed API look like?（期望的 API）
能通过ConfigProvider 配置全局组件的一个RTL或LTR，并且能单独控制组件的一个RTL开启关闭

**Comment by oasis-cloud** [comment]
有这种语言包可以提供出来吗

**Comment by xiaoyatong** [comment]
> ### What problem does this feature solve?（这个功能解决的问题）
> 在特殊语言下能支持组件的RTL
> 
> ### What does the proposed API look like?（期望的 API）
> 能通过ConfigProvider 配置全局组件的一个RTL或LTR，并且能单独控制组件的一个RTL开启关闭

请问可以提供相关的主题包么

**Comment by Ruler1020730** [comment]
> > ### 这个功能解决什么问题？（这个功能解决的问题）
> > 在语言特殊下能支持组件的RTL
> > ### 提议的API是什么样的？（期望的API）
> > 能够通过ConfigProvider配置全局组件的一个RTL或LTR，并且能够单独控制组件的一个RTL开启关闭
> 
> 请问可以提供相关的主题包么

维吾尔语 也是rtl 你们已经有了，但组件没有支持rtl
