### ISSUE TITLE
@nutui/nutui-react-taro swiper在h5端兼容问题

### ISSUE THREAD

**Issue by yaob421123** [jdf2e/nutui-react#1213]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-react version（nutui-react 版本）
2.0.2

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
mac

### Taro environmental information（taro 环境信息）
3.6.6

### Reproduction link（重现链接）
无

### Steps to reproduce（重现步骤）
<img width="477" alt="image" src="https://github.com/jdf2e/nutui-react/assets/15102592/cd520bf0-22fd-44f7-a49e-9aecc1988552">

滑动过程中，`Swiper.Item` 渲染异常，滑动结束显示正常

```js
import { View, Text, Button } from '@tarojs/components'
import { Swiper } from '@nutui/nutui-react-taro';
import './index.scss';

const demo = {
  display: 'flex'
}

const div = {
  flex: 1,
  border: '1px solid red'
}

export default function Index() {
  
  return (
    <View className='index'>
      <Swiper loop>
        <Swiper.Item>
          <div style={demo}>
            <div style={div}>1</div>
            <div style={div}>2</div>
            <div style={div}>3</div>
            <div style={div}>4</div>
          </div>
        </Swiper.Item>
        <Swiper.Item>
          <div style={demo}>
            <div style={div}>5</div>
            <div style={div}>6</div>
            <div style={div}>7</div>
            <div style={div}>8</div>
          </div>
        </Swiper.Item>
        <Swiper.Item>
          <div style={demo}>
            <div style={div}>9</div>
            <div style={div}>10</div>
            <div style={div}>11</div>
            <div style={div}>12</div>
          </div>
        </Swiper.Item>
      </Swiper>
    </View>
  )
}
```

### What is expected?（期望的结果是什么？）
无

### What is actually happening?（实际的结果是什么？）
无

**Comment by oasis-cloud** [comment]
由于 swiper 封装的 Taro Swiper 组件，问题是因为 Taro Swiper 自身导致，可以关注 https://github.com/NervJS/taro/issues/14160 的处理情况

**Comment by xiaoyatong** [comment]
目前看，bug修复的还有些问题，已反馈taro侧~

**Comment by xiaoyatong** [comment]
taro版本依赖升级到 3.6.14 即可解决。nutui 随后升级到 3.6.18，可关注。
