### ISSUE TITLE
下拉刷新跟着示例没用，是不支持？

### ISSUE THREAD

**Issue by YL920123** [jdf2e/nutui-react#1216]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.2

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
14.2

### Browser and its version（浏览器及其版本）
微信开发者工具

### System and its version（系统及其版本）
window11

### Taro environmental information（taro 环境信息）
taro3.6.6

### Reproduction link（重现链接）
[nutui.jd.com/taro/react/2x/](https://nutui.jd.com/taro/react/2x/#/zh-CN/component/pulltorefresh)

### Steps to reproduce（重现步骤）
00

### What is expected?（期望的结果是什么？）
0

### What is actually happening?（实际的结果是什么？）
0

**Comment by oasis-cloud** [comment]
需要配合一些样式，可以参考上面 PR 中的 demo
