### ISSUE TITLE
在android7自带浏览器里面打开白屏

### ISSUE THREAD

**Issue by gonganruyi** [jdf2e/nutui-react#1234]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.5.8

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
QQ Browser 6.6 OnePlus3T android 7.0

### System and its version（系统及其版本）
OnePlus3T android 7.0

### Reproduction link（重现链接）
[http://github.com/](http://github.com)

### Steps to reproduce（重现步骤）
使用官方demo在一加手机android7自带浏览器里面打开白屏

### What is expected?（期望的结果是什么？）
可以正常打开官方demo界面

### What is actually happening?（实际的结果是什么？）
白屏

### Remarks（补充说明）
使用官方demo在一加手机android7自带浏览器里面打开白屏

**Comment by eiinu** [comment]
demo 页面和组件的使用都是正常的。
白屏的是文档站点，下次发版前会修复。
