### ISSUE TITLE
form组件必填项星号必须指定require，rules中的require:true不起作用

### ISSUE THREAD

**Issue by JokerAn** [jdf2e/nutui-react#1241]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
2.0.4

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.20.0

### Browser and its version（浏览器及其版本）
chrome114

### System and its version（系统及其版本）
MacM1

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/stupefied-minsky-rghfvz?file=/src/App.js)

### Steps to reproduce（重现步骤）
打开就能看，无需点击什么；我看官网form中的必填项只要rules中的require=true就会有必填项星号，我这只能手动添加required

### What is expected?（期望的结果是什么？）
与官网展示一致只要rules中的require=true就会有必填项星号

### What is actually happening?（实际的结果是什么？）
rules中的require=true没有出现红色星号

**Comment by oasis-cloud** [comment]
props 中的 require 用来控制 星号是否展示，真正的校验由 规则中的 require 控制。
