### ISSUE TITLE
FormItem组件的label属性ts类型不够准确

### ISSUE THREAD

**Issue by MorningK** [jdf2e/nutui-react#1247]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.5

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.16.1

### Browser and its version（浏览器及其版本）
edge 114

### System and its version（系统及其版本）
Win11 wsl2

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.9-alpha.8

  Taro CLI 3.6.9-alpha.8 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.1/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/components: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/helper: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-framework-react: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-html: ^3.6.8 => 3.6.8
      @tarojs/plugin-platform-alipay: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-h5: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-jd: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-qq: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-swan: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-tt: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-weapp: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/react: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/runtime: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/shared: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/taro: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/taro-loader: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/webpack5-runner: 3.6.9-alpha.8 => 3.6.9-alpha.8
      babel-preset-taro: 3.6.9-alpha.8 => 3.6.9-alpha.8
      eslint-config-taro: 3.6.9-alpha.8 => 3.6.9-alpha.8
      react: ^18.0.0 => 18.2.0

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/p/sandbox/nutui-react-forked-5qs3rx?file=%2Fsrc%2FApp.tsx%3A31%2C53)

### Steps to reproduce（重现步骤）
设置FormItem组件的label属性为ReactElement而非string
```
const iconLabel = (
    <span>
      <Ask />
      地址
    </span>
  );
        <Form.Item label={iconLabel} name="address">
          <TextArea placeholder="请输入地址" maxLength={100} />
        </Form.Item>
```
![image](https://github.com/jdf2e/nutui-react/assets/21361743/17fbdece-fe41-4a92-a78b-c070498a0b1f)

### What is expected?（期望的结果是什么？）
ts类型不报错

### What is actually happening?（实际的结果是什么？）
ts类型报错，label只接受string类型
![image](https://github.com/jdf2e/nutui-react/assets/21361743/21c3d24d-65dc-4950-8d82-56a601afcee5)

**Comment by oasis-cloud** [comment]
formItem 的 label 现在版本中的类型是 string，你是说想支持 ReactNode？

**Comment by MorningK** [comment]
> formItem 的 label 现在版本中的类型是 string，你是说想支持 ReactNode？

是的，感谢处理
