### ISSUE TITLE
nutui-react-taro：InfiniteLoading里渲染的子组件中唤起popup，会导致InfiniteLoading滚动回最顶部

### ISSUE THREAD

**Issue by Ruboyq** [jdf2e/nutui-react#1252]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.5

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.15.0

### Browser and its version（浏览器及其版本）
无

### System and its version（系统及其版本）
mac

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.8

  Taro CLI 3.6.8 environment info:
    System:
      OS: macOS 11.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 18.15.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 9.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.7 => 3.6.7 
      @tarojs/components: 3.6.7 => 3.6.7 
      @tarojs/helper: 3.6.7 => 3.6.7 
      @tarojs/plugin-framework-react: 3.6.7 => 3.6.7 
      @tarojs/plugin-html: ^3.6.7 => 3.6.8 
      @tarojs/plugin-platform-alipay: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-h5: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-jd: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-qq: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-swan: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-tt: 3.6.7 => 3.6.7 
      @tarojs/plugin-platform-weapp: 3.6.7 => 3.6.7 
      @tarojs/react: 3.6.7 => 3.6.7 
      @tarojs/runtime: 3.6.7 => 3.6.7 
      @tarojs/shared: 3.6.7 => 3.6.7 
      @tarojs/taro: 3.6.7 => 3.6.7 
      @tarojs/taro-loader: 3.6.7 => 3.6.7 
      @tarojs/webpack5-runner: 3.6.7 => 3.6.7 
      babel-preset-taro: 3.6.7 => 3.6.7 
      eslint-config-taro: 3.6.7 => 3.6.7 
      react: ^18.0.0 => 18.2.0 

### Reproduction link（重现链接）
[https://github.com/](https://github.com)

### Steps to reproduce（重现步骤）
InfiniteLoading里面写button，唤起InfiniteLoading同层的popup，会导致InfiniteLoading滚动回顶部

### What is expected?（期望的结果是什么？）
InfiniteLoading保持在之前的位置

### What is actually happening?（实际的结果是什么？）
popup出现，InfiniteLoading滚动回了顶部

**Comment by oasis-cloud** [comment]
由于 popup 放在 InfiniteLoading，在组件隐藏后，dom 树会更新，导致滚动条位置变更，可将 popup 放在 InfiniteLoading 里面。
![image](https://github.com/jdf2e/nutui-react/assets/12181600/1af8fbfd-2fb2-4843-8a4f-5b83b6d2e7b6)
