### ISSUE TITLE
微信小程序使用page进行主题定制无效

### ISSUE THREAD

**Issue by Constantine-Marx** [jdf2e/nutui-react#1253]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.6

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
9.6.7

### Browser and its version（浏览器及其版本）
Chrome(114.0.5735.248)

### System and its version（系统及其版本）
windows11 21H2

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.7

  Taro CLI 3.6.7 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.7 => 3.6.7
      @tarojs/components: 3.6.7 => 3.6.7
      @tarojs/helper: 3.6.7 => 3.6.7
      @tarojs/plugin-framework-react: 3.6.7 => 3.6.7
      @tarojs/plugin-html: ^3.6.8 => 3.6.8
      @tarojs/plugin-platform-alipay: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-h5: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-jd: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-qq: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-swan: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-tt: 3.6.7 => 3.6.7
      @tarojs/plugin-platform-weapp: 3.6.7 => 3.6.7
      @tarojs/react: 3.6.7 => 3.6.7
      @tarojs/runtime: 3.6.7 => 3.6.7
      @tarojs/shared: 3.6.7 => 3.6.7
      @tarojs/taro: 3.6.7 => 3.6.7
      @tarojs/webpack5-runner: 3.6.7 => 3.6.7
      babel-preset-taro: 3.6.7 => 3.6.7
      eslint-config-taro: 3.6.7 => 3.6.7
      react: ^18.0.0 => 18.2.0
      taro-ui: ^3.1.0-beta.2 => 3.1.0-beta.5

### Reproduction link（重现链接）
[github.com](https://github.com/Constantine-Marx/jiajiaohui)

### Steps to reproduce（重现步骤）
1、用Webstorm打开项目，在命令行输入`npm run dev:weapp`
2、打开微信开发者工具，打开项目等待编译完成
3、点击“时间降序”，弹出Picker，观察Picker样式

### What is expected?（期望的结果是什么？）
确认和取消的字号增大，变为30px

### What is actually happening?（实际的结果是什么？）
确认和取消的字号仍为14px,

### Remarks（补充说明）
可改为颜色，一样不会生效

**Comment by Constantine-Marx** [comment]
字号有效了，但是颜色不会改变

**Comment by oasis-cloud** [comment]
如果是感觉 nutui 字号小，可以在 postcss 的配置中增加如下内容：

```
pxtransform: {
        enable: true,
        config: {
          selectorBlackList: ['nut-']
        }
      },
```

**Comment by Constantine-Marx** [comment]
> 

字号可以改变了，只是颜色设置了但是还是不会变

**Comment by oasis-cloud** [comment]
@import '@nutui/nutui-react-taro/dist/style.css'; 建议你不要每个页面引入这个文件，最好是通过按需加载样式的方式来处理。可以在 babel.config.js 中增加如下配置并安装 babel-plugin-import

```
plugins: [
    [
      "import",
      {
        "libraryName": "@nutui/nutui-react-taro",
        "libraryDirectory": "dist/esm",
        "style": true,
        "camel2DashComponentName": false
      },
      'nutui-react-taro'
    ]
]
```

**Comment by oasis-cloud** [comment]
你已经在 app.scss 引入 @import '@nutui/nutui-react-taro/dist/style.css';，其他页面不需要在引入这个样式。而且你的 Header.js 中没有引入 Header.scss
