### ISSUE TITLE
微信小程序在FormItem中使用Input组件输入后逐个删除最后一个无法成功删除

### ISSUE THREAD

**Issue by MorningK** [jdf2e/nutui-react#1258]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.0

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18

### Browser and its version（浏览器及其版本）
edge 115

### System and its version（系统及其版本）
windows11 wsl2

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.9-alpha.8

  Taro CLI 3.6.9-alpha.8 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.1/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/components: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/helper: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-framework-react: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-html: ^3.6.8 => 3.6.8
      @tarojs/plugin-platform-alipay: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-h5: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-jd: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-qq: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-swan: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-tt: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/plugin-platform-weapp: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/react: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/runtime: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/shared: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/taro: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/taro-loader: 3.6.9-alpha.8 => 3.6.9-alpha.8
      @tarojs/webpack5-runner: 3.6.9-alpha.8 => 3.6.9-alpha.8
      babel-preset-taro: 3.6.9-alpha.8 => 3.6.9-alpha.8
      eslint-config-taro: 3.6.9-alpha.8 => 3.6.9-alpha.8
      react: ^18.0.0 => 18.2.0

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/p/sandbox/nutui-react-forked-c6gdjt?file=%2Fsrc%2FApp.tsx%3A16%2C1)

### Steps to reproduce（重现步骤）
在FormItem中使用Input组件，输入内容后删除内容，删除至最后一个时，无法删除成功，第二次重试才能成功，而且伴随内容闪现
```
 <Form labelPosition="right">
      <Form.Item required label="数字" name="number">
        <Input type="number" placeholder="请输入数字并逐个删除" />
      </Form.Item>
    </Form>
```
实际情况
![3352493](https://github.com/jdf2e/nutui-react/assets/21361743/3dfa5907-911c-48c7-9269-29970bc7cadf)

### What is expected?（期望的结果是什么？）
可以一次性正常删除至内容为空

### What is actually happening?（实际的结果是什么？）
无法一次性正常删除至内容为空

### Remarks（补充说明）
安卓、ISO和微信开发者工具都这样

**Comment by MorningK** [comment]
单独使用Input组件是正常的，但是放在FormItem里就会这样

**Comment by oasis-cloud** [comment]
上述问题是因为 taro 中的 Input 组件存在问题，可以升级 taro 到 3.6.8，同时升级 nutui-react-taro 到最新版本

**Comment by promiseLC** [comment]
<img width="584" alt="image" src="https://github.com/jdf2e/nutui-react/assets/56290517/0a7f1c85-3e23-444e-9916-4a1164d38bdb">

我taro3.6.8 nui 2.0.9 还是有这个问题

**Comment by oasis-cloud** [comment]
可升级到 taro 最新版本

https://github.com/jdf2e/nutui-react/assets/12181600/30ee5f38-81fe-4f7b-8911-8ab9b9098def
