### ISSUE TITLE
这里计算完小于零，是不是应该加一下判断

### ISSUE THREAD

**Issue by fullee** [jdf2e/nutui-react#1273]
https://github.com/jdf2e/nutui-react/blob/166ce9ac20cf0eb5ed0ee0868b99b56a1aba89ef/src/packages/elevator/elevator.tsx#L125

![image](https://github.com/jdf2e/nutui-react/assets/11188837/4127a79f-dec7-434c-9484-379da827a4a3)

**Comment by oasis-cloud** [comment]
-1 会导致什么样的问题？

**Comment by fullee** [comment]
![image](https://github.com/jdf2e/nutui-react/assets/11188837/50f6bd9f-0408-4030-b692-cfa3b38378b7)
像这里用到了codeIndex，数组索引小于0就报错吧

**Comment by fullee** [comment]
![83228d97c4e9e4e6f19d35042c03433](https://github.com/jdf2e/nutui-react/assets/11188837/9dcc07b4-cb0e-4791-b5a7-a4d035afc3da)
我这边是这里报的错

**Comment by oasis-cloud** [comment]
怎样才能复现你说的问题？可以提供 demo 吗，以便此问题更快的解决

**Comment by fullee** [comment]
应该是useEffect更新数据后出现这个问题，不过我改好了
https://github.com/fullee/nutui-react/commit/f9d6a2845d89905246a6e28903e0c3e2dcf4a668

但是husk一直过不了，就没提PR

**Comment by oasis-cloud** [comment]
> 应该是useEffect更新数据后出现这个问题，不过我改好了 [fullee@f9d6a28](https://github.com/fullee/nutui-react/commit/f9d6a2845d89905246a6e28903e0c3e2dcf4a668)
> 
> 但是husk一直过不了，就没提PR

是不是应该修改 codeIndex 赋值的地方更好一些？

**Comment by fullee** [comment]
效率真高，啥时候发版，哈哈

**Comment by oasis-cloud** [comment]
> 效率真高，啥时候发版，哈哈

2023年8月4日发版
