### ISSUE TITLE
calendar组件，日期范围选择

### ISSUE THREAD

**Issue by Tenodec** [jdf2e/nutui-react#128]
选择区间日期的时候，选择日期后，再选择这个日期前的日期，会出现文字错位。比如先选5.27 再选5.20

**Comment by oasis-cloud** [comment]
辛苦提供具体的版本号，以及最小可复现代码仓库

**Comment by oasis-cloud** [comment]
建议安装最新版本的看一下，目前未富先出来

**Comment by oasis-cloud** [comment]
可尝试使用最新版本的 @nutui/nutui-react。
