### ISSUE TITLE
NoticeBar在CustomWrapper包裹下不能如期使用

### ISSUE THREAD

**Issue by DuduStyle** [jdf2e/nutui-react#1280]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.8

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.0

### Browser and its version（浏览器及其版本）
无 小程序环境

### System and its version（系统及其版本）
 Windows 10 10.0.22621

### Taro environmental information（taro 环境信息）
Taro v3.6.11

  Taro CLI 3.6.11 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.11 => 3.6.11
      @tarojs/components: 3.6.11 => 3.6.11
      @tarojs/helper: 3.6.11 => 3.6.11
      @tarojs/plugin-framework-react: 3.6.11 => 3.6.11
      @tarojs/plugin-html: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-alipay: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-h5: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-jd: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-qq: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-swan: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-tt: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-weapp: 3.6.11 => 3.6.11
      @tarojs/react: 3.6.11 => 3.6.11
      @tarojs/runtime: 3.6.11 => 3.6.11
      @tarojs/shared: 3.6.11 => 3.6.11
      @tarojs/taro: 3.6.11 => 3.6.11
      @tarojs/taro-loader: 3.6.11 => 3.6.11
      @tarojs/webpack5-runner: 3.6.11 => 3.6.11
      babel-preset-taro: 3.6.11 => 3.6.11
      eslint-config-taro: 3.6.11 => 3.6.11
      react: ^18.0.0 => 18.2.0

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/p/github/DuduStyle/nuti-taro-ui/master?file=/project.tt.json:1,1&workspaceId=37e10cc9-9f8c-45ad-9476-1b59b2cf110c)

[github仓库](https://github.com/DuduStyle/nuti-taro-ui)

### Steps to reproduce（重现步骤）
yarn dev:weapp
打开首页观察控制台

### What is expected?（期望的结果是什么？）
正常滚动

### What is actually happening?（实际的结果是什么？）
不滚动，页面报错
![a66a356a1b6c40283e9e4c94afad5ca](https://github.com/jdf2e/nutui-react/assets/31200868/df18653d-700f-4c71-998e-84d172274f81)
![image](https://github.com/jdf2e/nutui-react/assets/31200868/d80c6434-02a4-4288-a9e8-297091dbe275)

**Comment by oasis-cloud** [comment]
taro 项目的 issue 关于 CustomWrapper 的还比较多，建议先不使用 CustomWrapper

**Comment by onlyling** [comment]
`Swipe` 也有相似问题。

**Comment by DuduStyle** [comment]
> taro 项目的 issue 关于 CustomWrapper 的还比较多，建议先不使用 CustomWrapper

大佬给Taro项目组反馈下？@oasis-cloud
