### ISSUE TITLE
Cascader value属性不受控

### ISSUE THREAD

**Issue by wangjianbing0629** [jdf2e/nutui-react#1281]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
2.0.10

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
macos12

### Reproduction link（重现链接）
[codesandbox.io/s/09yj90](https://codesandbox.io/s/09yj90?file)

### Steps to reproduce（重现步骤）
绑定value不生效

### What is expected?（期望的结果是什么？）
value属性为受控

### What is actually happening?（实际的结果是什么？）
value属性为受控

**Comment by oasis-cloud** [comment]
codesandbox 中的安装的并不是 @nutui/nutui-react，而是 @nutui/nutui
