### ISSUE TITLE
NumberKeyboard onConfirm不会触发

### ISSUE THREAD

**Issue by AvaKnew** [jdf2e/nutui-react#1283]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-react version（nutui-react 版本）
2.0.10

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
18.15.0

### Browser and its version（浏览器及其版本）
edge

### System and its version（系统及其版本）
window 11

### Taro environmental information（taro 环境信息）
Taro CLI 3.6.11 environment info:
    System:
      OS: Windows 10 10.0.22631
    Binaries:
      Node: 18.15.0 - D:\APP\NVM\node\node.EXE
      Yarn: 1.22.19 - D:\APP\NVM\npm\yarn.CMD
      npm: 9.5.0 - D:\APP\NVM\node\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.11 => 3.6.11
      @tarojs/components: 3.6.11 => 3.6.11
      @tarojs/helper: 3.6.11 => 3.6.11
      @tarojs/plugin-framework-react: 3.6.11 => 3.6.11
      @tarojs/plugin-html: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-h5: 3.6.11 => 3.6.11
      @tarojs/plugin-platform-weapp: 3.6.11 => 3.6.11
      @tarojs/react: 3.6.11 => 3.6.11
      @tarojs/runtime: 3.6.11 => 3.6.11
      @tarojs/shared: 3.6.11 => 3.6.11
      @tarojs/taro: 3.6.11 => 3.6.11
      @tarojs/taro-loader: 3.6.11 => 3.6.11
      @tarojs/webpack5-runner: 3.6.11 => 3.6.11
      babel-preset-taro: 3.6.11 => 3.6.11
      eslint-config-taro: 3.6.11 => 3.6.11
      react: ^18.2.0 => 18.2.0

### Reproduction link（重现链接）
无

### Steps to reproduce（重现步骤）
<NumberKeyboard visible title="12312" onConfirm={console.log} />

### What is expected?（期望的结果是什么？）
onConfirm正常执行

### What is actually happening?（实际的结果是什么？）
onConfirm不执行，执行了onClose

### Remarks（补充说明）
![image](https://github.com/jdf2e/nutui-react/assets/8371138/c96c941d-79b7-48e3-9280-39b4f4462bff)

**Comment by oasis-cloud** [comment]
你使用的是 type=rightColumn 的键盘吗？

**Comment by AvaKnew** [comment]
type=default，当设置标题，右上角有个完成按钮，设置是confirmText，但点击是调用了onClose

![image](https://github.com/jdf2e/nutui-react/assets/8371138/96c40ca8-58df-4825-a0e3-1b6fafca924f)
