### ISSUE TITLE
微信小程序中skeleton显示隐藏问题

### ISSUE THREAD

**Issue by suyuan0** [jdf2e/nutui-react#1287]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.10

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
17.0.0

### Browser and its version（浏览器及其版本）
115.0.5790.114

### System and its version（系统及其版本）
13.4.1

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.11

  Taro CLI 3.6.11 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 17.0.0 - ~/.nvm/versions/node/v17.0.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v17.0.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.11 => 3.6.11 
      @tarojs/components: 3.6.11 => 3.6.11 
      @tarojs/helper: 3.6.11 => 3.6.11 
      @tarojs/plugin-framework-react: 3.6.11 => 3.6.11 
      @tarojs/plugin-html: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-alipay: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-h5: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-jd: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-qq: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-swan: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-tt: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-weapp: 3.6.11 => 3.6.11 
      @tarojs/react: 3.6.11 => 3.6.11 
      @tarojs/runtime: 3.6.11 => 3.6.11 
      @tarojs/shared: 3.6.11 => 3.6.11 
      @tarojs/taro: 3.6.8 => 3.6.8 
      @tarojs/taro-loader: 3.6.11 => 3.6.11 
      @tarojs/webpack5-runner: 3.6.11 => 3.6.11 
      babel-preset-taro: 3.6.11 => 3.6.11 
      eslint-config-taro: 3.6.11 => 3.6.11 
      react: ^18.0.0 => 18.0.0 

### Reproduction link（重现链接）
[nutui.jd.com/taro/react/2x/](https://nutui.jd.com/taro/react/2x/#/zh-CN/component/skeleton)

### Steps to reproduce（重现步骤）
骨架屏无法通过visible来控制状态

### What is expected?（期望的结果是什么？）
可以通过visible来控制

### What is actually happening?（实际的结果是什么？）
visible状态无效

**Comment by oasis-cloud** [comment]
visible 的默认值是 false，false 表示展示 skeleton 的占位，true 表示隐藏占位。可以理解为 visible: false 不展示 skeleton 的子元素，true，展示子元素。

```tsx
<Cell className="ske-cell-single">
  <Skeleton visible={showS}>
     <div> Child </div>
  </Skeleton>
</Cell>
<Cell>
  <div onClick={() => {setShowS(false)}}>显示</div>
  <div onClick={() => {setShowS(true)}}>隐藏</div>
</Cell>
```

**Comment by suyuan0** [comment]
ok

**Comment by suyuan0** [comment]
已解决
