### ISSUE TITLE
input在提交后重置内容

### ISSUE THREAD

**Issue by Hanchengluo** [jdf2e/nutui-react#1288]
### What problem does this feature solve?（这个功能解决的问题）
https://nutui.jd.com/taro/react/2x/#/zh-CN/component/input   ,  在数据提交后想input的值回复到没提交前的空，但用了value或default都不可以。
	<Form labelPosition="Top"   name="basic"
          name="basic" labelCol={{ span: 5, }} wrapperCol={{ span: 16, }}
          initialValues={{ remember: true, }}  
		  onFinish={(obj) => submitSucceed(obj)}
        onFinishFailed={(error) => submitFailed(error)}    >
		<Input onChange={(val: string, name: string) => input_change(val,'msg_contents')}   
		placeholder="请输入评论" 
		ref={ref} 
		clearable center slotButton={<Button size="small" type="primary" formType="submit">发送</Button>}
        />
		   
         
      </Form>

### What does the proposed API look like?（期望的 API）
在数据提交后想input的值回复到没提交前的空

**Comment by Hanchengluo** [comment]
这段是可以 重置input但我还要提交内容 
const [message, setMessage] = useState('');
  const handleChange = event => {
    setMessage(event.target.value);
  };

  const handleClick = () => {
    // ?️ 清除 input 值
    setMessage('');
  };

  return (
    <div>
      <input
        id="message"
        name="message"
        type="text"
        onChange={handleChange}
        value={message}
      />

      <button onClick={handleClick}>Clear field</button>
    </div>
  );
};

**Comment by Hanchengluo** [comment]
临时解决方法，在form加一个增量式变量key,   key= {inputs}

**Comment by oasis-cloud** [comment]
可以给 Form 组件传入 Form.useForm() 创建的 form 控制实例，通过此实例子，调用 resetFields() 进行重置

**Comment by oasis-cloud** [comment]
可以参考文档中 “Form.useForm 对表单数据域进行交互” 的 Demo
