### ISSUE TITLE
input样式不生效

### ISSUE THREAD

**Issue by suyuan0** [jdf2e/nutui-react#1299]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.11

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
17.0.0

### Browser and its version（浏览器及其版本）
115.0.5790.170

### System and its version（系统及其版本）
13.4.1

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.11

  Taro CLI 3.6.11 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 17.0.0 - ~/.nvm/versions/node/v17.0.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v17.0.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.11 => 3.6.11 
      @tarojs/components: 3.6.11 => 3.6.11 
      @tarojs/helper: 3.6.11 => 3.6.11 
      @tarojs/plugin-framework-react: 3.6.11 => 3.6.11 
      @tarojs/plugin-html: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-alipay: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-h5: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-jd: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-qq: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-swan: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-tt: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-weapp: 3.6.11 => 3.6.11 
      @tarojs/react: 3.6.11 => 3.6.11 
      @tarojs/runtime: 3.6.11 => 3.6.11 
      @tarojs/shared: 3.6.11 => 3.6.11 
      @tarojs/taro: 3.6.8 => 3.6.8 
      @tarojs/taro-loader: 3.6.11 => 3.6.11 
      @tarojs/webpack5-runner: 3.6.11 => 3.6.11 
      babel-preset-taro: 3.6.11 => 3.6.11 
      eslint-config-taro: 3.6.11 => 3.6.11 
      react: ^18.2.0 => 18.2.0 

### Reproduction link（重现链接）
[nutui.jd.com/taro/react/2x/](https://nutui.jd.com/taro/react/2x/#/zh-CN/component/input)

### Steps to reproduce（重现步骤）
通过root修改input样式，input单独拿出来可以，但是放到Form.Item里面没有生效
--nutui-input-border-bottom --nutui-input-border-bottom-width

### What is expected?（期望的结果是什么？）
修改input样式

### What is actually happening?（实际的结果是什么？）
样式无效

### Remarks（补充说明）
Form label标签位置更改为top，form.item内容宽度没有更改，只占页面的一半左右，希望可以通过样式修改宽度或者默认100%

**Comment by oasis-cloud** [comment]
在 formItem 中将 input 和 textarea 的边框设置为 0 了，所以通过 css 变量设置不生效，需要通过 css 选择器进行覆盖
