### ISSUE TITLE
日期选择器，确认按钮溢出

### ISSUE THREAD

**Issue by ivantree** [jdf2e/nutui-react#1304]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
2.0.12

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
WIN10 

### Reproduction link（重现链接）
[github.com](https://github.com/jdf2e/nutui-react/blob/next/src/packages/calendar/demo.tsx)

### Steps to reproduce（重现步骤）
 <Calendar
      visible={ showFilterDate }
      type={'single'}
      defaultValue={ date }
      startDate="2022-01-11"
      onClose={ ()=>setShowFilterDate(false) }
      onConfirm={ onFilterDateConfirm }
    />

### What is expected?（期望的结果是什么？）
修复

### What is actually happening?（实际的结果是什么？）
溢出

**Comment by ivantree** [comment]
![微信截图_20230813223436](https://github.com/jdf2e/nutui-react/assets/9014680/f217ef08-8f4d-4680-bfa8-f6cd7d5c7aaa)

**Comment by oasis-cloud** [comment]
修改过主题相关的 css 吗？建议先排查下是不是修改过相关的 css

**Comment by ivantree** [comment]
![image](https://github.com/jdf2e/nutui-react/assets/9014680/e9b1a6cb-969e-42a9-b63e-912689fb5f21)
只在这里做了修改，测试时出现的BUG

**Comment by oasis-cloud** [comment]
可以提供完整的 Demo 吗，我在 next 分支上复现不出来你的问题
