### ISSUE TITLE
ConfigProvider自定义theme在小程序端不工作？

### ISSUE THREAD

**Issue by minzojian** [jdf2e/nutui-react#1305]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.10

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
macOS 13.4.1

### Taro environmental information（taro 环境信息）
 Taro CLI 3.6.11 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm

### Reproduction link（重现链接）
[nutui.jd.com](https://nutui.jd.com/nutui-issue-helper/?repo=jdf2e/nutui-react&lang=zh-cn)

### Steps to reproduce（重现步骤）
在app.tsx中
```
  const myTheme = {
    nutuiBrandColor: 'green',
  nutuiBrandColorStart: 'green',
  nutuiBrandColorEnd: 'green',
  }

  return (
    <ConfigProvider theme={myTheme}>
     {props.children}
    </ConfigProvider>
  )
```
子页面中正常使用nutui的组件，比如放置一个普通的按钮

### What is expected?（期望的结果是什么？）
nutui组件的主色调都会变成绿色

### What is actually happening?（实际的结果是什么？）
并没有改变，自定义主题失效

### Remarks（补充说明）
H5版的能工作，但是小程序这边不工作

**Comment by oasis-cloud** [comment]
ConfigProvider 在小程序中只能改变子组件的主题颜色，如果需要全局变更，可以在 app.css 文件中设置 css 变量

**Comment by oasis-cloud** [comment]
如果上述回复还未能解决您的问题，可以提供可复现 Demo，以便帮助您进一步的定位问题。

**Comment by minzojian** [comment]
> ConfigProvider 在小程序中只能改变子组件的主题颜色，如果需要全局变更，可以在 app.css 文件中设置 css 变量
您的意思是，只能在每一个想要改变颜色的地方(比如每个页面里)，都包一个configprovider？而不能在app.tsx里包一个全局唯一的provider?

采用CSS变量的方式，的确能改变按钮颜色，但是某些组件失效，比如环形进度条。
仔细看了一下，环形进度条是生成的SVG代码，而里边的填充没有用到CSS变量的感觉

![image](https://github.com/jdf2e/nutui-react/assets/361781/b6115e47-e789-4ecf-8bab-1b5570f10eaf)

**Comment by minzojian** [comment]
总结一下
1.因为在小程序的入口组件里不能渲染其它内容，所以在app.tsx里直接使用ConfigProvider会失效（因为ConfigProvider是渲染了一个view并注入css变量的方式实现）
2.所以只有在每个page里去包一个ConfigProvider，为保持统一，可以把用到的css变量对象单独提成为一个全局变量。
3.环形进度条确实没有用到CSS变量，不过有一个color属性，可以设置color值为上一步中的全局变量里的nutuiBrandColor值即可
