### ISSUE TITLE
Tabs 组件的 type="smile" 微笑曲线失效了

### ISSUE THREAD

**Issue by chrysanthemum** [jdf2e/nutui-react#1313]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
2.0.12

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18

### Browser and its version（浏览器及其版本）
Chrome

### System and its version（系统及其版本）
Mac

### Reproduction link（重现链接）
[github.com/jdf2e/nutui-react](https://github.com/jdf2e/nutui-react)

### Steps to reproduce（重现步骤）
2.0以上版本，在哪里测试，Tabs 组件的 type="smile" 微笑曲线都失效

### What is expected?（期望的结果是什么？）
这个特征还支持么

### What is actually happening?（实际的结果是什么？）
支持

**Comment by chrysanthemum** [comment]
在小程序环境中

**Comment by chrysanthemum** [comment]
测试代码，在下面仓库，谢谢！
https://github.com/chrysanthemum/nutui-smile

**Comment by chrysanthemum** [comment]
NUTUI 有无可能放弃TS，转JSDOC   ：）

**Comment by eiinu** [comment]
文档 demo 有问题，API 表格以及实际代码中该字段为 activeType
