### ISSUE TITLE
taro@3.6版本 prebundle 会报找不到组件错误

### ISSUE THREAD

**Issue by skyintree** [jdf2e/nutui-react#1316]
### What problem does this feature solve?（这个功能解决的问题）
文档中  https://nutui.jd.com/taro/react/2x/#/zh-CN/guide/start-react   在注意事项中的第三条有说出现当前错误有解决方法，但是按照文档修改仍旧会报错，在各种盲目的尝试还有翻各种issue中找到下面这个配置才是正确的

### What does the proposed API look like?（期望的 API）
现在文档中的配置
```
// config/index.js
config = {
  compiler: {
    type: 'webpack5',
    prebundle: false
  },
  cache: false
}
```

正确的配置
```
// config/index.js
compiler: {
    type: 'webpack5',
    prebundle: { enable: true, exclude: ['@nutui/nutui-react-taro'] }
  }
```

**Comment by oasis-cloud** [comment]
在 windows 上面吗？taro 版本具体是多少？

**Comment by skyintree** [comment]
是的  windows，昨天新建的项目是"@tarojs/react": "3.6.13", 实际上在2月前，我尝试更新到3.6.8的时候就有该错误了，将taro版本回退到3.6.7就可以正常使用
