### ISSUE TITLE
模块“"@nutui/nutui-react-taro"”没有导出的成员“Space”。ts(2305)

### ISSUE THREAD

**Issue by libra-co** [jdf2e/nutui-react#1325]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

^2.0.0

### 平台

weapp

### 重现链接

https://codepen.io/916196375/pen/GRPgOBB

### 重现步骤

import { Avatar,Space } from '@nutui/nutui-react-taro';

### 期望的结果是什么？

Space组件被引入

### 实际的结果是什么？

Space组件未被引入,提示 :模块“"@nutui/nutui-react-taro"”没有导出的成员“Space”。ts(2305)

### 环境信息

👽 Taro v3.6.13

  Taro CLI 3.6.13 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.19.1 - D:\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
      npm: 9.8.1 - D:\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.13 => 3.6.13
      @tarojs/components: 3.6.13 => 3.6.13
      @tarojs/helper: 3.6.13 => 3.6.13
      @tarojs/plugin-framework-react: 3.6.13 => 3.6.13
      @tarojs/plugin-html: 3.6.13 => 3.6.13
      @tarojs/plugin-platform-alipay: 3.6.13 => 3.6.13
      @tarojs/plugin-platform-h5: 3.6.13 => 3.6.13
      @tarojs/plugin-platform-jd: 3.6.13 => 3.6.13
      @tarojs/plugin-platform-qq: 3.6.13 => 3.6.13
      @tarojs/plugin-platform-swan: 3.6.13 => 3.6.13
      @tarojs/plugin-platform-tt: 3.6.13 => 3.6.13
      @tarojs/plugin-platform-weapp: 3.6.13 => 3.6.13
      @tarojs/react: 3.6.13 => 3.6.13
      @tarojs/runtime: 3.6.13 => 3.6.13
      @tarojs/shared: 3.6.13 => 3.6.13
      @tarojs/taro: 3.6.13 => 3.6.13
      @tarojs/taro-loader: 3.6.13 => 3.6.13
      @tarojs/webpack5-runner: 3.6.13 => 3.6.13
      babel-preset-taro: 3.6.13 => 3.6.13
      eslint-config-taro: 3.6.13 => 3.6.13
      react: ^18.0.0 => 18.0.0

**Comment by ivan-My** [comment]
升级组件库版本

**Comment by oasis-cloud** [comment]
升级到最新版本
