### ISSUE TITLE
抖音小程序下 Dialog 里面的content无效

### ISSUE THREAD

**Issue by snoopy1412** [jdf2e/nutui-react#1329]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.14

### 平台

tt

### 重现链接

无

### 重现步骤

`   <Dialog title="组件调用" content="测试一下content能不能支持" visible>
        但是完全没用
      </Dialog>`

### 期望的结果是什么？

能够渲染出content内容

### 实际的结果是什么？

无法渲染成功

### 环境信息

`👽 Taro v3.6.11

  Taro CLI 3.6.11 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.11 => 3.6.11 
      @tarojs/components: 3.6.11 => 3.6.11 
      @tarojs/helper: 3.6.11 => 3.6.11 
      @tarojs/plugin-framework-react: 3.6.11 => 3.6.11 
      @tarojs/plugin-html: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-alipay: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-h5: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-jd: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-qq: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-swan: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-tt: 3.6.11 => 3.6.11 
      @tarojs/plugin-platform-weapp: 3.6.11 => 3.6.11 
      @tarojs/react: 3.6.11 => 3.6.11 
      @tarojs/runtime: 3.6.11 => 3.6.11 
      @tarojs/shared: 3.6.11 => 3.6.11 
      @tarojs/taro: 3.6.11 => 3.6.11 
      @tarojs/taro-loader: 3.6.11 => 3.6.11 
      @tarojs/webpack5-runner: 3.6.11 => 3.6.11 
      babel-preset-taro: 3.6.11 => 3.6.11 
      eslint-config-taro: 3.6.11 => 3.6.11 
      react: ^18.0.0 => 18.2.0 `

### 其他补充信息

react 18
webpack 5

**Comment by snoopy1412** [comment]
怎么官方一个回复都没有？

**Comment by doom-9** [comment]
我也遇到类似的问题了
