### ISSUE TITLE
1.5.4  switch组件 抖音不显示 急急急！！！！！

### ISSUE THREAD

**Issue by xTzyang** [jdf2e/nutui-react#1330]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

1.54

### 平台

tt

### 重现链接

没有复现demo

### 重现步骤

组件不显示

### 期望的结果是什么？

显示！

### 实际的结果是什么？

不显示

**Comment by beginnerZhang** [comment]
@nutui/nutui-react-taro@1.5.4下复现是可以显示的，不显示可能是因为样式配置问题，可以检查一下babel.config.js中的配置，plugins的位置可以按照下面这样：
`module.exports = {
  presets: [],
  plugins: []
}`
其他配置请参考 https://nutui.jd.com/taro/react/1x/#/zh-CN/guide/starttaro-react ，
也可以使用2.x 版本获得更好体验！
<img width="327" alt="image" src="https://github.com/jdf2e/nutui-react/assets/49085996/220953b6-b3a1-4e68-af63-157c5dd00f80">
