### ISSUE TITLE
[FR]: picker 选项内容是否能自定义展示，接受reactDom

### ISSUE THREAD

**Issue by 5201314999** [jdf2e/nutui-react#1331]
### 这个功能解决了什么问题？

picker 选项内容是否能自定义展示，接受reactDom , 目前只能接收string，文案，比较简单

### 你期望的组件设计是怎样的？

options 数据结构能接收自定义reactDom

**Comment by xiaoyatong** [comment]
text 里可以写 dom节点。
<img width="702" alt="image" src="https://github.com/jdf2e/nutui-react/assets/84436086/9382b06e-d91e-482a-81f8-be457a2c8150">

![image](https://github.com/jdf2e/nutui-react/assets/84436086/91d57019-f199-48e3-805f-6ebfe47d27c6)
