### ISSUE TITLE
Calendar 无法正常滚动

### ISSUE THREAD

**Issue by qnnp-me** [jdf2e/nutui-react#1351]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.14

### 平台

weapp

### 重现链接

https://github.com/jdf2e/nutui-react

### 重现步骤

在动态生成的表单中使用Calendar组件作为子组件时、Calendar组件滚动时会自动复位、应该是state刷新造成的rerende

### 期望的结果是什么？

Calendar 正常滚动

### 实际的结果是什么？

Calendar 组件作为动态表单子组件无法正常滚动

### 环境信息

~

### 其他补充信息

~

**Comment by byMoWen** [comment]
大佬我更新到2.0.16发现问题    h5 的日历要用taro-react    weapp要用taro-react-taro.......
