### ISSUE TITLE
[FR]: 鸡肋的form表单期望完善以下功能

### ISSUE THREAD

**Issue by codedart2018** [jdf2e/nutui-react#1397]
### 这个功能解决了什么问题？

1.期望校验不通过，输入合法值无法自动消除掉。必须再次submit。这会导致用户误认为输入错误。
<img width="365" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12706830/42979275-de35-43df-8bdc-6f9a89527830">

2.期望rule自定义验证，期望增加第三个参数返回整个表单value的值，有种最常见的情况，密码比对，第一个表单和第二个表单值要进行比对是否一致，现在只能通过挂载ref form.getFieldValue　来解决。虽然可以解决问题，但确把简单的事情复杂化了。
![image](https://github.com/jdf2e/nutui-react/assets/12706830/0fca9f39-1521-4201-8bec-0e3e9b446d87)

3.期望可以Form.Item可以穿透value值到下面组件去。常见问题就是form.item里不一定是表单。可能是view 布局。目前是可以正常布局。但值不能穿透下去。只能通过手动setFieldValue来解决。

4.期望可以在Form.Item里自定义函数渲染数据。具体可以像antd一样。下面截图示义
![image](https://github.com/jdf2e/nutui-react/assets/12706830/68975117-4e48-4ee4-a7d3-bca233c1a29e)

5.期望Form组件把changValues　props加上如果遇没有完善value值穿透下方，那么我可以通过监听changeValues来改变。而不是在表单上做change setFieldValue.

### 你期望的组件设计是怎样的？

综上如果不是复杂的表单不验证可用，如果一用验证，一个form几十个字段。不能自动消除错误满屏的错误提示会误导用户。只能说前端3　5个表单可用验证，就目前情况来说如果字段多了前端的验证只能取消掉。只用后端验证。期望能完善以上的点，都是实际开发中常见到的。

**Comment by codedart2018** [comment]
补充，期望form ref 能返回所以value值　如antd getFieldsValue() 把整个表单的值都可以拿出来。现在form ref上看了没有这个方法或对象。无法取得值。好痛苦的一件事啊！

**Comment by oasis-cloud** [comment]
> 补充，期望form ref 能返回所以value值　如antd getFieldsValue() 把整个表单的值都可以拿出来。现在form ref上看了没有这个方法或对象。无法取得值。好痛苦的一件事啊！

ref 在 2.0.16 版本上可以使用了

**Comment by codedart2018** [comment]
> 2.0.16

2.0.16我刚升了，并没有发现ref form上有新的字段。getFieldsValue　在实际开发中很重要。
<img width="1022" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12706830/bf518cc5-6ec7-4c05-b860-d51cd8492d57">

**Comment by oasis-cloud** [comment]
> > 2.0.16
> 
> 2.0.16我刚升了，并没有发现ref form上有新的字段。getFieldsValue　在实际开发中很重要。 <img alt="image" width="1022" src="https://user-images.githubusercontent.com/12706830/265945073-bf518cc5-6ec7-4c05-b860-d51cd8492d57.png">

获取全部值的方法没加，2.0.16 版本加了 ref

**Comment by codedart2018** [comment]
> > > 2.0.16
> > 
> > 
> > 2.0.16我刚升了，并没有发现ref form上有新的字段。getFieldsValue　在实际开发中很重要。 <img alt="image" width="1022" src="https://user-images.githubusercontent.com/12706830/265945073-bf518cc5-6ec7-4c05-b860-d51cd8492d57.png">
> 
> 获取全部值的方法没加，2.0.16 版本加了 ref

还是希望后面的版本在form上能把获得所有值给返回来，我现在几十个字段都是暴力的定义一个数组　然后循环 ``` form.getFieldValue ``` 取数据，取出来做二次处理，然后再又循环给Set回来　如果form 上有监听onChangeValues 那么就方便很多啦！

**Comment by mrsquhuainan** [comment]
weapp 环境下Uploader组件在Form里上传失败 fileList map is not function
