### ISSUE TITLE
[FR]: Badge position位置值类型与文档值类型不符,且期望css 变量可以支持改变value内容宽度

### ISSUE THREAD

**Issue by codedart2018** [jdf2e/nutui-react#1401]
### 这个功能解决了什么问题？

文档为number类型，实际开发为string类型。
![image](https://github.com/jdf2e/nutui-react/assets/12706830/c446b05f-b5e8-41d1-95f8-aea88557805d)
且期望css 变量可以支持改变value内容宽度，目前是手工绑定css 再修改里面的类。希望能手动变量。
<img width="388" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12706830/fd98bf8b-1007-484f-bfab-169030f76760">

### 你期望的组件设计是怎样的？

实际期望可以number 也可以string

**Comment by oasis-cloud** [comment]
> 且期望css 变量可以支持改变value内容宽度，目前是手工绑定css 再修改里面的类。希望能手动变量。

增加 min-width 可以满足你的需求吗
