### ISSUE TITLE
[FR]: 期望Picker组件也能像级联组件一样有optionKeyt自定义options中的关键字

### ISSUE THREAD

**Issue by codedart2018** [jdf2e/nutui-react#1402]
### 这个功能解决了什么问题？

解决了系统后端不用再单独写个接口输出了，用户可自定义改变options字段进行映射。看了下cascader组件有可以自定义，希望picker组件也可以加上去。

### 你期望的组件设计是怎样的？

和cascader一样。可以自定义value text为用户指定字段

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-react/issues/953
