### ISSUE TITLE
建议:组件 menu菜单 提供遮罩层关闭/打开事件回调处理函数

### ISSUE THREAD

**Issue by liuyunzyj** [jdf2e/nutui-react#1434]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.16

### 平台

h5, weapp, alipay, jd, tt, 其他小程序

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/component/menu

### 重现步骤

![image](https://github.com/jdf2e/nutui-react/assets/40293335/7b0be0d7-52c9-4897-a66d-516e24e700f9)

### 期望的结果是什么？

组件 menu菜单 提供遮罩层关闭/打开事件回调处理函数

### 实际的结果是什么？

组件 menu菜单 未提供遮罩层关闭/打开事件回调处理函数

**Comment by oasis-cloud** [comment]
Menu 组件上有 onOpen 和 onClose 事件，文档上未更新

**Comment by liuyunzyj** [comment]
onOpen 和 onClose 事件没有返回是那个Menu.Item吗？因为要知道是哪个Menu.Item才好对数据处理。
