### ISSUE TITLE
Form组件里放uploader 上传时会报错

### ISSUE THREAD

**Issue by mrsquhuainan** [jdf2e/nutui-react#1439]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.17

### 平台

weapp

### 重现链接

在Form 组件里嵌套一个Uploader组件就能复现

### 重现步骤

在Form 组件里嵌套一个Uploader组件就能复现

![企业微信截图_4a591a93-d8b1-453e-b95f-b4c1818d0129](https://github.com/jdf2e/nutui-react/assets/14908176/a943c033-0e82-4e5d-b2bb-5bd4e4318365)

### 期望的结果是什么？

能够在Form里正常使用Uploader组件

### 实际的结果是什么？

![企业微信截图_4a591a93-d8b1-453e-b95f-b4c1818d0129](https://github.com/jdf2e/nutui-react/assets/14908176/6a88b86a-1d11-4f00-87e2-c4568d009a2c)

**Comment by codedart2018** [comment]
需要你额外处理才行　自己封装下form.item 把upload变成受控的组件就好了

**Comment by codedart2018** [comment]
```
import React from 'react';
import { Form } from '@nutui/nutui-react-taro';
import { UploadFormItemProps } from '@/components/UploadFormItem/types';
import Upload from '../Upload';
import { apiUrl } from '@/utils/request';
import './style.scss';

const UploadFormItem: React.FC<UploadFormItemProps> = (props) => {
  const {
    className,
    style,
    uploadStyle,
    uploadClassName,
    required,
    label,
    name,
    uploadName = 'file',
    maxCount,
    uploadIcon,
    mediaType,
    onChange,
  } = props;

  return (
    <>
      <Form.Item required={required} label={label} name={name} className={className} style={style}>
        <Upload
          style={uploadStyle}
          className={uploadClassName}
          url={`${apiUrl}/weapp/attachment/upload`}
          name={uploadName as string}
          mediaType={mediaType}
          maxCount={maxCount}
          onChange={onChange}
          uploadIcon={uploadIcon}
          // previewType={'list'} //暂时不要使用，有bug list模式下不能正常显示上传按钮
        />
      </Form.Item>
    </>
  );
};

export default UploadFormItem;

```

**Comment by codedart2018** [comment]
upload 组件也要二次封装，自己控制　value onchange事件

**Comment by codedart2018** [comment]
upload组件　也是封装的很无语，只能自己二次上手

**Comment by mrsquhuainan** [comment]
> ```
> import React from 'react';
> import { Form } from '@nutui/nutui-react-taro';
> import { UploadFormItemProps } from '@/components/UploadFormItem/types';
> import Upload from '../Upload';
> import { apiUrl } from '@/utils/request';
> import './style.scss';
> 
> const UploadFormItem: React.FC<UploadFormItemProps> = (props) => {
>   const {
>     className,
>     style,
>     uploadStyle,
>     uploadClassName,
>     required,
>     label,
>     name,
>     uploadName = 'file',
>     maxCount,
>     uploadIcon,
>     mediaType,
>     onChange,
>   } = props;
> 
>   return (
>     <>
>       <Form.Item required={required} label={label} name={name} className={className} style={style}>
>         <Upload
>           style={uploadStyle}
>           className={uploadClassName}
>           url={`${apiUrl}/weapp/attachment/upload`}
>           name={uploadName as string}
>           mediaType={mediaType}
>           maxCount={maxCount}
>           onChange={onChange}
>           uploadIcon={uploadIcon}
>           // previewType={'list'} //暂时不要使用，有bug list模式下不能正常显示上传按钮
>         />
>       </Form.Item>
>     </>
>   );
> };
> 
> export default UploadFormItem;
> ```



> ```
> import React from 'react';
> import { Form } from '@nutui/nutui-react-taro';
> import { UploadFormItemProps } from '@/components/UploadFormItem/types';
> import Upload from '../Upload';
> import { apiUrl } from '@/utils/request';
> import './style.scss';
> 
> const UploadFormItem: React.FC<UploadFormItemProps> = (props) => {
>   const {
>     className,
>     style,
>     uploadStyle,
>     uploadClassName,
>     required,
>     label,
>     name,
>     uploadName = 'file',
>     maxCount,
>     uploadIcon,
>     mediaType,
>     onChange,
>   } = props;
> 
>   return (
>     <>
>       <Form.Item required={required} label={label} name={name} className={className} style={style}>
>         <Upload
>           style={uploadStyle}
>           className={uploadClassName}
>           url={`${apiUrl}/weapp/attachment/upload`}
>           name={uploadName as string}
>           mediaType={mediaType}
>           maxCount={maxCount}
>           onChange={onChange}
>           uploadIcon={uploadIcon}
>           // previewType={'list'} //暂时不要使用，有bug list模式下不能正常显示上传按钮
>         />
>       </Form.Item>
>     </>
>   );
> };
> 
> export default UploadFormItem;
> ```

这样就可以了么？

**Comment by codedart2018** [comment]
> > ```
> > import React from 'react';
> > import { Form } from '@nutui/nutui-react-taro';
> > import { UploadFormItemProps } from '@/components/UploadFormItem/types';
> > import Upload from '../Upload';
> > import { apiUrl } from '@/utils/request';
> > import './style.scss';
> > 
> > const UploadFormItem: React.FC<UploadFormItemProps> = (props) => {
> >   const {
> >     className,
> >     style,
> >     uploadStyle,
> >     uploadClassName,
> >     required,
> >     label,
> >     name,
> >     uploadName = 'file',
> >     maxCount,
> >     uploadIcon,
> >     mediaType,
> >     onChange,
> >   } = props;
> > 
> >   return (
> >     <>
> >       <Form.Item required={required} label={label} name={name} className={className} style={style}>
> >         <Upload
> >           style={uploadStyle}
> >           className={uploadClassName}
> >           url={`${apiUrl}/weapp/attachment/upload`}
> >           name={uploadName as string}
> >           mediaType={mediaType}
> >           maxCount={maxCount}
> >           onChange={onChange}
> >           uploadIcon={uploadIcon}
> >           // previewType={'list'} //暂时不要使用，有bug list模式下不能正常显示上传按钮
> >         />
> >       </Form.Item>
> >     </>
> >   );
> > };
> > 
> > export default UploadFormItem;
> > ```
> 
> > ```
> > import React from 'react';
> > import { Form } from '@nutui/nutui-react-taro';
> > import { UploadFormItemProps } from '@/components/UploadFormItem/types';
> > import Upload from '../Upload';
> > import { apiUrl } from '@/utils/request';
> > import './style.scss';
> > 
> > const UploadFormItem: React.FC<UploadFormItemProps> = (props) => {
> >   const {
> >     className,
> >     style,
> >     uploadStyle,
> >     uploadClassName,
> >     required,
> >     label,
> >     name,
> >     uploadName = 'file',
> >     maxCount,
> >     uploadIcon,
> >     mediaType,
> >     onChange,
> >   } = props;
> > 
> >   return (
> >     <>
> >       <Form.Item required={required} label={label} name={name} className={className} style={style}>
> >         <Upload
> >           style={uploadStyle}
> >           className={uploadClassName}
> >           url={`${apiUrl}/weapp/attachment/upload`}
> >           name={uploadName as string}
> >           mediaType={mediaType}
> >           maxCount={maxCount}
> >           onChange={onChange}
> >           uploadIcon={uploadIcon}
> >           // previewType={'list'} //暂时不要使用，有bug list模式下不能正常显示上传按钮
> >         />
> >       </Form.Item>
> >     </>
> >   );
> > };
> > 
> > export default UploadFormItem;
> > ```
> 
> 这样就可以了么？

需要你二次封装，也就是说把upload重新封装一次把它变成受控的组件，你上传调用upload组件，upload组件，调用onChange事件，返回给form　value 　它不是一个正经的数组。你调用upload 的success方法，你打印file 你看它文件列表就是一个数组不像数组，对象不像对象的东西。反正upload组件封装的很蛋疼。上周我开发，我本来想提is的也没提。
我给你完整我的upload代码，你参考修改吧


```
Upload.tsx

import React, { useEffect, useState } from 'react';
import { fileResConvert, TaroErrorTips, TaroNoneTips } from '@/utils';
import { Button, Cell, Popup, Uploader, Video } from '@nutui/nutui-react-taro';
import { PreviewProps, UploadProps } from '@/components/Upload/types';
import { FileType } from '@nutui/nutui-react-taro/dist/types/packages/uploader/uploader.taro';
import classNames from 'classnames';
import { deleteAttachment } from '@/services/common';
import Taro from '@tarojs/taro';
import SafeArea from '@/components/SafeArea';
import { View } from '@tarojs/components';
import './style.scss';

const Upload: React.FC<UploadProps> = (props) => {
  const {
    className,
    style,
    name,
    value,
    maxCount,
    url,
    sourceType,
    sizeType,
    camera,
    mediaType,
    previewType,
    multiple,
    fit,
    uploadIcon,
    onChange,
    ...other
  } = props;
  const [list, setList] = useState<FileType<string>[]>([]);
  const [preview, setPreview] = useState<PreviewProps>({
    url: '',
    open: false,
  });

  const handleFailure = (options) => {
    if (options?.fileList) {
      //处理失败，把失败的文件移除，给个tips提示
      const res = options.fileList.reduce((val, item) => {
        if (item.status === 'success') {
          val.push(item);
        } else if (options.responseText.statusCode !== 200) {
          TaroErrorTips('上传失败');
        }
        return val;
      }, []);
      setList([...res]);
    }
  };

  const handleSuccess = (options) => {
    if (options?.fileList) {
      const res = options.fileList.reduce((val, item) => {
        //判断状态是否为success
        if (item?.percentage === 100 && options.responseText.statusCode === 200) {
          const parsedData = JSON.parse(options.responseText.data);
          //为组件内部上传
          if (parsedData.code === 0) {
            const data = parsedData.data;
            val.push(fileResConvert(data));
          } else {
            TaroErrorTips('上传失败');
          }
        } else if (item?.status === 'done') {
          //此为后端原有的数据
          val.push(fileResConvert(item));
        } else if (item?.status === 'success') {
          //本列表的success
          val.push(item);
        }
        return val;
      }, []);
      onChange?.([...res]);
      setList([...res]);
    }
  };

  const handleDelete = (options) => {
    //向后台发起删除
    if (options?.id) {
      deleteAttachment({ id: options.id }).then(res => {
        if (res.code === 0) {
          TaroNoneTips('删除成功');
          const index = list.findIndex(function(obj) {
            return obj.id === options.id;
          });
          if (index !== -1) {
            list.splice(index, 1);
            setList([...list]);
            onChange?.([...list]);
          }
        } else {
          TaroErrorTips('删除失败');
        }
      });
    }
  };

  useEffect(() => {
    setList(value || []);
  }, []);

  return (
    <>
      <Uploader
        className={classNames('c-upload', className)}
        name={name}
        url={url}
        maxCount={maxCount}
        sourceType={sourceType}
        sizeType={sizeType}
        mediaType={mediaType}
        camera={camera}
        previewType={previewType}
        fit={fit}
        value={list}
        multiple={multiple}
        uploadIcon={uploadIcon}
        onFailure={handleFailure}
        onSuccess={handleSuccess}
        onDelete={handleDelete}
        {...other}
      />
  
    </>
  );
};

export default Upload;

```

配合上面我贴出的代码使用，就好了。

**Comment by cdx111** [comment]
不用那么麻烦，这样就可以
`function Upload(props: { value: any; onChange: any; token }) {
  return (
    <Uploader
      maxCount={1}
      url={`${process.env.API_DOMAIN}/customer/upload`}
      headers={{
        Authorization: `${props.token}`,
      }}
      name='file'
      value={props.value}
      onChange={(e) => {
        props.onChange(e.fileList);
      }}
      onSuccess={(params) => {
        if ((params.responseText as any).statusCode === 200) {
          const d = JSON.parse((params.responseText as any).data).data;
          props.onChange([
            {
              status: "success",
              uid: 1,
              type: "image",
              url: d,
              name: "credit",
            },
          ]);
        }
      }}
      uploadIcon={<IconFont name='uploader'></IconFont>}
    ></Uploader>
  );
}`

**Comment by Skedush** [comment]
点击upload会触发表单自动提交，怎么解决？
