### ISSUE TITLE
DatePicker的value无法受控

### ISSUE THREAD

**Issue by wangchenglong1234** [jdf2e/nutui-react#1440]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.15

### 平台

weapp

### 重现链接

https://95q5fz-5173.csb.app/

### 重现步骤
一、初始化DatePicker的value值new Date()
二、点击按钮, 设置value为new Date('2021-12-12')
三、查看datepicker日期显示位置

### 期望的结果是什么？

希望根据设置的Date来调整picker项位置

### 实际的结果是什么？

动态设置value的时候，其值在打开时不能正确显示当前位置。（位置是初始化时候的）

**Comment by cdx111** [comment]
同样的问题

**Comment by wangchenglong1234** [comment]
> 同样的问题

目前我的解决方案是，动态去渲染这个组件，每次都初始化。但有个问题是就是没有弹出的动画。

**Comment by wangchenglong1234** [comment]
> 同样的问题

或者是使用picker组件，手动添加时间日期数据，当普通的picker来用。感觉这个库的活跃度并不高，很多组件都还有问题。

**Comment by cdx111** [comment]
> > 同样的问题
> 
> 或者是使用picker组件，手动添加时间日期数据，当普通的picker来用。感觉这个库的活跃度并不高，很多组件都还有问题。

后面我用那个日历组件代替了

**Comment by cdx111** [comment]
这个什么时候可以修复@xiaoyatong

**Comment by cdx111** [comment]
@oasis-cloud
