### ISSUE TITLE
upload组件上传图片会出现裂开的图

### ISSUE THREAD

**Issue by 420509089** [jdf2e/nutui-react#1442]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

1.5.3

### 平台

h5

### 重现链接

https://nutui.jd.com/h5/react/2x/demo.html#/zh-CN/component/Uploader

### 重现步骤

用小米的手机（我的小米11，以及红米k40p，都会出现这个问题），在微博上随便保存一张图片，然后再从upload组件上传

### 期望的结果是什么？

希望解决这个bug

### 实际的结果是什么？

图片预览会出现裂开的图

**Comment by Frank17008** [comment]
看下是不是图片格式的问题，我们遇到过小米或者红米有个高清拍照功能好像，图片格式是 `.HEIC`

**Comment by 420509089** [comment]
> 看下是不是图片格式的问题，我们遇到过小米或者红米有个高清拍照功能好像，图片格式是 `.HEIC`
应该是小米从微博上保存下来的图片转heic格式了，导致图片预览转base64的过程出了问题

**Comment by 420509089** [comment]
应该是小米保存微博的图片转heic格式了，导致图片预览转base64的过程出现了问题
