### ISSUE TITLE
[FR]: Swiper onChange 返回是事件，不是文档上的值，indicator无法正常显示，value命名不规范

### ISSUE THREAD

**Issue by codedart2018** [jdf2e/nutui-react#1450]
### 这个功能解决了什么问题？

小程序端

onChange返回与文档不符，到底是要返回 current number 还是事件
<img width="801" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12706830/d2549c77-462c-4012-bcca-e81eba37bebd">

默认指示器无法正常显示，只能自定义
value 命名不规范。默认defaultValue 一般是指非受控的，value属于受挫。

### 你期望的组件设计是怎样的？

其它参数未做验证，上面希望处理掉。有其它问题再补充！

**Comment by xiaoyatong** [comment]
indicator 无法正常显示：
https://github.com/jdf2e/nutui-react/pull/1474
