### ISSUE TITLE
uploader组件会触发表单的onFinish事件

### ISSUE THREAD

**Issue by suyuan0** [jdf2e/nutui-react#1469]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

18.0.20

### 平台

h5

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/component/form

### 重现步骤

调用uploader组件会触发form的onFinish方法

### 期望的结果是什么？

只上传图片，不进行校验

### 实际的结果是什么？

只上传图片，进行了表单校验

**Comment by Skedush** [comment]
taro版本的h5还是存在这个问题。
