### ISSUE TITLE
Support for defaultProps will be removed from function components in a future major release. 

### ISSUE THREAD

**Issue by kurisu994** [jdf2e/nutui-react#1488]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.18

### 平台

h5

### 重现链接

https://github.com/kurisu994/next-nutui-demo

### 重现步骤

启动后访问 localhost:3000/login页面就会提示。
Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### 期望的结果是什么？

没有这个警告

### 实际的结果是什么？

几乎所有nutui的组件都会有这个警告
![image](https://github.com/jdf2e/nutui-react/assets/26473919/5501bcdf-8720-4216-9817-3ef33e23e5d0)

### 环境信息

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 667.27 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /opt/homebrew/opt/node@18/bin/npm
    Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.6
  npmPackages:
    @nutui/nutui-react: ^2.0.18 => 2.0.18

**Comment by kurisu994** [comment]
最后只能过滤掉这个报错
```js
const error = console.error;
  console.error = (...args: any) => {
    if (/defaultProps/.test(args[0])) return;
    error(...args);
  };
```

**Comment by kkfive** [comment]
同样的问题

**Comment by xian107** [comment]
请问如何解决掉这个报错警告？很烦人！

**Comment by eiinu** [comment]
> 请问如何解决掉这个报错警告？很烦人！

React 版本 <= 18.2.0 时，不会有这个警告。

**Comment by Ttou** [comment]
降成 18.2.0 确实没这个提示了

**Comment by Duuun** [comment]
18.0.0还有

**Comment by imwangpan** [comment]
官方啥时候能修复这个问题呀？最新版 2.6.14 依然会报错：
Warning: o: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at o (webpack-internal:///./node_modules/@nutui/icons-react/dist/es/icons/Marshalling.js:11:171)
