### ISSUE TITLE
[FR]: Menu 菜单组件，如何区分是点击遮罩层关闭还是点击自己自定义按钮通过itemRef?.current?.toggle(false)关闭的，现在好像没有办法区分

### ISSUE THREAD

**Issue by liuyunzyj** [jdf2e/nutui-react#1492]
### 这个功能解决了什么问题？

当用户点击遮罩层关闭，对数据进行回滚到上次选择的条件数据筛选，当用户点击自定义按钮通过itemRef?.current?.toggle(false)关闭的进行用户所选条件数据筛选

### 你期望的组件设计是怎样的？

需要区分是点击遮罩层关闭还是点击自己自定义按钮通过itemRef?.current?.toggle(false)关闭的。

**Comment by oasis-cloud** [comment]
通过 itemRef 方式关闭的话，你可以再关闭语句之后执行数据回滚操作，这样是不是也可完成你的要求。

**Comment by liuyunzyj** [comment]
我需要在，当用户点击遮罩层关闭，对数据进行回滚到上次选择的条件数据筛选，通过 itemRef 方式关闭的话是对用户本次选择的数据筛选条件进行处理。因而用户点击遮罩层关闭和通过 itemRef 方式关闭我处理的数据逻辑是完全不一样的。
