### ISSUE TITLE
css变量配置在app.scss之后不生效

### ISSUE THREAD

**Issue by vulgarLover** [jdf2e/nutui-react#1493]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.17

### 平台

weapp

### 重现链接

https://github.com/vulgarLover/nutui-demo

### 重现步骤

npm install

npm run dev:weapp

### 期望的结果是什么？

全局样式css变量在app.scss配置之后能够生效

### 实际的结果是什么？

没有生效

### 环境信息

� Taro v3.6.16

  Taro CLI 3.6.16 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.16 => 3.6.16
      @tarojs/components: 3.6.16 => 3.6.16
      @tarojs/helper: 3.6.16 => 3.6.16
      @tarojs/plugin-framework-react: 3.6.16 => 3.6.16
      @tarojs/plugin-html: ^3.6.16 => 3.6.16
      @tarojs/plugin-platform-alipay: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-h5: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-jd: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-qq: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-swan: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-tt: 3.6.16 => 3.6.16
      @tarojs/plugin-platform-weapp: 3.6.16 => 3.6.16
      @tarojs/react: 3.6.16 => 3.6.16
      @tarojs/runtime: 3.6.16 => 3.6.16
      @tarojs/shared: 3.6.16 => 3.6.16
      @tarojs/taro: 3.6.16 => 3.6.16
      @tarojs/taro-loader: 3.6.16 => 3.6.16
      @tarojs/webpack5-runner: 3.6.16 => 3.6.16
      babel-preset-taro: 3.6.16 => 3.6.16
      eslint-config-taro: 3.6.16 => 3.6.16
      react: ^18.0.0 => 18.2.0

**Comment by oasis-cloud** [comment]
需要再 config/index.js 中增加如下配置
```
  sass:{
    data: `@import "@nutui/nutui-react-taro/dist/styles/variables.scss";`
  },
```

babel 配置文件中加入如下内容：

```
plugins: [
	[
      "import",
      {
        "libraryName": "@nutui/nutui-react-taro",
        "libraryDirectory": "dist/esm",
        "style": true,
        "camel2DashComponentName": false
      },
      'nutui-react-taro'
    ]
]

```
