### ISSUE TITLE
NoticeBar 公告栏 ，装入等待时间要duration时间才出现，令画面太突然

### ISSUE THREAD

**Issue by clayzx** [jdf2e/nutui-react#1499]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

v2.0.15

### 平台

weapp

### 重现链接

官方提供的DEMO一样有这个问题

### 重现步骤

在垂直模式下，第一次进入，滚动内容需要等待duration时间后才显示，在没显示之前就是空白，这也太突兀了吧。
虽然可以把duration时间改成0来实现立即显示，但是就没有垂直滚动效果了。
我看到之前有一个一样的问题提交，但是现在为什么又回去了呢？
[NoticeBar 公告栏 ，装入等待时间要1秒才出现，令画面太突然 #516](https://github.com/jdf2e/nutui-react/issues/516)

我测试了一下，只需要把137行的
``setTimeout(() => {
  startRollEasy()
}, Number(duration))
``
改为直接调用`startRollEasy()；`就可以了，老板请看下！

另外，在垂直模式下，如果传入的list只有一个元素，滚动也会看起来很怪，会出现空白。
能不能在只有一个元素的情况下就不滚动，或者就1个元素循环滚动，不要出现空白就行。

### 期望的结果是什么？

装载后立即显示第一个，然后再等待duration时间进行滚动。

### 实际的结果是什么？

载入时出现空白，需要等待duration时间后才会出现内容。

### 其他补充信息

我是把NoticeBar放到一个容器中（一个有装饰的Card）显示的，空白期间就一个空容器，看起来太突兀了。。。

**Comment by musicode** [comment]
@oasis-cloud @xiaoyatong
这种明显的低级bug，都没人处理的么？京东的技术能力有点让人怀疑啊
