### ISSUE TITLE
按照官方例子使用Uploader上传文件时报错

### ISSUE THREAD

**Issue by lavender1225** [jdf2e/nutui-react#1506]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.17

### 平台

jd

### 重现链接

内部项目，暂时没有

### 重现步骤

使用代码如下：
`<Uploader
        url="xxx"
        onStart={onStart}
 />`

上传时报错：
<img width="877" alt="image" src="https://github.com/jdf2e/nutui-react/assets/63383303/baff3f88-58d2-4fbb-9e4b-2c5571037395">

### 期望的结果是什么？

能正常上传

### 实际的结果是什么？

目前上传时直接报错

### 环境信息

Taro v3.6.14

**Comment by oasis-cloud** [comment]
内部项目可以内部交流
