### ISSUE TITLE
在微信小程序中，form表单触发required校验之后，input组件输入一个字符就会失去焦点，键盘收回，无法继续输入。官方demo也能复现这个问题

### ISSUE THREAD

**Issue by mjkohoh** [jdf2e/nutui-react#1507]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.18

### 平台

weapp

### 重现链接

官方提供的DEMO一样有这个问题

### 重现步骤

1. 打开官方NutUI React微信小程序，进入数据录入下的Form模块。
2. 在基础用法demo中直接点击提交，触发required校验。
3. 在姓名input中输入一个字符，比如：1。这个时候input就会失去焦点，键盘会收回。需要再次点击input才能继续输入

### 期望的结果是什么？

在微信小程序中，form表单触发required校验之后，input组件输入一个字符后不会失去焦点，可以继续输入。

### 实际的结果是什么？

在微信小程序中，form表单触发required校验之后，input组件输入一个字符后失去焦点，无法继续输入。

### 环境信息

👽 Taro v3.6.17

  Taro CLI 3.6.17 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 3.6.1 - ~/.nvm/versions/node/v18.16.1/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.17 => 3.6.17 
      @tarojs/components: 3.6.17 => 3.6.17 
      @tarojs/helper: 3.6.17 => 3.6.17 
      @tarojs/plugin-framework-react: 3.6.17 => 3.6.17 
      @tarojs/plugin-html: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-alipay: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-h5: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-jd: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-qq: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-swan: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-tt: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-weapp: 3.6.17 => 3.6.17 
      @tarojs/react: 3.6.17 => 3.6.17 
      @tarojs/runtime: 3.6.17 => 3.6.17 
      @tarojs/shared: 3.6.17 => 3.6.17 
      @tarojs/taro: 3.6.17 => 3.6.17 
      @tarojs/taro-loader: 3.6.17 => 3.6.17 
      @tarojs/webpack5-runner: 3.6.17 => 3.6.17 
      babel-preset-taro: 3.6.17 => 3.6.17 
      eslint-config-taro: 3.6.17 => 3.6.17 
      react: ^18.0.0 => 18.2.0

**Comment by mjkohoh** [comment]
下面是我个人项目中触发这个问题的代码片段
```
import React from 'react';
import { View } from '@tarojs/components';
import { Button, Form, Input } from '@nutui/nutui-react-taro';
import './index.scss';

const Login: React.FC = () => {
  const footer = (
    <>
      <Button formType='submit' block type='primary' shape='square'>
        登录
      </Button>
    </>
  );

  const loginHandle = (values: any) => {
    console.log('loginHandle', values);
  };

  return (
    <View>
      <Form
        divider
        footer={footer}
        onFinish={loginHandle}>
        <Form.Item
          name='username'
          required
          rules={[{ required: true, message: '请输入用户名' }]}>
          <Input placeholder='请输入用户名' clearable />
        </Form.Item>
        <Form.Item
          name='password'
          required
          rules={[{ required: true, message: '请输入密码' }]}>
          <Input placeholder='请输入密码' type='password' clearable />
        </Form.Item>
      </Form>
    </View>
  );
};

export default Login;


```

**Comment by mjkohoh** [comment]
下面是我录制的官方demo复现该问题的视频

https://github.com/jdf2e/nutui-react/assets/4298789/4a476543-043d-48df-91b6-200d726bd72d

**Comment by codedart2018** [comment]
同样有此问题，之前是无法消除警告提示，现在是验证失去焦点

**Comment by mjkohoh** [comment]
我邪恶的修改了formitem.taro.tsx，给errorMessage外面加了一个div，然后bug就不再出现了。当然，这个div我加的很邪恶。

![WX20230927-120128@2x](https://github.com/jdf2e/nutui-react/assets/4298789/89dc2e29-f704-4fd3-bacb-9b70cb97499f)

**Comment by codedart2018** [comment]
> 我邪恶的修改了formitem.taro.tsx，给errorMessage外面加了一个div，然后bug就不再出现了。当然，这个div我加的很邪恶。
> 
> ![WX20230927-120128@2x](https://user-images.githubusercontent.com/4298789/270858553-89dc2e29-f704-4fd3-bacb-9b70cb97499f.png)

等着修复处理吧

**Comment by WweiweiSmile** [comment]
可以给 Input 组件添加 autoFocus 属性，解决这个问题

**Comment by desiyc** [comment]
页面中有多个 Input 组件，添加了autoFocus之后会造成软键盘反复弹起

**Comment by Phyzait** [comment]
`"@nutui/nutui-react-taro": "^2.3.11"` 2.3.11 `taro weapp`也出现了这个问题，官方demo并没有问题，很神奇
```tsx
export default () => {
  const [form] = Form.useForm();
  const onSubmit = async (params: Record<string, any>) => {
    const { pwd, newPwd, confirmPwd } = params;

    console.log(pwd, newPwd, confirmPwd);
  };

  return (
    <View className={styles.page}>
      <Form className={styles.form} form={form} onFinish={onSubmit}>
        <Form.Item
          label="旧密码"
          name="pwd"
          rules={[
            {
              required: true,
              validator: (_, value) => {
                if ((value ?? "").length < 6) {
                  return false;
                }
                return true;
              },
              message: "密码格式不正确",
            },
          ]}
        >
          <Input
            type="password"
            maxLength={30}
            placeholder="请输入旧密码"
            clearable
          />
        </Form.Item>
        <Form.Item
          label="新密码"
          name="newPwd"
          rules={[
            {
              required: true,
              validator: (_, value) => {
                if ((value ?? "").length < 6) {
                  return false;
                }
                return true;
              },
              message: "密码格式不正确",
            },
            {
              required: true,
              validator: (_, value) => {
                return form.getFieldValue("pwd") != value;
              },
              message: "旧密码与新密码不能一致",
            },
          ]}
        >
          <Input
            type="password"
            maxLength={30}
            placeholder="请输入新密码"
            clearable
          />
        </Form.Item>

        <Form.Item
          label="确认密码"
          name="confirmPwd"
          rules={[
            {
              required: true,
              validator: (_, value) => {
                return form.getFieldValue("newPwd") == value;
              },
              message: "新旧密码不一致",
            },
          ]}
        >
          <Input
            type="password"
            maxLength={30}
            placeholder="请输入新密码"
            clearable
          />
        </Form.Item>
      </Form>

      <Button
        formType="submit"
        className={styles.btn_submit}
        onClick={form.submit}
      >
        确 认
      </Button>
    </View>
  );
};

```
