### ISSUE TITLE
Ellipsis 文本省略不起作用，没有省略号

### ISSUE THREAD

**Issue by Aristodemusa** [jdf2e/nutui-react#1510]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.18

### 平台

h5

### 重现链接

xxx

### 重现步骤

<Ellipsis
          content=“女扮男装的沈清笛自愿入九王府，与半身不遂又脾气火爆的崔兰溪相依为命。府上揭不开锅，她独自担起担子，赚钱养王爷，王爷有病，她自学医术诊治。崔兰溪不中用，就由沈清笛来保护他。此处无财无宝，更没有人了解她到底图的什么。豫章故郡，洪都新府，阴雨绵绵的蛮荒之地，她图的不过是个遮风挡雨的家。”
          expandText="展开"
          collapseText="收起"
        />

### 期望的结果是什么？

在两三行的时候会有省略号，展开折叠效果

### 实际的结果是什么？

没有省略号及折叠

**Comment by Me-UserName** [comment]
2.0.24还是错误，官方示例也是不起作用

**Comment by cdx111** [comment]
请提供示例代码，谢谢

**Comment by atom-shanghai** [comment]
import  React from "react";
import { Ellipsis, Cell } from '@nutui/nutui-react';

const App = () => {
  const content =
    'NutUI3.0上线后我们研发团队也在不断的优化、测试、使用、迭代 Vue3 的相关组件，但是在跨端小程序的开发过程中，发现没有合适的组件库可以支持多端开发。为了填补这一空白，同时为了优化开发者体验，让 NutUI 能够为更多的开发者带来便利，我们决定在 NutUI 中增加小程序多端适配的能力。'
  return (
    <Cell>
    <Ellipsis content={content} direction="end"/>
    </Cell>
  );
};
export default App;

**Comment by ukvytw18** [comment]
官方示例都是有问题的  https://nutui.jd.com/taro/react/2x/#/zh-CN/component/ellipsis

**Comment by shaohuahuang** [comment]
> 官方示例都是有问题的 https://nutui.jd.com/taro/react/2x/#/zh-CN/component/ellipsis

确实是有问题

**Comment by Me-UserName** [comment]
能否尽快把这个处理掉
