### ISSUE TITLE
Form组件 FormItem initialValue不会被提交

### ISSUE THREAD

**Issue by Phyzait** [jdf2e/nutui-react#1511]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.18

### 平台

h5

### 重现链接

xxx

### 重现步骤

FormItem设置initialValue后，不对表单做任何操作，直接点击提交

### 期望的结果是什么？

设置了initialValue后，及时不对表单进行操作onFinish时也应该提交

### 实际的结果是什么？

设置了initialValue后，onFinish时值并未提交上来

**Comment by Phyzait** [comment]
补充信息：Form与FormItem同时设置了initialValue，但是Form的initialValue是空对象{}，不存在该name

**Comment by oasis-cloud** [comment]
可以一份可复现的 Demo ，Form 上的初始值优先级高于 FormItem 上的初始值。也可通过 ref 提供的 setFieldsValue 控制 Form 的值
