### ISSUE TITLE
[FR]: DatePicker onClose　重复多次执行，且需要添加一个onCancel方法来区分是确认还是取消

### ISSUE THREAD

**Issue by codedart2018** [jdf2e/nutui-react#1524]
### 这个功能解决了什么问题？

在onClose console的时候重复执行至少2两次，如果只是从蒙层关闭的话onClose只会执行一次。
另需要增加onCancel方法，现在的情况确认和onClose都会执行onClose　我根本分不清是点击的确认按钮还是点击的取消按钮。点击取消我需要单独做事情，而不是在onClose里去做处理。

### 你期望的组件设计是怎样的？

增加 onCancel 方法来严格区分确认和取消事件

**Comment by codedart2018** [comment]
准确的来说应该是从popup就应该增加 onCancel 方法

**Comment by cdx111** [comment]
遇到同样的问题

**Comment by cdx111** [comment]
遇到同样的问题
