### ISSUE TITLE
自定义主题失效

### ISSUE THREAD

**Issue by dingminghui** [jdf2e/nutui-react#1526]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.15

### 平台

weapp

### 重现链接

https://github.com/dingminghui/taro-demo

### 重现步骤

直接通过 taro 生成选择模版 react-NutUI

按照方法二自定义主题，打包后不生效
https://nutui.jd.com/taro/react/2x/#/zh-CN/guide/theme-react

### 期望的结果是什么？

自定义主题生效

### 实际的结果是什么？

不生效
![image](https://github.com/jdf2e/nutui-react/assets/49083552/4083913b-452f-401d-9132-68a45a120730)

### 环境信息

👽 Taro v3.6.17

  Taro CLI 3.6.17 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.8.1 - /opt/homebrew/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.17 => 3.6.17 
      @tarojs/components: 3.6.17 => 3.6.17 
      @tarojs/helper: 3.6.17 => 3.6.17 
      @tarojs/plugin-framework-react: 3.6.17 => 3.6.17 
      @tarojs/plugin-html: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-alipay: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-h5: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-jd: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-qq: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-swan: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-tt: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-weapp: 3.6.17 => 3.6.17 
      @tarojs/react: 3.6.17 => 3.6.17 
      @tarojs/runtime: 3.6.17 => 3.6.17 
      @tarojs/shared: 3.6.17 => 3.6.17 
      @tarojs/taro: 3.6.17 => 3.6.17 
      @tarojs/taro-loader: 3.6.17 => 3.6.17 
      @tarojs/webpack5-runner: 3.6.17 => 3.6.17 
      babel-preset-taro: 3.6.17 => 3.6.17 
      eslint-config-taro: 3.6.17 => 3.6.17 
      react: ^18.0.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 5.0.2

**Comment by oasis-cloud** [comment]
通过 sass 自定义主题，babel 配置中的 style 选项不能用 css，应该将是 style 设置为 true

**Comment by oasis-cloud** [comment]
```js
plugins: [
    [
      "import",
      {
        "libraryName": "@nutui/nutui-react",
        "libraryDirectory": "dist/esm",
        "style": true,
        "camel2DashComponentName": false
      },
      'nutui-react'
    ]
  ]
```

**Comment by dingminghui** [comment]
@oasis-cloud 谢谢
