### ISSUE TITLE
在calendar.scss底部定义的nut-popup__close-icon样式导致--nutui-popup-close-icon-margin失效

### ISSUE THREAD

**Issue by clayzx** [jdf2e/nutui-react#1528]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

v2.0.15

### 平台

weapp

### 重现链接

无

### 重现步骤

在calendar.scss最底部的这个样式，

.nut-popup__close-icon {
  top: 7px !important;
}

在全量引入的情况下，会影响所有弹出层的close的top位置，导致--nutui-popup-close-icon-margin变量设置无效。

建议把这个样式移动到.nut-calendar内部，如：

.nut-calendar {
    ......
    .nut-popup__close-icon {
      top: 7px !important;
    }
}

### 期望的结果是什么？

通过--nutui-popup-close-icon-margin能正常设置popup的关闭按钮位置

### 实际的结果是什么？

被calendar.scss中定义的nut-popup__close-icon样式覆盖了

**Comment by xiaoyatong** [comment]
嗯确实有这个问题，我们在next-theme里升级了这部分的布局结构，但是需要等到月底或者下月初才能发版。
