### ISSUE TITLE
menuitem 编译为h5页面滑动提示 p.getBoundingClientRect(...).then is not a function

### ISSUE THREAD

**Issue by liuyunzyj** [jdf2e/nutui-react#1546]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.20

### 平台

h5

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/component/menu

### 重现步骤

使用menu、menuitem组件编译为h5，滑动页面将会报错如图。![image](https://github.com/jdf2e/nutui-react/assets/40293335/9b232f74-a3d1-44ba-b1aa-b06ff89f6953)

### 期望的结果是什么？

解决一下图片上的错误![image](https://github.com/jdf2e/nutui-react/assets/40293335/0a1ca5a0-eabb-4ffe-9a33-bd820cd4ee30)

### 实际的结果是什么？

![image](https://github.com/jdf2e/nutui-react/assets/40293335/3c5f7a0b-9b57-4c03-9fe6-bee8d817d513)

**Comment by oasis-cloud** [comment]
taro 下请使用 @nutui/nutui-react-taro 包

**Comment by oasis-cloud** [comment]
可以详细描述下组件的使用方式，问题的复现步骤
