### ISSUE TITLE
Calendar 组件编译为h5页面滑动Calendar 组件提示 Cannot read properties of undefined (reading 'scrollTop')

### ISSUE THREAD

**Issue by liuyunzyj** [jdf2e/nutui-react#1547]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.20

### 平台

h5

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/component/calendar

### 重现步骤

![image](https://github.com/jdf2e/nutui-react/assets/40293335/514b969d-671c-4315-8c43-b321303fd03a)

### 期望的结果是什么？

不报错

### 实际的结果是什么？

![image](https://github.com/jdf2e/nutui-react/assets/40293335/f2fecca9-82ee-415b-a77c-5e2027f0d39f)

**Comment by oasis-cloud** [comment]
taro 下请使用 @nutui/nutui-react-taro 包
