### ISSUE TITLE
Image 组件样式被破坏了

### ISSUE THREAD

**Issue by hellohejinyu** [jdf2e/nutui-react#1554]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.21

### 平台

weapp

### 重现链接

https://codesandbox.io/p/sandbox/nutui-react-2x-demo-fg4vxd?file=/src/App.tsx

### 重现步骤

小程序端才会被影响，所以上面的复现链接没用，不用看。

https://github.com/jdf2e/nutui-react/blob/503df58b20a7bca3ae04d3e620ebef0dfcfc69e1/src/packages/image/image.taro.tsx#L65

这里的 `100px` 是否为误写，它破坏了之前的样式。

### 期望的结果是什么？

我觉得这里应该是 `100%`，不是 `100px`

### 实际的结果是什么？

造成已有页面的 Image 组件显示有问题

**Comment by xiaoyatong** [comment]
默认需要给 height 赋值的，如果是100% 不会生效。

**Comment by hellohejinyu** [comment]
新版本这个 100px 搞的 Avatar 组件都没法用了，图片都是拉伸状态。

<img width="1470" alt="image" src="https://github.com/jdf2e/nutui-react/assets/8766034/159d5aef-6ff3-4fa7-9700-bd6dfb8838e1">

下面是旧版本的正常表现
<img width="234" alt="image" src="https://github.com/jdf2e/nutui-react/assets/8766034/1b449457-3926-4543-ab40-23f233e5e1aa">

**Comment by w960603** [comment]
果然是组件库搞的鬼，搞这种破坏性的操作，真是害人不浅啊。。

**Comment by cdx111** [comment]
你自己重新设置一个高度不行吗

**Comment by hellohejinyu** [comment]
> 你自己重新设置一个高度不行吗

当然可以，但是那意味着需要过一遍项目中所有的 Avatar 和 Image 以及潜在用到 Image 的组件。改完之后还得再验证一下页面上展示是否正确。这个工作量估计不小。
