### ISSUE TITLE
Uploader 中的 fit 属性无效，无法控制图片的 mode

### ISSUE THREAD

**Issue by hellohejinyu** [jdf2e/nutui-react#1555]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.21

### 平台

weapp

### 重现链接

https://codesandbox.io/p/sandbox/nutui-react-2x-demo-fg4vxd?file=/src/App.tsx

### 重现步骤

我看代码里面图片的 mode 是写死的值 aspectFit。

https://github.com/jdf2e/nutui-react/blob/e1fcb4bff93ad24acfdaacbd86caf68020edfc93/src/packages/uploader/preview.taro.tsx#L70

会造成上传的图片全部有白边。
<img width="463" alt="image" src="https://github.com/jdf2e/nutui-react/assets/8766034/d4db3aac-661b-40a5-befa-5ba82de8f6df">

### 期望的结果是什么？

fit 能够正常工作

### 实际的结果是什么？

没有按照预计工作

**Comment by beginnerZhang** [comment]
fix(Uploader): 设置fit 属性无效 #1559

**Comment by xiaochunyu** [comment]
这个功能在2.6.14版本中还是没有的。
