### ISSUE TITLE
[FR]: Uploader 组件上传 在h5环境兼容上传视频文件

### ISSUE THREAD

**Issue by liuyunzyj** [jdf2e/nutui-react#1556]
### 这个功能解决了什么问题？

Uploader 组件上传 在h5环境兼容上传视频文件

### 你期望的组件设计是怎样的？

Uploader 组件上传 在h5环境兼容上传视频文件

**Comment by oasis-cloud** [comment]
iOS 真机测试中上传视频没有选择视频后无响应，效果和 PC 不一致
