### ISSUE TITLE
react-taro版本的Form组件没有暴露getFieldsValue方法

### ISSUE THREAD

**Issue by desiyc** [jdf2e/nutui-react#1561]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.14

### 平台

weapp

### 重现链接

https://codesandbox.io/p/sandbox/nutui-react-2x-demo-fg4vxd?file=/src/App.tsx

### 重现步骤

打印form实例化对象发现没有getFieldsValue方法

### 期望的结果是什么？

期望能够有getFieldsValue方法

### 实际的结果是什么？

没有getFieldsValue方法

**Comment by desiyc** [comment]
![image](https://github.com/jdf2e/nutui-react/assets/74251905/246ebad4-4689-4a60-868a-20a0ec309db0)

**Comment by oasis-cloud** [comment]
可升级到最新的 nutui react 版本，从 2.0.18之后的版本提供了getFieldsValue
