### ISSUE TITLE
图标按钮失效

### ISSUE THREAD

**Issue by Me-UserName** [jdf2e/nutui-react#1572]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.x

### 平台

weapp

### 重现链接

无

### 重现步骤

<Button shape="square" type="primary" icon="star">收藏</Button>

### 期望的结果是什么？

图标可以展示，建议Icon 用<iconName />的方式，<Button shape="square" type="primary" icon={<iconName />}>收藏</Button>

### 实际的结果是什么？

无图标，icon="name" 显示出来的是 name ，非图标

**Comment by xiaoyatong** [comment]
看看这个文档有没有帮助
https://nutui.jd.com/h5/react/2x/#/zh-CN/component/icon
