### ISSUE TITLE
Avatar无接触校验失败状态

### ISSUE THREAD

**Issue by iamzhangxin** [jdf2e/nutui-react#1574]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.15

### 平台

weapp, tt

### 重现链接

https://codesandbox.io/p/sandbox/sleepy-dream-s39zw6

### 重现步骤

```
function App() {
  
  const [form] = useForm();

  const chooseAvatar = async (event: any) => {
    // const res = await uploadFilePromise('avatar/user/', avatarUrl, 'user');
    const fileUrl = "https://img1.baidu.com/it/u=3129770633,3933811923&fm=253&fmt=auto&app=138&f=JPEG?w=889&h=500";
    form.setFieldsValue({avatarUrl: fileUrl});
  };

  return (
    <Form
        divider
        form={form}
        labelPosition='left'
        onFinishFailed={(values: any, error: any) => console.log(values, error)}
        footer={
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              width: '100%',
            }}
          >
            <Button formType='submit' type='primary'>
              提交
            </Button>
          </div>
        }
      >
        <FormItem
          label='头像'
          name='avatarUrl'
          valuePropName='src'
          rules={[{required: true, message: "请上传头像"}]}
        >
          <Avatar
            size='large'
          >
            <Button openType='chooseAvatar' className='x-hidden-button'
              onChooseAvatar={(event) => chooseAvatar(event)}
            ></Button>
          </Avatar>
        </FormItem>
      </Form>
  );
}
```

export default App;
先点击提交，校验失败之后，上传了头像之后。校验不消失

### 期望的结果是什么？

上传了头像之后。校验消失

### 实际的结果是什么？

上传了头像之后。校验不消失

### 环境信息

👽 Taro v3.6.16

  Taro CLI 3.6.16 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.17.1 - D:\nvm\nodejs\node.EXE
      Yarn: 1.22.19 - D:\nvm\nodejs\yarn.CMD
      npm: 10.0.0 - D:\nvm\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.17 => 3.6.17 
      @tarojs/components: 3.6.17 => 3.6.17 
      @tarojs/helper: 3.6.17 => 3.6.17 
      @tarojs/plugin-framework-react: 3.6.17 => 3.6.17 
      @tarojs/plugin-html: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-alipay: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-h5: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-jd: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-qq: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-swan: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-tt: 3.6.17 => 3.6.17
      @tarojs/plugin-platform-weapp: 3.6.17 => 3.6.17
      @tarojs/plugin-react-devtools: ^3.6.18 => 3.6.18
      @tarojs/react: 3.6.17 => 3.6.17
      @tarojs/runtime: 3.6.17 => 3.6.17
      @tarojs/shared: 3.6.17 => 3.6.17
      @tarojs/taro: 3.6.17 => 3.6.17
      @tarojs/taro-loader: 3.6.17 => 3.6.17
      @tarojs/webpack5-runner: 3.6.17 => 3.6.17
      babel-preset-taro: 3.6.17 => 3.6.17
      eslint-config-taro: 3.6.17 => 3.6.17
      react: ^18.0.0 => 18.2.0

### 其他补充信息

无

**Comment by oasis-cloud** [comment]
Form 的校验触发实际在子组件的 onChange 时，上面的例子中可以给 Avatar 进行封装，提供 onChange 方法。FormItem 下的组件需是受控组件，才满足 FormItem 的使用条件。
