### ISSUE TITLE
input 初始化赋值和在form组件中验证问题

### ISSUE THREAD

**Issue by zcrkey** [jdf2e/nutui-react#1575]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.22

### 平台

h5

### 重现链接

https://codesandbox.io/p/sandbox/rough-meadow-9vs6ww?file=%2Fsrc%2FApp.tsx%3A7%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clno838t70009356l7577suoz%2522%252C%2522sizes%2522%253A%255B69.76498237367802%252C30.235017626321977%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clno838t60004356lc4t74k6z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clno838t70006356l334mt5ff%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clno838t70008356ltpmth622%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clno838t60004356lc4t74k6z%2522%253A%257B%2522id%2522%253A%2522clno838t60004356lc4t74k6z%2522%252C%2522activeTabId%2522%253A%2522clno838t60003356lju2u8c43%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clno838t60003356lju2u8c43%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clnsc4dwg002e356k0cixa76p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clno838t70008356ltpmth622%2522%253A%257B%2522id%2522%253A%2522clno838t70008356ltpmth622%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clno838t70007356l88zf78bn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clno838t70007356l88zf78bn%2522%257D%252C%2522clno838t70006356l334mt5ff%2522%253A%257B%2522id%2522%253A%2522clno838t70006356l334mt5ff%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clno838t70005356l1p93khob%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clno838t70005356l1p93khob%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 重现步骤

1、在input组件赋值的时候，没有正确赋值，代码如下
```
<FormItem name="text1"  label="文本1" required rules={[{ required: true, message: `请输入文本` }]}>
<Input value="2" />
</FormItem>
```

2、点击提交按钮之后，初始化的值未能通过表单验证

### 期望的结果是什么？

初始化赋值之后，点击提交按钮，能够通过表单验证

### 实际的结果是什么？

点击提交按钮，已经有赋值的字段，实际上未能通过表单验证

### 环境信息

Taro CLI 3.6.17 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.14.0 - D:\Program Files\nodejs\node.EXE 
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD   
      npm: 8.3.1 - D:\Program Files\nodejs\npm.CMD     
    npmPackages:
      @tarojs/cli: 3.6.17 => 3.6.17 
      @tarojs/components: 3.6.17 => 3.6.17 
      @tarojs/components-rn: ^3.6.17 => 3.6.17         
      @tarojs/helper: 3.6.17 => 3.6.17 
      @tarojs/plugin-framework-react: 3.6.17 => 3.6.17 
      @tarojs/plugin-html: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-alipay: 3.6.17 => 3.6.17 
      @tarojs/plugin-platform-h5: 3.6.17 => 3.6.17     
      @tarojs/plugin-platform-jd: 3.6.17 => 3.6.17     
      @tarojs/plugin-platform-qq: 3.6.17 => 3.6.17     
      @tarojs/plugin-platform-swan: 3.6.17 => 3.6.17   
      @tarojs/plugin-platform-tt: 3.6.17 => 3.6.17     
      @tarojs/plugin-platform-weapp: 3.6.17 => 3.6.17  
      @tarojs/react: 3.6.17 => 3.6.17 
      @tarojs/rn-runner: ^3.6.17 => 3.6.17 
      @tarojs/rn-supporter: ^3.6.17 => 3.6.17 
      @tarojs/runtime: 3.6.17 => 3.6.17 
      @tarojs/runtime-rn: ^3.6.17 => 3.6.17 
      @tarojs/shared: 3.6.17 => 3.6.17 
      @tarojs/taro: 3.6.17 => 3.6.17 
      @tarojs/taro-loader: 3.6.17 => 3.6.17 
      @tarojs/taro-rn: ^3.6.17 => 3.6.17 
      @tarojs/webpack5-runner: 3.6.17 => 3.6.17        
      babel-preset-taro: 3.6.17 => 3.6.17 
      eslint-config-taro: 3.6.17 => 3.6.17 
      expo: ~47.0.3 => 47.0.14 
      react: ^18.1.0 => 18.2.0 
      react-native: ^0.70.5 => 0.70.13

**Comment by oasis-cloud** [comment]
在 form 中使用 input 通过 formItem 的 initialValue 或 from 的 initialValue 设置
