### ISSUE TITLE
[FR]:  编译微信小程序 解决多个页面使用相同组件样式编译警告

### ISSUE THREAD

**Issue by liuyunzyj** [jdf2e/nutui-react#1587]
### 这个功能解决了什么问题？

![image](https://github.com/jdf2e/nutui-react/assets/40293335/b108e0a6-8343-43b3-a9e8-7e51a0fd64e4)

### 你期望的组件设计是怎样的？

![image](https://github.com/jdf2e/nutui-react/assets/40293335/e4814b84-a0e4-41ec-8328-19329c85c244)

**Comment by eiinu** [comment]
在配置中可以屏蔽该警告
```js
// config/index.js
export default {
  mini: {
    miniCssExtractPluginOption: {
      ignoreOrder: true
    }
  }
}
```

**Comment by liuyunzyj** [comment]
屏蔽该警告,我是知道呀，这个不是重复引用了吗？没有办法解决吗？

**Comment by eiinu** [comment]
https://github.com/jdf2e/nutui-react/discussions/1324#discussioncomment-8795338
