### ISSUE TITLE
表单必填项校验时机

### ISSUE THREAD

**Issue by Linxiaoxxx** [jdf2e/nutui-react#1589]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.5

### 平台

weapp

### 重现链接

无

### 重现步骤

在校验的时候，刚输入一个字符，光标会消失，真机则会收起键盘
如何将校验时机改为用户输入完成，validateTrigger应该设置为什么值，文档也并没有说明
![image](https://github.com/jdf2e/nutui-react/assets/28133060/b6ca7257-32fb-4785-8473-3fc72f22782a)
![image](https://github.com/jdf2e/nutui-react/assets/28133060/a9691809-6f5a-4c99-a187-bc90c2f18cfa)

### 期望的结果是什么？

用户输入完成再校验

### 实际的结果是什么？

只要输入一个字符，就会光标消失，真机则收起键盘

**Comment by xiaoyatong** [comment]
升级一下版本试试。

**Comment by Linxiaoxxx** [comment]
> 升级一下版本试试。

可以了 谢谢
