### ISSUE TITLE
Collapse.Item编译为h5页面提示"createSelectorQuery is not a function"

### ISSUE THREAD

**Issue by aukufddxxyy** [jdf2e/nutui-react#1594]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.23

### 平台

h5

### 重现链接

https://github.com/aukufddxxyy/selectorQuery.git

### 重现步骤

`npm run dev`
<img width="323" alt="image" src="https://github.com/jdf2e/nutui-react/assets/66539808/8fb7fa90-932c-4965-bf4a-51e2a2f674bc">

### 期望的结果是什么？

不应该有"createSelectorQuery is not a function"的报错

### 实际的结果是什么？

_tarojs_taro__WEBPACK_IMPORTED_MODULE_2___default(...).createSelectorQuery is not a function

### 环境信息

👽 Taro v3.6.18

  Taro CLI 3.6.18 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.7.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 10.1.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.18 => 3.6.18 
      @tarojs/components: 3.6.18 => 3.6.18 
      @tarojs/helper: 3.6.18 => 3.6.18 
      @tarojs/plugin-framework-react: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-alipay: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-h5: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-jd: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-qq: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-swan: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-tt: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-weapp: 3.6.18 => 3.6.18 
      @tarojs/react: 3.6.18 => 3.6.18 
      @tarojs/runtime: 3.6.18 => 3.6.18 
      @tarojs/shared: 3.6.18 => 3.6.18 
      @tarojs/taro: 3.6.18 => 3.6.18 
      @tarojs/taro-loader: 3.6.18 => 3.6.18 
      @tarojs/webpack5-runner: 3.6.18 => 3.6.18 
      babel-preset-taro: 3.6.18 => 3.6.18 
      eslint-config-taro: 3.6.18 => 3.6.18 
      react: ^18.0.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 4.8.4

**Comment by eiinu** [comment]
需要在 prebundle 配置中屏蔽组件库：

```js
// config/index.js
export defualt {
  compiler: {
    type: 'webpack5',
    prebundle: {
      exclude: ['@nutui/nutui-react-taro', '@nutui/icons-react-taro']
    }
  },
}
```

**Comment by aukufddxxyy** [comment]
解决了！谢谢
