### ISSUE TITLE
npm run dev 时报错

### ISSUE THREAD

**Issue by Just-focus** [jdf2e/nutui-react#160]
npm run dev 时报错

```jsx
Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2019", "firefox78", "safari13.1")
```

<img width="471" alt="image" src="https://user-images.githubusercontent.com/18374969/179201878-e3458c9d-35cf-44a3-a1f4-be3f5bb7f307.png">

**Comment by oasis-cloud** [comment]
安装 lzutf8 0.6.0 版本
