### ISSUE TITLE
datepicker主题定制 样式变量失效

### ISSUE THREAD

**Issue by mortyhuang** [jdf2e/nutui-react#1611]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.24

### 平台

weapp, tt

### 重现链接

https://codesandbox.io/p/sandbox/nutui-react-2x-demo-fg4vxd?file=%2Fsrc%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clovm3vww00093b6jivxy3s5j%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clovm3vwv00043b6jzldfghns%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clovm3vwv00063b6jhpmrodg2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clovm3vwv00083b6ju9v7ccyo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B72.38255409394228%252C27.617445906057725%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clovm3vwv00043b6jzldfghns%2522%253A%257B%2522id%2522%253A%2522clovm3vwv00043b6jzldfghns%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clovm3vwv00033b6jizrabyeo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clovm3vwv00033b6jizrabyeo%2522%257D%252C%2522clovm3vwv00083b6ju9v7ccyo%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clovm3vwv00073b6judjsmzuf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clovm3vwv00083b6ju9v7ccyo%2522%252C%2522activeTabId%2522%253A%2522clovm3vwv00073b6judjsmzuf%2522%257D%252C%2522clovm3vwv00063b6jhpmrodg2%2522%253A%257B%2522id%2522%253A%2522clovm3vwv00063b6jhpmrodg2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clovm3vwv00053b6jo999w14d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clovmaeyc00h23b6jme2cml84%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clovmafbl0008ehhp33i7de5i%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clovm3vwv00053b6jo999w14d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 重现步骤

在taro 3.6.19里面直接预览小程序
```ts
import { ConfigProvider, DatePicker } from "@nutui/nutui-react-taro";

const App = () => {
  const Theme = {
    nutuiPickerItemHeight: "88px",
    nutuiPickerItemActiveTextColor: "#ff79ab",
    nutuiPickerItemActiveLineBorder: "#ff79ab",
    nutuiPickerItemTextColor: "#ff79ab",
  };
  return (
    <>
      <ConfigProvider theme={Theme}>
        <div className="custom-picker">
          <DatePicker title="宝宝生日" visible showChinese />
        </div>
      </ConfigProvider>
    </>
  );
};
export default App;

```

### 期望的结果是什么？

对应的颜色和高度变化

### 实际的结果是什么？

颜色和高度没有如何变化

### 环境信息

```sh
Taro CLI 3.6.19 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/Library/Caches/fnm_multishells/32578_1699778940851/bin/node
      npm: 8.19.3 - ~/Library/Caches/fnm_multishells/32578_1699778940851/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.19 => 3.6.19 
      @tarojs/components: 3.6.16 => 3.6.16 
      @tarojs/helper: 3.6.16 => 3.6.16 
      @tarojs/mini-runner: 3.6.16 => 3.6.16 
      @tarojs/plugin-framework-react: 3.6.16 => 3.6.16 
      @tarojs/plugin-html: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-alipay: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-h5: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-jd: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-qq: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-swan: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-tt: 3.6.16 => 3.6.16 
      @tarojs/plugin-platform-weapp: 3.6.16 => 3.6.16 
      @tarojs/react: 3.6.16 => 3.6.16 
      @tarojs/runtime: 3.6.16 => 3.6.16 
      @tarojs/shared: 3.6.16 => 3.6.16 
      @tarojs/taro: 3.6.16 => 3.6.16 
      @tarojs/taro-loader: 3.6.16 => 3.6.16 
      @tarojs/webpack5-runner: 3.6.16 => 3.6.16 
      babel-preset-taro: 3.6.16 => 3.6.16 
      eslint-config-taro: 3.6.16 => 3.6.16 
      react: ^18.0.0 => 18.2.0 
```

**Comment by xiaoyatong** [comment]
nutuiPickerItemActiveTextColor 这个废弃了~ 其他的修订后可用~
