### ISSUE TITLE
popup visible快速改变时为false时不关闭

### ISSUE THREAD

**Issue by ZCY-G** [jdf2e/nutui-react#1638]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.0

### 平台

weapp

### 重现链接

无

### 重现步骤

```tsx
visible={
  latestFamilyBenefit?.dateTo &&
  !isPast(new Date(latestFamilyBenefit?.dateTo)) &&
  familyById?.createdBy?.id === userId.toString() &&
  (!familyMealPreferences || familyMealPreferences.length === 0) &&
  mealPreference
}
```
除了`mealPreference`是state，其他都是网络请求获取，会在短时间内改变多次
<img width="245" alt="截屏2023-11-15 11 36 05" src="https://github.com/jdf2e/nutui-react/assets/59002875/c4ff020c-9190-409e-b202-b99dc7b6f6d3">

### 期望的结果是什么？

自动关闭popup

### 实际的结果是什么？

不关闭popup，且由于visible为false，无法关闭

**Comment by oasis-cloud** [comment]
> 除了mealPreference是state，其他都是网络请求获取，会在短时间内改变多次
其他都是网络请求获取，怎么赋值？无 state 变化，组件会更新吗？

**Comment by ZCY-G** [comment]
1. `latestFamilyBenefit`、`familyById`和`familyMealPreferences`来自服务器返回的数据，截图展示的是和visible参数对应的值
2. 不需要state变化，传入的props改变时对应组件会更新
