### ISSUE TITLE
在已有的云开发 Taro 项目中引入 NutUI React后报错无法正常运行

### ISSUE THREAD

**Issue by leeeero** [jdf2e/nutui-react#1646]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.24

### 平台

weapp

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/guide/start-react

### 重现步骤

1. 按照https://nutui.jd.com/taro/react/2x/#/zh-CN/guide/start-react文档里的说明依次安装了对应的安装包并且修改了配置后
2. 执行npm run dev:weapp
3. 终端出现error提示：
`No matching export in "node_modules/@tarojs/runtime/dist/runtime.esm.js" for import "isHasExtractProp"
node_modules/@tarojs/plugin-html/dist/runtime.js:1:9:
      1 │ import { isHasExtractProp } from '@tarojs/runtime';`
微信开发者工具白屏，切控制台出现报错：
`VM1418:9 app.js错误:
 TypeError: Cannot read property 'type' of undefined
    at TaroHooks.tap (.._src_runtime-hooks.ts:167)
    at Object.node_modulesTarojsPluginHtmlDistRuntimeJs [as ./node_modules/@tarojs/plugin-html/dist/runtime.js]`
      

### 期望的结果是什么？

正常使用

### 实际的结果是什么？

微信开发者工具白屏，终端报错：
VM1418:9 app.js错误:
 TypeError: Cannot read property 'type' of undefined
    at TaroHooks.tap (.._src_runtime-hooks.ts:167)
    at Object.node_modulesTarojsPluginHtmlDistRuntimeJs [as ./node_modules/@tarojs/plugin-html/dist/runtime.js]

### 环境信息

 Taro CLI 3.6.18 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.18 => 3.6.18
      @tarojs/components: 3.6.18 => 3.6.18
      @tarojs/helper: 3.6.18 => 3.6.18
      @tarojs/plugin-framework-react: 3.6.18 => 3.6.18
      @tarojs/plugin-html: ^3.6.19 => 3.6.19
      @tarojs/plugin-platform-alipay: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-h5: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-jd: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-qq: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-swan: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-tt: 3.6.18 => 3.6.18
      @tarojs/plugin-platform-weapp: 3.6.18 => 3.6.18
      @tarojs/react: 3.6.18 => 3.6.18
      @tarojs/runtime: 3.6.18 => 3.6.18
      @tarojs/shared: 3.6.18 => 3.6.18
      @tarojs/taro: 3.6.7 => 3.6.7
      @tarojs/taro-loader: 3.6.18 => 3.6.18
      @tarojs/webpack5-runner: 3.6.18 => 3.6.18
      babel-preset-taro: 3.6.18 => 3.6.18
      eslint-config-taro: 3.6.18 => 3.6.18
      react: ^18.0.0 => 18.2.0
      taro-ui: ^3.1.1 => 3.1.1

**Comment by eiinu** [comment]
首先应该保证所有 `@tarojs` 包使用同一个版本，如果仍有问题，需要提供可复现的 demo

**Comment by leeeero** [comment]
> 首先应该保证所有 `@tarojs` 包使用同一个版本，如果仍有问题，需要提供可复现的 demo

感谢，已经解决
需要将@tarojs/plugin-html的版本降级到3.6.18。
