### ISSUE TITLE
[FR]: 各类弹窗比如Dialog、ActionSheet等，部分情况会以父元素进行定位，而不是小程序窗口进行定位

### ISSUE THREAD

**Issue by Ryan-CW-Code** [jdf2e/nutui-react#1655]
### 这个功能解决了什么问题？

弹出框显示错乱。

### 你期望的组件设计是怎样的？

所有弹出框都应该以小程序窗口进行定位

**Comment by Ryan-CW-Code** [comment]
```
export default memo(function HouseInfo() {
  //   const parkId = Number(gradeRoutes.index.params?.id);
  const [isVisible2, setIsVisible2] = useState(false);

  return (
    <div style={{ background: '#ff8787', height: '100vh', margin: '180px auto 0' }}>
      <div onClick={() => setIsVisible2(true)}>点我打开ActionSheet</div>
      <Tabs activeType="smile" align="left">
        <Tabs.TabPane title="aaaaaaaaaaaa" value={0}>
          <div style={{ height: '200px' }}>asdfffffffffffffffffffffff</div>
          <ActionSheet visible={isVisible2} cancelText="取消" onCancel={() => setIsVisible2(false)}>
            <h2>nihao</h2>
          </ActionSheet>
        </Tabs.TabPane>
      </Tabs>
    </div>
  );
});
```
这是一个复现demo。
![image](https://github.com/jdf2e/nutui-react/assets/75795462/a139fc3f-30e2-4528-93e8-1d7970db9179)

**Comment by Ryan-CW-Code** [comment]
使用子组件向父组件传递 ActionSheet的方式暂时解决了这个问题

**Comment by eiinu** [comment]
主要原因是 fixed 定位的元素（比如 Dialog、基于 Popup 的 ActionSheet 等）的定位目标会受到 transform 布局元素（比如 Tabs）的干扰，这个是 CSS 的标准规则。
解决办法是不在 transform 布局元素中使用 fixed 定位元素，放在层级外面就可以了。

**Comment by Ryan-CW-Code** [comment]
> 主要原因是 fixed 定位的元素（比如 Dialog、基于 Popup 的 ActionSheet 等）的定位目标会受到 transform 布局元素（比如 Tabs）的干扰，这个是 CSS 的标准规则。 解决办法是不在 transform 布局元素中使用 fixed 定位元素，放在层级外面就可以了。

感谢，查到的原因也是这样的。放外面会导致我们传递很多层参数，只能用子组件向父组件传递这样取巧的方式来避免容器限制了
