### ISSUE TITLE
Popup在开启lockscroll后内部也无法滚动

### ISSUE THREAD

**Issue by scrapstation** [jdf2e/nutui-react#1676]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.1.0

### 平台

weapp

### 重现链接

https://codesandbox.io/p/devbox/withered-cookies-dxfcgl?file=%2Fpackage.json%3A13%2C36&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpb1jh1p0009356kz81bogxm%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpb1jh1o0004356k7jwrzh7u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpb1jh1p0006356kybn0dn3v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpb1jh1p0008356kn7c2plyj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpb1jh1o0004356k7jwrzh7u%2522%253A%257B%2522id%2522%253A%2522clpb1jh1o0004356k7jwrzh7u%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb1li72005q356knbp1elwq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A36%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A36%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpb1li72005q356knbp1elwq%2522%257D%252C%2522clpb1jh1p0008356kn7c2plyj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb1jh1p0007356k2k71baye%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpb1jh1p0008356kn7c2plyj%2522%252C%2522activeTabId%2522%253A%2522clpb1jh1p0007356k2k71baye%2522%257D%252C%2522clpb1jh1p0006356kybn0dn3v%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb1jh1p0005356kj05mt47v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clpb1jh1p0006356kybn0dn3v%2522%252C%2522activeTabId%2522%253A%2522clpb1jh1p0005356kj05mt47v%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 重现步骤

```
<Popup visible round lockScroll position="bottom">
      <View style={{ height: '60vh'}}>
     </View>
</Popup >
```

### 期望的结果是什么？

期望背景不可滚动，popup内部可以滚动

### 实际的结果是什么？

背景和Popup内部都不可以滚动了

### 其他补充信息

下方无法滚动！
![image](https://github.com/jdf2e/nutui-react/assets/56467036/b4c7aeff-f439-49d0-920e-72fed14ff7eb)

**Comment by scrapstation** [comment]
#1537 1537

**Comment by scrapstation** [comment]
@oasis-cloud 有时间看一下吗，可能跟近期的fix有关

**Comment by oasis-cloud** [comment]
从你提供的demo 增加 lockscroll 后无法复现你的问题。
https://github.com/jdf2e/nutui-react/assets/12181600/2493c4e4-1d64-4f17-afbc-9af566607e07

**Comment by Ryan-CW-Code** [comment]
> 从你提供的demo 增加 lockscroll 后无法复现你的问题。 https://github.com/jdf2e/nutui-react/assets/12181600/2493c4e4-1d64-4f17-afbc-9af566607e07

我在新版本也遇到这个问题了。不管有没有设置lockscroll都不可以手指滑动。我使用的ActionSheet组件，在内部自定义内容使用滚动，鼠标滚轮滚动有效，手指和鼠标左键滑动无效。
退回到2.0.22版本就没问题了，就是[1537](https://github.com/jdf2e/nutui-react/pull/1537)更新前的一个版本。2.0.23就不行了

**Comment by oasis-cloud** [comment]
> > 从你提供的demo 增加 lockscroll 后无法复现你的问题。 [jdf2e/nutui-react/assets/12181600/2493c4e4-1d64-4f17-afbc-9af566607e07](https://github.com/jdf2e/nutui-react/assets/12181600/2493c4e4-1d64-4f17-afbc-9af566607e07)
> 
> 我在新版本也遇到这个问题了。不管有没有设置lockscroll都不可以手指滑动。我使用的ActionSheet组件，在内部自定义内容使用滚动，鼠标滚轮滚动有效，手指和鼠标左键滑动无效。 退回到2.0.22版本就没问题了，就是[1537](https://github.com/jdf2e/nutui-react/pull/1537)更新前的一个版本。2.0.23就不行了

你使用的是 @nutui/nutui-react-taro 版本生成 H5 页面吗？

**Comment by Ryan-CW-Code** [comment]
> > > 从你提供的demo 增加 lockscroll 后无法复现你的问题。 [jdf2e/nutui-react/assets/12181600/2493c4e4-1d64-4f17-afbc-9af566607e07](https://github.com/jdf2e/nutui-react/assets/12181600/2493c4e4-1d64-4f17-afbc-9af566607e07)
> > 
> > 
> > 我在新版本也遇到这个问题了。不管有没有设置lockscroll都不可以手指滑动。我使用的ActionSheet组件，在内部自定义内容使用滚动，鼠标滚轮滚动有效，手指和鼠标左键滑动无效。 退回到2.0.22版本就没问题了，就是[1537](https://github.com/jdf2e/nutui-react/pull/1537)更新前的一个版本。2.0.23就不行了
> 
> 你使用的是 @nutui/nutui-react-taro 版本生成 H5 页面吗？
我用的Taro小程序
下面的代码在2.0.22可以手指和鼠标左键滑动，2.0.23就不可以了
```
import { View } from "@tarojs/components";
import { ActionSheet } from "@nutui/nutui-react-taro";

export default function Index() {
  return (
    <View className="index">
      <ActionSheet style={{ overflow: "auto", height: "300px" }} visible={true}>
        {Array(100)
          .fill("")
          .map((_, index) => (
            <div>{index}</div>
          ))}
      </ActionSheet>
    </View>
  );
}
```

**Comment by Ryan-CW-Code** [comment]
@oasis-cloud @xiaoyatong 麻烦关注下这个问题哈，issue里面也有类似的问题。
