### ISSUE TITLE
Picker confirm操作后蒙层没有关闭

### ISSUE THREAD

**Issue by Liaozhou22** [jdf2e/nutui-react#1677]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.1.0

### 平台

weapp

### 重现链接

Picker修复confirm失效问题后出现了 confirm操作后蒙层没有关闭

### 重现步骤

可以测试一下

### 期望的结果是什么？

cofirm后蒙层关闭

### 实际的结果是什么？

cofirm后蒙层没有关闭

**Comment by xiaoyatong** [comment]
目前用 2.1.0 和 2.2.0 都没有复现。demo如下：

```
const [isVisible2, setIsVisible2] = useState(false);

<Picker
        visible={isVisible2}
        options={listData2}
        onClose={() => setIsVisible2(false)}
        defaultValue={["Wednesday"]}
        onChange={changePicker}
        onConfirm={(list, values) => confirmPicker("mutil", list, values)}
      />
```

如还有问题，辛苦反馈一下 demo。

**Comment by painoBoy** [comment]
import React, {ReactNode, useState} from 'react';
import {Picker} from "@nutui/nutui-react-taro";
import { MiniListItem} from "../index";
import classNames from "classnames";
import {View} from "@tarojs/components";


type MiniPickerProps = {
  listData:any;
  label:string|ReactNode;
  onConfirmPicker:(options:any,values?:any)=>void;
}
const MiniPicker:React.FC<MiniPickerProps> = (props)=> {
  const { listData ,label,onConfirmPicker,...rest} = props
  const [visible, setVisible] = useState(false)
  const [value,setValue] = useState() as any;
  const confirmPicker = (options: any, values: (string | number)[]) => {
    setValue(options[0]?.text);
    onConfirmPicker && onConfirmPicker(options,values);
  }



    return (
      <View {...rest} onClick={()=>setVisible(true)} >
        <MiniListItem
          className={classNames({
            placeholder: !value,
          })}
          title={label}
          extra={value || null}
        />
        <Picker
          visible={visible}
          options={listData}
          onConfirm={(list, values) => confirmPicker(list, values)}
          onClose={() => setVisible(false)}
        >
        </Picker>
      </View>
    );
}

export default React.memo(MiniPicker);

**Comment by Liaozhou22** [comment]
import React, {ReactNode, useState} from 'react';
import {Picker} from "@nutui/nutui-react-taro";
import { MiniListItem} from "../index";
import classNames from "classnames";
import {View} from "@tarojs/components";


type MiniPickerProps = {
  listData:any;
  label:string|ReactNode;
  onConfirmPicker:(options:any,values?:any)=>void;
}
const MiniPicker:React.FC<MiniPickerProps> = (props)=> {
  const { listData ,label,onConfirmPicker,...rest} = props
  const [visible, setVisible] = useState(false)
  const [value,setValue] = useState() as any;
  const confirmPicker = (options: any, values: (string | number)[]) => {
    setValue(options[0]?.text);
    onConfirmPicker && onConfirmPicker(options,values);
  }



    return (
      <View {...rest} onClick={()=>setVisible(true)} >
        <MiniListItem
          className={classNames({
            placeholder: !value,
          })}
          title={label}
          extra={value || null}
        />
        <Picker
          visible={visible}
          options={listData}
          onConfirm={(list, values) => confirmPicker(list, values)}
          onClose={() => setVisible(false)}
        >
        </Picker>
      </View>
    );
}

export default React.memo(MiniPicker);


帮忙看看这个代码有啥问题没呢 调用了组件 onConfirm事件后没有关闭蒙层
