### ISSUE TITLE
[FR]: Rate组件

### ISSUE THREAD

**Issue by lemonweb** [jdf2e/nutui-react#1680]
### 这个功能解决了什么问题？

和 slider 一样的交互形式

### 你期望的组件设计是怎样的？

Rate组件支持滑动选择，拖动选择

**Comment by sunsunmonkey** [comment]
这个我可以做吗🙃

**Comment by lemonweb** [comment]
您好，您发送的邮件我已经收到！

**Comment by xiaoyatong** [comment]
> 这个我可以做吗🙃

可以的，直接提交pr就好了

**Comment by lemonweb** [comment]
您好，您发送的邮件我已经收到！

**Comment by lemonweb** [comment]
您好，您发送的邮件我已经收到！
