### ISSUE TITLE
Input value 没有空判断

### ISSUE THREAD

**Issue by zjxpcyc** [jdf2e/nutui-react#1764]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.x

### 平台

weapp, 其他小程序

### 重现链接

https://github.com/jdf2e/nutui-react/blob/next/src/packages/input/input.tsx#L226

### 重现步骤

代码  [https://github.com/jdf2e/nutui-react/blob/next/src/packages/input/input.tsx#L226](https://github.com/jdf2e/nutui-react/blob/next/src/packages/input/input.tsx#L226)

`
value.length > 0
`

应该修改为
`
value?.length > 0
`

### 期望的结果是什么？

正常判空

### 实际的结果是什么？

报错

**Comment by oasis-cloud** [comment]
value 通过 usePropsValue 设置了默认值未空字符串，应该不需要再加判断，可以具体描述下如何才能触发错误吗
