### ISSUE TITLE
希望遵循语义化版本规则

### ISSUE THREAD

**Issue by hellohejinyu** [jdf2e/nutui-react#1771]
### 这个功能解决了什么问题？

今天升级了库的版本，然后发现样式破坏了。检查下来发现是库的组件中的类名规则被修改了。
<img width="1040" alt="image" src="https://github.com/jdf2e/nutui-react/assets/8766034/c889483b-376d-4faa-a72a-4f86da2c93a7">
因为开发过程中会微调样式，所以会用到组件的类名。

### 你期望的组件设计是怎样的？

建议遵循语义化版本，非 `major` 版本变化不要有破坏性更新，否则会让使用者不敢更新库的版本，那样就无法使用最新的特性和 bug 的修复了。

**Comment by yeeli** [comment]
而且改能不能一次性改完，做个大版本升级， 还分批次改，2.2.0 改一版，刚调整完， 2.3.0又改一版导致好多样式完全错乱

**Comment by xiaoyatong** [comment]
嗯嗯。抱歉给您带来了困扰，这次版本的样式变量会暂不再改动。
我们稍后尽快给大家一个变更文档、然后再出一个升级工具~
