### ISSUE TITLE
 WXSS 文件编译错误] ./app-origin.wxss  error at token "*"   2 |   !*** css ./node_modules/css-loader/dist/cjs.js??

### ISSUE THREAD

**Issue by vczyh** [jdf2e/nutui-react#1772]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.3.0

### 平台

weapp

### 重现链接

https://github.com/vczyh/taro-nutui-test

### 重现步骤

![CleanShot 2023-12-10 at 20 34 44@2x](https://github.com/jdf2e/nutui-react/assets/33161749/effa6678-1897-4d56-b0da-6c2a79f23373)

### 期望的结果是什么？

1

### 实际的结果是什么？

![CleanShot 2023-12-10 at 20 34 44@2x](https://github.com/jdf2e/nutui-react/assets/33161749/27d5b5ce-b0f1-46e3-bb0f-ab599d22dc8f)

### 环境信息

👽 Taro v3.6.20

  Taro CLI 3.6.20 environment info:
    System:
      OS: macOS 14.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.20 => 3.6.20 
      @tarojs/components: 3.6.20 => 3.6.20 
      @tarojs/helper: 3.6.20 => 3.6.20 
      @tarojs/plugin-framework-react: 3.6.20 => 3.6.20 
      @tarojs/plugin-html: ^3.6.20 => 3.6.20 
      @tarojs/plugin-platform-alipay: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-h5: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-jd: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-qq: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-swan: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-tt: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-weapp: 3.6.20 => 3.6.20 
      @tarojs/react: 3.6.20 => 3.6.20 
      @tarojs/runtime: 3.6.20 => 3.6.20 
      @tarojs/shared: 3.6.20 => 3.6.20 
      @tarojs/taro: 3.6.20 => 3.6.20 
      @tarojs/taro-loader: 3.6.20 => 3.6.20 
      @tarojs/webpack5-runner: 3.6.20 => 3.6.20 
      babel-preset-taro: 3.6.20 => 3.6.20 
      eslint-config-taro: 3.6.20 => 3.6.20 
      react: ^18.0.0 => 18.2.0

**Comment by vczyh** [comment]
经过微信群大佬 RyanCW 的确定，是由于全局引入的原因，我按照他说的改成按需引入就可以了，这个还得让维护者看看了。

**Comment by scrapstation** [comment]
+1，但我已经是按需引入了，仍然报这个错

**Comment by vczyh** [comment]
> +1，但我已经是按需引入了，仍然报这个错

不应该啊，全局引入没有注释掉？

**Comment by scrapstation** [comment]
我猜测问题的原因是，小程序不支持 * 选择器，而某些样式还没改完，全局用一定会有问题，按需用不一定会有问题

**Comment by vczyh** [comment]
> 我猜测问题的原因是，小程序不支持 * 选择器，而某些样式还没改完，全局用一定会有问题，按需用不一定会有问题

应该是的，最近两个版本变动有点大

**Comment by oasis-cloud** [comment]
可以看下是不是使用了 searchbar 组件

**Comment by scrapstation** [comment]
> 可以看下是不是使用了 searchbar 组件

是的，注掉就不报错了

**Comment by vczyh** [comment]
> 可以看下是不是使用了 searchbar 组件

大佬，给看下这个：https://github.com/jdf2e/nutui-react/issues/1649
好像仍然没有修复

**Comment by scrapstation** [comment]
> > 可以看下是不是使用了 searchbar 组件
> 
> 大佬，给看下这个：#1649 好像仍然没有修复

哈哈 大家遇到的问题大差不差

**Comment by oasis-cloud** [comment]
> > 可以看下是不是使用了 searchbar 组件
> 
> 大佬，给看下这个：#1649 好像仍然没有修复

重新打开，继续修😂

**Comment by vczyh** [comment]
> > > 可以看下是不是使用了 searchbar 组件
> > 
> > 
> > 大佬，给看下这个：#1649 好像仍然没有修复
> 
> 重新打开，继续修😂

哈哈哈，辛苦了

**Comment by imyuanli** [comment]
我按需引入不报你这个错误了，但是我报了一个新的错误啊
![image](https://github.com/jdf2e/nutui-react/assets/75649798/dc92c45b-a77d-4243-85e7-b1d03fe28974)
