### ISSUE TITLE
InputNumber 样式变量使用不合变量定义

### ISSUE THREAD

**Issue by onlyling** [jdf2e/nutui-react#1780]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.3.0

### 平台

weapp

### 重现链接

https://github.com/jdf2e/nutui-react/blob/next/src/styles/theme-default.scss

### 重现步骤

```jsx
const Demo = () => <InputNumber />
```

```scss
page {
  //
  // 背景色
  // 卡片背景色
  // --nutui-gray-1: #ffffff;
  // 卡片内嵌背景色，用于卡片内部的信息包裹，感知较弱。
  // --nutui-gray-2: #f8f8f8;
  // 页面基底色，用于卡片式页面的兜底，永远置于页面最底层。
  // --nutui-gray-3: #f6f6f6;
  // 文字色
  // 四级文字色，不可操作内容色，用于预置内容、无效内容、特殊不可点击按钮、组件边框线等。
  // --nutui-gray-4: #bfbfbf;
  // 三级文字色（次要）
  // --nutui-gray-5: #8c8c8c;
  // 二级文字色（常规），用于次级标题、属性标示、非主要信息引导等。
  // --nutui-gray-6: #595959;
  // 一级文字色（重要）主要内容用色，常用语常规标题内容、细文浏览、常规按钮文字以及图表引导。
  // --nutui-gray-7: #1a1a1a; 

  --orange-gray-10: #000;
  --orange-gray-9: rgba(0, 0, 0, 0.85);
  --orange-gray-8: rgba(0, 0, 0, 0.65);
  --orange-gray-7: rgba(0, 0, 0, 0.45);
  --orange-gray-6: rgba(0, 0, 0, 0.25);
  --orange-gray-5: rgba(0, 0, 0, 0.15);
  --orange-gray-4: rgba(0, 0, 0, 0.1);
  --orange-gray-3: rgba(0, 0, 0, 0.06);
  --orange-gray-2: rgba(0, 0, 0, 0.04);
  --orange-gray-1: #fff;

  // 2.3.0
  --nutui-gray-4: var(--orange-gray-5);
  --nutui-gray-5: var(--orange-gray-7);
  --nutui-gray-6: var(--orange-gray-8);
  --nutui-gray-7: var(--orange-gray-9);
}
```

### 期望的结果是什么？

使用语义化命名变量。

### 实际的结果是什么？

<img width="931" alt="image" src="https://github.com/jdf2e/nutui-react/assets/9999765/c3b519ae-2e53-48e8-a521-0eb4e7e298fe">
<img width="910" alt="image" src="https://github.com/jdf2e/nutui-react/assets/9999765/818e25b7-0f2d-43c1-8b84-3a248775b271">

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-react/blob/next/src/styles/variables.scss
https://github.com/jdf2e/nutui-react/blob/next/src/styles/theme-default.scss

这两个文件都要关注到~~~

**Comment by xiaoyatong** [comment]
另外，__ 和 -- 已简化为 -。
![image](https://github.com/jdf2e/nutui-react/assets/84436086/10f1ab89-1570-4b74-85a0-2d6fb3ce2599)

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-react/discussions/1779
