### ISSUE TITLE
微信小程序 Button disabled 状态下，边框颜色并没有半透明化

### ISSUE THREAD

**Issue by onlyling** [jdf2e/nutui-react#1781]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.3.0

### 平台

weapp

### 重现链接

https://nutui.jd.com/h5/react/2x/#/zh-CN/component/button

### 重现步骤

```jsx
const Demo = () => <Button disabled block type="primary">加入进货单</Button>
```

真机与模拟器上表现一致。

<img width="370" alt="image" src="https://github.com/jdf2e/nutui-react/assets/9999765/576b5941-5b2c-48d4-ba43-febc2e2929be">

### 期望的结果是什么？

与 web 端（文档）保持一致。
<img width="357" alt="image" src="https://github.com/jdf2e/nutui-react/assets/9999765/82783c7d-e82f-4066-9f57-bef6b8ebf664">

### 实际的结果是什么？

边框颜色并没有半透明化。
在小程序端或许可以考虑使用整体半透明的方式。
<img width="697" alt="image" src="https://github.com/jdf2e/nutui-react/assets/9999765/4e03f69d-1b6c-4731-b65c-8d2e7c677c24">

**Comment by xiaoyatong** [comment]
私聊，加我一下微信：hanyuxinting

**Comment by xiaoyatong** [comment]
加一下这个微信：
![image](https://github.com/jdf2e/nutui-react/assets/84436086/3485db5e-a24a-49ae-9cc0-0938165e7730)

**Comment by xiaoyatong** [comment]
这部分主要是主题定制 这块的样式变量做了一些修订。
https://github.com/jdf2e/nutui-react/blob/next/src/styles/variables.scss

关注一下这个文件~

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-react/discussions/1779
