### ISSUE TITLE
打包的时候 SassError: Undefined variable  $nut-tabs-title-gap 

### ISSUE THREAD

**Issue by gonganruyi** [jdf2e/nutui-react#1790]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.12

### 平台

h5

### 重现链接

@nutui/nutui-react-taro 

### 重现步骤

<img width="445" alt="image" src="https://github.com/jdf2e/nutui-react/assets/4279222/0cff9ac9-ae73-43bb-a561-eccd3e2b5413">

### 期望的结果是什么？

正常打包

### 实际的结果是什么？

未正常打包

**Comment by oasis-cloud** [comment]
可以确认下 node_modules 中的具体版本号，如果是 2.3 版本，$nut-tabs-title-gap 改为 $tabs-titles-gap

**Comment by gonganruyi** [comment]
已经解决了，，，，没有锁包导致的！！
