### ISSUE TITLE
Form表单里面使用Picker

### ISSUE THREAD

**Issue by cdx111** [jdf2e/nutui-react#1791]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.0.22

### 平台

weapp

### 重现链接

小程序无法放到codesandbox

### 重现步骤

在Form表单里面使用Picker无法显示选项，如果View套住Form.Item就无法显示选项，不嵌套可以正常显示
<Form>
<View>
<Form.Item>
<Picker></Picker>
</Form.Item>
</View>
</Form>
[WXML Runtime warning] ./base.wxml
 Template `tmpl_15_2` not found.
  113 |   <picker-view-column name="{{i.p0}}" style="{{i.st}}" class="{{i.cl}}" bindtap="eh"  id="{{i.uid||i.sid}}" data-sid="{{i.sid}}">
  114 |     <block wx:for="{{i.cn}}" wx:key="sid">
> 115 |       <template is="{{xs.a(c, item.nn, l)}}" data="{{i:item,c:c+1,l:xs.f(l,item.nn)}}" />
      |                    ^
  116 |     </block>
  117 |   </picker-view-column>
  118 | </template>

### 期望的结果是什么？

正常显示选项

### 实际的结果是什么？

正常显示选项

**Comment by oasis-cloud** [comment]
From 组件下要直接嵌套 Form.Item, 不能通过 View 等标签包裹 Form.Item

**Comment by cdx111** [comment]
> From 组件下要直接嵌套 Form.Item, 不能通过 View 等标签包裹 Form.Item

有时候需要自定义一些标题怎么办？
