### ISSUE TITLE
taro h5 Tabs 切换 tab，tab 标签会滚动到初始位置

### ISSUE THREAD

**Issue by shushu2013** [jdf2e/nutui-react#1798]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.23

### 平台

h5

### 重现链接

https://github.com/shushu2013/taro3.6.20.git

### 重现步骤
```
$ git clone https://github.com/shushu2013/taro3.6.20.git

$ cd taro3.6.20

// 需要在分支 nutui-tabs 中测试
$ git checkout nutui-tabs

$ pnpm install

$ pnpm dev:h5
```
```
Tabs 组件使用了 scrollView 设置了 scrollLeft ，但是没有记录 scrollLeft 的值导致的
```

参考 Taro 的 issue： [https://github.com/NervJS/taro/issues/8466#issuecomment-877587029](https://github.com/NervJS/taro/issues/8466#issuecomment-877587029)

https://github.com/jdf2e/nutui-react/assets/6076072/2254580b-7af2-4cab-9cd1-fe0f7e7d3ca1

### 期望的结果是什么？

tabs 标签不滚动

### 实际的结果是什么？

tabs 标签会滚动到初始位置

### 环境信息

👽 Taro v3.6.20

  Taro CLI 3.6.20 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.20 => 3.6.20 
      @tarojs/components: 3.6.20 => 3.6.20 
      @tarojs/helper: 3.6.20 => 3.6.20 
      @tarojs/mini-runner: 3.6.20 => 3.6.20 
      @tarojs/plugin-framework-react: 3.6.20 => 3.6.20 
      @tarojs/plugin-html: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-alipay: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-h5: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-jd: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-qq: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-swan: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-tt: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-weapp: 3.6.20 => 3.6.20 
      @tarojs/react: 3.6.20 => 3.6.20 
      @tarojs/runtime: 3.6.20 => 3.6.20 
      @tarojs/shared: 3.6.20 => 3.6.20 
      @tarojs/taro: 3.6.20 => 3.6.20 
      @tarojs/webpack-runner: 3.6.20 => 3.6.20 
      babel-preset-taro: 3.6.20 => 3.6.20 
      eslint-config-taro: 3.6.20 => 3.6.20 
      react: ^18.0.0 => 18.0.0 
    npmGlobalPackages:
      typescript: 5.0.4

**Comment by oasis-cloud** [comment]
tab 标题滚动，需要设置 name props。现在已经关联了修复 pr，默认给 name 设置上值，避免使用的时候忘记设置 name，而导致标题滚动无效
