### ISSUE TITLE
[FR]: 2.3.+版本的UI是否需要走查一遍？很多细节不太符合直觉，对比旧版本和nutui vue版本也有所不同

### ISSUE THREAD

**Issue by Ryan-CW-Code** [jdf2e/nutui-react#1802]
### 这个功能解决了什么问题？

规范nutui样式，很多细节对比旧版本和nutui vue版本都不同。
个人感觉并不是V12规范就这样，而是很多地方看起来**不符合直觉**。
比如Tabs的微笑曲线很小，PullToRefresh提示文案字体很小等等。 
色彩规范通过--nutui-color-primary修改主题色，但是有些地方依然保持京东红。
蛮多地方的间距看起来也很奇怪
icon高度异常，使用flex对齐，视觉上并没有对齐

### 你期望的组件设计是怎样的？

规范nutui样式

**Comment by Ryan-CW-Code** [comment]
很多组件还会在控制台打印很多warn信息

**Comment by Me-UserName** [comment]
色彩规范通过--nutui-color-primary修改主题色，但是有些地方依然保持京东红。
比如 Primary Button 就不起作用

**Comment by cdx111** [comment]
> 色彩规范通过--nutui-color-primary修改主题色，但是有些地方依然保持京东红。
> 比如 Primary Button 就不起作用

确实，我升级后需要手动覆盖很多样式....

**Comment by xiaoyatong** [comment]
大家看一下这个：https://github.com/jdf2e/nutui-react/discussions/1779
