### ISSUE TITLE
[FR]: Tabbar用法是否有问题？handleClick事件不生效，而且只能传idx（number）类型，限制的太窄

### ISSUE THREAD

**Issue by lijie1024512** [jdf2e/nutui-react#1806]
### 这个功能解决了什么问题？

import React, { useState } from "react";
import { Tabbar } from "@nutui/nutui-react";
import { Cart, Category, Find, Home, User } from "@nutui/icons-react";

const App = () => {
  const clickItem = (val) => {
    // 自定义操作 没有val
    console.log("val", val);

  };
  const arr = [
    {
      name: "首页",
      id: 1,
      isShow: true
    },
    {
      name: "分类",
      id: 2,
      isShow: false,

    },
    {
      name: "发现",
      id: 3,
      isShow: true,

    }
  ]
  return (
    <Tabbar fixed>
      {arr.map((item, index) => (
        <Tabbar.Item
          // 点击不生效
          handleClick={() => clickItem(item.id)}
          key={index}
          title={item.name}
          // 此处和item里的name或者icon字段去选中自定义icon
          icon={<Home width={20} height={20} />}
        />
      ))}
    </Tabbar>
  );
};

export default App;

### 你期望的组件设计是怎样的？

 <Tabbar fixed>
      {arr.map((item, index) => (
        <Tabbar.Item
          // 点击把整个item信息带出去自定义处理
          onClick={() => clickItem(item)}
          key={index}
          title={item.name}
          // 此处和item里的name或者icon字段去选中自定义icon
          icon={<Home width={20} height={20} />}
        />
      ))}
    </Tabbar>

**Comment by oasis-cloud** [comment]
不可以设置 handleclick，只可以在 tabbar 上设置 onSwitch。handleclick 是 item 的内置方法，之后会隐藏 tabbaritem 的内部属性
