### ISSUE TITLE
Button：自定义主题后，danger Button 颜色不正确

### ISSUE THREAD

**Issue by vczyh** [jdf2e/nutui-react#1807]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.3.2

### 平台

weapp

### 重现链接

https://github.com/vczyh/taro-nutui-test/tree/loading-button-color

### 重现步骤

```tsx
export default function Index() {

  return (
    <ConfigProvider theme={{
      nutuiColorPrimary: '#1677ff',
      nutuiColorPrimaryStop1: '#1677ff',
      nutuiColorPrimaryStop2: '#1677ff',
    }}
    >
      <Button type='danger'>Danger</Button>
    </ConfigProvider>
  )
}
```

### 期望的结果是什么？

虽然自定义 brand 颜色为蓝色， danger type button 按钮依然应该是偏红色

### 实际的结果是什么？

![CleanShot 2023-12-21 at 15 59 17@2x](https://github.com/jdf2e/nutui-react/assets/33161749/b348b53d-580f-4ca1-8545-cc45762b304e)

**Comment by Me-UserName** [comment]
使用 CSS Variables 进行主题配置 --nutui-brand-8: #1677ff，Primary Button 颜色仍然为京东红，2.3.2版

**Comment by oasis-cloud** [comment]
> 使用 CSS Variables 进行主题配置 --nutui-brand-8: #1677ff，Primary Button 颜色仍然为京东红，2.3.2版

Primary Button 的背景色是采用的渐变模式，可以修改 $color-primary-stop-1和 $color-primary-stop-2。色值之间还不具备联动逻辑。

**Comment by oasis-cloud** [comment]
> ### NutUI React 包名
> @nutui/nutui-react-taro
> 
> ### NutUI React 版本号
> 2.3.2
> 
> ### 平台
> weapp
> 
> ### 重现链接
> [vczyh/taro-nutui-test@`loading-button-color`](https://github.com/vczyh/taro-nutui-test/tree/loading-button-color?rgh-link-date=2023-12-21T08%3A05%3A37Z)
> 
> ### 重现步骤
> ```tsx
> export default function Index() {
> 
>   return (
>     <ConfigProvider theme={{
>       nutuiColorPrimary: '#1677ff',
>       nutuiColorPrimaryStop1: '#1677ff',
>       nutuiColorPrimaryStop2: '#1677ff',
>     }}
>     >
>       <Button type='danger'>Danger</Button>
>     </ConfigProvider>
>   )
> }
> ```
> 
> ### 期望的结果是什么？
> 虽然自定义 brand 颜色为蓝色， danger type button 按钮依然应该是偏红色
> 
> ### 实际的结果是什么？
> ![CleanShot 2023-12-21 at 15 59 17@2x](https://private-user-images.githubusercontent.com/33161749/292133721-b348b53d-580f-4ca1-8545-cc45762b304e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMDk3NzksIm5iZiI6MTcwMzIwOTQ3OSwicGF0aCI6Ii8zMzE2MTc0OS8yOTIxMzM3MjEtYjM0OGI1M2QtNTgwZi00Y2ExLTg1NDUtY2M0NTc2MmIzMDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAxNDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OGNiOTYyNjMyMDdiNTZjODU4ZTBjMjUyNWZmNDUxMTJkMWFmYzBjNWNiZTk2NDQwYWYxMzliYWJiNjc0YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8GruHwrGUtG7yoxG0hOa3xf5z3GKgFARdSp2a-xeXiw)
> 
> ### 环境信息
> _No response_
> 
> ### 其他补充信息
> _No response_

你应该在你的主题中修改 $color-danger，或者修改 --nutui-color-danger。像下面这样

```
  nutuiColorPrimary: '#1677ff',
  nutuiColorDanger: 'red',
  nutuiColorPrimaryStop1: '#1677ff',
  nutuiColorPrimaryStop2: '#1677ff',
```

**Comment by vczyh** [comment]
> > ### NutUI React 包名
> > @nutui/nutui-react-taro
> > ### NutUI React 版本号
> > 2.3.2
> > ### 平台
> > weapp
> > ### 重现链接
> > [vczyh/taro-nutui-test@`loading-button-color`](https://github.com/vczyh/taro-nutui-test/tree/loading-button-color?rgh-link-date=2023-12-21T08%3A05%3A37Z)
> > ### 重现步骤
> > ```tsx
> > export default function Index() {
> > 
> >   return (
> >     <ConfigProvider theme={{
> >       nutuiColorPrimary: '#1677ff',
> >       nutuiColorPrimaryStop1: '#1677ff',
> >       nutuiColorPrimaryStop2: '#1677ff',
> >     }}
> >     >
> >       <Button type='danger'>Danger</Button>
> >     </ConfigProvider>
> >   )
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 期望的结果是什么？
> > 虽然自定义 brand 颜色为蓝色， danger type button 按钮依然应该是偏红色
> > ### 实际的结果是什么？
> > ![CleanShot 2023-12-21 at 15 59 17@2x](https://private-user-images.githubusercontent.com/33161749/292133721-b348b53d-580f-4ca1-8545-cc45762b304e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMDk3NzksIm5iZiI6MTcwMzIwOTQ3OSwicGF0aCI6Ii8zMzE2MTc0OS8yOTIxMzM3MjEtYjM0OGI1M2QtNTgwZi00Y2ExLTg1NDUtY2M0NTc2MmIzMDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAxNDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OGNiOTYyNjMyMDdiNTZjODU4ZTBjMjUyNWZmNDUxMTJkMWFmYzBjNWNiZTk2NDQwYWYxMzliYWJiNjc0YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8GruHwrGUtG7yoxG0hOa3xf5z3GKgFARdSp2a-xeXiw)
> > ### 环境信息
> > _No response_
> > ### 其他补充信息
> > _No response_
> 
> 你应该在你的主题中修改 $color-danger，或者修改 --nutui-color-danger。像下面这样
> 
> ```
>   nutuiColorPrimary: '#1677ff',
>   nutuiColorDanger: 'red',
>   nutuiColorPrimaryStop1: '#1677ff',
>   nutuiColorPrimaryStop2: '#1677ff',
> ```

我有个疑问，为什么 `success` 等其他按钮有默认颜色，为什么 `danger` 的默认颜色就是 `primary` 呢，是不是默认也应该设置为 `red` 呢。

```css
// 成功
$color-success: var(--nutui-color-success, #00bc14) !default;
$color-success-pressed: var(--nutui-color-success-pressed) !default;
$color-success-disabled: var(--nutui-color-success-disabled, #b2f0ae) !default;
$color-success-light: var(--nutui-color-success-light) !default;
$color-success-background: var(--nutui-color-success-background) !default;

// 警告
$color-warning: var(--nutui-color-warning, rgba(255, 158, 13, 1)) !default;
$color-warning-pressed: var(--nutui-color-warning-pressed) !default;
$color-warning-disabled: var(--nutui-color-warning-disabled, #fdd3b9) !default;
$color-warning-light: var(--nutui-color-warning-light) !default;
$color-warning-background: var(--nutui-color-warning-background) !default;

// 危险
$color-danger: var(--nutui-color-danger, $color-primary) !default;
$color-danger-pressed: var(--nutui-color-danger-pressed) !default;
$color-danger-disabled: var(
  --nutui-color-danger-disabled,
  $color-primary-disabled
) !default;
```

**Comment by xiaoyatong** [comment]
> > > ### NutUI React 包名
> > > @nutui/nutui-react-taro
> > > ### NutUI React 版本号
> > > 2.3.2
> > > ### 平台
> > > weapp
> > > ### 重现链接
> > > [vczyh/taro-nutui-test@`loading-button-color`](https://github.com/vczyh/taro-nutui-test/tree/loading-button-color?rgh-link-date=2023-12-21T08%3A05%3A37Z)
> > > ### 重现步骤
> > > ```tsx
> > > export default function Index() {
> > > 
> > >   return (
> > >     <ConfigProvider theme={{
> > >       nutuiColorPrimary: '#1677ff',
> > >       nutuiColorPrimaryStop1: '#1677ff',
> > >       nutuiColorPrimaryStop2: '#1677ff',
> > >     }}
> > >     >
> > >       <Button type='danger'>Danger</Button>
> > >     </ConfigProvider>
> > >   )
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### 期望的结果是什么？
> > > 虽然自定义 brand 颜色为蓝色， danger type button 按钮依然应该是偏红色
> > > ### 实际的结果是什么？
> > > ![CleanShot 2023-12-21 at 15 59 17@2x](https://private-user-images.githubusercontent.com/33161749/292133721-b348b53d-580f-4ca1-8545-cc45762b304e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMDk3NzksIm5iZiI6MTcwMzIwOTQ3OSwicGF0aCI6Ii8zMzE2MTc0OS8yOTIxMzM3MjEtYjM0OGI1M2QtNTgwZi00Y2ExLTg1NDUtY2M0NTc2MmIzMDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAxNDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OGNiOTYyNjMyMDdiNTZjODU4ZTBjMjUyNWZmNDUxMTJkMWFmYzBjNWNiZTk2NDQwYWYxMzliYWJiNjc0YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8GruHwrGUtG7yoxG0hOa3xf5z3GKgFARdSp2a-xeXiw)
> > > ### 环境信息
> > > _No response_
> > > ### 其他补充信息
> > > _No response_
> > 
> > 
> > 你应该在你的主题中修改 $color-danger，或者修改 --nutui-color-danger。像下面这样
> > ```
> >   nutuiColorPrimary: '#1677ff',
> >   nutuiColorDanger: 'red',
> >   nutuiColorPrimaryStop1: '#1677ff',
> >   nutuiColorPrimaryStop2: '#1677ff',
> > ```
> 
> 我有个疑问，为什么 `success` 等其他按钮有默认颜色，为什么 `danger` 的默认颜色就是 `primary` 呢，是不是默认也应该设置为 `red` 呢。
> 
> ```css
> // 成功
> $color-success: var(--nutui-color-success, #00bc14) !default;
> $color-success-pressed: var(--nutui-color-success-pressed) !default;
> $color-success-disabled: var(--nutui-color-success-disabled, #b2f0ae) !default;
> $color-success-light: var(--nutui-color-success-light) !default;
> $color-success-background: var(--nutui-color-success-background) !default;
> 
> // 警告
> $color-warning: var(--nutui-color-warning, rgba(255, 158, 13, 1)) !default;
> $color-warning-pressed: var(--nutui-color-warning-pressed) !default;
> $color-warning-disabled: var(--nutui-color-warning-disabled, #fdd3b9) !default;
> $color-warning-light: var(--nutui-color-warning-light) !default;
> $color-warning-background: var(--nutui-color-warning-background) !default;
> 
> // 危险
> $color-danger: var(--nutui-color-danger, $color-primary) !default;
> $color-danger-pressed: var(--nutui-color-danger-pressed) !default;
> $color-danger-disabled: var(
>   --nutui-color-danger-disabled,
>   $color-primary-disabled
> ) !default;
> ```

我觉得你说的有道理，我们修订一下。

**Comment by vczyh** [comment]
> > > > ### NutUI React 包名
> > > > @nutui/nutui-react-taro
> > > > ### NutUI React 版本号
> > > > 2.3.2
> > > > ### 平台
> > > > weapp
> > > > ### 重现链接
> > > > [vczyh/taro-nutui-test@`loading-button-color`](https://github.com/vczyh/taro-nutui-test/tree/loading-button-color?rgh-link-date=2023-12-21T08%3A05%3A37Z)
> > > > ### 重现步骤
> > > > ```tsx
> > > > export default function Index() {
> > > > 
> > > >   return (
> > > >     <ConfigProvider theme={{
> > > >       nutuiColorPrimary: '#1677ff',
> > > >       nutuiColorPrimaryStop1: '#1677ff',
> > > >       nutuiColorPrimaryStop2: '#1677ff',
> > > >     }}
> > > >     >
> > > >       <Button type='danger'>Danger</Button>
> > > >     </ConfigProvider>
> > > >   )
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ### 期望的结果是什么？
> > > > 虽然自定义 brand 颜色为蓝色， danger type button 按钮依然应该是偏红色
> > > > ### 实际的结果是什么？
> > > > ![CleanShot 2023-12-21 at 15 59 17@2x](https://private-user-images.githubusercontent.com/33161749/292133721-b348b53d-580f-4ca1-8545-cc45762b304e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMDk3NzksIm5iZiI6MTcwMzIwOTQ3OSwicGF0aCI6Ii8zMzE2MTc0OS8yOTIxMzM3MjEtYjM0OGI1M2QtNTgwZi00Y2ExLTg1NDUtY2M0NTc2MmIzMDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDAxNDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OGNiOTYyNjMyMDdiNTZjODU4ZTBjMjUyNWZmNDUxMTJkMWFmYzBjNWNiZTk2NDQwYWYxMzliYWJiNjc0YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8GruHwrGUtG7yoxG0hOa3xf5z3GKgFARdSp2a-xeXiw)
> > > > ### 环境信息
> > > > _No response_
> > > > ### 其他补充信息
> > > > _No response_
> > > 
> > > 
> > > 你应该在你的主题中修改 $color-danger，或者修改 --nutui-color-danger。像下面这样
> > > ```
> > >   nutuiColorPrimary: '#1677ff',
> > >   nutuiColorDanger: 'red',
> > >   nutuiColorPrimaryStop1: '#1677ff',
> > >   nutuiColorPrimaryStop2: '#1677ff',
> > > ```
> > 
> > 
> > 我有个疑问，为什么 `success` 等其他按钮有默认颜色，为什么 `danger` 的默认颜色就是 `primary` 呢，是不是默认也应该设置为 `red` 呢。
> > ```css
> > // 成功
> > $color-success: var(--nutui-color-success, #00bc14) !default;
> > $color-success-pressed: var(--nutui-color-success-pressed) !default;
> > $color-success-disabled: var(--nutui-color-success-disabled, #b2f0ae) !default;
> > $color-success-light: var(--nutui-color-success-light) !default;
> > $color-success-background: var(--nutui-color-success-background) !default;
> > 
> > // 警告
> > $color-warning: var(--nutui-color-warning, rgba(255, 158, 13, 1)) !default;
> > $color-warning-pressed: var(--nutui-color-warning-pressed) !default;
> > $color-warning-disabled: var(--nutui-color-warning-disabled, #fdd3b9) !default;
> > $color-warning-light: var(--nutui-color-warning-light) !default;
> > $color-warning-background: var(--nutui-color-warning-background) !default;
> > 
> > // 危险
> > $color-danger: var(--nutui-color-danger, $color-primary) !default;
> > $color-danger-pressed: var(--nutui-color-danger-pressed) !default;
> > $color-danger-disabled: var(
> >   --nutui-color-danger-disabled,
> >   $color-primary-disabled
> > ) !default;
> > ```
> 
> 我觉得你说的有道理，我们修订一下。

点赞！

**Comment by xiaoyatong** [comment]
代码已合并~~
