### ISSUE TITLE
2.3.3 微信小程序 DatePicker 只渲染为一个数字“0”

### ISSUE THREAD

**Issue by thep0y** [jdf2e/nutui-react#1814]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.3.3

### 平台

weapp

### 重现链接

https://github.com/thep0y/nutui-react-taro-2.3.3

### 重现步骤

直接导入 DatePicker 就能看到效果。

### 期望的结果是什么？

正常渲染 DatePicker

### 实际的结果是什么？

只有一个 0。

<img width="326" alt="截屏2023-12-23 21 52 12" src="https://github.com/jdf2e/nutui-react/assets/51874567/e0f2ba9c-ee1a-4a3a-8774-6daad1169a78">

### 环境信息

👽 Taro v3.6.21

  Taro CLI 3.6.21 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - /opt/homebrew/opt/node@18/bin/node
      npm: 10.2.3 - /opt/homebrew/opt/node@18/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.21 => 3.6.21
      @tarojs/components: 3.6.21 => 3.6.21
      @tarojs/helper: 3.6.21 => 3.6.21
      @tarojs/plugin-framework-react: 3.6.21 => 3.6.21
      @tarojs/plugin-html: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-alipay: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-h5: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-jd: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-qq: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-swan: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-tt: 3.6.21 => 3.6.21
      @tarojs/plugin-platform-weapp: 3.6.21 => 3.6.21
      @tarojs/react: 3.6.21 => 3.6.21
      @tarojs/runtime: 3.6.21 => 3.6.21
      @tarojs/shared: 3.6.21 => 3.6.21
      @tarojs/taro: 3.6.21 => 3.6.21
      @tarojs/taro-loader: 3.6.21 => 3.6.21
      @tarojs/webpack5-runner: 3.6.21 => 3.6.21
      babel-preset-taro: 3.6.21 => 3.6.21
      eslint-config-taro: 3.6.21 => 3.6.21
      react: ^18.0.0 => 18.0.0

### 其他补充信息

降到 2.3.2 可以正常渲染，但 2.3.2 的 DatePicker 有受控的 bug

**Comment by Ryan-CW-Code** [comment]
+1
