### ISSUE TITLE
primary 按钮的颜色通过css变量设置无效，通过ConfigProvider才有效

### ISSUE THREAD

**Issue by Ryan-CW-Code** [jdf2e/nutui-react#1815]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.3.3

### 平台

weapp

### 重现链接

代码量比较小，暂无

### 重现步骤

通过 ConfigProvider 设置按钮主题可以生效
```
      <ConfigProvider
        theme={{
          nutuiColorPrimary: '#2566ff',
          nutuiColorPrimaryStop1: '#2566ff',
          nutuiColorPrimaryStop2: '#2566ff',
        }}
      >
        <Button block type="primary" size="large">
          primary
        </Button>
      </ConfigProvider>
```

通过css变量设置不生效
![image](https://github.com/jdf2e/nutui-react/assets/75795462/966df63d-7308-4291-9c40-3751062a0c0a)

### 期望的结果是什么？

可以通过css变量定制所有按钮样式

### 实际的结果是什么？

必须通过ConfigProvider或者手动指定按钮颜色

**Comment by Me-UserName** [comment]
Primary Button 的背景色是采用的渐变模式，需要修改 $color-primary-stop-1和 $color-primary-stop-2
感觉这里的设计怪怪的！

**Comment by xiaoyatong** [comment]
css 怎么引入的

**Comment by xiaoyatong** [comment]
> Primary Button 的背景色是采用的渐变模式，需要修改 $color-primary-stop-1和 $color-primary-stop-2 感觉这里的设计怪怪的！

主要是想只设置起止色值就好了，有什么更好的办法么

**Comment by Ryan-CW-Code** [comment]
> css 怎么引入的

直接在app.ts里面引入的，nutui进行按需引用和全量引用都不行
![image](https://github.com/jdf2e/nutui-react/assets/75795462/4fab6f59-715f-4169-9ebf-d2b86be1f1cf)


类似这样的很多都是生效的。
```
--nutui-color-primary
--nutui-tabs-titles-gap
--nutui-input-padding
```
但是 --nutui-color-primary-stop1 和 --nutui-color-primary-stop2 不生效
![image](https://github.com/jdf2e/nutui-react/assets/75795462/aa0e4c91-730f-4de9-bba7-cfbede94fe6a)

**Comment by Ryan-CW-Code** [comment]
fork了一份代码，看了下

--nutui-color-primary-stop-1: #2566ff;
 --nutui-color-primary-stop-2: #2566ff;
改为上面形式，可以了
