### ISSUE TITLE
VirtualList 虚拟列表闪屏&多次触发onScroll&快滚动存在空白

### ISSUE THREAD

**Issue by moaiqin** [jdf2e/nutui-react#1821]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.3.3

### 平台

h5, jd

### 重现链接

https://nutui.jd.com/h5/react/2x/#/zh-CN/component/virtuallist

### 重现步骤

1. nutui-react官网case
2. VirtualList 虚拟列表
3. 垂直不等高模式 -> 慢下滑或下列表 -> 列表item抖动闪屏
4. 垂直不等高模式 -> 快速上滑列表 -> onScroll函数多次触发
5.  垂直不等高模式 -> 快速上滑列表 -> 页面item项出现空白

### 期望的结果是什么？

1. 慢下滑或下列表页面顺畅，不闪屏抖动情况
2. 上滑列表到底部 onScroll只触发一次
3. 快速上滑列表，页面item项不出现空白

### 实际的结果是什么？

3. 垂直不等高模式 -> 慢下滑或下列表 -> 列表item抖动闪屏
4. 垂直不等高模式 -> 快速上滑列表 -> onScroll函数多次触发
5.  垂直不等高模式 -> 快速上滑列表 -> 页面item项出现空白

### 环境信息

1. 小程序环境
 System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.18 => 3.6.18 
      @tarojs/components: 3.6.18 => 3.6.18 
      @tarojs/helper: 3.6.18 => 3.6.18 
      @tarojs/plugin-framework-react: 3.6.18 => 3.6.18 
      @tarojs/plugin-html: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-alipay: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-h5: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-jd: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-qq: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-swan: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-tt: 3.6.18 => 3.6.18 
      @tarojs/plugin-platform-weapp: 3.6.18 => 3.6.18 
      @tarojs/react: 3.6.18 => 3.6.18 
      @tarojs/runtime: 3.6.18 => 3.6.18 
      @tarojs/shared: 3.6.18 => 3.6.18 
      @tarojs/taro: 3.6.18 => 3.6.18 
      @tarojs/taro-loader: 3.6.18 => 3.6.18 
      @tarojs/webpack5-runner: 3.6.18 => 3.6.18 
      babel-preset-taro: 3.6.18 => 3.6.18 
      eslint-config-taro: 3.6.18 => 3.6.18 
      react: ^18.0.0 => 18.2.0

**Comment by mrold** [comment]
问题依然存在啊 【垂直不等高模式 -> 慢下滑或下列表 -> 列表item抖动闪屏】
@oasis-cloud @moaiqin

**Comment by xm1769315774** [comment]
+1上滑下滑快速的时候都有空白，复现步骤，直接扫官方的示例二维码即可复现
