### ISSUE TITLE
升级至v2.3.3后 <DatePicker /> 渲染为一个'0'

### ISSUE THREAD

**Issue by zicjin** [jdf2e/nutui-react#1822]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.3.3

### 平台

weapp

### 重现链接

https://github.com/zicjin/taro-issus

### 重现步骤

```shell
pnpm i
pnpm run build:weapp
```
微信开发者工具打开项目即可

### 期望的结果是什么？

正常渲染<DatePicker />

### 实际的结果是什么？

0

### 其他补充信息
退回2.3.2是没有问题的。
```shell
pnpm i @nutui/nutui-react-taro@2.3.2
rm -rf dist
pnpm run build:weapp
```
顺便问一下，为何一定要删除dist目录才能更改package版本号生效呢？直接build:weapp居然是无效的？

**Comment by oasis-cloud** [comment]
问题同 #1814
