### ISSUE TITLE
export 'RectDown' (imported as 'RectDown') was not found in '@nutui/icons-react-taro'

### ISSUE THREAD

**Issue by liuyunzyj** [jdf2e/nutui-react#1824]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.3.3

### 平台

h5

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/component/button

### 重现步骤

![image](https://github.com/jdf2e/nutui-react/assets/40293335/51dd7065-c72d-4142-8c1e-2d9ad56cc742)
![image](https://github.com/jdf2e/nutui-react/assets/40293335/61beca67-cfce-4560-911a-9a8402203deb)

### 期望的结果是什么？

不要出现错误

### 实际的结果是什么？

![image](https://github.com/jdf2e/nutui-react/assets/40293335/53bbdf45-13a6-4768-9597-6ba01611c7e3)

**Comment by liuyunzyj** [comment]
环境信息：
"dependencies": {
		"@babel/runtime": "^7.19.0",
		"@nutui/icons-react-taro": "^1.0.0",
		"@nutui/nutui-react-taro": "^2.3.3",
		"@tarojs/components": "3.6.20",
		"@tarojs/helper": "3.6.20",
		"@tarojs/plugin-framework-react": "3.6.20",
		"@tarojs/plugin-html": "3.6.20",
		"@tarojs/plugin-mock": "^0.0.9",
		"@tarojs/plugin-platform-alipay": "3.6.20",
		"@tarojs/plugin-platform-h5": "3.6.20",
		"@tarojs/plugin-platform-jd": "3.6.20",
		"@tarojs/plugin-platform-qq": "3.6.20",
		"@tarojs/plugin-platform-swan": "3.6.20",
		"@tarojs/plugin-platform-tt": "3.6.20",
		"@tarojs/plugin-platform-weapp": "3.6.20",
		"@tarojs/react": "3.6.20",
		"@tarojs/router": "3.6.20",
		"@tarojs/runtime": "3.6.20",
		"@tarojs/shared": "3.6.20",
		"@tarojs/taro": "3.6.20",
		"@tarojs/taro-h5": "3.6.20",
		"classnames": "^2.3.2",
		"dayjs": "^1.11.5",
		"lodash": "^4.17.21",
		"mobx": "^4.8.0",
		"mobx-react": "^6.1.4",
		"nervjs": "^1.5.7",
		"promise": "^8.2.0",
		"react": "18.2.0",
		"react-dom": "18.2.0",
		"react-is": "^18.2.0",
		"use-debounce": "^9.0.4",
		"zustand": "^4.3.8"
	},
	"devDependencies": {
		"@babel/core": "^7.19.1",
		"@commitlint/cli": "^11.0.0",
		"@commitlint/config-conventional": "^11.0.0",
		"@commitlint/lint": "^17.0.3",
		"@mini-types/alipay": "^1.0.9",
		"@pmmmwh/react-refresh-webpack-plugin": "0.5.4",
		"@tarojs/cli": "3.6.20",
		"@tarojs/webpack5-runner": "3.6.20",
		"@tarox/plugin-init-app": "^1.0.0-alpha.16",
		"@types/react": "18.0.15",
		"@types/webpack-env": "^1.18.0",
		"@typescript-eslint/eslint-plugin": "^4.0.0",
		"@typescript-eslint/parser": "^4.0.0",
		"@youtils/commitlint-plugin-standard": "^0.0.1",
		"@youtils/prettier-config-standard": "^1.0.1",
		"babel-loader": "^8.2.5",
		"babel-plugin-import": "^1.13.3",
		"babel-preset-taro": "3.6.20",
		"cache-loader": "^4.1.0",
		"cross-env": "^7.0.2",
		"eslint": "^6.8.0",
		"eslint-config-taro": "3.6.20",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-react-hooks": "^1.6.1",
		"husky": "^8.0.1",
		"lint-staged": "^10.4.0",
		"markdownlint": "^0.25.1",
		"markdownlint-cli2": "^0.4.0",
		"miniprogram-automator": "^0.11.0",
		"miniprogram-automator-scripts": "0.0.2",
		"plop": "^2.7.4",
		"postcss": "^8.4.18",
		"prettier": "^2.1.2",
		"pretty-quick": "^3.0.2",
		"react-refresh": "0.11.0",
		"stylelint": "9.3.0",
		"taro-plugin-compiler-optimization": "^1.0.1",
		"taro-plugin-dotenv": "^1.0.0",
		"thread-loader": "^3.0.4",
		"typescript": "^4.1.0",
		"webpack": "^5.74.0"
	}

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-react/discussions/1779
