### ISSUE TITLE
tabs 初始化显示非第一个 tab 页，有明显的动画切换

### ISSUE THREAD

**Issue by shushu2013** [jdf2e/nutui-react#1841]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.3.4

### 平台

h5

### 重现链接

https://github.com/shushu2013/taro3.6.20.git

### 重现步骤

```
$ git clone https://github.com/shushu2013/taro3.6.20.git

$ cd taro3.6.20

// 需要在分支 nutui-tabs-index 中测试
$ git checkout nutui-tabs-index

$ pnpm install

$ pnpm dev:h5
```
tabs 初始化设置显示第三个 tab 页，进入页面时，会有动画切换

https://github.com/jdf2e/nutui-react/assets/6076072/7da25827-e05a-4f00-9785-77774ecd8700

### 期望的结果是什么？

tabs 初始化不是第一个 tab 页时，进入页面时，希望不会有动画切换

### 实际的结果是什么？

tabs 初始化不是第一个 tab 页时，进入页面时，有动画切换

### 环境信息

👽 Taro v3.6.20

  Taro CLI 3.6.20 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.20 => 3.6.20 
      @tarojs/components: 3.6.20 => 3.6.20 
      @tarojs/helper: 3.6.20 => 3.6.20 
      @tarojs/mini-runner: 3.6.20 => 3.6.20 
      @tarojs/plugin-framework-react: 3.6.20 => 3.6.20 
      @tarojs/plugin-html: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-alipay: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-h5: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-jd: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-qq: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-swan: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-tt: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-weapp: 3.6.20 => 3.6.20 
      @tarojs/react: 3.6.20 => 3.6.20 
      @tarojs/runtime: 3.6.20 => 3.6.20 
      @tarojs/shared: 3.6.20 => 3.6.20 
      @tarojs/taro: 3.6.20 => 3.6.20 
      @tarojs/webpack-runner: 3.6.20 => 3.6.20 
      babel-preset-taro: 3.6.20 => 3.6.20 
      eslint-config-taro: 3.6.20 => 3.6.20 
      react: ^18.0.0 => 18.0.0 
    npmGlobalPackages:
      typescript: 5.0.4

**Comment by cdx111** [comment]
你可以进来的时候关闭动画，然后在开启动画

**Comment by eiinu** [comment]
v2.6.3 已修复
