### ISSUE TITLE
编译成钉钉小程序（nutui v2），组件内含有icon的组件都报错

### ISSUE THREAD

**Issue by wangshuo1779** [jdf2e/nutui-react#1846]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.15

### 平台

其他小程序

### 重现链接

import React from 'react' import { View } from '@tarojs/components' import { Button } from "@nutui/nutui-react-taro" import './index.scss'  function Index() {   return (     <View className="nutui-react-demo">       <View className="index">         欢迎使用 NutUI React 开发 Taro 多端项目。       </View>       <View className="index">         <Button type="primary" className="btn">           NutUI React Button         </Button>       </View>     </View>   ) }  export default Index

### 重现步骤

![截屏2024-01-08 10 49 30](https://github.com/jdf2e/nutui-react/assets/111849327/108e797e-b19e-47d3-9d72-fe446aaf2d99)
![WechatIMG23](https://github.com/jdf2e/nutui-react/assets/111849327/536a43b6-493e-416c-a4a0-8dc461c5c672)

代码中使用图一这些组件，编译成钉钉小程序，都会报图二这样的错误，但是编译成微信小程序会正常显示。

### 期望的结果是什么？

使用Button等组件，编译成钉钉小程序正常显示，不报错。

### 实际的结果是什么？

页面报错
![Uploading WechatIMG23.jpg…]()

### 环境信息

Apples-MacBook-Pro:nutui apple$ taro info
👽 Taro v3.6.20

  Taro CLI 3.6.20 environment info:
    System:
      OS: macOS 12.6.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.20 => 3.6.20 
      @tarojs/components: 3.6.20 => 3.6.20 
      @tarojs/helper: 3.6.20 => 3.6.20 
      @tarojs/plugin-framework-react: 3.6.20 => 3.6.20 
      @tarojs/plugin-html: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-alipay: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-h5: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-jd: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-qq: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-swan: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-tt: 3.6.20 => 3.6.20 
      @tarojs/plugin-platform-weapp: 3.6.20 => 3.6.20 
      @tarojs/react: 3.6.20 => 3.6.20 
      @tarojs/runtime: 3.6.20 => 3.6.20 
      @tarojs/shared: 3.6.20 => 3.6.20 
      @tarojs/taro: 3.6.20 => 3.6.20 
      @tarojs/taro-loader: 3.6.20 => 3.6.20 
      @tarojs/webpack5-runner: 3.6.20 => 3.6.20 
      babel-preset-taro: 3.6.20 => 3.6.20 
      eslint-config-taro: 3.6.20 => 3.6.20 
      react: ^18.0.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 5.0.4

### 其他补充信息

{
  "name": "nutui",
  "version": "1.0.0",
  "private": true,
  "description": "nutui",
  "templateInfo": {
    "name": "react-NutUI",
    "typescript": true,
    "css": "sass"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:dd": "taro build --type dd",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:jd": "taro build --type jd",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:dd": "npm run build:dd -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:jd": "npm run build:jd -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch"
  },
  "browserslist": [
    "last 3 versions",
    "Android >= 4.1",
    "ios >= 8"
  ],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@nutui/nutui-react-taro": "^2.0.15",
    "@tarojs/components": "3.6.20",
    "@tarojs/helper": "3.6.20",
    "@tarojs/plugin-framework-react": "3.6.20",
    "@tarojs/plugin-html": "3.6.20",
    "@tarojs/plugin-platform-alipay": "3.6.20",
    "@tarojs/plugin-platform-alipay-dd": "^0.3.1",
    "@tarojs/plugin-platform-h5": "3.6.20",
    "@tarojs/plugin-platform-jd": "3.6.20",
    "@tarojs/plugin-platform-qq": "3.6.20",
    "@tarojs/plugin-platform-swan": "3.6.20",
    "@tarojs/plugin-platform-tt": "3.6.20",
    "@tarojs/plugin-platform-weapp": "3.6.20",
    "@tarojs/react": "3.6.20",
    "@tarojs/runtime": "3.6.20",
    "@tarojs/shared": "3.6.20",
    "@tarojs/taro": "3.6.20",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-refresh": "^0.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
    "@tarojs/cli": "3.6.20",
    "@tarojs/taro-loader": "3.6.20",
    "@tarojs/webpack5-runner": "3.6.20",
    "@types/node": "^18.15.11",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@types/react-router-dom": "^5.1.7",
    "@types/react-syntax-highlighter": "^13.5.2",
    "@types/react-test-renderer": "^18.0.0",
    "@types/react-transition-group": "^4.4.4",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "@typescript-eslint/parser": "^5.20.0",
    "babel-plugin-import": "^1.13.3",
    "babel-preset-taro": "3.6.20",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.6.20",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "postcss": "^8.4.18",
    "style-loader": "1.3.0",
    "stylelint": "^14.4.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.1.0",
    "webpack": "^5.78.0"
  }
}

**Comment by wangshuo1779** [comment]
![Uploading 截屏2024-01-08 10.49.30.png…]()

**Comment by Me-UserName** [comment]
编译成支付宝小程序报同样的错误，凡带有icon的组件都出错

**Comment by 5082673** [comment]
尝试一下

// config/index.js
config = {
  compiler: {
    type: 'webpack5',
    prebundle: {
      exclude: ['@nutui/nutui-react-taro', '@nutui/icons-react-taro']
    }
  },
  cache: {
    enable: false
  }
}

**Comment by wangshuo1779** [comment]
@5082673  配置里加了后还是不行，还是报同样的错误。

**Comment by 5082673** [comment]
> @5082673 配置里加了后还是不行，还是报同样的错误。

开发者工具 -> 详情 -> 编译配置 -> 转 ES5编译配置 -> 只编译项目代码
再试试呢

**Comment by Me-UserName** [comment]
> 还是报同样的错误

+1

**Comment by wangshuo1779** [comment]
> > @5082673 配置里加了后还是不行，还是报同样的错误。
> 
> 开发者工具 -> 详情 -> 编译配置 -> 转 ES5编译配置 -> 只编译项目代码 再试试呢

转 ES5编译配置 ->    一直显示保持历史行为，无法修改，怎么处理呀？taro里钉钉小程序的项目配置文件名是什么呀？我看文档里没找到

**Comment by wangshuo1779** [comment]
![Uploading 截屏2024-01-10 14.10.32.png…]()

**Comment by oasis-cloud** [comment]
可在 package.json 中增加 "resolutions": {
    "@nutui/icons-react-taro": "1.0.2"
  }，然后重新安装

**Comment by wangshuo1779** [comment]
可以了，感谢大佬🙏
