### ISSUE TITLE
Input受控模式，手动修改value后，onChange会自动触发，并传入上一个value的值

### ISSUE THREAD

**Issue by WweiweiSmile** [jdf2e/nutui-react#1876]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.3.6

### 平台

weapp

### 重现链接

https://y83cjj-5173.csb.app/

### 重现步骤

安卓端微信小程序调用以下组件可复现，注：微信开发者工具与CodeSandbox无法复现

``` typescript
import { View } from "@tarojs/components";
import { Input, Button } from "@nutui/nutui-react-taro";
import { useState } from "react";

const Test = () => {
  const [keyword, setKeyword] = useState("");

  return <View>
    <Input value={keyword} onChange={setKeyword}/>
    <Button onClick={() => {setKeyword("");}}>清空</Button>
  </View>;
};

export default Test
;
```

### 期望的结果是什么？

`<Input />`组件输入`"test"`值后，点击`清空`按钮，输入框清空

### 实际的结果是什么？

点击`清空`按钮后`keyword`更新为`""`，随后`<Input />`组件的`onChange`事件会被自动调用并传入`"test"`值，导致`<Input />`组件的值未能清空

**Comment by WweiweiSmile** [comment]
github复现库：https://github.com/WweiweiSmile/nutui-input-test.git

**Comment by cdx111** [comment]
i am the same problem as well
