### ISSUE TITLE
Popup 组件配置 destroyOnClose 属性不生效

### ISSUE THREAD

**Issue by DamnTime** [jdf2e/nutui-react#1901]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

3.5.0

### 平台

weapp

### 重现链接

https://github.com/jdf2e/nutui-react/blob/v2.3.5/src/packages/popup/popup.taro.tsx#L251

### 重现步骤

```tsx
import React, { useState } from "react";
import { Input } from '@tarojs/components';
import { Popup, Cell } from '@nutui/nutui-react-taro';

const App = () => {
  const [showBasic, setShowBasic] = useState(false);
  return (
    <>
        <Cell title="展示弹出层"  onClick={() => { setShowBasic(true) }}/>
        <Popup visible={ showBasic } style={{ padding: '30px 50px' }} destroyOnClose={false} onClose={ () => { setShowBasic(false) } }>
            <Input />
        </Popup>
    </>
  );
};
export default App;
```

### 期望的结果是什么？

popup 关闭后input输入框的值保留

### 实际的结果是什么？

popup 关闭后input输入框的值被清空

### 其他补充信息

源码在调用 CSSTransition 组件时，直接设置了 unmountOnExit 为true（已贴出源码地址链接）。 怀疑是这个原因

**Comment by oasis-cloud** [comment]
对，是这个原因。有兴趣可以提交相关 PR 进行修复。
