### ISSUE TITLE
DatePicker 受控模式下出现 2 月 31 日

### ISSUE THREAD

**Issue by lmlss** [jdf2e/nutui-react#1923]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.3.7

### 平台

weapp

### 重现链接

官网扫码

### 重现步骤

扫官网体验小程序二维码
进入 DatePicker
<img width="369" alt="image" src="https://github.com/jdf2e/nutui-react/assets/86602019/6fdcffe0-662d-4b0a-a3d2-016430319447">

### 期望的结果是什么？

月份改变，对应每月有多少天动态改变

### 实际的结果是什么？

当月份改变时，对应的天没有改变。
会出现 2 月 31 日。。。

**Comment by cdx111** [comment]
。。。
