### ISSUE TITLE
[FR]: 希望提供功能更强大的form组件

### ISSUE THREAD

**Issue by liqingitt** [jdf2e/nutui-react#1924]
### 这个功能解决了什么问题？

1、当表单内字段的值发生变化时，进行一些统一的处理。目前只能在每个表单项上绑定onChange
2、表单内字段发生变化，需要动态控制其他字段显示或隐藏时，也只能通过绑定onChange，并且定一个一个state去控制
（antd-mobile中则可以这样做：<Form.item>
{()=>{
const xxx = form.getValues()
if(xxx){
return null

}

return <Form.Item name={"xxx"}>
<input />
</Form>

}}
<Form.Item>）

### 你期望的组件设计是怎样的？

参照antd 或antd-mobile 的Form组件api就好啦

**Comment by liqingitt** [comment]
<img width="375" alt="WechatIMG144" src="https://github.com/jdf2e/nutui-react/assets/84669383/cf8b92b1-6dff-4fb7-a590-9ffffa105b12">
补充上面代码示例

**Comment by onlyling** [comment]
可以基于 [rc-field-form](https://www.npmjs.com/package/rc-field-form) 简单封装一下就好了，配合 Field 的 `onMetaChange` 回调把每个 Field 错误信息显示出来。

逻辑封装可以参考 [react-native-xiaoshu-form](https://github.com/hjfruit/react-native-xiaoshu/tree/main/src/form)，UI 就配合自己的需求搞。
