### ISSUE TITLE
CountDown组件onEnd存在多次回调

### ISSUE THREAD

**Issue by yeeli** [jdf2e/nutui-react#1934]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.3.6

### 平台

weapp, alipay

### 重现链接

https://github.com/jdf2e/nutui-react/blob/next/src/packages/countdown/countdown.taro.tsx

### 重现步骤

CountDown组件在倒数结束时调用onEnd会存在调用多次

### 期望的结果是什么？

在未设置millisecond为true的时候， CountDown组件的onEnd方法在秒数等于0时只被调用一次

### 实际的结果是什么？

在未设置millisecond为true的时候， CountDown组件的onEnd方法被在秒数等于0时被调用了多次

### 其他补充信息

在源码tick方法中， 由于Date.now()获取毫秒级时间， 在tick方法中秒数已经等于0的时候， 毫秒还是会大于0，remainTime 大于0 会使tick方法会存在多次自我调用， 所以导致我未开启毫秒级渲染时， onEnd被多次调用

```
  const tick = () => {
    stateRef.current.timer = requestAnimationFrame(() => {
      if (stateRef.current.counting) {
        const currentTime = Date.now() - stateRef.current.diffTime
        const remainTime = Math.max(
          stateRef.current.handleEndTime - currentTime,
          0
        )

        stateRef.current.restTime = remainTime
        setRestTime(remainTime)

        if (!remainTime) {
          stateRef.current.counting = false
          pause()
          onEnd && onEnd()
        }

        if (remainTime > 0) {
          tick()
        }
      }
    })
  }
```

**Comment by Miles-hxy** [comment]
根据这段源码，tick是被多次调用了，但会刷新counting状态，所以onEnd不会重复调用吧。可以提供个能调用多次onEnd的demo.
