### ISSUE TITLE
使用scss 配置主题色无效

### ISSUE THREAD

**Issue by WuQiang19950420** [jdf2e/nutui-react#1947]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.3.1

### 平台

weapp

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/guide/theme-react

### 重现步骤

<img width="785" alt="image" src="https://github.com/jdf2e/nutui-react/assets/50325159/6fcc41ed-4aeb-4e0c-a898-36f48e4d7964">
<img width="1444" alt="image" src="https://github.com/jdf2e/nutui-react/assets/50325159/72ac3096-13e5-48ac-8205-c6e4bc6f39e7">
<img width="942" alt="image" src="https://github.com/jdf2e/nutui-react/assets/50325159/5477b750-9d02-4ee6-8ef4-edf778075c91">

配置都配置好了 不知道哪个步骤错了

### 期望的结果是什么？

主题色变换

### 实际的结果是什么？

主题色变换

### 环境信息

	"dependencies": {
		"@babel/runtime": "^7.7.7",
		"@linaria/core": "^6.0.0",
		"@linaria/react": "^6.0.0",
		"@nutui/nutui-react-taro": "^2.3.10",
		"@tarojs/components": "3.6.23",
		"@tarojs/helper": "3.6.23",
		"@tarojs/plugin-framework-react": "3.6.23",
		"@tarojs/plugin-html": "3.6.23",
		"@tarojs/plugin-platform-alipay": "3.6.23",
		"@tarojs/plugin-platform-h5": "3.6.23",
		"@tarojs/plugin-platform-jd": "3.6.23",
		"@tarojs/plugin-platform-qq": "3.6.23",
		"@tarojs/plugin-platform-swan": "3.6.23",
		"@tarojs/plugin-platform-tt": "3.6.23",
		"@tarojs/plugin-platform-weapp": "3.6.23",
		"@tarojs/react": "3.6.23",
		"@tarojs/runtime": "3.6.23",
		"@tarojs/shared": "3.6.23",
		"@tarojs/taro": "3.6.23",
		"@wyw-in-js/babel-preset": "^0.3.0",
		"react": "^18.0.0",
		"react-dom": "^18.0.0"
	},
	"devDependencies": {
		"@babel/core": "^7.8.0",
		"@pmmmwh/react-refresh-webpack-plugin": "^0.5.5",
		"@tarojs/cli": "3.6.23",
		"@tarojs/taro-loader": "3.6.23",
		"@tarojs/webpack5-runner": "3.6.23",
		"@types/node": "^18.15.11",
		"@types/react": "^18.0.0",
		"@types/webpack-env": "^1.13.6",
		"@wyw-in-js/webpack-loader": "^0.3.0",
		"babel-plugin-import": "^1.13.8",
		"babel-preset-taro": "3.6.23",
		"eslint": "^8.12.0",
		"eslint-config-taro": "3.6.23",
		"eslint-plugin-import": "^2.12.0",
		"eslint-plugin-react": "^7.8.2",
		"eslint-plugin-react-hooks": "^4.2.0",
		"react-refresh": "^0.11.0",
		"stylelint": "^14.4.0",
		"ts-node": "^10.9.1",
		"webpack": "5.78.0"
	}

**Comment by eiinu** [comment]
文档已更新。
