### ISSUE TITLE
input组件value传undefined不会清空

### ISSUE THREAD

**Issue by KellenHe** [jdf2e/nutui-react#1952]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.3.10

### 平台

h5

### 重现链接

https://codesandbox.io/p/sandbox/wandering-voice-nf3ts5

### 重现步骤

1、input的value设置为123
2、改变value为undefined
3、input没有被清空，还是123

### 期望的结果是什么？

可以被清空

### 实际的结果是什么？

没有清空

**Comment by oasis-cloud** [comment]
为什么不传空串？

**Comment by KellenHe** [comment]
如果默认是一个空字符串，defaultValue会失效，设置type=password也会无法输入。感觉这块有点问题。
@oasis-cloud

**Comment by KellenHe** [comment]
在formily一些表单组件中使用，表单重置传的也是undefined。
@oasis-cloud

**Comment by oasis-cloud** [comment]
你提供的 sandbox 打不开，是在 form 下使用 input，通过 form 重置吗，可以写下 demo 吗？

**Comment by KellenHe** [comment]
> 你提供的 sandbox 打不开，是在 form 下使用 input，通过 form 重置吗，可以写下 demo 吗？

https://codesandbox.io/p/devbox/wandering-voice-nf3ts5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clswm1e6400073j6gzl1df90k%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clswm1e6400023j6gigazh7q9%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clswm1e6400043j6gh6allulx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clswm1e6400063j6gat91ch11%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clswm1e6400023j6gigazh7q9%2522%253A%257B%2522id%2522%253A%2522clswm1e6400023j6gigazh7q9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clswm30bz004d3j6g4uqlxmqs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A16%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clswm30bz004d3j6g4uqlxmqs%2522%257D%252C%2522clswm1e6400063j6gat91ch11%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clswm1e6400053j6g2924ypyq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clswm1e6400063j6gat91ch11%2522%252C%2522activeTabId%2522%253A%2522clswm1e6400053j6g2924ypyq%2522%257D%252C%2522clswm1e6400043j6gh6allulx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clswm1e6400033j6g3gneeour%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clswm1e6400043j6gh6allulx%2522%252C%2522activeTabId%2522%253A%2522clswm1e6400033j6g3gneeour%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by KellenHe** [comment]
> 你提供的 sandbox 打不开，是在 form 下使用 input，通过 form 重置吗，可以写下 demo 吗？

可以打开了，https://codesandbox.io/p/devbox/wandering-voice-nf3ts5?file=%2Fsrc%2FApp.tsx%3A13%2C2

是在form中重置，form重置后返回的value是undefined。

**Comment by oasis-cloud** [comment]
在 Form 中可以通过 FormInstance 上的 resetFields 方法进行重置，或者通过 setFieldsValue 设置空字符串
