### ISSUE TITLE
Ellipsis rows设置成多行的时候，内容超过一行，但不满省略内容的时候，页面只展示了一行内容

### ISSUE THREAD

**Issue by ht-xiaomei** [jdf2e/nutui-react#2008]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.3.10

### 平台

jd

### 重现链接

git@coding.jd.com:cofe/fe-im-mp.git

### 重现步骤

 <Ellipsis
        rows={4}
        content={'hello,我是文本消息hello,我是文本消息hello,我是文本消息hello,我是文本消息hello,我是文本消息hello,我是文本消息hello,我是文本消息hello,'}
        direction="end"
        expandText="展开"
        collapseText="收起"
        width={263}
      />

### 期望的结果是什么？

全部展示完所有的内容，没有收起展开额外东西

### 实际的结果是什么？

只展示了一行文字内容

**Comment by Me-UserName** [comment]
同样遇到这个问题

**Comment by Me-UserName** [comment]
V2.4
