### ISSUE TITLE
使用TimeSelect组件在抖音小程序展示错误

### ISSUE THREAD

**Issue by limuen** [jdf2e/nutui-react#2056]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.4.0

### 平台

tt

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/component/timeselect

### 重现步骤

import { TimeSelect } from "@nutui/nutui-react-taro";

<TimeSelect
        visible={visible}
        options={options}
        style={{
          height: "auto"
        }}
        onSelect={handleSelect}
        onDateChange={handleDateChange}
        onTimeChange={handleTimeChange}
      />
正常来说是一行一个，现在都并排
![561710749027_ pic](https://github.com/jdf2e/nutui-react/assets/31790606/f7c104dd-090f-4def-bef1-379816e0a905)

### 期望的结果是什么？

期望按照官方的预览走

### 实际的结果是什么？

现在并排

**Comment by xiaoyatong** [comment]
可通过样式变量处理~
在v3 中会重新适配~
