### ISSUE TITLE
微信小程序下， 给Ellipsis组件设置fontSize后工作不正常

### ISSUE THREAD

**Issue by alan0x** [jdf2e/nutui-react#2077]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.4.1

### 平台

weapp

### 重现链接

https://github.com/FPG-Alan/nutui-ellipsis-reproduce

### 重现步骤

渲染一个Ellipsis组件， props如下：
```tsx
<Ellipsis
   content={content}
   rows="3"
   style={{ fontSize: '20rpx' }}
/>
```

### 期望的结果是什么？

显示三行文字， 末尾显示“...”

### 实际的结果是什么？

初始显示四行文字， 然后每100ms显示的文字减一， 直到两行。

**Comment by xiaoyatong** [comment]
现在如果显示一行，会这样：
![image](https://github.com/jdf2e/nutui-react/assets/84436086/8568db50-6358-4ee7-aca7-0023bb74f447)

我是这样理解的：如果字修改小号时，是不是可以让放下更多的字？
多行也有类似问题：
![image](https://github.com/jdf2e/nutui-react/assets/84436086/6c56aaa2-605c-4c4d-ba6e-39c28a524c22)

辛苦跟进~

**Comment by alan0x** [comment]
这也是因为没有给用于测量宽度的`nut-ellipsis-copy`正确的font size造成的， 如果把`nut-ellipsis-copy`显示出来可以看到：
![image](https://github.com/jdf2e/nutui-react/assets/5809641/86ef0f59-0062-4ee8-8124-31320a5871d2)
此时`nut-ellipsis-copy`使用的是默认字号， 宽度也是按照默认字号来算的。

如果给`nut-ellipsis-copy`设置了正确的字号， 显示的是正确的， 因为字号缩小， 此时可以放下更多的字：
![image](https://github.com/jdf2e/nutui-react/assets/5809641/7cea4b87-98ab-47a5-84f5-c357082c758e)

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-react/pull/2078
