### ISSUE TITLE
Infiniteloading 组件 pullTxt、loadTxt 和 loadMoreTxt 参数无效

### ISSUE THREAD

**Issue by JaxonSong** [jdf2e/nutui-react#212]
pullTxt、loadTxt、loadMoreTxt属性设置了都无效，还是显示的默认文字，代码如下：
![image](https://user-images.githubusercontent.com/38279131/184075190-27d322ea-df51-44fb-8218-f66464fccf94.png)

**Comment by junjun666** [comment]
感谢问题的详细描述，这边正抓紧修复~
