### ISSUE TITLE
[FR]: Icon官网Demo中的图标复制

### ISSUE THREAD

**Issue by chengluliu** [jdf2e/nutui-react#2125]
### 这个功能解决了什么问题？

官网示例中的图标组件无法复制了
https://nutui.jd.com/taro/react/2x/#/zh-CN/component/icon

### 你期望的组件设计是怎样的？

如果是业务需要修改掉的, 能否给一份能使用图标的Icon字典让咱们知道可以使用哪些

**Comment by xiaoyatong** [comment]
是说目前组件里内置了哪些icon吗

**Comment by chengluliu** [comment]
> 是说目前组件里内置了哪些icon吗

恩 , 是的童姐姐,  现在官网例子上不能点击复制了, 然后我在使用过程中,不知道组件具体叫什么名字 , 后来我是查看css用过特征字符串去尝试, 这样会有点困扰
