### ISSUE TITLE
在ios环境下，日历卡片，切换月份不触发onPageChange事件

### ISSUE THREAD

**Issue by zixiao144** [jdf2e/nutui-react#2152]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.5.1

### 平台

weapp

### 重现链接

..

### 重现步骤

CalendarCard 组件在ios环境下切换月份不触发onPageChange事件

### 期望的结果是什么？

触发onPageChange事件

### 实际的结果是什么？

触发onPageChange事件

**Comment by zixiao144** [comment]
<CalendarCard value={date} onPageChange={()=>changeMonth()} renderDayTop={renderDayTop}

**Comment by oasis-cloud** [comment]
可以将 demo 补全一些。目前通过官方网站的 Demo1， 增加 onPageChange 事件后，切换月份在 iOS 的小程序中可以出发。
