### ISSUE TITLE
Checkbox主题色不生效

### ISSUE THREAD

**Issue by 814351846** [jdf2e/nutui-react#2161]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.4.0

### 平台

weapp

### 重现步骤

--nutui-color-primary-stop-1: #2566ff;
--nutui-color-primary-stop-2: #5c8cfb;
Checkbox defaultChecked={checked} />
主题色无效

### 期望的结果是什么？

设置主题色

### 实际的结果是什么？

主题色不生效

### 其他补充信息

Taro v3.6.24

**Comment by oasis-cloud** [comment]
checkbox 没用到 primary-stop，使用的是 --nutui-color-primary

**Comment by 814351846** [comment]
感谢
