### ISSUE TITLE
Swiper异步加载indicator不显示

### ISSUE THREAD

**Issue by lwpassvoice** [jdf2e/nutui-react#2166]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.5.2

### 平台

weapp

### 重现链接

https://codesandbox.io/p/sandbox/nutui-react-2x-demo-fg4vxd?file=/src/App.tsx

### 重现步骤

直接复制文档swiper中异步加载的代码
```
import React, { useEffect, useState } from 'react'
import { Swiper } from '@nutui/nutui-react-taro'

const Demo2 = () => {
  const list = [
    'https://storage.360buyimg.com/jdc-article/NutUItaro34.jpg',
    'https://storage.360buyimg.com/jdc-article/NutUItaro2.jpg',
    'https://storage.360buyimg.com/jdc-article/welcomenutui.jpg',
    'https://storage.360buyimg.com/jdc-article/fristfabu.jpg',
  ]

  const [asyncList, setAsyncList] = useState<string[]>([])
  useEffect(() => {
    setTimeout(() => {
      setAsyncList(list)
    }, 3000)
  }, [])
  return (
    <Swiper defaultValue={0} indicator>
      {asyncList.map((item, index) => (
        <Swiper.Item key={item}>
          <img width="100%" height="100%" src={item} alt="" />
        </Swiper.Item>
      ))}
    </Swiper>
  )
}
export default Demo2

```

### 期望的结果是什么？

indicator能显示

### 实际的结果是什么？

![image](https://github.com/jdf2e/nutui-react/assets/22510735/fdb3df3a-75e6-4c77-a27f-5218bab8317b)

indicator未显示

### 其他补充信息

![image](https://github.com/jdf2e/nutui-react/assets/22510735/75e93dc0-b139-4386-a7ba-71c5fcc38258)
[CodeSandbox](https://codesandbox.io/p/sandbox/nutui-react-2x-demo-fg4vxd?file=/src/App.tsx)  CodeSandbox不能fork

**Comment by WuJiY** [comment]
依然不显示
