### ISSUE TITLE
Uploader  在安卓版京me中为啥不能打开摄像头

### ISSUE THREAD

**Issue by mgserss** [jdf2e/nutui-react#2172]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.4.0

### 平台

h5

### 重现链接

https://nutui.jd.com/h5/react/2x/#/zh-CN/component/uploader

### 重现步骤

打开京me，打开上述官网Uploader  链接，点击上传，ios可以选择摄像头相册，安卓立马跳到相册

### 期望的结果是什么？

安卓在京me里也能打开摄像头

### 实际的结果是什么？

不能打开

**Comment by xiaoyatong** [comment]
1

**Comment by xiaoyatong** [comment]
该问题已反馈容器处理。
