### ISSUE TITLE
签名组件错误

### ISSUE THREAD

**Issue by hsulei** [jdf2e/nutui-react#2187]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.1

### 平台

weapp

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/component/signature

### 重现步骤

1. 点击确认，签名内容自动清除
2. 在微信小程序开发工具中使用，confirm 返回的是临时的http路径，而不是图片的base64

### 期望的结果是什么？

点击确认，签名内容不清除
confirm 返回图片base64

### 实际的结果是什么？

1. 点击确认，签名内容自动清除
2. 在微信小程序开发工具中使用，confirm 返回的是临时的http路径

**Comment by Miles-hxy** [comment]
问题2底层是通过canvasToTempFilePath api,主要是返回临时文件路径。可通过自定义操作文件处理。
