### ISSUE TITLE
按需添加组件提示模块找不到 template xxx not found， 已按照文档要求安装beble插件

### ISSUE THREAD

**Issue by ONE-0508** [jdf2e/nutui-react#2191]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.1

### 平台

weapp

### 重现链接

无

### 重现步骤

安装 nutui 后， 按需引入插件， 编译成微信小程序后提示 Templat xxx not found, 已按照文档需求安装插件， 并配置config

# 页面
```
import { 
  Button,
} from '@nutui/nutui-react-taro'

export default function page() {
    return (
     <View>
        <Button >hello</Button>
     </View>
   )
}
```

# bable.config.js

```
module.exports = {
  presets: [
    ['taro', {
      framework: 'react',
      ts: true
    }]
  ],
  plugins: [
    [
      "import",
      {
        "libraryName": "@nutui/nutui-react-taro",
        "libraryDirectory": "dist/esm",
        "style": 'css',
        "camel2DashComponentName": false
      },
      'nutui-react-taro'
    ]
  ]
}
```

# config/index.ts
```
 config = {
     compiler: {
      type: 'webpack5',
      prebundle: {
        exclude: [
          '@nutui/nutui-react-taro', 
          '@nutui/icons-react-taro',
        ]
      }
    },
}

```

编译后显示
![468cdd03e54eed72eddde6fd00ee4dab](https://github.com/jdf2e/nutui-react/assets/136966769/9584285a-dc1d-4b4f-9b9b-1e7577be1bb0)

页面无法显示button组件
<img width="309" alt="image" src="https://github.com/jdf2e/nutui-react/assets/136966769/ef16d711-5547-4699-94e6-df8c89496e0f">

### 期望的结果是什么？

正常显示组件

### 实际的结果是什么？

无法显示

### 环境信息

  Taro CLI 3.6.27 environment info:
    System:
      OS: macOS 13.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.19.1/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.26 => 3.6.26
      @tarojs/components: 3.6.26 => 3.6.26
      @tarojs/helper: 3.6.26 => 3.6.26
      @tarojs/plugin-framework-react: 3.6.26 => 3.6.26
      @tarojs/plugin-html: ^3.6.27 => 3.6.27
      @tarojs/plugin-platform-alipay: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-h5: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-jd: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-qq: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-swan: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-tt: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-weapp: 3.6.26 => 3.6.26
      @tarojs/react: 3.6.26 => 3.6.26
      @tarojs/runtime: 3.6.26 => 3.6.26
      @tarojs/shared: 3.6.26 => 3.6.26
      @tarojs/taro: 3.6.26 => 3.6.26
      @tarojs/taro-loader: 3.6.26 => 3.6.26
      @tarojs/webpack5-runner: 3.6.26 => 3.6.26
      babel-preset-taro: 3.6.26 => 3.6.26
      eslint-config-taro: 3.6.26 => 3.6.26
      react: ^18.0.0 => 18.2.0

**Comment by Miles-hxy** [comment]
看一下注意事项3能否解决你的问题https://nutui.jd.com/taro/react/2x/#/zh-CN/guide/start-react

**Comment by ONE-0508** [comment]
> 看一下注意事项3能否解决你的问题https://nutui.jd.com/taro/react/2x/#/zh-CN/guide/start-react

emm 问题描述里面 config/index.js 就是按照 注意事项3进行配置的

**Comment by Miles-hxy** [comment]
cache试了么

**Comment by ONE-0508** [comment]
> cache试了么

也设定为false 了

**Comment by eiinu** [comment]
`@tarojs/plugin-html` 的版本不正确。

**Comment by xiaoyatong** [comment]
要确保所有的引入的taro的版本是一致的。

**Comment by Deja-vuuu** [comment]
> 要确保所有的引入的taro的版本是一致的。

要确保所有的引入的taro的版本是一致的是什么意思 大佬？

**Comment by Deja-vuuu** [comment]
> > 要确保所有的引入的taro的版本是一致的。
> 
> 要确保所有的引入的taro的版本是一致的是什么意思 大佬？

我懂了 nutui-react 的taro版本要跟项目一样   taro v4 cli生成项目模版没法用
