### ISSUE TITLE
Taro版本 Button 无法设置 nativeType  按钮原始类型  submit  reset   button，没有属性

### ISSUE THREAD

**Issue by jiankian** [jdf2e/nutui-react#2193]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.1

### 平台

h5

### 重现链接

https://github.com/jdf2e/nutui-react/issues/2186

### 重现步骤

Taro版本没有 nativeType属性，不能设置button原生的button类型
非Taro版本就有
假如Taro开发的跨端小程序要打包h5版本时，按钮无法设置原始类型，现在的type属性是设置按钮的样式的类型的

nativeType | 按钮原始类型 | submit \| reset \| button
-- | -- | --

### 期望的结果是什么？

Taro版本增加原始类型支持，使能在Taro跨端打包的H5版本能自定义button的原始类型。
nativeType | 按钮原始类型 | submit \| reset \| button
-- | -- | --

### 实际的结果是什么？

Taro打包h5版本无法设置按钮原始type

### 其他补充信息

![image](https://github.com/jdf2e/nutui-react/assets/9036838/960c3edd-c407-462e-8c2d-ae111f5ba14c)

**Comment by jiankian** [comment]
已有解决代码提交，请求合入主包
[https://github.com/jdf2e/nutui-react/pull/2195](https://github.com/jdf2e/nutui-react/pull/2195)

**Comment by Skedush** [comment]
+1
