### ISSUE TITLE
修改主题色后，Dialog 确认按钮颜色没有同步成主题色

### ISSUE THREAD

**Issue by zhangminggeek** [jdf2e/nutui-react#2197]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.0

### 平台

weapp

### 重现链接

https://codesandbox.io/p/devbox/nutui-react-2x-demo-fg4vxd?file=%2Fsrc%2FApp.tsx%3A9%2C5

### 重现步骤

1. app.css 文件中修改主题色变量

```css
page {
  --nutui-color-primary: #003c43;
}
```

2. 使用 Dialog 组件，发现按钮颜色还是红色

### 期望的结果是什么？

dialog 按钮颜色与主题色相同

### 实际的结果是什么？

dialog 按钮颜色未被修改，还是默认的红色

### 环境信息

Taro CLI 3.6.26 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.5.1 - ~/.nvm/versions/node/v20.9.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.26 => 3.6.26
      @tarojs/components: 3.6.26 => 3.6.26
      @tarojs/helper: 3.6.26 => 3.6.26
      @tarojs/plugin-framework-react: 3.6.26 => 3.6.26
      @tarojs/plugin-html: ^3.6.26 => 3.6.26
      @tarojs/plugin-platform-alipay: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-h5: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-jd: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-qq: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-swan: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-tt: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-weapp: 3.6.26 => 3.6.26
      @tarojs/react: 3.6.26 => 3.6.26
      @tarojs/runtime: 3.6.26 => 3.6.26
      @tarojs/shared: 3.6.26 => 3.6.26
      @tarojs/taro: 3.6.26 => 3.6.26
      @tarojs/webpack5-runner: 3.6.26 => 3.6.26
      babel-preset-taro: 3.6.26 => 3.6.26
      eslint-config-taro: 3.6.26 => 3.6.26
      react: ^18.2.0 => 18.2.0

**Comment by Alex-huxiyang** [comment]
如果你希望改dialog的按钮字体色，需要设置的变量是--nutui-color-primary-text，如果是背景色可设在--nutui-color-primary-stop-1和--nutui-color-primary-stop-2。具体设置什么变量建议通过浏览器工具查看目标样式对应的变量名。

**Comment by Miles-hxy** [comment]
如果您希望改dialog的按钮字体色，需要设置的变量是--nutui-color-primary-text，如果是背景色可设在--nutui-color-primary-stop-1和--nutui-color-primary-stop-2。具体设置什么变量建议通过浏览器工具查看目标样式对应的变量名。
