### ISSUE TITLE
taro开发h5页面使用Ellipsis报错：Cannot set properties of undefined (setting 'fontSize')

### ISSUE THREAD

**Issue by buchuang** [jdf2e/nutui-react#2198]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.0

### 平台

h5

### 重现链接

无

### 重现步骤

直接引入就会出现：
<Ellipsis
        content={content}
        direction='end'
        rows='3'
        expandText='展开'
        collapseText='收起'
      />

### 期望的结果是什么？

正常显示

### 实际的结果是什么？

报Cannot set properties of undefined (setting 'fontSize')

**Comment by Miles-hxy** [comment]
可以提供报错的demo么

**Comment by buchuang** [comment]
> 可以提供报错的demo么

git地址：https://github.com/buchuang/taro1.git
h5在首页引入Ellipsis就会报错，小程序正常的

**Comment by buchuang** [comment]
> > 可以提供报错的demo么
> 
> git地址：https://github.com/buchuang/taro1.git h5在首页引入Ellipsis就会报错，小程序正常的

对了，还有一个警告信息麻烦也看下，关于图标的问题

**Comment by Alex-huxiyang** [comment]
> > > 可以提供报错的demo么
> > 
> > 
> > git地址：https://github.com/buchuang/taro1.git h5在首页引入Ellipsis就会报错，小程序正常的
> 
> 对了，还有一个警告信息麻烦也看下，关于图标的问题

这个是在哪里

**Comment by buchuang** [comment]
> > > > 可以提供报错的demo么
> > > 
> > > 
> > > git地址：https://github.com/buchuang/taro1.git h5在首页引入Ellipsis就会报错，小程序正常的
> > 
> > 
> > 对了，还有一个警告信息麻烦也看下，关于图标的问题
> 
> 这个是在哪里

你拉下代码，然后运行，会出现个警告
