### ISSUE TITLE
taro开发H5页面中使用DatePicker组件报错：Uncaught TypeError: Cannot read properties of undefined (reading 'baseVal')

### ISSUE THREAD

**Issue by buchuang** [jdf2e/nutui-react#2208]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.0

### 平台

h5

### 重现链接

https://github.com/buchuang/taro1.git

### 重现步骤

随便一个页面引入DatePicker组件，就会报错

### 期望的结果是什么？

不报错，正常显示日期选择

### 实际的结果是什么？

报错Uncaught TypeError: Cannot read properties of undefined (reading 'baseVal')

**Comment by buchuang** [comment]
尽快解决一下，急用

**Comment by buchuang** [comment]
凡是设计到动画弹出的组件，都会出现这个问题，试了一下Picker也是

**Comment by buchuang** [comment]
能不能帮忙定位下哪个依赖问题？

**Comment by buchuang** [comment]
找到问题了
h5: {
      publicPath: "auto",
      staticDirectory: "static",
      // useHtmlComponents: true, //使用了 H5 端使用兼容性组件库，把这个注释掉就行了
      output: {
        filename: "js/[name].[hash:8].js",
        chunkFilename: "js/[name].[chunkhash:8].js",
      },
      ...
      }

**Comment by eiinu** [comment]
> 找到问题了 h5: { publicPath: "auto", staticDirectory: "static", // useHtmlComponents: true, //使用了 H5 端使用兼容性组件库，把这个注释掉就行了 output: { filename: "js/[name].[hash:8].js", chunkFilename: "js/[name].[chunkhash:8].js", }, ... }

还有一些问题需要修改：

1、所有 Taro 相关的依赖版本都应该保持一致且锁定，比如 `@tarojs/components-react`、`@tarojs/plugin-html` 的版本都不正确。
2、React 项目中不应该安装 `@nutui/nutui-taro`，这是一个 Vue 组件库
3、自定义主题没有生效，参考 https://nutui.jd.com/taro/react/2x/#/zh-CN/guide/theme-react 修改

**Comment by buchuang** [comment]
> > 找到问题了 h5: { publicPath: "auto", staticDirectory: "static", // useHtmlComponents: true, //使用了 H5 端使用兼容性组件库，把这个注释掉就行了 output: { filename: "js/[name].[hash:8].js", chunkFilename: "js/[name].[chunkhash:8].js", }, ... }
> 
> 还有一些问题需要修改：
> 
> 1、所有 Taro 相关的依赖版本都应该保持一致且锁定，比如 `@tarojs/components-react`、`@tarojs/plugin-html` 的版本都不正确。 2、React 项目中不应该安装 `@nutui/nutui-taro`，这是一个 Vue 组件库 3、自定义主题没有生效，参考 https://nutui.jd.com/taro/react/2x/#/zh-CN/guide/theme-react 修改

自定义主题我换了CSS Vars来组织样式，但是进入页面<Empty description='暂无儿童信息' actions={[{ text: "新增" }]} />的新增按钮还是没有采用主题按钮，我在当前页面加入主题按钮组件后，Empty组件也跟着变了，我怀疑这是个bug

**Comment by eiinu** [comment]
> > > 找到问题了 h5: { publicPath: "auto", staticDirectory: "static", // useHtmlComponents: true, //使用了 H5 端使用兼容性组件库，把这个注释掉就行了 output: { filename: "js/[name].[hash:8].js", chunkFilename: "js/[name].[chunkhash:8].js", }, ... }
> > 
> > 
> > 还有一些问题需要修改：
> > 1、所有 Taro 相关的依赖版本都应该保持一致且锁定，比如 `@tarojs/components-react`、`@tarojs/plugin-html` 的版本都不正确。 2、React 项目中不应该安装 `@nutui/nutui-taro`，这是一个 Vue 组件库 3、自定义主题没有生效，参考 [nutui.jd.com/taro/react/2x/#/zh-CN/guide/theme-react](https://nutui.jd.com/taro/react/2x/#/zh-CN/guide/theme-react) 修改
> 
> 自定义主题我换了CSS Vars来组织样式，但是进入页面<Empty description='暂无儿童信息' actions={[{ text: "新增" }]} />的新增按钮还是没有采用主题按钮，我在当前页面加入主题按钮组件后，Empty组件也跟着变了，我怀疑这是个bug

配置里面引用了错误的包的样式变量文件

**Comment by buchuang** [comment]
> > > > 找到问题了 h5: { publicPath: "auto", staticDirectory: "static", // useHtmlComponents: true, //使用了 H5 端使用兼容性组件库，把这个注释掉就行了 output: { filename: "js/[name].[hash:8].js", chunkFilename: "js/[name].[chunkhash:8].js", }, ... }
> > > 
> > > 
> > > 还有一些问题需要修改：
> > > 1、所有 Taro 相关的依赖版本都应该保持一致且锁定，比如 `@tarojs/components-react`、`@tarojs/plugin-html` 的版本都不正确。 2、React 项目中不应该安装 `@nutui/nutui-taro`，这是一个 Vue 组件库 3、自定义主题没有生效，参考 [nutui.jd.com/taro/react/2x/#/zh-CN/guide/theme-react](https://nutui.jd.com/taro/react/2x/#/zh-CN/guide/theme-react) 修改
> > 
> > 
> > 自定义主题我换了CSS Vars来组织样式，但是进入页面<Empty description='暂无儿童信息' actions={[{ text: "新增" }]} />的新增按钮还是没有采用主题按钮，我在当前页面加入主题按钮组件后，Empty组件也跟着变了，我怀疑这是个bug
> 
> 配置里面引用了错误的包的样式变量文件

我把所有的样式引入全注释掉，仅配置了按需加载，在小程序上<Empty/>组件上的新增按钮是正常显示红色的，在h5中是灰色的
