### ISSUE TITLE
Signature组件生成的图片背景是透明的

### ISSUE THREAD

**Issue by WuQiang19950420** [jdf2e/nutui-react#2229]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.3

### 平台

weapp

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/component/signature

### 重现步骤

<img width="1070" alt="image" src="https://github.com/jdf2e/nutui-react/assets/50325159/04d3cc16-46fd-45f1-b47d-ed356fa17afa">

### 期望的结果是什么？

签名版是什么颜色 那么生成的图片就是什么颜色

### 实际的结果是什么？

生成透明底

**Comment by Miles-hxy** [comment]
可以理解签名板颜色背景在某些应用场景中的价值，但使用透明背景能提高签名的灵活性和适用性，从而轻松应用于各种不同的背景上，以更好覆盖更多使用场景。

**Comment by WuQiang19950420** [comment]
> 可以理解签名板颜色背景在某些应用场景中的价值，但使用透明背景能提高签名的灵活性和适用性，从而轻松应用于各种不同的背景上，以更好覆盖更多使用场景。

可以给个属性 是否透明
