### ISSUE TITLE
【Swipe】小程序端左滑出现操作项后，点击组件外部无法收回

### ISSUE THREAD

**Issue by zhangminggeek** [jdf2e/nutui-react#2239]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.0

### 平台

weapp

### 重现链接

https://codesandbox.io/p/devbox/nutui-react-2x-demo-fg4vxd?file=%2Fsrc%2FApp.tsx

### 重现步骤

```
<Swipe
  rightAction={
    <View style={{ height: '100%', width: '60px' }}>click</View>
  }
>
  <Cell title="test" />
</Swipe>
```

### 期望的结果是什么？

点击组件外部，操作栏收回

### 实际的结果是什么？

点击组件外部，操作栏未收回

### 环境信息

 Taro CLI 3.6.26 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.5.1 - ~/.nvm/versions/node/v20.9.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.26 => 3.6.26
      @tarojs/components: 3.6.26 => 3.6.26
      @tarojs/helper: 3.6.26 => 3.6.26
      @tarojs/plugin-framework-react: 3.6.26 => 3.6.26
      @tarojs/plugin-html: ^3.6.26 => 3.6.26
      @tarojs/plugin-platform-alipay: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-h5: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-jd: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-qq: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-swan: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-tt: 3.6.26 => 3.6.26
      @tarojs/plugin-platform-weapp: 3.6.26 => 3.6.26
      @tarojs/react: 3.6.26 => 3.6.26
      @tarojs/runtime: 3.6.26 => 3.6.26
      @tarojs/shared: 3.6.26 => 3.6.26
      @tarojs/taro: 3.6.26 => 3.6.26
      @tarojs/webpack5-runner: 3.6.26 => 3.6.26
      babel-preset-taro: 3.6.26 => 3.6.26
      eslint-config-taro: 3.6.26 => 3.6.26
      react: ^18.2.0 => 18.2.0

**Comment by eiinu** [comment]
在小程序的环境限制下无法实现 onClickAway 的逻辑。

**Comment by zhangminggeek** [comment]
> 在小程序的环境限制下无法实现 onClickAway 的逻辑。

那这种场景有什么解决方案呢

**Comment by lv2000-creat** [comment]
请问楼主解决了吗

**Comment by zhangminggeek** [comment]
> 请问楼主解决了吗

换了交互方式，不用这个组件了哈哈哈
