### ISSUE TITLE
Menu组件在选项文字很多时右侧箭头展示异常

### ISSUE THREAD

**Issue by zzzhangy** [jdf2e/nutui-react#2250]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

3.6.28

### 平台

weapp

### 重现链接

https://github.com/jdf2e/nutui-react

### 重现步骤

  const [options] = useState([
    { text: '全部稿件类型', value: 0 },
    { text: '原创', value: 1 },
    { text: '转载', value: 2 },
  ])
  const [options1] = useState([
    { text: '全部内容来源', value: '' },
    { text: '今日头条今日头条今今日头条今日头条今今日头条今日头条今', value: 'b' },
    { text: '微信', value: 'c' },
  ])
      <Menu onClose={(i: number) => console.log('onClose', i)} onOpen={(i: number) => console.log('onOpen', i)}>
        <Menu.Item
          options={options}
          defaultValue={0}
          onChange={(val) => {
            console.log(val)
          }}
        />
        <Menu.Item options={options1} defaultValue="" />
      </Menu>

### 期望的结果是什么？

箭头正常展示

### 实际的结果是什么？

![image](https://github.com/jdf2e/nutui-react/assets/116279784/101e797c-b3a3-4cea-8610-44249b2950cd)

### 环境信息

  Taro CLI 3.6.28 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.17.0 - E:\nvm\node.js\node.EXE
      Yarn: 1.22.22 - E:\nvm\node_global\yarn.CMD      
      npm: 9.6.7 - E:\nvm\node.js\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.28 => 3.6.28 
      @tarojs/components: 3.6.28 => 3.6.28 
      @tarojs/helper: 3.6.28 => 3.6.28 
      @tarojs/plugin-framework-react: 3.6.28 => 3.6.28 
      @tarojs/plugin-html: 3.6.28 => 3.6.28 
      @tarojs/plugin-platform-alipay: 3.6.28 => 3.6.28 
      @tarojs/plugin-platform-h5: 3.6.28 => 3.6.28     
      @tarojs/plugin-platform-jd: 3.6.28 => 3.6.28     
      @tarojs/plugin-platform-qq: 3.6.28 => 3.6.28     
      @tarojs/plugin-platform-swan: 3.6.28 => 3.6.28   
      @tarojs/plugin-platform-tt: 3.6.28 => 3.6.28     
      @tarojs/plugin-platform-weapp: 3.6.28 => 3.6.28  
      @tarojs/react: 3.6.28 => 3.6.28 
      @tarojs/runtime: 3.6.28 => 3.6.28 
      @tarojs/shared: 3.6.28 => 3.6.28 
      @tarojs/taro: 3.6.28 => 3.6.28
      @tarojs/taro-loader: 3.6.28 => 3.6.28
      @tarojs/webpack5-runner: 3.6.28 => 3.6.28
      babel-preset-taro: 3.6.28 => 3.6.28
      eslint-config-taro: 3.6.28 => 3.6.28
      react: ^18.0.0 => 18.3.1

**Comment by zzzhangy** [comment]
![image](https://github.com/jdf2e/nutui-react/assets/116279784/05cae8d8-44db-4fb1-a52a-5995f6092440)
xia下拉框也挺小

**Comment by zzzhangy** [comment]
@Alex-huxiyang

**Comment by Miles-hxy** [comment]
你说的是选中的那个对号样式不正常吗

**Comment by zzzhangy** [comment]
对的

**Comment by Miles-hxy** [comment]
好的
