### ISSUE TITLE
微信小程序 Form.Item 下的 Input 无法聚焦

### ISSUE THREAD

**Issue by royue** [jdf2e/nutui-react#2256]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.4

### 平台

weapp

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/component/form

### 重现步骤

Tabs Tabs.TabPane 下使用 Form.Item 包裹 input

### 期望的结果是什么？

input 可以获得焦点

### 实际的结果是什么？

input 无法获取焦点 无法输入

### 环境信息

  Taro CLI 3.6.29 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
      npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.29 => 3.6.29 
      @tarojs/components: 3.6.29 => 3.6.29 
      @tarojs/helper: 3.6.29 => 3.6.29 
      @tarojs/plugin-framework-react: 3.6.29 => 3.6.29 
      @tarojs/plugin-html: 3.6.29 => 3.6.29 
      @tarojs/plugin-platform-alipay: 3.6.29 => 3.6.29 
      @tarojs/plugin-platform-h5: 3.6.29 => 3.6.29 
      @tarojs/plugin-platform-jd: 3.6.29 => 3.6.29 
      @tarojs/plugin-platform-qq: 3.6.29 => 3.6.29 
      @tarojs/plugin-platform-swan: 3.6.29 => 3.6.29 
      @tarojs/plugin-platform-tt: 3.6.29 => 3.6.29 
      @tarojs/plugin-platform-weapp: 3.6.29 => 3.6.29 
      @tarojs/react: 3.6.29 => 3.6.29 
      @tarojs/runtime: 3.6.29 => 3.6.29 
      @tarojs/shared: 3.6.29 => 3.6.29 
      @tarojs/taro: 3.6.29 => 3.6.29 
      @tarojs/taro-loader: 3.6.29 => 3.6.29 
      @tarojs/webpack5-runner: 3.6.29 => 3.6.29 
      babel-preset-taro: 3.6.29 => 3.6.29 
      eslint-config-taro: 3.6.29 => 3.6

**Comment by Alex-huxiyang** [comment]
可以发下demo

**Comment by oasis-cloud** [comment]
taro 版本降级到 3.6.22 试试
