### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'cancel')

### ISSUE THREAD

**Issue by xian107** [jdf2e/nutui-react#2257]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.4

### 平台

h5

### 重现步骤

![image](https://github.com/jdf2e/nutui-react/assets/13252682/bcfe5518-f3b1-4287-98fb-45f199a507cd)
`<Form.Item
          label="业务"
          name="picker"
          trigger="onConfirm"
          getValueFromEvent={(...args) => args[1]}
          onClick={(event, ref: any) => {
            ref.open();
          }}
          rules={[
            {
              required: true,
              message: "请选择业务",
            },
          ]}
        >
          <Picker options={[busList]} onConfirm={onConfirmBus}>
            {(value: any = {}) => {
              return (
                <Cell
                  style={{
                    padding: 0,
                    "--nutui-cell-divider-border-bottom": "0",
                  }}
                  className="nutui-cell--clickable"
                  title={
                    value.length
                      ? busList.filter((po) => po.value === value[0])[0]?.text
                      : "请选择"
                  }
                  extra={<ArrowRight />}
                  align="center"
                />
              );
            }}
          </Picker>
        </Form.Item>`

### 期望的结果是什么？

不会报错

**Comment by Miles-hxy** [comment]
需要您提供一个可以复现的完整demo，便于我们排查导致该问题的根本原因。
