### ISSUE TITLE
请问Uploader如何上传非图片文件

### ISSUE THREAD

**Issue by xian107** [jdf2e/nutui-react#2264]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.4

### 平台

h5

### 重现链接

希望Uploader能上传非图片文件

### 重现步骤

希望Uploader能上传非图片文件

### 期望的结果是什么？

希望Uploader能上传非图片文件

### 实际的结果是什么？

希望Uploader能上传非图片文件

**Comment by Miles-hxy** [comment]
现在就可以https://nutui.jd.com/h5/react/2x/#/zh-CN/component/uploader

**Comment by xian107** [comment]
> 现在就可以https://nutui.jd.com/h5/react/2x/#/zh-CN/component/uploader
@Alex-huxiyang nutui-react-taro 这个小程序一起的不行

**Comment by eiinu** [comment]
微信小程序本身不支持上传图片、视频以外类型的文件。
