### ISSUE TITLE
倒计时组件无法修改结束时间

### ISSUE THREAD

**Issue by Sweechirly** [jdf2e/nutui-react#2276]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.4

### 平台

h5

### 重现链接

https://codesandbox.io/p/devbox/festive-poitras-jmljhv?file=%2Fsrc%2FApp.tsx%3A12%2C35&workspaceId=3ae1f994-2641-4833-9b28-c616d8ff8a99&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwhgk4wz00083b6ti915ds4q%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwhgk4wz00033b6tjfbr21p2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwhgk4wz00053b6t5gd31jxb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwhgk4wz00073b6t4lfygcl6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwhgk4wz00033b6tjfbr21p2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwhgk4wz00023b6t5aopfv9m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A35%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A35%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwhgk4wz00033b6tjfbr21p2%2522%252C%2522activeTabId%2522%253A%2522clwhgk4wz00023b6t5aopfv9m%2522%257D%252C%2522clwhgk4wz00073b6t4lfygcl6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwhgk4wz00063b6thlu081fy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwhgk4wz00073b6t4lfygcl6%2522%252C%2522activeTabId%2522%253A%2522clwhgk4wz00063b6thlu081fy%2522%257D%252C%2522clwhgk4wz00053b6t5gd31jxb%2522%253A%257B%2522id%2522%253A%2522clwhgk4wz00053b6t5gd31jxb%2522%252C%2522activeTabId%2522%253A%2522clwhgk4wz00043b6t4ej2br06%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwhgk4wz00043b6t4ej2br06%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clwhgneoi002v3b6rjw4qoa56%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwhgnevl007ddkhp3p74ddcb%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 重现步骤

在useEffect里修改endTime,无效。偶尔有效也会自动开始，并不能控制

### 期望的结果是什么？

修改endTime

### 实际的结果是什么？

不可修改，且autoStart失效

### 其他补充信息

App.tsx和App1.tsx都有问题

**Comment by Miles-hxy** [comment]
这种情况是不是应该用useState

**Comment by Sweechirly** [comment]
> 这种情况是不是应该用useState

没用

**Comment by Alex-huxiyang** [comment]
import React, { useEffect, useRef, useState } from 'react'
import { Cell, CountDown } from '@nutui/nutui-react'

const Demo1 = () => {
  const endTimeRef = useRef({
    endTime: Date.now() + 5 * 1000,
  })
  const [endTime, setEndTime] = useState(Date.now() + 5 * 1000)
  useEffect(() => {
    // endTimeRef.current.endTime = Date.now() + 60 * 1000;
    // console.log(endTimeRef.current);
    setEndTime(Date.now() + 8 * 1000)
  }, []);
  const onEnd = () => {
    console.log('countdown: ended.')
  }
  return (
    <Cell>
      {/* <CountDown endTime={endTimeRef.current.endTime} onEnd={onEnd} /> */}
      <CountDown endTime={endTime} onEnd={onEnd} />
    </Cell>
  )
}
export default Demo1

**Comment by Miles-hxy** [comment]
```tsx
import { useEffect, useState } from 'react'
import { Cell, CountDown } from '@nutui/nutui-react'

const Demo1 = () => {
  const [endTime, setEndTime] = useState(Date.now() + 5 * 1000)
  useEffect(() => {
    setEndTime(Date.now() + 8 * 1000)
  }, [])
  const onEnd = () => {
    console.log('countdown: ended.')
  }
  return (
    <Cell>
      <CountDown endTime={endTime} onEnd={onEnd} />
    </Cell>
  )
}
export default Demo1

```

**Comment by Sweechirly** [comment]
> ```tsx
> import { useEffect, useState } from 'react'
> import { Cell, CountDown } from '@nutui/nutui-react'
> 
> const Demo1 = () => {
>   const [endTime, setEndTime] = useState(Date.now() + 5 * 1000)
>   useEffect(() => {
>     setEndTime(Date.now() + 8 * 1000)
>   }, [])
>   const onEnd = () => {
>     console.log('countdown: ended.')
>   }
>   return (
>     <Cell>
>       <CountDown endTime={endTime} onEnd={onEnd} />
>     </Cell>
>   )
> }
> export default Demo1
> ```

autoStart={false}失效,抱歉标题没有说这个问题，其实我是因为autoStart={false}不可用才提的这个问题，中间发现了useRef不能改时间

**Comment by Miles-hxy** [comment]
autostart参考这个的使用
```tsx
import React, { useRef } from 'react'
import { Cell, CountDown, Grid, GridItem, Button } from '@nutui/nutui-react'

const Demo9 = () => {
  const countDownRef = useRef<any>(null)
  const start = () => {
    countDownRef.current && countDownRef.current.start()
  }

  const pause = () => {
    countDownRef.current && countDownRef.current.pause()
  }

  const reset = () => {
    countDownRef.current && countDownRef.current.reset()
  }
  return (
    <>
      <Cell>
        <CountDown
          format="ss:SS"
          autoStart={false}
          time={20000}
          ref={countDownRef}
        />
      </Cell>
      <Grid columns="3" style={{ marginBottom: '5px' }}>
        <GridItem>
          <Button type="primary" onClick={start}>
            开始
          </Button>
        </GridItem>
        <GridItem>
          <Button type="primary" onClick={pause}>
            暂停
          </Button>
        </GridItem>
        <GridItem>
          <Button type="primary" onClick={reset}>
            重置
          </Button>
        </GridItem>
      </Grid>
    </>
  )
}
export default Demo9

```

**Comment by Miles-hxy** [comment]
Demo9

**Comment by Sweechirly** [comment]
> Demo9

请查看codesandbox，无法更新time
