### ISSUE TITLE
Tag 组件 type 为 danger 时，背景颜色 css 变量用了 --nutui-color-primary，应该有一个属于 danger 状态的颜色

### ISSUE THREAD

**Issue by zhangminggeek** [jdf2e/nutui-react#2277]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.0

### 平台

weapp

### 重现链接

https://codesandbox.io/p/sandbox/nutui-react-2x-demo-fg4vxd?file=/src/App.tsx

### 重现步骤

<Tag type="danger">标签</Tag>

### 期望的结果是什么？

status 为 danger 时有一个自己的颜色变量

### 实际的结果是什么？

使用了 primary 状态的颜色变量

**Comment by Miles-hxy** [comment]
有道理👍
