### ISSUE TITLE
ActionSheet 动作面板 小程序展示bug

### ISSUE THREAD

**Issue by chengluliu** [jdf2e/nutui-react#2278]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.5

### 平台

weapp

### 重现链接

https://github.com/chengluliu/NutUIDemo.git

### 重现步骤

运行小程序点击按钮即可看到

### 期望的结果是什么？

正常显示样式

### 实际的结果是什么？

样式有小问题

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-react/pull/2285
