### ISSUE TITLE
countDown组件页面销毁后没有正常销毁

### ISSUE THREAD

**Issue by RyunNeo** [jdf2e/nutui-react#2280]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.3

### 平台

alipay

### 重现链接

无

### 重现步骤

A页面进入B页面，B页面使用countdown组件开始倒数，B页面设置了某一时间戳（假设时间戳为：1716531731000），进入页面后返回上级页面，再次进入B页面，countdown组件展示的还是上次的倒数时间。
```jsx
const endTime = 1716531731000;
return (
// 第一次进入假如是00:29:59
// 重新进入还是00:29:59
<CountDown endTime={endTime} />
)
```

### 期望的结果是什么？

重新进入B页面后，倒数时间更新为重新计算的时间。假如第一次是00:29:59，间隔10s后进入，应该是从00:29:49开始

### 实际的结果是什么？

countDown组件页面销毁后没有正常销毁，重新进入页面后，倒数的时间还是上次记录的时间，没有更新

**Comment by irisSong** [comment]
destroy设置true
