### ISSUE TITLE
Form.Item组件 name="avatar" 当页面返回时报错： TypeError: Cannot delete property 'avatar' of 

### ISSUE THREAD

**Issue by baozixiangqianchong** [jdf2e/nutui-react#2283]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.0.19

### 平台

weapp

### 重现链接

https://codesandbox.io/p/devbox/exciting-thompson-qzgzxt?file=%2Fsrc%2FApp.tsx%3A7%2C12&workspaceId=300ba855-20fd-4f3b-a730-7d479170198b

### 重现步骤

` <Form.Item label="头像" name="avatar">
            <View className="flex-align set_action">
              <Image
                width="32rpx"
                height="32rpx"
                src={stewardData && stewardData.avatar}
              />
            </View>
          </Form.Item>`

### 期望的结果是什么？

页面正常

### 实际的结果是什么？

报错：._node_modules_react-reconciler_cjs_react-reconciler.production.min.js:formatted:1 TypeError: Cannot delete property 'avatar' of #<Object>，同时当前页面不能进行其他操作

### 环境信息

Taro v3.6.29

### 其他补充信息

Node v18.20.0

**Comment by oasis-cloud** [comment]
可以将 @nutui/nutui-react-taro 升级到最新版本，在最新版本通过您提供的代码，未复现出描述中的问题。
