### ISSUE TITLE
[FR]: Card 组件根据参调判断是否需要展示

### ISSUE THREAD

**Issue by wenlingang** [jdf2e/nutui-react#2287]
### 这个功能解决了什么问题？

Card 组件目前看只适用于商品类型的内容，比如我其实想不展示 price 这些内容，当我没有入参的时候他会是 0

### 你期望的组件设计是怎样的？

显示内容根据参数判断可见，这样 Card 组件可以应用更多场景

**Comment by wenlingang** [comment]
如果有这样的计划，我可以贡献代码

**Comment by xiaoyatong** [comment]
可以直接提pr

**Comment by Me-UserName** [comment]
这个提议好

**Comment by wenlingang** [comment]
@xiaoyatong 提了 PR，这里是判断了值是否有效而决定显示，没有新增 hide 相关属性去做，感觉会让属性变繁琐，这里应该是不需要向下兼容的吧，因为之前使用这些属性的应该是都会主动传入值
