### ISSUE TITLE
Calendar 日历里的 自定义按钮，点击最近7天进行快捷选择日期后，点击确定获取不到选择的日期

### ISSUE THREAD

**Issue by yangqianlu** [jdf2e/nutui-react#2289]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.3.12

### 平台

h5

### 重现链接

https://codesandbox.io/p/sandbox/nutui-react-6psg8z

### 重现步骤

使用nutui里的Calendar 日历中的自定义按钮的demo，点击最近7天进行快捷选中日期后，虽然选中了日期，但是点击确定的时候，获取不到选中日期的开始时间和结束时间，而是之前的日期。

### 期望的结果是什么？

期望，进行快捷选中完日期后，点击确定可以或者到选中日期的开始时间和结束时间

### 实际的结果是什么？

是之前的日期

**Comment by yangqianlu** [comment]
<img width="506" alt="image" src="https://github.com/jdf2e/nutui-react/assets/24307255/4cd08eb6-36cc-409c-8d08-2cd7cbefab69">
点了上面的最近七天按钮后，点击确定，打印结果如下：
![Uploading image.png…]()

**Comment by yangqianlu** [comment]
使用自定义按钮renderHeaderButtons 添加一个重置按钮也是一样的效果。
下次需求迭代 日历需要支持重置的功能，预计使用时间在2024年7月中旬，需求上线时间预计在7月底

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-react/pull/2436
