### ISSUE TITLE
【Fix】构建时，组件库下*.scss文件复制目标路径出错

### ISSUE THREAD

**Issue by Yyunfan** [jdf2e/nutui-react#2314]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.8

### 平台

h5, weapp, alipay, jd, tt, 其他小程序

### 重现链接

https://codesandbox.io/p/devbox/nutui-react-2x-demo-fg4vxd

### 重现步骤

**操作系统**：Windows
**Node版本**：18.19.1
**PNPM版本**：9.1.4

**执行npm scripts**
`pnpm run build // 构建`

### 期望的结果是什么？

能正常构建成功组件库

### 实际的结果是什么？

Error: Can't find stylesheet to import.
  ╷
3 │ @import '../../packages/button/button.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  dist\styles\themes\default.scss 3:9  root stylesheet

![image](https://github.com/jdf2e/nutui-react/assets/11605443/38064c2e-c649-4294-9d91-2bf8793df7db)

**Comment by Yyunfan** [comment]
**文件：** scripts\generate-themes.js#L15

**原因：**
Windows系统下glob.sync('./src/packages/**/*.scss', { dotRelative: true })后获得路径： .\src\packages\badge\badge.scss 执行 `${cs.replace('./src/', '')}` 时候会替换失败，导致复制到dist/src/packages路径了，后续脚本就执行错误了。

**一个修改建议：**
标准化路径完再替换src为空

`let destDir = path.normalize(cs);
destDir = destDir.replace(path.normalize('.\\src\\'), '')`
`
tasks.push(
    fs.copy(path.resolve(__dirname, `.${cs}`), path.resolve(__dirname, `../dist`, destDir))
`

**Comment by xiaoyatong** [comment]
可以直接提交pr

**Comment by Yyunfan** [comment]
> 可以直接提交pr

有空review下
