### ISSUE TITLE
Drag组件拖拽后会在原地留一个div，它会遮挡住下层元素的，导致下层元素点击事件无法触发

### ISSUE THREAD

**Issue by VicEcho** [jdf2e/nutui-react#2328]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.8

### 平台

h5

### 重现链接

https://nutui.jd.com/h5/react/2x/#/zh-CN/component/drag

### 重现步骤

初始化的Drag组件如果遮挡了下层元素，拖拽后，下层元素点击事件无法触发

### 期望的结果是什么？

不会组织下层元素点击事件触发

### 实际的结果是什么？

Drag组件拖拽后会在原地留一个div，它会持续遮挡住下层元素的，导致下层元素点击事件无法触发

**Comment by xm1769315774** [comment]
这个改造把初始位置改的有问题了，辛苦检查一下。具体的表现我在commit里边评论了

**Comment by qchen-chat-edu** [comment]
可能跟原问题不一样但表现类似，2.7.4版本的表现是nut-drag这个div的宽高默认都是0，让内容自己overflow出来，这时候拖动后即使有个没有大小的nut-drag留在原地也不会影响点击事件。
但是如果用户自己给nut-drag设置了宽高就不行了。解决方法就是不设置宽高，这时候贴边可能会有些问题，自己计算一下就好了
