### ISSUE TITLE
[FR]: 希望有一套 dark 风格的配色

### ISSUE THREAD

**Issue by 160905** [jdf2e/nutui-react#2340]
### 这个功能解决了什么问题？

解决了小程序自动切换 dark 和 light 的主题功能，跟随手机系统

### 你期望的组件设计是怎样的？

组件库中 ConfigProvider 有一套完美的 dark 模式的 色值搭配

**Comment by oasis-cloud** [comment]
在 styles 目录中有 theme-dark 的文件
