### ISSUE TITLE
[FR]: Calendar 日历使用renderHeaderButtons

### ISSUE THREAD

**Issue by zzzhangy** [jdf2e/nutui-react#2341]
### 这个功能解决了什么问题？

![image](https://github.com/jdf2e/nutui-react/assets/116279784/4f98f874-7752-4a05-9878-4db40fc3b3cf)
const selectOptions = [
  {
    label: '近1天',
    value: [dayjs().add(-1, 'day').format('YYYY-MM-DD'), dayjs().format('YYYY-MM-DD')],
  },
  {
    label: '近7天',
    value: [dayjs().add(-7, 'day').format('YYYY-MM-DD'), dayjs().format('YYYY-MM-DD')],
  },
  {
    label: '近30天',
    value: [dayjs().add(-30, 'day').format('YYYY-MM-DD'), dayjs().format('YYYY-MM-DD')],
  },
  {
    label: '近一年',
    value: [dayjs().add(-365, 'day').format('YYYY-MM-DD'), dayjs().format('YYYY-MM-DD')],
  },
]
        renderHeaderButtons={() => {
          return (
            <View className="time-select-btn-container">
              {selectOptions.map((item, index) => {
                return (
                  <View
                    className="time-select-btn"
                    key={index}
                    onClick={() => {
                      setDate(item.value)
                    }}
                  >
                    {item.label}{' '}
                  </View>
                )
              })}
            </View>
          )
        }}

### 你期望的组件设计是怎样的？

 Calendar 日历使用renderHeaderButtons自定义例如近30天这种，修改选中后onConfirm能够锁定选中后的日期而不是只有点击select才能修改onConfirm的日期参数，或者有没有办法实现，我对现有api的理解是无法实现

**Comment by xiaoyatong** [comment]
同 https://github.com/jdf2e/nutui-react/issues/2289
已修复~
