### ISSUE TITLE
[FR]: 希望增加 Form 的只读功能，满足提交后的表单回显或者是详情查看

### ISSUE THREAD

**Issue by 160905** [jdf2e/nutui-react#2386]
### 这个功能解决了什么问题？

解决了表单提交后，对于审核中状态的只读模式回显，如果是 Upload 回显，期望只 render 图片

### 你期望的组件设计是怎样的？

再 form 上增加 bool 属性 readOnly

**Comment by oasis-cloud** [comment]
给 formitem 中的组件设置为 readonly 可以实现
