### ISSUE TITLE
A页面引入import  Dialog, B页面 也import  Dialog 会报错

### ISSUE THREAD

**Issue by WyntersN** [jdf2e/nutui-react#2398]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.11

### 平台

weapp

### 重现链接

@nutui/nutui-react-taro

### 重现步骤

A page
import { Avatar, Dialog } from "@nutui/nutui-react-taro";

B page
import { Dialog } from "@nutui/nutui-react-taro";

### 期望的结果是什么？

希望不要报错

### 实际的结果是什么？

Conflicting order. Following module has been added:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].oneOf[0].use[2]!./node_modules/@nutui/icons-react-taro/dist/style_icon.css
despite it was not able to fulfill desired ordering with these modules:
 * css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].oneOf[0].use[2]!./node_modules/@nutui/nutui-react-taro/dist/esm/Dialog/style/style.css
   - couldn't fulfill desired order of chunk group(s) pages/A
   - while fulfilling desired order of chunk group(s) pages/B
    at Array.forEach (<anonymous>)

**Comment by oasis-cloud** [comment]
可以增加如下配置：
mini: {
    miniCssExtractPluginOption: {
      ignoreOrder: true,
    },
  },

**Comment by WyntersN** [comment]
> 可以增加如下配置： mini: { miniCssExtractPluginOption: { ignoreOrder: true, }, },

谢谢您
