### ISSUE TITLE
<ArrowLeft/>等方式使用icon。微信内置浏览器不显示图标。能不能有配置参数决定使用css还是base64 

### ISSUE THREAD

**Issue by xiaof520** [jdf2e/nutui-react#2399]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.11

### 平台

h5

### 重现链接

https://github.com/jdf2e/nutui-icons

### 重现步骤

<ArrowLeft/>

### 期望的结果是什么？

微信内置浏览器正常显示图标。

### 实际的结果是什么？

不显示

**Comment by oasis-cloud** [comment]
可以参考https://github.com/jdf2e/nutui-icons/pull/17

**Comment by xiaof520** [comment]
> 可以参考[jdf2e/nutui-icons#17](https://github.com/jdf2e/nutui-icons/pull/17)

谢谢，可以了
