### ISSUE TITLE
input输入框在钉钉小程序下类型为text时候，输入一段中文后，无法继续录入

### ISSUE THREAD

**Issue by zqianling** [jdf2e/nutui-react#2402]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.11

### 平台

alipay, 其他小程序

### 重现链接

暂无

### 重现步骤

input输入框在钉钉小程序下类型为text时候，输入一段中文后，再次数据，无法录入了，哪怕重新聚焦再输入都不好使，最大长度设置的很大，不会是最大长度限制导致的，设备苹果13，版本号ios17.5.1。

### 期望的结果是什么？

输入完一段内容后能继续录入

### 实际的结果是什么？

输入完后无法继续录入

**Comment by xiaoyatong** [comment]
帮忙确认下 这块最多输入了多少字符。

**Comment by zqianling** [comment]
在模拟器里可以输入很多很多，100个不止，到手机上不行了

**Comment by zqianling** [comment]
<Input
              placeholder="请搜索"
              clearable
              maxLength={30}
              type="text"
              focus={false}
              controlled={false}
              enableNative={false}
            />
            
          经过测试发现不使用原生键盘没有问题，配置enableNative=false既可以解决此问题。
