### ISSUE TITLE
组件 Address  有对应的地址库吗

### ISSUE THREAD

**Issue by WyntersN** [jdf2e/nutui-react#2404]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.11

### 平台

weapp

### 重现链接

 @nutui/nutui-react-taro

### 重现步骤

![image](https://github.com/jdf2e/nutui-react/assets/27792650/1b553468-3750-4c68-b319-34b11838f483)

**Comment by xiaoyatong** [comment]
是希望拿到地址数据么？

**Comment by WyntersN** [comment]
> 是希望拿到地址数据么？

是全国地址库，总不可能我把全国地址一个个输一遍吧

**Comment by xiaoyatong** [comment]
目前没有，可以看看 腾讯的一些 sdk

**Comment by jianhuagao** [comment]
可以试试这个
https://gist.github.com/afc163/7582f35654fd03d5be7009444345ea17

**Comment by WyntersN** [comment]
> 可以试试这个
> 
> https://gist.github.com/afc163/7582f35654fd03d5be7009444345ea17

我试了 里面的json链接打不开了

**Comment by jianhuagao** [comment]
如果只是weapp用的话，可以用官方的Picker，自带数据
import { Picker } from '@tarojs/components';
<Picker
     headerText="选择省份"
     mode="region"
     onChange={() => {}}
    >
          选择
</Picker>

**Comment by jianhuagao** [comment]
如果只是weapp用的话，可以用官方的Picker，自带数据
```tsx
import { Picker } from '@tarojs/components';
<Picker
     headerText="选择省份"
     mode="region"
     onChange={() => {}}
  >
     选择
</Picker>
