### ISSUE TITLE
DatePicker 设置 endDate 存在bug

### ISSUE THREAD

**Issue by zqianling** [jdf2e/nutui-react#2434]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.12

### 平台

alipay

### 重现链接

暂无

### 重现步骤

DatePicker 设置 type="datetime" 并且 endDate = 2024-07-11 11:42:00
修改小时后，分钟列表没有更新，修改日期后，小时和分钟列表也没有更新。
![d84cd90660d9dcc7cccc12e7b3a012dc](https://github.com/jdf2e/nutui-react/assets/50726927/e649b9b1-178b-40f5-91a0-3cfec66fbaf0)

### 期望的结果是什么？

改变日后，小时和分钟列表更新，更新小时后，分钟列表更新

### 实际的结果是什么？

改变日后，小时和分钟列表未更新，更新小时后，分钟列表未更新

**Comment by Miles-hxy** [comment]
可以提供下代码，没复现成功。
