### ISSUE TITLE
dialog h5下 onConfirm 不触发

### ISSUE THREAD

**Issue by xiaof520** [jdf2e/nutui-react#2446]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.13

### 平台

h5

### 重现链接

https://github.com/jdf2e/nutui-react/blob/next/src/packages/dialog/dialog.taro.tsx

### 重现步骤

Dialog.open("test", {}）

### 期望的结果是什么？

正常触发

### 实际的结果是什么？

异常

**Comment by xiaof520** [comment]
发现是Button  disabled  影响，disabled = false  也影响触发click

**Comment by xiaoyatong** [comment]
确保 disabled 给的值是布尔型。
