### ISSUE TITLE
希望每个组件的Props类型能export出去

### ISSUE THREAD

**Issue by darkmice** [jdf2e/nutui-react#246]
在原组件上进行业务组件开发时，需要继承原组件的props类型，没法直接通过
 `import { Icon, IconProps } from '@nutui/nutui-react' `

目前只能通过

`type IconProps = typeof Icon.defaultProps` 

这样不友好的方便来获取，感觉代码不够美观

**Comment by oasis-cloud** [comment]
确实不太美观，正在改造中

**Comment by oasis-cloud** [comment]
v1.3.1 版本已导出，可采用 import { IconProps } from '@nutui/nutui-react' 方式导入
