### ISSUE TITLE
【Collapse】组件样式不一致

### ISSUE THREAD

**Issue by Leo-Jackr** [jdf2e/nutui-react#2462]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.13

### 平台

h5

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/component/collapse

### 重现步骤

    <Collapse defaultActiveName={['1', '2']} expandIcon={<ArrowDown />}>
      <Collapse.Item title="标题1" name="1">
        京东“厂直优品计划”首推“政府优品馆” 3年覆盖80%镇级政府
      </Collapse.Item>
      <Collapse.Item title="标题2" name="2">
        京东“厂直优品
      </Collapse.Item>
      <Collapse.Item title="标题3" name="3" disabled>
        京东“厂直优品计划”首推“政府优品馆”
      </Collapse.Item>
    </Collapse>

    <Collapse defaultActiveName={['1', '2']} expandIcon={<ArrowDown />}>
      <Collapse.Item title="标题1" name="1">
        京东“厂直优品计划”首推
      </Collapse.Item>
      <Collapse.Item title="标题2" name="2">
        京东“厂直优品计划”首推“政府
      </Collapse.Item>
      <Collapse.Item title="标题3" name="3" disabled>
        京东“厂直优品计划”首推“政府优品馆”
      </Collapse.Item>
    </Collapse>

### 期望的结果是什么？

样式一致

### 实际的结果是什么？

根据内容是否换行，两者的样式不一致

**Comment by Miles-hxy** [comment]
没太理解你提到的“样式不一致”的含义，你的意思是不应该自动换行吗？

**Comment by xiaoyatong** [comment]
目前表现是如下，是支持换行的，没有特别的处理。
如果有需要的话，可以修改 `nut-collapse-item-content-text` 的样式。
![image](https://github.com/user-attachments/assets/3e15d6eb-0467-4cdd-be98-4da2658fbf8d)
