### ISSUE TITLE
2个 Popup 一个 向上弹出 一个 向下弹出 会出错 

### ISSUE THREAD

**Issue by WyntersN** [jdf2e/nutui-react#2463]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.11

### 平台

weapp

### 重现链接

 @nutui/nutui-react-taro

### 重现步骤

```tsx
<> 
<Popup
        visible={showBasic}
        position="top"
        style={{ height: '60vh' }}
        onClose={() => {
          setShowBasic(false)
        }}
      />
      
       <Popup
        visible={showBasic}
        position="bottom"
        style={{ height: '60vh' }}
        onClose={() => {
          setShowBasic(false)
        }}
      />
</>
```

top 的阴影部分 bottom 无法显示，PC端正常，移动端 会出现这样的问题

### 期望的结果是什么？

PC端(正常)
![image](https://github.com/user-attachments/assets/3603dbbd-2b46-480a-b9a8-7a1eec8d4c7d)

### 实际的结果是什么？

移动端(有问题)
![image](https://github.com/user-attachments/assets/45fef832-d345-4c4f-99b0-93dc78668e0f)

**Comment by xiaoyatong** [comment]
没看懂，你怎么用的。。。同时让一个从上边出来一个从下边出来？

**Comment by WyntersN** [comment]
> 没看懂，你怎么用的。。。同时让一个从上边出来一个从下边出来？
@xiaoyatong 
是的，上面弹出来填写资料，下面弹出来选择地址

**Comment by Miles-hxy** [comment]
还是逐个弹出或者放在一次弹出中要易用一些吧。

**Comment by WyntersN** [comment]
没有其他好的方式弹出，只能放2个Popup
