### ISSUE TITLE
Menu 组件 className 属性使用混乱

### ISSUE THREAD

**Issue by zhangminggeek** [jdf2e/nutui-react#2478]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.13

### 平台

weapp

### 重现链接

https://codesandbox.io/p/sandbox/nutui-react-2x-demo-fg4vxd?file=/src/App.tsx

### 重现步骤

https://github.com/jdf2e/nutui-react/blob/next/src/packages/menu/menu.taro.tsx#L144

这里给每一个 `nut-menu-title` 都添加了 Menu 组件的 `className` 属性，这不合理吧，当外部传入 `className` 属性时，`nut-menu` 和每一个子元素 `nut-menu-title` 都拥有了同一个类名，这会造成混乱

### 期望的结果是什么？

个人认为给 Menu 传入的 className 应该只给 `nut-menu` 使用，并且每个 `nut-menu-title` 支持配置各自的 `className`，使用场景是，当 Menu 中某个 Menu.Item 的选项被选中时希望对应的 `nut-menu-title` 变成主题色

### 实际的结果是什么？

`nut-menu` 和 `nut-menu-title` 共享了外部传入的 `className`

### 环境信息

Taro CLI 3.6.30 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
      npm: 10.5.1 - ~/.nvm/versions/node/v20.9.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.30 => 3.6.30
      @tarojs/components: 3.6.30 => 3.6.30
      @tarojs/helper: 3.6.30 => 3.6.30
      @tarojs/plugin-framework-react: 3.6.30 => 3.6.30
      @tarojs/plugin-html: ^3.6.30 => 3.6.30
      @tarojs/plugin-platform-alipay: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-h5: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-jd: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-qq: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-swan: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-tt: 3.6.30 => 3.6.30
      @tarojs/plugin-platform-weapp: 3.6.30 => 3.6.30
      @tarojs/react: 3.6.30 => 3.6.30
      @tarojs/runtime: 3.6.30 => 3.6.30
      @tarojs/shared: 3.6.30 => 3.6.30
      @tarojs/taro: 3.6.30 => 3.6.30
      @tarojs/webpack5-runner: 3.6.30 => 3.6.30
      babel-preset-taro: 3.6.30 => 3.6.30
      eslint-config-taro: 3.6.30 => 3.6.30
      react: ^18.3.1 => 18.3.1

**Comment by xiaoyatong** [comment]
我觉得你说的很有道理。
可以提一个pr，解决两个问题：
1、当前给 nut-menu 的 classname 保留；
2、给每个 nut-menu-title 增加 一个classname，个人思路是，可延续1中的classname，另加上 title 的index 作为区别。
如有更好方式也可~~
期待你的pr

**Comment by Miles-hxy** [comment]
延续第一点。个人思路第二点中给每个 nut-menu-title附加一个我们的类名如`nut-menu-title${index}`,使用者直接去通过它来灵活控制每个title。传入的classname默认是控制nut-menu的。看看会不会方便呢
