### ISSUE TITLE
[FR]: 希望 Menu 的 `nut-menu-title` 可以独立配置 icon

### ISSUE THREAD

**Issue by zhangminggeek** [jdf2e/nutui-react#2479]
### 这个功能解决了什么问题？

独立配置  `nut-menu-title` 的 icon

使用场景如图：
![image](https://github.com/user-attachments/assets/2899c43d-f141-41c8-9afe-f772f4ddc5af)

### 你期望的组件设计是怎样的？

https://github.com/jdf2e/nutui-react/blob/472fe690a4247eacf81ad7191dacc434b2b05127/src/packages/menu/menu.taro.tsx#L154

这里的 icon，不要使用 Menu 统一配置 icon，要分开配置，这样每个 `nut-menu-title` 都可以有独立的 icon

**Comment by xiaoyatong** [comment]
这个支持自定义的，使用 icon 属性。

**Comment by xiaoyatong** [comment]
menu 和 menuitem 都支持自定义icon

**Comment by zhangminggeek** [comment]
> menu 和 menuitem 都支持自定义icon

menu 的确可以自定义 icon，但是他的自定义传入后，每个 `nut-menu-title` 的 icon 都是一样的，我在 issue 中提的是希望可以给每个 `nut-menu-title` 配置不同的 icon，目前的 api 是无法满足的。你可以看下我在问题中提到的那部分代码，可以发现 icon 并不是来自每一个 menuitem 的配置，而是统一的 menu 的 props 中的 icon。

希望可以重新打开这个 issue @xiaoyatong
