### ISSUE TITLE
当前版本InfiniteLoading组件在滑动到底部（显示没有更多数据）以后，每次触发子元素组件的点击事件，会导致触发下拉刷新事件

### ISSUE THREAD

**Issue by colin-online** [jdf2e/nutui-react#2485]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.14

### 平台

h5

### 重现链接

无

### 重现步骤

index.jsx代码如下：
import React from 'react';
import { InfiniteLoading } from '@nutui/nutui-react';
import usePresenter from './presenter';
import styles from './style.module.scss';

/* 加载ICON */
const LOADING_ICON = (type = false, size = 1) => {
  if (!type) {
    return (
      <div style={{ transform: `scale(${size})` }}>
        <svg
          width="36"
          height="26"
          viewBox="0 0 36 26"
          fill="none"
          className="nut-infinite-top-tips-icons"
        >
          <path
            d="M34.7243 10.965C32.842 8.94809 32.4297 5.92727 31.2018 4.90525C29.9738 3.88324 28.1722 5.51123 27.5089 6.46993C23.8429 3.88324 17.9809 4.00082 17.9809 4.00082C17.9809 4.00082 12.1458 3.88324 8.47083 6.46993C7.80754 5.51123 6.01488 3.88324 4.78691 4.90525C3.55894 5.92727 3.15559 8.94809 1.2733 10.965C-0.133943 12.4844 -0.250465 12.9276 0.323186 14.1305C0.887874 15.3334 4.40149 16.3283 6.88432 13.9496C7.21596 15.1887 10.0125 21.9991 17.9899 21.9991C25.9672 21.9991 28.7817 15.1887 29.1043 13.9496C31.5872 16.3283 35.1098 15.3334 35.6834 14.1305C36.2481 12.9276 36.1316 12.4844 34.7243 10.965Z"
            fill="#8c8c8c"
          />
        </svg>
      </div>
    );
  }
  return (
    <svg width="72" height="40" viewBox="0 0 72 40" xmlns="http://www.w3.org/2000/svg">
      <circle cx="12" cy="20" r="5" fill="#8c8c8c" />
      <circle cx="36" cy="20" r="5" fill="#8c8c8c" />
      <circle cx="60" cy="20" r="5" fill="#8c8c8c" />
    </svg>
  );
};

function InfiniteLoad(props) {
  const [states, events] = usePresenter(props);
  const { pullingState, hasMore, products, children } = states || {};
  const { onLoadMore, onRefresh } = events || {};

  return (
    <InfiniteLoading
      pullingText={
        <div className={styles.pulling}>
          {LOADING_ICON(pullingState, 1.2)}
          <span>{pullingState ? '刷新中' : '下拉刷新'}</span>
        </div>
      }
      loadMoreText={
        <div className={`${styles.loadMore} ${products?.length <= 0 ? styles.loadMoreHide : null}`}>
          {LOADING_ICON(false)}
          <span>没有更多了</span>
        </div>
      }
      loadingText={
        <div className={styles.loading}>
          {LOADING_ICON(true, 0.6)}
          <span>努力加载中</span>
        </div>
      }
      target="refreshScroll"
      pullRefresh={true}
      threshold={300}
      hasMore={hasMore}
      onLoadMore={onLoadMore}
      onRefresh={onRefresh}
    >
      {children}
    </InfiniteLoading>
  );
}

export default React.memo(InfiniteLoad);
presenter.js代码如下：

export default (props) => {
  const {
    products = [],
    pullingState = false,
    hasMore = true,
    children,
    onLoadMore,
    onRefresh,
  } = props || {};

  const states = { pullingState, hasMore, products, children };
  const events = {
    onLoadMore,
    onRefresh,
  };
  return [states, events];
};

### 期望的结果是什么？

InfiniteLoading包裹的productList列表组件的productCard子组件，点击事件不要触发下拉刷新事件

### 实际的结果是什么？

InfiniteLoading包裹的productList列表组件的productCard子组件，点击事件会触发下拉刷新事件

### 环境信息

 "@nutui/nutui-react": "^2.6.14"

### 其他补充信息

无

**Comment by colin-online** [comment]
![image](https://github.com/user-attachments/assets/5ff20c75-4cf1-463c-83d3-0785a441e453)

**Comment by colin-online** [comment]
![image](https://github.com/user-attachments/assets/e0744df2-169d-4075-b8df-1219c10494fc)

**Comment by Alex-huxiyang** [comment]
<ul style={InfiniteUlStyle} id="scroll">
          <InfiniteLoading
            target="scroll"
            hasMore={hasMore}
            onLoadMore={loadMore}
          >
            <div onClick={() => console.log('children')}>
              {defaultList.map((item, index) => {
                return (
                  <li style={InfiniteLiStyle} key={index}>
                    {item}
                  </li>
                )
              })}
            </div>
          </InfiniteLoading>
        </ul>

**Comment by Alex-huxiyang** [comment]
根据你的描述没有复现成功。

**Comment by Miles-hxy** [comment]
根据你的描述没有复现成功。
```jsx
import React, { useState, useEffect, CSSProperties } from 'react'
import { Cell, InfiniteLoading } from '@nutui/nutui-react'

const sleep = (time: number): Promise<unknown> =>
  new Promise((resolve) => {
    setTimeout(resolve, time)
  })
const InfiniteUlStyle: CSSProperties = {
  height: '300px',
  width: '100%',
  padding: '0',
  overflowY: 'auto',
  overflowX: 'hidden',
}
const InfiniteLiStyle: CSSProperties = {
  marginTop: '10px',
  fontSize: '14px',
  color: 'rgba(100, 100, 100, 1)',
  textAlign: 'center',
}
const Demo1 = () => {
  const [defaultList, setDefaultList] = useState<string[]>([])
  const [hasMore, setHasMore] = useState(true)

  useEffect(() => {
    init()
  }, [])

  const loadMore = async () => {
    console.log('loadMore')
    await sleep(200)
    const curLen = defaultList.length
    for (let i = curLen; i < curLen + 10; i++) {
      defaultList.push(`${i}`)
    }
    if (defaultList.length >= 30) {
      setHasMore(false)
    } else {
      setDefaultList([...defaultList])
    }
  }

  const init = () => {
    for (let i = 0; i < 10; i++) {
      defaultList.push(`${i}`)
    }
    setDefaultList([...defaultList])
  }

  return (
    <>
      <Cell>
        <ul style={InfiniteUlStyle} id="scroll">
          <InfiniteLoading
            target="scroll"
            hasMore={hasMore}
            onLoadMore={loadMore}
          >
            <div onClick={() => console.log('children')}>
              {defaultList.map((item, index) => {
                return (
                  <li style={InfiniteLiStyle} key={index}>
                    {item}
                  </li>
                )
              })}
            </div>
          </InfiniteLoading>
        </ul>
      </Cell>
    </>
  )
}
export default Demo1
```
可以提供一个类似这种简洁能够突出重点、可复现的demo  提高排查效率

**Comment by HeyShinner** [comment]
> 根据你的描述没有复现成功。
> 
> ```js
> import React, { useState, useEffect, CSSProperties } from 'react'
> import { Cell, InfiniteLoading } from '@nutui/nutui-react'
> 
> const sleep = (time: number): Promise<unknown> =>
>   new Promise((resolve) => {
>     setTimeout(resolve, time)
>   })
> const InfiniteUlStyle: CSSProperties = {
>   height: '300px',
>   width: '100%',
>   padding: '0',
>   overflowY: 'auto',
>   overflowX: 'hidden',
> }
> const InfiniteLiStyle: CSSProperties = {
>   marginTop: '10px',
>   fontSize: '14px',
>   color: 'rgba(100, 100, 100, 1)',
>   textAlign: 'center',
> }
> const Demo1 = () => {
>   const [defaultList, setDefaultList] = useState<string[]>([])
>   const [hasMore, setHasMore] = useState(true)
> 
>   useEffect(() => {
>     init()
>   }, [])
> 
>   const loadMore = async () => {
>     console.log('loadMore')
>     await sleep(200)
>     const curLen = defaultList.length
>     for (let i = curLen; i < curLen + 10; i++) {
>       defaultList.push(`${i}`)
>     }
>     if (defaultList.length >= 30) {
>       setHasMore(false)
>     } else {
>       setDefaultList([...defaultList])
>     }
>   }
> 
>   const init = () => {
>     for (let i = 0; i < 10; i++) {
>       defaultList.push(`${i}`)
>     }
>     setDefaultList([...defaultList])
>   }
> 
>   return (
>     <>
>       <Cell>
>         <ul style={InfiniteUlStyle} id="scroll">
>           <InfiniteLoading
>             target="scroll"
>             hasMore={hasMore}
>             onLoadMore={loadMore}
>           >
>             <div onClick={() => console.log('children')}>
>               {defaultList.map((item, index) => {
>                 return (
>                   <li style={InfiniteLiStyle} key={index}>
>                     {item}
>                   </li>
>                 )
>               })}
>             </div>
>           </InfiniteLoading>
>         </ul>
>       </Cell>
>     </>
>   )
> }
> export default Demo1
> ```
> 
> 可以提供一个类似这种简洁能够突出重点、可复现的demo 提高排查效率

我用你的例子，pullRefresh 和 onRfresh 配置可以触发的这个 bug

**Comment by HeyShinner** [comment]
![image](https://github.com/user-attachments/assets/bf1ec4db-caf1-4c7c-aa22-ba3a9d3618fe)
@Alex-huxiyang
