### ISSUE TITLE
 @nutui/nutui-react-taro@1.3.0 在taro上使用有问题可以看一下吗

### ISSUE THREAD

**Issue by tianwawawa** [jdf2e/nutui-react#249]

**Comment by oasis-cloud** [comment]
具体问题描述一下

**Comment by oasis-cloud** [comment]
请提供 taro 版本信息，或最小可复现代码仓库

**Comment by oasis-cloud** [comment]
taro 脚手架

babel 配置中增加如下内容；

plugins: [
    [
      "import",
      {
        "libraryName": "@nutui/nutui-react-taro",
        "libraryDirectory": "dist/esm",
        "style": true,
        "camel2DashComponentName": false
      },
      'nutui-react-taro'
    ]
  ]

sass 配置如下：

sass:{
    data: `@import "@nutui/nutui-react-taro/dist/styles/variables.scss";`
  },

**Comment by tianwawawa** [comment]
感谢 感谢
