### ISSUE TITLE
ActionSheet 组件设置 round 不生效

### ISSUE THREAD

**Issue by zhangminggeek** [jdf2e/nutui-react#2497]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.15

### 平台

weapp

### 重现链接

https://codesandbox.io/p/sandbox/nutui-react-2x-demo-fg4vxd?file=/src/App.tsx

### 重现步骤

给 ActionSheet 设置 `round` 为 `false` 无法生效

https://github.com/zhangminggeek/nutui-react/blob/96eb279af77e28eb46252f3b249295b4aeb80bd8/src/packages/actionsheet/actionsheet.taro.tsx#L63

### 期望的结果是什么？

建议把 `round` 设置一个默认值 `true` 即可，不然用户无法修改这个值

### 实际的结果是什么？

设置 `round` 不生效

**Comment by Miles-hxy** [comment]
经过讨论。我们暂不打算透传round属性。目前可通过css变量设置圆角～

**Comment by zhangminggeek** [comment]
> 经过讨论。我们暂不打算透传round属性。目前可通过css变量设置圆角～

方便告知下是出于什么原因考虑吗

**Comment by Miles-hxy** [comment]
> > 经过讨论。我们暂不打算透传round属性。目前可通过css变量设置圆角～
> 
> 方便告知下是出于什么原因考虑吗
下方弹出要圆角属于某种视觉规范。改动较大。暂时不动了～
