### ISSUE TITLE
使用最新react18以上版本构建，控制台报错

### ISSUE THREAD

**Issue by wou101771** [jdf2e/nutui-react#2503]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.15

### 平台

h5

### 重现链接

无

### 重现步骤

报错，chunk-CE7SSQE4.js?v=c41d5c05:521 Warning: a4: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### 期望的结果是什么？

解决

### 实际的结果是什么？

解决

**Comment by xiaoyatong** [comment]
doing
