### ISSUE TITLE
 Uploader 上传组件上传成功后 onSuccess  参数里面放files 数组是空的，没有对应上传后的文件列表，从12-15测试都有这个问题  

### ISSUE THREAD

**Issue by zixiao144** [jdf2e/nutui-react#2506]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.15

### 平台

weapp

### 重现链接

0.

### 重现步骤

 Uploader 上传组件上传成功后 onSuccess  参数里面放files 数组是空的，没有对应上传后的文件列表，从12-15测试都有这个问题  

### 期望的结果是什么？

 Uploader 上传组件上传成功后 onSuccess  参数里面放files 数组是空的，没有对应上传后的文件列表，从12-15测试都有这个问题  

### 实际的结果是什么？

 Uploader 上传组件上传成功后 onSuccess  参数里面放files 数组是空的，没有对应上传后的文件列表，从12-15测试都有这个问题  

### 环境信息

 Uploader 上传组件上传成功后 onSuccess  参数里面放files 数组是空的，没有对应上传后的文件列表，从12-15测试都有这个问题  

### 其他补充信息

 Uploader 上传组件上传成功后 onSuccess  参数里面放files 数组是空的，没有对应上传后的文件列表，从12-15测试都有这个问题

**Comment by TSjianjiao** [comment]
#2444 和这个bug原因类似，内部数据状态处理有问题，而且并没有解决问题。 [onStart之后的事件会把fileList设置成空数组](https://github.com/jdf2e/nutui-react/blob/40daef4883c5dfd218465d578a7f567370545823/src/packages/uploader/uploader.tsx#L206)。

现在临时解决方法只有写个空的beforeXhrUpload属性，让内部不走默认的事件处理逻辑。同时设置`value`和`onChange`让`Uploader`受控。
```tsx
    <Uploader
      value={fileList}
      beforeXhrUpload={beforeUpload}
      onDelete={(file, fileList) => {
        setFileList(fileList);
      }}
      onChange={uplaodFiles}
    />

  function uplaodFiles(files: FileItem[]) {
   files.forEach(file => {
     if(file.status === 'ready') {
        // 自行调用接口上传
       // 自行修改fileList中文件的状态
     }
   })
 }
```
在`onChange`里面遍历入参`fileList`，如果是`ready`状态就自己写上传逻辑，同时`setFileList`。

`onChange`只会在设置初始值和添加新文件的时候触发，其他操作都需要自己维护`fileList`。

**Comment by Miles-hxy** [comment]
> #2444 和这个bug原因类似，内部数据状态处理有问题，而且并没有解决问题。 [onStart之后的事件会把fileList设置成空数组](https://github.com/jdf2e/nutui-react/blob/40daef4883c5dfd218465d578a7f567370545823/src/packages/uploader/uploader.tsx#L206)。
> 
> 现在临时解决方法只有写个空的beforeXhrUpload属性，让内部不走默认的事件处理逻辑。同时设置`value`和`onChange`让`Uploader`受控。
> 
> ```tsx
>     <Uploader
>       value={fileList}
>       beforeXhrUpload={beforeUpload}
>       onDelete={(file, fileList) => {
>         setFileList(fileList);
>       }}
>       onChange={uplaodFiles}
>     />
> 
>   function uplaodFiles(files: FileItem[]) {
>    files.forEach(file => {
>      if(file.status === 'ready') {
>         // 自行调用接口上传
>        // 自行修改fileList中文件的状态
>      }
>    })
>  }
> ```
> 
> 在`onChange`里面遍历入参`fileList`，如果是`ready`状态就自己写上传逻辑，同时`setFileList`。
> 
> `onChange`只会在设置初始值和添加新文件的时候触发，其他操作都需要自己维护`fileList`。

数据状态更新的逻辑已经重写了，不会重置为空数组

**Comment by TSjianjiao** [comment]
> > #2444 和这个bug原因类似，内部数据状态处理有问题，而且并没有解决问题。 [onStart之后的事件会把fileList设置成空数组](https://github.com/jdf2e/nutui-react/blob/40daef4883c5dfd218465d578a7f567370545823/src/packages/uploader/uploader.tsx#L206)。
> > 现在临时解决方法只有写个空的beforeXhrUpload属性，让内部不走默认的事件处理逻辑。同时设置`value`和`onChange`让`Uploader`受控。
> > ```tsx
> >     <Uploader
> >       value={fileList}
> >       beforeXhrUpload={beforeUpload}
> >       onDelete={(file, fileList) => {
> >         setFileList(fileList);
> >       }}
> >       onChange={uplaodFiles}
> >     />
> > 
> >   function uplaodFiles(files: FileItem[]) {
> >    files.forEach(file => {
> >      if(file.status === 'ready') {
> >         // 自行调用接口上传
> >        // 自行修改fileList中文件的状态
> >      }
> >    })
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在`onChange`里面遍历入参`fileList`，如果是`ready`状态就自己写上传逻辑，同时`setFileList`。
> > `onChange`只会在设置初始值和添加新文件的时候触发，其他操作都需要自己维护`fileList`。
> 
> 数据状态更新的逻辑已经重写了，不会重置为空数组

我也是2.6.15，在微信小程序上自定义了beforeXhrUpload后就会有这个问题。官网的beforeXhrUpload例子也是无法显示。

**Comment by Miles-hxy** [comment]
嗯嗯。

**Comment by zzhao8053** [comment]
2.6.17 还是有这个问题

**Comment by zk020106** [comment]
还真是 有这个问题 我找了一天 我说线上没问题 本地测试环境一跑 发现有bug 结果是版本自己升级了。。。

**Comment by WuJiY** [comment]
2.7.1好像还存在

**Comment by WuJiY** [comment]
最新的2.7.9问题依然存在，官方不维护了？ @Alex-huxiyang

**Comment by shuqianchi** [comment]
> 最新的2.7.9问题依然存在，官方不维护了？ @Alex-huxiyang

用v3呗
