### ISSUE TITLE
Form 关联显示后提交表单不触发校验

### ISSUE THREAD

**Issue by 160905** [jdf2e/nutui-react#2522]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

"^2.3.10"

### 平台

weapp

### 重现链接

https://github.com/160905/nutui-bug

### 重现步骤

1. 设置两个字段的 `Form.Item A` 和 `Form.Item A`，并设置 reules 都是 required
2. 当字段 A 有值时展示 字段 B 的录入
3. 提交表单时，字段 B 没有出发校验

### 期望的结果是什么？

字段 B 根据 字段A 的值判断是否展示和输入，并且字段 B 可以接受表单提交时的验证

### 实际的结果是什么？

提交表单后字段 B 没有触发校验显示错误信息，而且 Form.Item 的 label 也不显示

### 环境信息

Taro v3.6.30

  Taro CLI 3.6.30 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
      npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.30 => 3.6.30 
      @tarojs/components: 3.6.30 => 3.6.30 
      @tarojs/helper: 3.6.30 => 3.6.30 
      @tarojs/plugin-framework-react: 3.6.30 => 3.6.30 
      @tarojs/plugin-html: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-alipay: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-h5: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-jd: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-qq: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-swan: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-tt: 3.6.30 => 3.6.30 
      @tarojs/plugin-platform-weapp: 3.6.30 => 3.6.30 
      @tarojs/react: 3.6.30 => 3.6.30 
      @tarojs/runtime: 3.6.30 => 3.6.30 
      @tarojs/shared: 3.6.30 => 3.6.30 
      @tarojs/taro: 3.6.30 => 3.6.30 
      @tarojs/taro-loader: 3.6.30 => 3.6.30 
      @tarojs/webpack5-runner: 3.6.30 => 3.6.30 
      babel-preset-taro: 3.6.30 => 3.6.30 
      eslint-config-taro: 3.6.30 => 3.6.30 
      react: ^18.0.0 => 18.3.1 

 System:
    OS: macOS 13.3.1
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700KF
    Memory: 5.42 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.2/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v16.20.2/bin/pnpm
    Watchman: 2023.12.04.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 16.4

**Comment by Miles-hxy** [comment]
应该是使用方式的问题。我更新了正确的demo演示，你可以看看
