### ISSUE TITLE
[FR]: Timeline 组件

### ISSUE THREAD

**Issue by ToQuery** [jdf2e/nutui-react#2542]
### 这个功能解决了什么问题？

需要显示时间序列

### 你期望的组件设计是怎样的？

参考 taro-ui ，https://taro-ui.jd.com/#/docs/timeline

**Comment by Me-UserName** [comment]
https://nutui.jd.com/taro/react/2x/#/zh-CN/component/steps

**Comment by ToQuery** [comment]
可以临时这样用，但顺序相反

**Comment by xiaoyatong** [comment]
可以自定义
