### ISSUE TITLE
taro 创建的项目 nav 和内容直接存在3-5个像素的空白的高度

### ISSUE THREAD

**Issue by ToQuery** [jdf2e/nutui-react#2544]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.14

### 平台

weapp

### 重现链接

https://github.com/ToQuery/taro-nutui-bug

### 重现步骤

如果页面中第一个元素为非 View 则与 Nav 之间会存在一个空白的高度。
eq: src/pages/index/index.tsx:29

### 期望的结果是什么？

不要存在空白的高度差

### 实际的结果是什么？

存在空白的高度差

### 环境信息

👽 Taro v4.0.4

  Taro CLI 4.0.4 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    npmPackages:
      @tarojs/cli: 4.0.4 => 4.0.4 
      @tarojs/components: 4.0.4 => 4.0.4 
      @tarojs/helper: 4.0.4 => 4.0.4 
      @tarojs/plugin-framework-react: 4.0.4 => 4.0.4 
      @tarojs/plugin-html: 4.0.4 => 4.0.4 
      @tarojs/plugin-platform-alipay: 4.0.4 => 4.0.4 
      @tarojs/plugin-platform-h5: 4.0.4 => 4.0.4 
      @tarojs/plugin-platform-jd: 4.0.4 => 4.0.4 
      @tarojs/plugin-platform-qq: 4.0.4 => 4.0.4 
      @tarojs/plugin-platform-swan: 4.0.4 => 4.0.4 
      @tarojs/plugin-platform-tt: 4.0.4 => 4.0.4 
      @tarojs/plugin-platform-weapp: 4.0.4 => 4.0.4 
      @tarojs/react: 4.0.4 => 4.0.4 
      @tarojs/runtime: 4.0.4 => 4.0.4 
      @tarojs/shared: 4.0.4 => 4.0.4 
      @tarojs/taro: 4.0.4 => 4.0.4 
      @tarojs/taro-loader: 4.0.4 => 4.0.4 
      @tarojs/webpack5-runner: 4.0.4 => 4.0.4 
      babel-preset-taro: 4.0.4 => 4.0.4 
      eslint-config-taro: 4.0.4 => 4.0.4 
      react: ^18.0.0 => 18.3.1

**Comment by ToQuery** [comment]
存在高度差
![WX20240819-100853@2x](https://github.com/user-attachments/assets/fb4d3dc9-753f-47d2-bd6f-6ea61ff7c210)

代码示例：
![WX20240819-101628@2x](https://github.com/user-attachments/assets/15410e69-616a-4869-8559-f5305d595934)

**Comment by ToQuery** [comment]
第一个元素为 View 不存在高度差：

![WX20240819-100644@2x](https://github.com/user-attachments/assets/9146e478-0671-49b4-8e5f-52bb1e743231)

代码示例：

![WX20240819-101815@2x](https://github.com/user-attachments/assets/b61c5652-4723-44fd-898e-ebe585c08052)

**Comment by oasis-cloud** [comment]
NutUI  的 Cell 组件存在 margin，可以通过样式覆盖处理掉。
