### ISSUE TITLE
Uploader 选择图片上传后，控件显示空白，图片显示不出来

### ISSUE THREAD

**Issue by youbenwu** [jdf2e/nutui-react#2546]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.6.16

### 平台

weapp

### 重现链接

https://github.com/youbenwu/testapp.git

### 重现步骤

<Uploader
            url={'https://z.outmao.cn/api/data/media/upload/image'}
            onStart={()=>{}}
          />

### 期望的结果是什么？

图片能正常显示

### 实际的结果是什么？

图片显示空白

**Comment by Miles-hxy** [comment]
你给的demo是2.6.14，升级下
