### ISSUE TITLE
[FR]: Cell 组件支持 open-type 可以打开对应的功能了

### ISSUE THREAD

**Issue by ToQuery** [jdf2e/nutui-react#2551]
### 这个功能解决了什么问题？

例如 openType=contact 打开客服

### 你期望的组件设计是怎样的？

例如 openType=contact 打开客服

**Comment by oasis-cloud** [comment]
小程序应该是在 button 组件上使用 open-type，cell 组件通过 view 实现，转译到小程序不存在open-type。https://developers.weixin.qq.com/miniprogram/dev/component/view.html
