### ISSUE TITLE
Cascader 级联选择器 value 属性 不生效

### ISSUE THREAD

**Issue by Topgt** [jdf2e/nutui-react#2555]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

^2.6.0

### 平台

weapp

### 重现链接

暂无

### 重现步骤

Cascader 级联选择器 value 无论设置任何值都不起作用

### 期望的结果是什么？

value 的值 由我自己在onPathChange 中自己使用setValue 设置值。

### 实际的结果是什么？

现在是即使我value传一个固定的值 级联选择器还是能选择内容

**Comment by Miles-hxy** [comment]
先升级到最新版本，应该处理过类似问题
