### ISSUE TITLE
Uploader 选择图片 sizeType类型无作用

### ISSUE THREAD

**Issue by spwuc** [jdf2e/nutui-react#2569]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

3.3.0

### 平台

weapp

### 重现链接

无

### 重现步骤

Uploader 选择图片sizeType类型无作用 sizeType传入['compressed'] 后还是可以选择原图，查看源码发现 sizeType 并没有使用传入的sizeType 
![image](https://github.com/user-attachments/assets/cc761def-9dd8-407b-a66d-afa7341b92f8)

### 期望的结果是什么？

希望sizeType 使用传入的sizeType  可以正确使用sizeType 

### 实际的结果是什么？

sizeType 传入 Uploader无效

**Comment by Miles-hxy** [comment]
这个新版本已经修复过了
