### ISSUE TITLE
表单validateFields行为疑问

### ISSUE THREAD

**Issue by TSjianjiao** [jdf2e/nutui-react#2588]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.18

### 平台

weapp

### 重现链接

https://codesandbox.io/p/devbox/bold-rain-grftzx?workspaceId=98e5ebf6-9ed7-4578-a09a-764843a9eb8f

### 重现步骤

1. 点击“提交”按钮，三个表单字段出现错误提示
2. 点击“填充值”按钮，第二个表单填充了值，但是错误信息并没有消失

### 期望的结果是什么？

第二个表单错误应该消失

### 实际的结果是什么？

第二个表单错误没有消失

### 其他补充信息

不知道是否是故意这样设计的，我看[源码中](https://github.com/jdf2e/nutui-react/blob/a2d7786f43a31967651e337fd2f8548ca6c584d8/src/packages/form/useform.taro.ts#L151)，`errs`通过判断长度来清空表单项的错误，但是如果前一个被验证的表单项有错误（也就是`errs`长度不为0），后续的表单项即使没有错误也不会清空状态

**Comment by JieJieeee** [comment]
我也遇到这个问题，目前是在第二次setFieldsValue手动validateFields一次以清楚错误信息。期待官方fix一下

**Comment by overcastsky** [comment]
我也遇到这个问题，手动setFieldsValue之后会触发所有表单的必填校验，当前标表单已设置校验实际为onBlur

**Comment by ryangopher** [comment]
@oasis-cloud Any update?

**Comment by overcastsky** [comment]
gsdg45sd4g5s4dg5sdイシリーズからドムをプレゼンりやかなベルガモットオジビタから

**Comment by 814351846** [comment]
setFieldsValue会触发Form.Item的rules

**Comment by overcastsky** [comment]
gsdg45sd4g5s4dg5sdイシリーズからドムをプレゼンりやかなベルガモットオジビタから
