### ISSUE TITLE
[FR]: nutui-docs仓库是否可以开放访问

### ISSUE THREAD

**Issue by HaoChenxin** [jdf2e/nutui-react#2602]
### 这个功能解决了什么问题？

我基于nutui-react 二次开发了组件库，想要部署下文档，发现workflow里面最后部署放到了nutui-docs仓库，可否提供下部署方案，或者放开下nutui-docs的访问权限，万分感激！

### 你期望的组件设计是怎样的？

提供二次开发能力

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-docs

**Comment by xiaoyatong** [comment]
部署不对外开放，可以提交pr
