### ISSUE TITLE
为什么没有ts类型提示，这可能只是一个疑问？！

### ISSUE THREAD

**Issue by dshuais** [jdf2e/nutui-react#2619]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.19

### 平台

weapp

### 重现链接

暂无

### 重现步骤

所有组件没有了ts类型提示，command+左击直接进入了这里，无法进入单个组件的类型注释页面，也没有类型提示了
<img width="794" alt="image" src="https://github.com/user-attachments/assets/dadaa106-1f88-43a8-a009-016b1a968116">

### 期望的结果是什么？

期望恢复类型提示

### 实际的结果是什么？

未恢复

**Comment by oasis-cloud** [comment]
升级到20版本
