### ISSUE TITLE
Image 组件在加载图片中灰色的背景怎么去掉？ 

### ISSUE THREAD

**Issue by desonyuan** [jdf2e/nutui-react#2643]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.21

### 平台

weapp

### 重现链接

https://codesandbox.io/p/devbox/nutui-react-2x-demo-fg4vxd?file=%2Fsrc%2FApp.tsx%3A6%2C26

### 重现步骤

Image 组件在加载图片中灰色的背景怎么去掉？ 

### 期望的结果是什么？

去掉灰色背景的方法

### 实际的结果是什么？

Image 组件在加载图片中灰色的背景怎么去掉？

**Comment by oasis-cloud** [comment]
可以将 .nut-img-loading 设置为 display:none
