### ISSUE TITLE
Form    setFieldsValue 设置后自动触发全部表单验证问题？

### ISSUE THREAD

**Issue by cbtan** [jdf2e/nutui-react#2649]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.23

### 平台

weapp

### 重现链接

没有

### 重现步骤

调用 setFieldsValue  设置一个字段，就全部 字段进行 检验了！

### 期望的结果是什么？

setFieldsValue  不要全部字段检验

### 实际的结果是什么？

setFieldsValue  不要全部字段检验

**Comment by ricardo-lumingfei** [comment]
同问 找到解决办法了吗请问？

**Comment by henryzp** [comment]
这个发布了么？还是计划什么时候发版？
