### ISSUE TITLE
[FR]: InfiniteLoading组件的target希望可以支持指定任意父级的容器，当父级容器产生滚动的时候，即可立即出发onScroll、onLoadMore等方法的执行

### ISSUE THREAD

**Issue by zepingFISH** [jdf2e/nutui-react#2702]
### 这个功能解决了什么问题？

解决了父子/父父子组件中，当子组件使用了InfiniteLoading，而是父级组件产生的滚动的时候，产生的两个滚动条相互影响的问题；并且，父级滚动就可以触发子组件方法的执行，就方便很多，而不用其他投机取巧的方法或者改造实现这种功能

### 你期望的组件设计是怎样的？

看看是不是直接可以复用这个target="refreshScroll"就行，然后指定的容器直接设置对应的id=“refreshScroll”就行

**Comment by BrightFuture888** [comment]
我是在h5中遇到的问题，这个字段的 loadMore，绑定scrollview以后，不能检测到加载更多，使用target也获取不了。都快想弃用转Vant了
