### ISSUE TITLE
InfiniteLoading 滚动加载组件；Taro在h5页面中使用出现，onScroll，loadMore，target没生效 等方法不能出现滚动效果，

### ISSUE THREAD

**Issue by BrightFuture888** [jdf2e/nutui-react#2718]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.7.0

### 平台

h5

### 重现链接

我是在taro中使用的

### 重现步骤

使用InfiniteLoading组件；在scrollView中下拉刷新在没有到顶部的时候就出发，极度影响交互。建议用两套代码去做小程序和h5的兼容优化。还有target这个属性可以明确到底是获取id还是获取类；遇到的场景：1. 使用scrollView组件，给scrollview声明id=“scroll-view” ；2. 使用InfiniteLoading组件的target = “scroll-view” 3. 使用onScroll没有效果；使用onLoadMore没有效果；给hasMore=true，也没有效果，4.如果注册了 下拉刷新，只要出现下拉就会出发下拉刷新。

### 期望的结果是什么？

1.我期望功能可以正常使用；2.例如我把 InfiniteLoading 嵌套在 滚动条中，可以使用target正常的触发对应的api；3.target说明传入的是 “#scroll” “.scroll” 还是什么。文档也太简陋了

### 实际的结果是什么？

功能不能使用。无法支持嵌套，获取不到对应的scroll事件

**Comment by zepingFISH** [comment]
我也遇到了，希望InfiniteLoading组件的target可以指定滚动容器

**Comment by BrightFuture888** [comment]
不能指定scrollView，但是可以指定一个 div盒子的
