### ISSUE TITLE
CountDown组件在小程序里无法显示

### ISSUE THREAD

**Issue by feituer** [jdf2e/nutui-react#2784]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

^2.7.0

### 平台

weapp

### 重现链接

https://gitee.com/teun/taro-demo

### 重现步骤

在小程序环境里：
1. 按照官网上手指南，无论是初始化仓库添加，还是在后续react中添加定时器组件
2. 页面无法显示倒计时
3. PS：兼容tawindcss不好

### 期望的结果是什么？

希望显示倒计时

### 实际的结果是什么？

页面空白没有内容

1. 价格Price组件，无法显示symbol标记

**Comment by irisSong** [comment]
compiler: {
      type: 'webpack5', 
      prebundle: {
        exclude: ['@nutui/nutui-react-taro', '@nutui/icons-react-taro']
      }
    }增加配置
