### ISSUE TITLE
作为Taro脚手架官方推荐的 react-NutUI 模板，却无法正常展示

### ISSUE THREAD

**Issue by ChuYang-FE** [jdf2e/nutui-react#2794]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.7.1

### 平台

h5, weapp

### 重现链接

@tarojs/cli 4.0.7：https://www.npmjs.com/package/@tarojs/cli

### 重现步骤

根据Taro脚手架，选择react-NutUI模板，构建项目成功。如下图：

然后启动项目，`pnpm dev:weapp` 或者 `pnpm dev:h5`

![re-produce](https://github.com/user-attachments/assets/ae024f1c-145c-49d4-8879-7b4156118c5b)

### 期望的结果是什么？

正常展示项目及组件。

### 实际的结果是什么？

- 微信小程序：组件无法显示，有警告（图一）
- H5：能显示组件，但报错（图二）

**微信小程序：**
![微信小程序](https://github.com/user-attachments/assets/53ce38ab-73ea-460d-9184-18dce8d8585a)

---

**H5：**
![H5](https://github.com/user-attachments/assets/b470d10d-cb10-4984-bcec-b65f512525fa)

### 环境信息
Node 22
设备：MacBook Air M3芯片 (macOS 15.1.1)

**Comment by 1021683053** [comment]
跟你一样

**Comment by Me-UserName** [comment]
这里有demo
https://github.com/jdf2e/nutui-demos

**Comment by WuJiY** [comment]
webpack可以 vite不行

**Comment by irisSong** [comment]
3、小程序项目运行时出现「找不到模板」的错误提示
解决方案：在 Taro 配置文件中关闭 prebundle 及 cache

// config/index.js
config = {
  compiler: {
    type: 'webpack5',
    prebundle: {
      exclude: ['@nutui/nutui-react-taro', '@nutui/icons-react-taro']
    }
  },
  cache: {
    enable: false
  }
}

**Comment by WuJiY** [comment]
vite不行

**Comment by 763483000** [comment]
我还以为我自己出了问题，2025年，依旧如此啊
