### ISSUE TITLE
setFieldsValue会触发Form.Item的rules

### ISSUE THREAD

**Issue by 814351846** [jdf2e/nutui-react#2816]
### NutUI React 包名

@nutui/nutui-react

### NutUI React 版本号

2.6.14

### 平台

h5, weapp

### 重现链接

https://nutui.jd.com/taro/react/2x/#/zh-CN/component/form

### 重现步骤

import React from 'react'
import Taro from '@tarojs/taro'
import { Form, Input, Radio } from '@nutui/nutui-react-taro'

const Demo5 = () => {
  const submitFailed = (error: any) => {
    Taro.showToast({ title: JSON.stringify(error), icon: 'error' })
  }

  const submitSucceed = (values: any) => {
    Taro.showToast({ title: JSON.stringify(values), icon: 'success' })
  }

  const [form] = Form.useForm()
  const onMenuChange = (value: string | number | boolean) => {
    switch (value) {
      case 'male':
        form.setFieldsValue({ note: '👨' })
        break
      case 'female':
        form.setFieldsValue({ note: '👩' })
        break
      default:
    }
  }
  return (
    <>
      <Form
        form={form}
        onFinish={(values) => submitSucceed(values)}
        onFinishFailed={(values, errors) => submitFailed(errors)}
      >
        <Form.Item
          label="字段A"
          name="username"
          rules={[{ required: true, message: '请输入字段A' }]}
        >
          <Input placeholder="请输入字段A" type="text" />
        </Form.Item>
        <Form.Item label="标注" name="note">
          <Input placeholder="请输入标注" type="string" />
        </Form.Item>
        <Form.Item label="字段E" name="gender">
          <Radio.Group onChange={onMenuChange}>
            <Radio value="male">A</Radio>
            <Radio value="female">B</Radio>
          </Radio.Group>
        </Form.Item>
      </Form>
    </>
  )
}

export default Demo5

### 期望的结果是什么？

不应该触发校验

### 实际的结果是什么？

触发了校验

**Comment by oasis-cloud** [comment]
重复 #2649
