### ISSUE TITLE
Uploader 上传组件在小程序端无法预览图片

### ISSUE THREAD

**Issue by Madq92** [jdf2e/nutui-react#2821]
### NutUI React 包名

@nutui/nutui-react-taro

### NutUI React 版本号

2.7.1

### 平台

weapp

### 重现链接

https://github.com/jdf2e/nutui-react/tree/next

### 重现步骤

1.当前项目
```
pnpm i
pnpm run dev:taro:weapp
```

2.微信开发者工具导入

3.路由到 Uploader 的 demo

### 期望的结果是什么？

在上传状态的 demo 中应该是可以显示图片预览的

### 实际的结果是什么？

![image](https://github.com/user-attachments/assets/40af6fcc-9e4e-4405-b8dc-acfce588862c)

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-react/pull/2825
