### ISSUE TITLE
Infiniteloading里的loadMore方法，当props更新的时候，loadMore方法取不到最新的props值，需要第二次执行才能取到。

### ISSUE THREAD

**Issue by zouyawen** [jdf2e/nutui-react#304]
const refreshLoadMore = (done: () => void) => {
    setTimeout(() => {
     const { newValue } = props; // 假设这个newValue 是该父组件传过来的值，且中途有修改。则需要执行到第二次refreshLoadMore ，newValue 才能取到修改之后的值
      const curLen = refreshList.length
      for (let i = curLen; i < curLen + 10; i++) {
        refreshList.push(`${i}`)
      }
      if (refreshList.length >= 30) {
        setRefreshHasMore(false)
      } else {
        setRefreshList([...refreshList])
      }
      done()
    }, 500)
  }

**Comment by oasis-cloud** [comment]
因为形成了闭包，导致获取不到新的 props，可以通过 useRef 的方式处理一下

**Comment by oasis-cloud** [comment]
const ref = useRef(props)
    useEffect(() => {
        ref.current = props
    }, [props])

    const loadMore = (done: () => void) => {
        setTimeout(() => {
            console.log('loadmore',ref.current)
            const curLen = defultList.length
            for (let i = curLen; i < curLen + 10; i++) {
                defultList.push(`${i}`)
            }
            if (defultList.length >= 30) {
                setHasMore(false)
            } else {
                setDefultList([...defultList])
            }
            done()
        }, 500)
    }
