### ISSUE TITLE
根据条件动态渲染不同页面时出现页面不停刷新 抖动的情况

### ISSUE THREAD

**Issue by yinweixx** [jdf2e/nutui-react#310]
不确定是不是我自己的开发问题，因为刚开始学习和使用react四天时间，还有些生疏，问题是这样的
在渲染列表页的时候，根据不同的情况，如果列表没有数据，则渲染<Empty/>，否则渲染正常的<Card/>
在return（）里使用了{!bool && <MyEmpty/>} ,bool = useState, MyEmpty自定义，{bool&&<MyCard/>}，同样MyCard自定义，  
此时在 MyCard 里面有一个 元素，例如<InputNumber/>，在获取change事件后，更新 useState时，会不停的重新渲染整个页面，此时页面会出现抖动的情况，如果将MyCard里的元素全部直接写到return（）里，则不会出现此情况。
问题就是这样，感谢大佬们的支持。

**Comment by yinweixx** [comment]
发现写的东西丢了， 则渲染 「Empty/」 否则渲染正常的 「Card/」, {!bool && 「MyEmpty」}   , {bool&& [MyCard/]}

**Comment by oasis-cloud** [comment]
要不咱直接贴代码？

**Comment by yinweixx** [comment]
const Detail = () => {
  const SwiperChange = () => {
      return (
        <>
          <MaskLayer />
        </>
      );
    };
  return <SwiperChange />;
}



export const MaskLayer = () => {
const [gender, setGender] = useStata("");
const chooseGender = (value) => {
    setGender(value);
  };
    return (
    <div className="down-in">
      <Row>
        <Col>
          <RadioGroup
            value={gender}
            direction="horizontal"
            onChange={(e) => chooseGender(e)}
          >
            <Radio shape="button" value="0">
              girl
            </Radio>
            <Radio shape="button" value="1">
              boy
            </Radio>
          </RadioGroup>
        </Col>
      </Row>
    </div>
  );
}

**Comment by yinweixx** [comment]
`return (
    <div className="down-in">
      <Row>
        <Col>
          <RadioGroup
            value={gender}
            direction="horizontal"
            onChange={(e) => chooseGender(e)}
          >
            <Radio shape="button" value="0">
              girl
            </Radio>
            <Radio shape="button" value="1">
              boy
            </Radio>
          </RadioGroup>
        </Col>
      </Row>
    </div>
  );`

**Comment by yinweixx** [comment]
`const Detail = () => {
const SwiperChange = () => {
    return (
      <>
        {/**这里是遮罩层 */}
        <MaskLayer />
      </>
    );
  };

  return <SwiperChange />;
};`

**Comment by yinweixx** [comment]
`const Detail = () => {
  const SwiperChange = () => {
    return (
      <>
        {/**这里是遮罩层 */}
        <MaskLayer />
      </>
    );
  };

  return <SwiperChange />;
};`

**Comment by yinweixx** [comment]
`const Detail = () => {
  const SwiperChange = () => {
    return (
      <>
        {/**这里是遮罩层 */}
        <MaskLayer />
      </>
    );
  };
  return <SwiperChange />;
};`
