### ISSUE TITLE
1.3.4 uploader组件 当listType 为 list 时 使用 isDeletable 无法隐藏 删除按钮

### ISSUE THREAD

**Issue by YYBT** [jdf2e/nutui-react#324]
版本 1.3.4
uploader组件 
当listType 为 list 时 使用 isDeletable 无法隐藏 删除按钮

disabled 设置禁用时 能否隐藏上传按钮和删除按钮

**Comment by junjun666** [comment]
1.当listType 为 list 时 使用 isDeletable 无法隐藏 删除按钮 --  功能已经新增修复
2.当listType 为 list 时 disabled 设置禁用，-- 可以代码自行控制上传按钮，删除按钮也可以用isDeletable来控制是否展示
