### ISSUE TITLE
TextArea taro字数限制问题

### ISSUE THREAD

**Issue by seewhy163** [jdf2e/nutui-react#325]
```
  <TextArea maxlength="1000" limitshow={true} ></TextArea>
```

设置了maxlength 1000 ，实际到140个字就无法继续输入了
![image](https://user-images.githubusercontent.com/8546571/192129986-8152496b-5e09-45d0-8ddd-4a99800b72ba.png)

**Comment by Huanghaiting** [comment]
![image](https://user-images.githubusercontent.com/17808807/200533875-8b90c9ad-e096-45d8-9340-f3844142402d.png)
如何重现？可以详细写下所用的版本
