### ISSUE TITLE
主包体积大

### ISSUE THREAD

**Issue by XiaoHu-Producer** [jdf2e/nutui-react#329]
1、使用环境nutui-react-taro、taro@3.65.6、react18编译完成
2、已经使用了官网推荐的按需引入

![1664439395680](https://user-images.githubusercontent.com/63284943/193168191-9d51b44f-309f-4b50-bacc-06c2110e6858.png)

**Comment by XiaoHu-Producer** [comment]
这个问题可以使用分包的形式来避免，我的解决方案如下
1、每个页面使用的nut组件不超过两个(单个Tabbar组件竟然占用超过230kb)
2、除了home页面其他的页面均采用分包的形式

**Comment by XiaoHu-Producer** [comment]
当你使用这个组件库来开发小程序的时候，整体资源打包会超过1M，因此，不要在tabbar页面使用过多的nut组件，尽量使用taro自带的组件来写主包页面

**Comment by oasis-cloud** [comment]
你的代码仓库可以提供一份吗？

**Comment by XiaoHu-Producer** [comment]
需要等待并且测试几天，那个代码仓库可以发到这里

**Comment by XiaoHu-Producer** [comment]
可以发送出来，需要等待几天
