### ISSUE TITLE
使用Taro.switchTab无法正确显示选中标签

### ISSUE THREAD

**Issue by lattemj** [jdf2e/nutui-react#331]
在微信小程序中自定义（custom-tab-bar）中使用Taro.switchTab后无法正确显示选中标签

**Comment by oasis-cloud** [comment]
你描述的问题看上去应该是 taro 的问题，可以尝试在 taro 那边也提交一个 issue

**Comment by lattemj** [comment]
问题已解决，如下：
const pageCtx = Taro.getCurrentInstance().page;
const tabbar = Taro.getTabBar<CustomTabBar>(pageCtx);
tabbar?.setCurrentActive(********);
自定义tabbar中使用类组件，通过上面方式调用组件中的方法来改变选中状态，单从组件中改变状态是没用的。这是小程序架构和原生tabbar导致，与taro或nutui本身无关。

**Comment by yukilu** [comment]
我也有这个问题，但是不用像楼上搞的这么复杂，[官方文档](https://docs.taro.zone/docs/custom-tabbar#%E7%8A%B6%E6%80%81%E7%AE%A1%E7%90%86)里写的很清楚，你不能在组件内部去改变状态，因为每个页面的tabBar组件都是独立的，你要使用状态托管去可以解决这个问题，我用的是redux
