### ISSUE TITLE
关于Input输入框的一些建议

### ISSUE THREAD

**Issue by cuicuiworld** [jdf2e/nutui-react#337]
1，defaultValue为双向绑定属性，如果能统一成value就好了，这样是不是可以为以后组件放到form中做铺垫？
2，希望添加renderLeftIcon<reactNode>、renderRightIcon<reactNode>属性，更好自定义图标。
3，Slots插槽部分slotButton和slotInput，希望能转化成react方式，如 renderButton 和 renderInput。

**Comment by cuicuiworld** [comment]
还是有两点问题请教一下。
1. 能不能使用value代替defaultValue呢？
2. 文档中说是双向绑定，但是我在例子中并没有体现双向绑定，传入输入框的输入值(defaultValue)作为受控值，还是要在事件中设置传入的受控值。

@oasis-cloud

**Comment by vickyYE** [comment]
> 还是有两点问题请教一下。
> 
> 1. 能不能使用value代替defaultValue呢？
> 2. 文档中说是双向绑定，但是我在例子中并没有体现双向绑定，传入输入框的输入值(defaultValue)作为受控值，还是要在事件中设置传入的受控值。
> 
> @oasis-cloud

您好，关于问题1，在组件中defaultValue绑定的就是input的value值，直接传defaultVaule就可以。
关于问题2，因为react中没有双向绑定的功能，只能利用state和change事件去模拟，需要在值改变时重置下传入的值，可以参考文档中基础用法的例子

```tsx
import  React, { useState } from "react";
import { Input } from '@nutui/nutui-react';

const App = () => {
    const [value, UpdateValue] = useState('')
  return (
    <>
      <Input label="文本" defaultValue={value}  placeholder="文本" change={(val) => {
            UpdateValue(val)
          }}/>
    </>
  );
};
export default App;
```
