### ISSUE TITLE
希望能出一个通过配置修改主题色功能

### ISSUE THREAD

**Issue by cuicuiworld** [jdf2e/nutui-react#338]
目前配置主题色是需要在webpack或vite文件中配置，希望能在ConfigProvider中可以修改主题色。

**Comment by oasis-cloud** [comment]
这里提到的主题色是指主题定制的 sass 文件吗？

**Comment by cuicuiworld** [comment]
import { ConfigProvider } from 'nutui-react-taro';

ConfigProvider.config({
  theme: {
    primaryColor: '#25b864',
  },
});

类似这种动态切换主题功能

**Comment by cuicuiworld** [comment]
> 这里提到的主题色是指主题定制的 sass 文件吗？



> 



> import { ConfigProvider } from 'nutui-react-taro';
> 
> ConfigProvider.config({ theme: { primaryColor: '#25b864', }, });
> 
> 类似这种动态切换主题功能

@oasis-cloud

**Comment by oasis-cloud** [comment]
可安装 v1.4.0 版本
