### ISSUE TITLE
Signature 小程序环境无法使用

### ISSUE THREAD

**Issue by leida1983** [jdf2e/nutui-react#339]
## 问题描述

Signature 控件在 小程序环境会显示不支持 Canvas 情况

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **React 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by oasis-cloud** [comment]
@nutui/nutui-react 和 @nutui/nutui-react-taro 用的哪个？

**Comment by oasis-cloud** [comment]
可安装 @nutui/nutui-react-taro@1.3.7 试一下
