### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by LiMao00** [jdf2e/nutui-react#351]
## 问题描述

文档页面：https://nutui.jd.com/react/#/zh-CN/guide/starttaro-react
错误：
```
sass:{
  data: `@import "@nutui/nutui-react/dist/styles/variables.scss";`
}

// 应改为
sass:{
  data: `@import "@nutui/nutui-react-taro/dist/styles/variables.scss";`
}
```

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **React 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by oasis-cloud** [comment]
下周版本迭代
