### ISSUE TITLE
nutui-react-taro Button大小问题

### ISSUE THREAD

**Issue by shizhier** [jdf2e/nutui-react#388]
## 问题描述

Button,在vue下正常显示，在react上显示很小
按以下文档，一步一步操作的
[https://nutui.jd.com/react/#/zh-CN/guide/starttaro-react](url)

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：v16.15.1
- **NutUI 版本**： "@nutui/nutui-react-taro": "^1.3.8",
- **React 版本**："^18.0.0",
- **引用方式**：  CDN / NPM ？

**Comment by oasis-cloud** [comment]
在 taro 创建项目的时候，可以选择 nutui-react 的 template
