### ISSUE TITLE
Grid组件中使用icon的问题

### ISSUE THREAD

**Issue by harry118** [jdf2e/nutui-react#392]
## 问题描述
1. Grid组件中使用icon，直接用官网的代码 icon是不会显示出来的
2. 如果像如下使用，icon 会出来（但是第一个GridItem的 icon会变小） 不知道什么原因
```
      <Grid gutter={3} square>
        <GridItem icon={<Icon name='dongdong' />} text='文字' />
        <GridItem icon='dongdong' text='文字' />
        <GridItem icon='dongdong' text='文字' />
      </Grid>
```

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： "@nutui/nutui-react-taro": "^1.3.4"
- **React 版本**：   18
- **引用方式**：  CDN / NPM ？

**Comment by yangxiaolu1993** [comment]
首先感谢对 NutUI-React 的支持，针对提出的问题
1、NutUI-React 调试工具的版本号未更新，我们会尽快安排更新；
2、<GridItem icon={<Icon name='dongdong' />} text='文字' /> 这样设置 Icon，说明已经要自定义 Icon 图标了，图标大小可以通过 Icon 组件的 size 属性设置，即： <GridItem icon={<Icon name='dongdong' size='28'/>}  text='文字' />
