### ISSUE TITLE
关于头像组件Avatar显示的问题

### ISSUE THREAD

**Issue by chengluliu** [jdf2e/nutui-react#397]
## 问题描述

> 在Taro 小程序 使用nut 头像组件的时候，在url已经有头像地址的情况下usestate重新赋值，不会更新头像，要清空url，再赋值才有效，这个问题是taro的问题还是咱们头像组件有缓存机制呀？

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 预期的行为和实际行为

希望在setState 之后 就可以 改变头像显示

## 复现步骤，具体代码
```
const Index = () => {
  const [userInfo, setUserInfo] = useState<UserType>({
    avatar:'https://ts1.cn.mm.bing.net/th/id/R-C.29a84eb867bf75b5327e7df3b1a7e32c?rik=iW9zjAJwqTB%2fdA&riu=http%3a%2f%2ftupian.qqw21.com%2farticle%2fUploadPic%2f2019-7%2f201971622263482217.jpeg&ehk=W4G6YV7SJ1LFEFGJ3r%2bsC66stsnts%2bGu%2b7tsCcMPWGA%3d&risl=&pid=ImgRaw&r=0'
  })
 

  /**
   * 初始化页面数据
   */
  const initData = async () => {
 

    const userRes = {
      // avatar:'https://ts1.cn.mm.bing.net/th/id/R-C.29a84eb867bf75b5327e7df3b1a7e32c?rik=iW9zjAJwqTB%2fdA&riu=http%3a%2f%2ftupian.qqw21.com%2farticle%2fUploadPic%2f2019-7%2f201971622263482217.jpeg&ehk=W4G6YV7SJ1LFEFGJ3r%2bsC66stsnts%2bGu%2b7tsCcMPWGA%3d&risl=&pid=ImgRaw&r=0'
      avatar:'https://huzhudian.zhaodaka.vip/api/static/upload/2022/11/02/63614f32eff12907c3f6dfd3.jpeg'

    }
    setUserInfo(userRes)
  }
 
 
  

  // 对应 onShow
  useDidShow(() => {
    console.log("onshow")
    initData()
  })

  
  return (
    <div className={styles.index}>
    
          {/*{ userInfo.avatar}*/}
          {
            userInfo.avatar !== '' ?
              (<Avatar className={styles.avatar} size="large" url={userInfo.avatar}/>) : (<Avatar className={styles.avatar} size="large" icon={'my'}/>)
          }
       
    </div>
  );
}
export default Index;
```

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 1.3.8
- **React 版本**：
- **引用方式**：  CDN / NPM ？

**Comment by chengluliu** [comment]
url 为空的话就可以正常切换, 所以变得要每次更新头像显示的话要去重置   avatar  为  '' 空字符串才能生效

**Comment by junjun666** [comment]
Avatar组件本身并没有缓存机制，看了下您发的代码，在不知道useDidShow是怎么封装的情况下，重新更新渲染是没有问题的，请您检查下是否是其他代码书写出现了问题，或者请您提供下详细的demo文件。

**Comment by chengluliu** [comment]
git@github.com:chengluliu/AvatarDemo.git

> Avatar组件本身并没有缓存机制，看了下您发的代码，在不知道useDidShow是怎么封装的情况下，重新更新渲染是没有问题的，请您检查下是否是其他代码书写出现了问题，或者请您提供下详细的demo文件。

[git@github.com:chengluliu/AvatarDemo.git](https://github.com/chengluliu/AvatarDemo.git)

在这个demo里 我初始化了一个头像地址, 并且在 onshow里改变它, 在咱们的Nutui组件是不起作用的, 在 taroify 的头像组件里是起效的. 可是我不想混合使用, 就想用咱们的NutUI
PS:   如果初始化的时候 给的是 空字符串""    是可以起效的
