### ISSUE TITLE
Menu 自定义菜单内容, 无法使用实例上的 toggle 方法手动关闭弹框。

### ISSUE THREAD

**Issue by jisuanjixue** [jdf2e/nutui-react#402]
## 问题描述
Menu 自定义菜单内容, 无法使用当点击自定义里的 button 手动关闭弹框, 使用的是 react 的 ref 获取实例上的 toggle 方法。

## 预期的行为和实际行为
希望点击日期的 button , 调用onConfirmDatePicker方法后关闭Menu弹窗

## 复现步骤，具体代码
`
<MenuItem title={dateValue} value={dateValue} style={{ display: dropShow ? "block" : "none" }} ref={menuRef}>
                <div style={{ marginTop: "300rpx", overflow: "hidden" }} className="datePopup">
                  <DatePicker
                    type="date"
                    visible={true}
                    title="日期选择"
                    isShowChinese
                    minDate={minDate}
                    maxDate={maxDate}
                    modelValue={defaultValue}
                    onChange={(columnIndex: number, values: (string | number)[], _: any[]) => setDateValue(values.join("-"))}
                    onConfirmDatePicker={(values, _) => {
                      menuRef.current.toggle();
                      // setTimeout(() => {
                      //   const query = Taro.createSelectorQuery();
                      //   query
                      //     .select(".menu")
                      //     .fields({ computedStyle: ["display"] }, res => {
                      //       console.log(res)
                      //       // res.display = "none";
                      //     })
                      //     .exec();
                      // }, 600);

                      // document.getElementsByClassName("menu").style.display = "none";
                      setDateValue(values.join("-"));
                      // setDropShow(false);
                      runDaily({ ...queryParams, date: values.join("-") });
                    }}
                    onCloseDatePicker={() => {
                      setDateValue(dayjsUtils.formatDate(new Date()));
                      runDaily(queryParams);
                    }}
                  />
`

## 相关环境信息
- **操作系统**：macOS10.15.7
- **Node 版本**：
- **NutUI 版本**： 1.3.8
- **React 版本**：18
- **引用方式**：  NPM ？

**Comment by oasis-cloud** [comment]
Hi 可以提供一个最小可复现 demo 吗
