### ISSUE TITLE
关于选项卡组件的一些建议

### ISSUE THREAD

**Issue by cuiyiworld** [jdf2e/nutui-react#405]
1. 希望能添加属性对选中底部展示样式颜色、形状、位置[偏移值]等修改，可以支持自定义渲染。
2. 数量多,滚动操作 时，希望能自动左右滚动的过程，目前是手动滚动。
3. 希望能添加卡片风格的选项卡（类似于分段器）。
<img width="442" alt="image" src="https://user-images.githubusercontent.com/21233144/199763380-8d67b36e-cc33-4f99-8a17-2a7e28f37ab9.png">

**Comment by xiaoyatong** [comment]
问题3.希望能添加卡片风格的选项卡（类似于分段器）。
能给一个图示么

**Comment by chrysanthemum** [comment]
支持，同时希望增加滑动切换

**Comment by xiaoyatong** [comment]
> 
是否与这个issue里的第二个相同？

https://github.com/jdf2e/nutui-react/issues/585

**Comment by xiaoyatong** [comment]
> 支持，同时希望增加滑动切换

是否与这个issue里的第二个相同？
https://github.com/jdf2e/nutui-react/issues/585

**Comment by chrysanthemum** [comment]
> > 支持，同时希望增加滑动切换
> 
> 是否与这个issue里的第二个相同？ #585

是的，谢谢！

**Comment by lshaofan** [comment]
希望增加滑动切换 +1

**Comment by xiaoyatong** [comment]
next-theme 下都已支持，待发版。

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-react/pull/1727
