### ISSUE TITLE
Swiper 轮播组件希望能增加一个当前页currentPage或value属性，表示当前页

### ISSUE THREAD

**Issue by cuicuiworld** [jdf2e/nutui-react#412]
Swiper 轮播组件希望能增加一个当前页currentPage或value属性，表示当前页。这样好和onChange事件进行受控处理。也可以达到使用ref. prev()、ref.next()、ref.to()进行切换操作同等效果。

**Comment by lkjh3214** [comment]
> Swiper 轮播组件希望能增加一个当前页currentPage或value属性，表示当前页。这样好和onChange事件进行受控处理。也可以达到使用ref. prev()、ref.next()、ref.to()进行切换操作同等效果。

onChange 事件触发时，组件内部的 _current 状态已变更。  当使用 外部传入的 value 进行完全受控处理时， value未改变时，轮播状态_current 需要变更为上一张图的 current , 当value 变化时， _current在变更为 当前 value。 同时会再次触发 onChange 事件。  因此会存在 以下问题： 1、当处于 第一张 或最后一张 图片时, change事件会多次触发  2、动画效果消失，或左右晃动。  建议具体描述下  应用场景
