### ISSUE TITLE
DatePicker 在小程序上 弹窗滑动事件穿透 ActionSheet DatePicker Popup

### ISSUE THREAD

**Issue by NeverMore2023** [jdf2e/nutui-react#414]
## 问题描述
京东，微信小程序下 ActionSheet DatePicker Popup 弹出后滑动组件内，背后页面跟着滑动，H5正常

## 预期的行为和实际行为
预期的行为：页面不滑动 
实际行为：页面滑动 

## 复现步骤，具体代码
 state = {
    showDatePicker: false
  }

  setShow1(isShow :boolean){
    this.setState({
      showDatePicker:isShow
    })
  }
  confirm1 = (values:(string|number)[],options:PickerOption[])=>{
  }
  componentDidHide () { }

  render () {
    return (
      <View className='index'>

        <View className='btn-parent'><Button type='primary' shape='square'>主要按钮</Button></View>
        <View className='btn-parent'><Button type='info'shape='square'>信息按钮</Button></View>
        <View className='btn-parent'><Button type='default'shape='square'>默认按钮</Button></View>
        <View className='btn-parent'><Button type='danger' shape='square'>危险按钮</Button></View>
        <View className='btn-parent'><Button type='warning' shape='square'>警告按钮</Button></View>
        <View className='btn-parent'><Button type='success'shape='square'>成功按钮</Button></View>
        <View className='btn-parent'><Button size='large' type='primary' className='button-radius-6'>大号按钮</Button></View>
        <View className='btn-parent'><Button size='normal' type='primary' className='button-radius-4'>普通按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-radius-3'>小型按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <Cell title='显示中文' desc='eeeeeeee' onClick={() => this.setShow1(true)} />
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>
        <View className='btn-parent'><Button size='small' type='primary' className='button-mini-radius-2'>mini按钮</Button></View>

        <DatePicker
          title='日期选择'
          visible={this.state.showDatePicker}
          isShowChinese
          onCloseDatePicker={() => this.setShow1(false)}
          onConfirmDatePicker={(values,options) => this.confirm1(values,options)}
        />
      </View>

## 相关环境信息
- **操作系统**：macos
- **Node 版本**：v14.20.0
- **NutUI 版本**：nutui-react-taro v1.3.9
- **React 版本**：18.0.0
- **引用方式**： NPM

**Comment by gooddaddy** [comment]
Overlay 遮罩层也存在着情况
