### ISSUE TITLE
Uploader组件在小程序上面上传不了文件

### ISSUE THREAD

**Issue by cuicuiworld** [jdf2e/nutui-react#415]
Uploader组件小程序案例里面，无论是哪一个案例，都上传不了，是缺少配置还是存在bug，还望悉知。

**Comment by junjun666** [comment]
不知道您这边说的上传不了是点击上传没有反应呢，还是说上传图片显示上传失败的图片呢？

**Comment by junjun666** [comment]
不知道您这边说的上传不了是点击上传没有反应呢，还是说上传图片显示上传失败的图片呢？

**Comment by junjun666** [comment]
不知道您这边说的上传不了是点击上传没有反应呢，还是说上传图片显示上传失败的图片呢？

**Comment by xsnt-zhang** [comment]
https://nutui.jd.com/react/#/zh-cn/component/uploader-taro官方示例无法达到描述预期，无法上传文件。与展示案例预期不一致。

**Comment by blin17** [comment]
我有类似问题，非debug mode就显示上传失败，但是我的图片在debug mode能上传。。。都不知道怎么debug
