### ISSUE TITLE
Button 组件小程序原生的授权事件没有被定义

### ISSUE THREAD

**Issue by chengluliu** [jdf2e/nutui-react#420]
## 你建议我们做什么？

>Button 组件小程序原生的授权事件没有被定义,例如 onGetPhoneNumber
>希望能把那些授权事件定义到类型中可以正确被ts提示

**Comment by simplyStyle** [comment]
预计在下个版本1.3.11版本中此功能  目前已经支持小程序原生button的所有事件了

**Comment by chengluliu** [comment]
棒，我就希望越来越好
