### ISSUE TITLE
Swiper组件源码taro部分swiper.taro.tsx里面的useReady能不能兼容一下h5端，否则使用这个组件报错。

### ISSUE THREAD

**Issue by cuicuiworld** [jdf2e/nutui-react#436]
### What problem does this feature solve?（这个功能解决的问题）
我是在纯h5方式，通过webpack配置，使用swiper组件，然后useReady报错。

### What does the proposed API look like?（期望的 API）
希望兼容一下h5不出现useReady报错

**Comment by oasis-cloud** [comment]
可以安装 v1.4.x 版本
