### ISSUE TITLE
SearchBar搜索框组件自定义图标基准线不一致导致没有对齐

### ISSUE THREAD

**Issue by cuicuiworld** [jdf2e/nutui-react#437]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.3.9

### React version（react 版本）
17.0.2

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(107.0.5304.87)

### System and its version（系统及其版本）
MacOS(12.3.1 (21E258))

### Taro environmental information（taro 环境信息）
3.4.9

### Steps to reproduce（重现步骤）
在h5demo页面和小程序demo页面中自定义图标设置demo中，图标没有对齐。
<img width="432" alt="image" src="https://user-images.githubusercontent.com/21233144/200728429-858d9cb9-3e1f-4594-871f-b76bcc523666.png">

### What is expected?（期望的结果是什么？）
图标对齐

### What is actually happening?（实际的结果是什么？）
图标没有对齐

**Comment by xiaoyatong** [comment]
fix
