### ISSUE TITLE
nutui-react/src/sites/mobile-taro运行npm run dev:weapp引入文件报错

### ISSUE THREAD

**Issue by Huanghaiting** [jdf2e/nutui-react#439]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.0.0

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
Windows 11

### Taro environmental information（taro 环境信息）
Taro v3.5.7

### Reproduction link（重现链接）
[github.com/jdf2e/nutui-react](https://github.com/jdf2e/nutui-react)

### Steps to reproduce（重现步骤）
npm run dev:weapp

### What is expected?（期望的结果是什么？）
正常运行项目

### What is actually happening?（实际的结果是什么？）
出现文件引入报错：
SassError: SassError: Can't find stylesheet to import.
     ╷
1036 │ @import '../price/Price.scss';
     │         ^^^^^^^^^^^^^^^^^^^^^
     ╵
  ../../packages/card/card.scss 1036:9  root stylesheet

### Remarks（补充说明）
main 分支

**Comment by oasis-cloud** [comment]
在项目根目录执行 npm run dev:taro:weapp
