### ISSUE TITLE
小程序扫码体验demo-选择TextArea组件，在显示字数统计栏输入超过20个字符，仍能输入

### ISSUE THREAD

**Issue by Huanghaiting** [jdf2e/nutui-react#442]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.0.0

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
Windows 11

### Taro environmental information（taro 环境信息）
Taro v3.5.7

### Reproduction link（重现链接）
[github.com/jdf2e/nutui-react](https://github.com/jdf2e/nutui-react)

### Steps to reproduce（重现步骤）
npm run dev:weapp
微信开发者工具打开
选择TextArea组件，在显示字数统计栏输入超过20个字符

### What is expected?（期望的结果是什么？）
超出20个字符应不能输入
### What is actually happening?（实际的结果是什么？）
超出20个字符仍能输入

### Remarks（补充说明）
官网的小程序扫码体验可复现

**Comment by oasis-cloud** [comment]
问题是由于 taro-plugin-html 在转换的时候，没有将 maxLength 进行正确的转换，可以关注：https://github.com/NervJS/taro/issues/12823

**Comment by AnteeHub** [comment]
> 问题是由于 taro-plugin-html 在转换的时候，没有将 maxLength 进行正确的转换，可以关注：[NervJS/taro#12823](https://github.com/NervJS/taro/issues/12823)

Taro 版本 < 3.5.9 使用 nutui-react-taro 包时会出现 `<Input type="textarea"/>` 中 `maxlength` 失效的情况， Taro 升级到 3.5.9 以上版本后，我在本地调试就正常了
