### ISSUE TITLE
Input defaultValue无法清空

### ISSUE THREAD

**Issue by shien-sun-we** [jdf2e/nutui-react#446]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.3.9

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
14.20.0

### Browser and its version（浏览器及其版本）
107.0.5304.87（正式版本） (x86_64)

### System and its version（系统及其版本）
 12.5.1

### Taro environmental information（taro 环境信息）
 Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.5 => 3.5.5 
      @tarojs/components: 3.5.5 => 3.5.5 
      @tarojs/helper: 3.5.5 => 3.5.5 
      @tarojs/mini-runner: ^3.5.5 => 3.5.7 
      @tarojs/plugin-framework-react: 3.5.5 => 3.5.5 
      @tarojs/plugin-html: ^3.5.5 => 3.5.7 
      @tarojs/plugin-platform-alipay: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-jd: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-qq: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-swan: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-tt: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-weapp: 3.5.5 => 3.5.5 
      @tarojs/react: 3.5.5 => 3.5.5 
      @tarojs/router: 3.5.5 => 3.5.5 
      @tarojs/runtime: 3.5.5 => 3.5.5 
      @tarojs/shared: 3.5.5 => 3.5.5 
      @tarojs/taro: 3.5.5 => 3.5.5 
      @tarojs/taro-h5: 3.5.5 => 3.5.5 
      @tarojs/webpack-runner: ^3.5.5 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.5 => 3.5.5 
      babel-preset-taro: 3.5.5 => 3.5.5 
      eslint-config-taro: 3.5.5 => 3.5.5 
      react: ^18.0.0 => 18.2.0 

### Reproduction link（重现链接）
[codepen.io](https://codepen.io/shien-sun-we/pen/rNKyOZw)

### Steps to reproduce（重现步骤）
const [brandName,setBrandName] = useState<string>('')
    setBrandName('')
    <Input className='customCell-Input' defaultValue={brandName}  placeholder='请输入' onChange={(val) => setBrandName(val)}/>

### What is expected?（期望的结果是什么？）
清空Input 并显示placeholder

### What is actually happening?（实际的结果是什么？）
无法清空

**Comment by vickyYE** [comment]
您好，用您给的“重现步骤”复现，发现您没有设置显示清除按钮的属性clearable，您可以这样尝试
<Input className='customCell-Input'  clearable defaultValue={brandName} placeholder='请输入' onChange={(val) => setBrandName(val)}/>
如果是二次设置defaultValue为空字符串，不生效问题，我们已经做了修改，下一版本会修复
