### ISSUE TITLE
TabbarItem 不支持onClick事件

### ISSUE THREAD

**Issue by comlejade** [jdf2e/nutui-react#469]
### What problem does this feature solve?（这个功能解决的问题）
tabbar组件在小程序中作为custom-tab-bar的时候，onSwitch事件中处理visible会和页面自定义的visible冲突，希望把事件写在onClick事件上

### What does the proposed API look like?（期望的 API）
无

**Comment by Hanchengluo** [comment]
to

**Comment by oasis-cloud** [comment]
可以提供最小可复现 Demo，组件实现中采用的是 onClick，没有理解 onSwitch事件中处理visible会和页面自定义的visible冲突
