### ISSUE TITLE
NavBar 左侧图标在小程序下不显示

### ISSUE THREAD

**Issue by comlejade** [jdf2e/nutui-react#473]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.3.11

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.17.0

### Browser and its version（浏览器及其版本）
微信开发者工具

### System and its version（系统及其版本）
windows 11

### Reproduction link（重现链接）
[github.com](https://github.com/comlejade/nutui-demo.git)

### Steps to reproduce（重现步骤）
小程序下，左侧箭头不显示，在app.scss中单独引入icon.scss 才显示，但是 designWidth 是 750 时，icon 大小不对，font-size,width等值都为空

### What is expected?（期望的结果是什么？）
无

### What is actually happening?（实际的结果是什么？）
无

**Comment by comlejade** [comment]
![image](https://user-images.githubusercontent.com/15702577/202825113-382a5579-d798-4623-b23c-29e0b73eef03.png)
![image](https://user-images.githubusercontent.com/15702577/202825129-669b2108-0b57-49c3-a59f-a218984e2a7d.png)

**Comment by oasis-cloud** [comment]
小程序场景需要使用 @nutui/nutui-react-taro, nutui 视觉规范为 375，可以在 px2rem 的时候排出 nutui- 和 nut-
