### ISSUE TITLE
自定义主题色，原生 tabbar active 选中仍是红色

### ISSUE THREAD

**Issue by hyyqcweb** [jdf2e/nutui-react#474]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.3.11

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.17.0

### Browser and its version（浏览器及其版本）
chrome  107.0.5304.110

### System and its version（系统及其版本）
mac 10.15

### Taro environmental information（taro 环境信息）
Taro v3.5.7

### Steps to reproduce（重现步骤）
// 自定义个主题色
```
 sass: {
    resource: [path.resolve(__dirname, '..', 'src/assets/style/theme.scss')],
    data: `@import "@nutui/nutui-react-taro/dist/styles/variables.scss";`,
  },
```
// theme.scss
```
$primary-color: #1884ff !default;
$primary-color-end: #1884ff !default;
```

### What is expected?（期望的结果是什么？）
tabbar active 跟随主题色

### What is actually happening?（实际的结果是什么？）
tabbar active 仍是大红色
![image](https://user-images.githubusercontent.com/17583072/202832134-6c187c1f-0e74-4c20-ad68-75d861354f3c.png)

**Comment by libin0824** [comment]
麻烦提供下可复现的代码。
