### ISSUE TITLE
打包后Rate组件图标消失

### ISSUE THREAD

**Issue by dingff** [jdf2e/nutui-react#484]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.3.11

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.19.1

### Browser and its version（浏览器及其版本）
chrome latest

### System and its version（系统及其版本）
macos 12.6

### Reproduction link（重现链接）
[github.com/dingff/taro3-demo](https://github.com/dingff/taro3-demo)

### Steps to reproduce（重现步骤）
yarn build:h5

### What is expected?（期望的结果是什么？）
图标正常显示

### What is actually happening?（实际的结果是什么？）
不显示

### Remarks（补充说明）
将publicPath改为./会出现这个问题
![image](https://user-images.githubusercontent.com/69964024/203509068-050558ef-5674-4a1a-bd92-a5cb66677eaf.png)

**Comment by oasis-cloud** [comment]
taro项目需要使用 @nutui/nutui-react-taro

**Comment by dingff** [comment]
就是用的这个啊，看我demo

**Comment by oasis-cloud** [comment]
可以参考 Taro 社区的 Issue https://github.com/NervJS/taro/issues/4163#issuecomment-522831187
