### ISSUE TITLE
@nutui/nutui-react-taro 最新版本1.3.12 启动报错

### ISSUE THREAD

**Issue by houhoz** [jdf2e/nutui-react#488]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.3.12

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
v18.12.1

### Browser and its version（浏览器及其版本）
小程序

### System and its version（系统及其版本）
MacOS13

### Taro environmental information（taro 环境信息）
  Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7 
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/helper: 3.5.7 => 3.5.7 
      @tarojs/plugin-framework-react: 3.5.7 => 3.5.7 
      @tarojs/plugin-html: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-alipay: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-jd: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-qq: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-swan: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-tt: 3.5.7 => 3.5.7 
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7 
      @tarojs/react: 3.5.7 => 3.5.7 
      @tarojs/router: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/shared: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/taro-h5: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 
      react: ^18.0.0 => 18.2.0 

### Reproduction link（重现链接）
[github.com](https://github.com/houhoz/football-league)

### Steps to reproduce（重现步骤）
安装新版本@nutui/nutui-react-taro 
1.3.12

### What is expected?（期望的结果是什么？）
正常启动

### What is actually happening?（实际的结果是什么？）
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
{
  moduleIdentifier: '/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle/@nutui_nutui-react-taro.js',
  moduleName: './node_modules/.taro/weapp/prebundle/@nutui_nutui-react-taro.js',
  loc: '11039:0-46',
  message: "Module not found: Error: Can't resolve 'react-router-dom' in '/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle'",
  moduleId: './node_modules/.taro/weapp/prebundle/@nutui_nutui-react-taro.js',
  moduleTrace: [
    {
      originIdentifier: 'container entry (default) [["./react",{"import":["/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle/react.js"]}],["./@tarojs/taro",{"import":["/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle/@tarojs_taro.js"]}],["./@nutui/nutui-react-taro",{"import":["/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle/@nutui_nutui-react-taro.js"]}],["./react/jsx-runtime",{"import":["/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle/react_jsx-runtime.js"]}],["./@tarojs/runtime",{"import":["/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle/@tarojs_runtime.js"]}],["./@tarojs/plugin-html/dist/runtime",{"import":["/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle/@tarojs_plugin-html_dist_runtime.js"]}],["./@tarojs/plugin-framework-react/dist/runtime",{"import":["/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle/@tarojs_plugin-framework-react_dist_runtime.js"]}],["./@tarojs/plugin-platform-weapp/dist/runtime",{"import":["/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle/@tarojs_plugin-platform-weapp_dist_runtime.js"]}],["./react-dom",{"import":["/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle/react-dom.js"]}]]',
      originName: 'container entry',
      moduleIdentifier: '/Users/hyzhao/Code/Github/football-league/node_modules/.taro/weapp/prebundle/@nutui_nutui-react-taro.js',
      moduleName: './node_modules/.taro/weapp/prebundle/@nutui_nutui-react-taro.js',
      dependencies: [ { loc: './@nutui/nutui-react-taro[0]' } ],
      originId: 'webpack/container/entry/taro_app_library',
      moduleId: './node_modules/.taro/weapp/prebundle/@nutui_nutui-react-taro.js'
    }
  ],

**Comment by dingff** [comment]
yarn add react-router-dom@5.3.3

**Comment by houhoz** [comment]
Form目前不支持小程序吗

**Comment by gyt95** [comment]
![509ac61ecad67467e336aed80561a32](https://user-images.githubusercontent.com/23090676/203973128-4ac96819-d063-45e3-a920-af90b23a1cb0.png)

你们都没遇到这个问题吗？启动不了

**Comment by AnteeHub** [comment]
same with the 

> yarn add react-router-dom@5.3.3

it worked

亲测有效

**Comment by paytham** [comment]
> 

对的，不支持。现阶段手写吧。我们也用了，Form 组件有问题。

**Comment by paytham** [comment]
> ![509ac61ecad67467e336aed80561a32](https://user-images.githubusercontent.com/23090676/203973128-4ac96819-d063-45e3-a920-af90b23a1cb0.png)
> 
> 你们都没遇到这个问题吗？启动不了

使用 yarn add react-router-dom@^5.3.3，注意包版本。

**Comment by MirGhojam** [comment]
为什么都移除了对react-router-dom的依赖，编译时还会出现相应的错误呢？ @oasis-cloud

**Comment by oasis-cloud** [comment]
v1.4.0 已修复
