### ISSUE TITLE
项目在react-router v6版本的场景下，组件库Cell报错

### ISSUE THREAD

**Issue by awefeng** [jdf2e/nutui-react#506]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.3.13

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.0

### Browser and its version（浏览器及其版本）
版本 107.0.5304.121（正式版本） (x86_64)

### System and its version（系统及其版本）
macos 13.0.1

### Reproduction link（重现链接）
[github.com](https://github.com/awefeng/fe-multi-mobile/tree/feature-ui)

### Steps to reproduce（重现步骤）
1. 仓库分支feature-ui
2. 除去NutUI-react依赖包，安装安装依赖跑起来
3. 再安装NutUI-REACT包

### What is expected?（期望的结果是什么？）
期望能够兼容react-router v6

### What is actually happening?（实际的结果是什么？）
提示找不到useHistory 

### Remarks（补充说明）
react router v6已经舍弃了useHistory

**Comment by awefeng** [comment]
在NutUI-react中的dependencies显示声明一下依赖的react-router-dom版本。

更建议是去掉Cell的to功能，这个功能比较鸡肋，暴露出click用户自己处理就行了。

**Comment by zouyawen** [comment]
什么时候能解决， 我的项目里用的也是v6+版本，找不到useHistory。==

**Comment by oasis-cloud** [comment]
v1.4.0 已移除 react-router-dom 的依赖，cell 组件和 tabbar 组件去掉了对 to 属性的支持
