### ISSUE TITLE
希望react的特色组件能和vue版本同步

### ISSUE THREAD

**Issue by Hanchengluo** [jdf2e/nutui-react#509]
### What problem does this feature solve?（这个功能解决的问题）
看到vue版的特色组件的示例在react版本里没有，能否同步提供react版呢？例如https://nutui.jd.com/#/zh-CN/component/category

### What does the proposed API look like?（期望的 API）
看到vue版的特色组件的示例在react版本里没有，能否同步提供react版呢？例如https://nutui.jd.com/#/zh-CN/component/category

**Comment by oasis-cloud** [comment]
特色组件重新规划，改为商城域组件，目前规划有30多个，分为商品类，订单类，售后类，发票类，客服类等。预计2023Q1末完成建设

**Comment by xiaoyatong** [comment]
https://nutui.jd.com/biz/h5/react/1x/#/zh-CN/component/Category
这个？不过目前biz 不支持多端。
