### ISSUE TITLE
Calendar组件 startText和endText不生效，平铺时按钮不显示

### ISSUE THREAD

**Issue by code-username** [jdf2e/nutui-react#511]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.3.13

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.1

### Browser and its version（浏览器及其版本）
 107.0.5304.123

### System and its version（系统及其版本）
window10

### Taro environmental information（taro 环境信息）
👽 Taro v3.5.7

  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - D:\node\node.EXE
      Yarn: 1.22.19 - C:\Users\16510\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD
      npm: 8.11.0 - D:\node\npm.CMD

### Reproduction link（重现链接）
[github.com](https://github.com/code-username/myApp.git)

### Steps to reproduce（重现步骤）
https://github.com/code-username/myApp.git

### What is expected?（期望的结果是什么？）
Calendar组件 startText和endText应该正常生效，再组件中应该显示buutton按钮

### What is actually happening?（实际的结果是什么？）
Calendar组件 startText和endText应该未生效，再组件中并未显示button按钮

**Comment by xiaoyatong** [comment]
辛苦帮忙发下重现链接，现在链接打不开~

**Comment by code-username** [comment]
> https://github.com/code-username/myApp.git

**Comment by xiaoyatong** [comment]
startText 和 endText，需要一个数组。
试试以下的代码。

```
const [date7, setDate7] = useState<string[]>(['2021-12-23', '2021-12-26'])
const setChooseValue7 = (param: string) => {
  setDate7([...[param[0][3], param[1][3]]])
}

<Calendar
    poppable={false}
    defaultValue={date7}
    isAutoBackFill
    type="range"
    startText="开始"
    endText="结束"
    onChoose={setChooseValue7}
  />
```
