### ISSUE TITLE
Swiper轮播组件图片自适应

### ISSUE THREAD

**Issue by Hanchengluo** [jdf2e/nutui-react#518]
### What problem does this feature solve?（这个功能解决的问题）
组件地址:https://nutui.jd.com/react/#/zh-CN/component/swiper  ，使用示范代码后，图片都变形（但官方示范例子竟然不是变形的），现增加自适应的优化。
1：<img里增加一个style变量SwiperItem_img_style，值是width: '100%'，让图片宽度满屏， <img src={item} alt="" style={SwiperItem_img_style} />。2： <Swiper 的高度height值改为auto,让高度自适应 <Swiper height="auto"

### What does the proposed API look like?（期望的 API）
Swiper轮播组件图片自适应

**Comment by Hanchengluo** [comment]
官方示范例子是指官方网站上的预览

**Comment by xiaoyatong** [comment]
可以使用 Image 组件，里边有 ImageFit 模式，可调整样式。
Swiper 组件目前提供的是壳子。
