### ISSUE TITLE
Layout布局在flex布局下col换行后第一个元素和最后一个元素贴边了

### ISSUE THREAD

**Issue by code-username** [jdf2e/nutui-react#529]
1. [###](url) NutUI scenes（nutui 场景）

小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.3.13

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15

### Browser and its version（浏览器及其版本）
 108.0.5359.94

### System and its version（系统及其版本）
windows

### Taro environmental information（taro 环境信息）
 Taro v3.5.7

  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - D:\node\node.EXE
      Yarn: 1.22.19 - C:\Users\16510\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD
      npm: 8.11.0 - D:\node\npm.CMD

### Reproduction link（重现链接）
[github.com](https://github.com/code-username/code-username.git)

### Steps to reproduce（重现步骤）
直接运行小程序，然后点击展开弹出层

### What is expected?（期望的结果是什么？）
Layout布局在flex布局下应正常平分父元素大小

### What is actually happening?（实际的结果是什么？）
Layout布局在flex布局下应没有达到预期

**Comment by oasis-cloud** [comment]
辛苦提供可复现 demo，或者补充截图等信息
