### ISSUE TITLE
Layout布局在flex布局下col换行后第一个元素和最后一个元素贴边了

### ISSUE THREAD

**Issue by code-username** [jdf2e/nutui-react#530]
1. [###](url) NutUI scenes（nutui 场景）

小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.3.13

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15

### Browser and its version（浏览器及其版本）
 108.0.5359.94

### System and its version（系统及其版本）
windows

### Taro environmental information（taro 环境信息）
 Taro v3.5.7

  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.1 - D:\node\node.EXE
      Yarn: 1.22.19 - C:\Users\16510\AppData\Roaming\npm\node_modules\yarn\bin\yarn.CMD
      npm: 8.11.0 - D:\node\npm.CMD

### Reproduction link（重现链接）
[github.com](https://github.com/code-username/code-username.git)

### Steps to reproduce（重现步骤）
直接运行小程序，然后点击展开弹出层

### What is expected?（期望的结果是什么？）
Layout布局在flex布局下应正常平分父元素大小
![image](https://user-images.githubusercontent.com/64359368/206437793-de9661b3-0603-4b3d-b472-1f02a90d53c4.png)

### What is actually happening?（实际的结果是什么？）
Layout布局在flex布局下应没有达到预期
![image](https://user-images.githubusercontent.com/64359368/206437593-ad3931f2-4fdf-4098-a99b-b1f95043b6c9.png)

 ###   #@**#[](url)**

**Comment by oasis-cloud** [comment]
辛苦描述下如何使用 layout 组件，可提供最小可复现 demo 吗

**Comment by code-username** [comment]
> 辛苦描述下如何使用 layout 组件，可提供最小可复现 demo 吗

      <Row gutter={10} type="flex" justify="space-around" wrap="wrap">
            <Col span="8">
                <div className="flex-content">span:6</div>
            </Col>
            <Col span="8">
                <div className="flex-content">span:6</div>
            </Col>
                 <Col span="8">
                <div className="flex-content">span:6</div>
            </Col>
                 <Col span="8">
                <div className="flex-content">span:6</div>
            </Col>
                 <Col span="8">
                <div className="flex-content">span:6</div>
            </Col>       <Col span="8">
                <div className="flex-content">span:6</div>
            </Col>
        </Row>

**Comment by code-username** [comment]
> 辛苦描述下如何使用 layout 组件zhi


> 辛苦描述下如何使用 layout 组件，可提供最小可复现 demo 吗

加了gutter属性就会出现这样的问题

**Comment by oasis-cloud** [comment]
layout 是按照 24 个单元进行划分的，gutter 是元素间的间距。
