### ISSUE TITLE
Taro版本支持基于 ES modules 的 tree shaking 按需加载

### ISSUE THREAD

**Issue by ljianc** [jdf2e/nutui-react#538]
### What problem does this feature solve?（这个功能解决的问题）
完全按照[官方文档](https://nutui.jd.com/react/#/zh-CN/guide/starttaro-react)配置后，
使用import { Button } from '@nutui/nutui-react-taro';
仅仅引用一个Button 组件，就用导入  986KB 的js文件, 没有按需加载的效果

### What does the proposed API look like?（期望的 API）
希望支持按需加载

**Comment by oasis-cloud** [comment]
可以提供 taro 的配置文件吗，或最小可复现的 demo

**Comment by oasis-cloud** [comment]
Button 组件中支持 icon 的显示，所以会将 iconfont 资源打包进来

**Comment by ljianc** [comment]
![1670834493395](https://user-images.githubusercontent.com/10055508/206999976-8b769131-3529-40fb-82a9-0470c091005e.png)
这个是[生成的文件](https://github.com/jdf2e/nutui-react/files/10206184/vendors-node_modules_taro_weapp_prebundle_nutui_nutui-react-taro_js.txt)
这个是[Taro配置文件](https://github.com/jdf2e/nutui-react/files/10206194/index.js.txt)

就是完全按照https://nutui.jd.com/react/#/zh-CN/guide/starttaro-react 配置的，
就放一个button。您新建个空项目试一下也可以。

**Comment by oasis-cloud** [comment]
是运行在 watch 模式下吗？实际应该看 build 模式下的产物

**Comment by ljianc** [comment]
![1675409676855](https://user-images.githubusercontent.com/10055508/216539589-a4f94d83-f51e-4588-a3a2-55df09d3af32.png)

watch 模式1M左右，build 模式380K左右，您那边写个hello world试一下吧

**Comment by oasis-cloud** [comment]
watch 模式下，taro 会对 node_modules 进行依赖预编译，可参考 https://docs.taro.zone/docs/prebundle。

**Comment by ljianc** [comment]
1 watch 模式下依赖预编译正常也是按需加载的
2 即便是在build的模式，仅引入一个button也不至于380K左右吧
