### ISSUE TITLE
react组件库的cell 用到了react-router-dom的useHistory。但项目用的是v6+。提示找不到useHistory

### ISSUE THREAD

**Issue by zouyawen** [jdf2e/nutui-react#543]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.3.14

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.16.1

### Browser and its version（浏览器及其版本）
Chrome（86.0.4240.198）

### System and its version（系统及其版本）
windows

### Reproduction link（重现链接）
[github.com](https://github.com/awefeng/fe-multi-mobile)

### Steps to reproduce（重现步骤）
react组件库的cell 用到了react-router-dom的useHistory。但项目用的是v6+。提示找不到useHistory

### What is expected?（期望的结果是什么？）
组件库不要使用react-router-dom的useHistory或者升级到6版本

### What is actually happening?（实际的结果是什么？）
提示export 'useHistory' (imported as 'useHistory') was not found in 'react-router-dom'

**Comment by Mickxuanyuan** [comment]
router V6 用不了， react 都依赖18+了，router升下级还是很合理的 哈哈，实在不行在dependencies 加个router依赖，不要依赖开发者本地的router。
希望快点解决。 mark

**Comment by oasis-cloud** [comment]
可安装 1.4.0，1.4.0 版本移除了 react-router-dom 的依赖
