### ISSUE TITLE
Bug: 受控模式下 Range 组件未兼容 modelValue 值为  0 时的情况

### ISSUE THREAD

**Issue by AnteeHub** [jdf2e/nutui-react#547]
### NutUI scenes（nutui 场景）
H5 + 小程序

### NutUI-react version（nutui-react 版本）
1.3.15

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
v16.14.2

### Browser and its version（浏览器及其版本）
Microsoft Edge 版本 108.0.1462.54 (正式版本) (arm64)

### System and its version（系统及其版本）
MacOS(12.6)

### Taro environmental information（taro 环境信息）
```sh
Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7 
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/helper: 3.5.7 => 3.5.7 
      @tarojs/plugin-framework-react: 3.5.7 => 3.5.7 
      @tarojs/plugin-html: ^3.5.7 => 3.5.8 
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7 
      @tarojs/plugin-react-devtools: ^3.5.7 => 3.5.8 
      @tarojs/react: 3.5.7 => 3.5.7 
      @tarojs/router: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/shared: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/taro-h5: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 
      react: ^18.0.0 => 18.2.0 
```

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/nutui-react-range-demo-v8r4kg?file=/src/App.tsx)

### Steps to reproduce（重现步骤）
1. 导入 `<Range/>` 组件
2. 设置最大值为 `10`，最小值为 `-10`，增加两个按钮和设置 `modelValue` 值的逻辑
3. 设置某个场景下 `<Range/>` 的 `modelValue` 值为 0， `<Range/>` 视图没有发生变化，但此时 `modelValue` 的值是正确的

如下：

```jsx

import React, { useState } from "react";
import { Range, Button } from "@nutui/nutui-react-taro";

const RangeApp = () => {
  const [value, setValue] = useState(0);
  return (
    <>
      <Button onClick={() => setValue(value - 5)}>-</Button>
      <Button onClick={() => setValue(value + 5)}>+</Button>
      <Range modelValue={value} min={-10} max={10} />
    </>
  );
};

export default RangeApp;

```

### What is expected?（期望的结果是什么？）
设置 `modelValue` 值为 0 时，`<Range/>` 组件的位置应该发生相应变化。

### What is actually happening?（实际的结果是什么？）
设置 `modelValue` 值为 0 时，`<Range/>` 组件的位置并未发生任何变化，直到 `modelValue` 的值不为 0 后，组件的位置才移动到相应的数值位置。如下方视频所示：

https://user-images.githubusercontent.com/55703989/208568602-8b4d4f5e-55e7-44e8-a3bc-96a8b3a5f92a.mp4

### Remarks（补充说明）
nutui-react 和 nutui-taro-react 中的 Range 组件逻辑均有以下类似的逻辑：

```jsx
  useEffect(() => {

    // fixme: 下面的逻辑判断未考虑到 0 
    if (modelValue) {
      if (!range && (modelValue < min || modelValue > max)) {
        SetInitValue(0)
        toastShow(`${modelValue} ${locale.range.rangeText}`)
        return
      }
      SetInitValue(modelValue)
    }
  }, [modelValue])
```
对于 `modelValue` 转化为 Boolean 的判断并未考虑到值为 0 的情况。

**Comment by AnteeHub** [comment]
> ### NutUI scenes（nutui 场景）
> H5（@nutui/nutui-react）
> 
> ### NutUI-react version（nutui-react 版本）
> 1.3.15
> 
> ### React version（react 版本）
> 18.2.0
> 
> ### Operating environment（运行环境）
> dev:h5
> 
> ### Citation method（引用方式）
> npm
> 
> ### Node version（node 版本）
> v16.14.2
> 
> ### Browser and its version（浏览器及其版本）
> Microsoft Edge 版本 108.0.1462.54 (正式版本) (arm64)
> 
> ### System and its version（系统及其版本）
> MacOS(12.6)
> 
> ### Reproduction link（重现链接）
> [codesandbox.io](https://codesandbox.io/s/nutui-react-range-demo-v8r4kg?file=/src/App.tsx)
> 
> ### Steps to reproduce（重现步骤）
> 1. 导入 `<Range/>` 组件
> 2. 设置最大值为 `10`，最小值为 `-10`，增加两个按钮和设置 `modelValue` 值的逻辑
> 3. 设置某个场景下 `<Range/>` 的 `modelValue` 值为 0， `<Range/>` 视图没有发生变化，但此时 `modelValue` 的值是正确的
> 
> 如下：
> 
> ```js
> import React, { useState } from "react";
> import { Range, Button } from "@nutui/nutui-react-taro";
> 
> const RangeApp = () => {
>   const [value, setValue] = useState(0);
> 
>   const handleSettingValue = (val) => {
>     return val > 10 ? 0 : val;
>   };
> 
>   return (
>     <>
>       <Button onClick={() => setValue(handleSettingValue(value - 5))}>-</Button>
>       <Button onClick={() => setValue(handleSettingValue(value + 5))}>+</Button>
>       <Range modelValue={value} min={-10} max={10} />
>     </>
>   );
> };
> 
> export default RangeApp;
> ```
> 
> ### What is expected?（期望的结果是什么？）
> 设置 `modelValue` 值为 0 时，并未发生任何变化。
> 
> ### What is actually happening?（实际的结果是什么？）
> 设置 `modelValue` 值为 0 时，`<Range/>` 组件的位置应该发生相应变化。
> 
> ### Remarks（补充说明）
> nutui-react 和 nutui-taro-react 中的 Range 组件逻辑均有以下类似的逻辑：
> 
> ```js
>   useEffect(() => {
> 
>     // fixme: 下面的逻辑判断未考虑到 0 
>     if (modelValue) {
>       if (!range && (modelValue < min || modelValue > max)) {
>         SetInitValue(0)
>         toastShow(`${modelValue} ${locale.range.rangeText}`)
>         return
>       }
>       SetInitValue(modelValue)
>     }
>   }, [modelValue])
> ```
> 
> 对于 `modelValue` 转化为 Boolean 的判断并未考虑到值为 0 的情况。

此外，这个问题可能会影响到使用了 `<Range/>` 的另外一个 nutui-react 组件： type 为 `progress` 的 `<Audio/>` 组件

**Comment by xiaoyatong** [comment]
已修复，下个版本。
