### ISSUE TITLE
Taro 环境 SearchBar onSearch 无法触发

### ISSUE THREAD

**Issue by hyyqcweb** [jdf2e/nutui-react#548]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.3.15

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.17.0

### Browser and its version（浏览器及其版本）
108.0.5359.98

### System and its version（系统及其版本）
macos 12.6.2

### Taro environmental information（taro 环境信息）
3.5.7

### Steps to reproduce（重现步骤）
<SearchBar
          actionText='搜索'
          onSearch={() => onSubmit(value)}
/>

### What is expected?（期望的结果是什么？）
onSearch 能通过 enter 或者 手机键盘搜索触发

### What is actually happening?（实际的结果是什么？）
无法触发

**Comment by xiaoyatong** [comment]
已修复。
