### ISSUE TITLE
@nutui/nutui-react-taro 支持上传非图片文件

### ISSUE THREAD

**Issue by aukufddxxyy** [jdf2e/nutui-react#561]
### What problem does this feature solve?（这个功能解决的问题）
https://nutui.jd.com/react/#/zh-cn/component/uploader-taro
使用taro时，官方示例中的所有uploader组件都只能选择图片上传。能否支持上传非图片文件。

### What does the proposed API look like?（期望的 API）
希望可以自定义accept参数，支持上传非图片类型文件。

**Comment by AnteeHub** [comment]
如果是微信小程序的话，默认是可以通过 uploader 上传视频和图片两种附件的，但是他们调用的 api 不相同。微信小程序还有一个上传其他类型文件的 api ，但是表现和 uploader 不相同（在真机上不会调用相册或者文件夹，而是会在最近聊天记录里选取聊天文件，并且 accept 参数在这个 api 中不能造成任何影响）。所以有时候可以看得到一些面向小程序的库并不会去做 uploader 相关的封装功能

**Comment by rendongsc** [comment]
vantui的Uploader支持，nutui-react-taro能支持的更好。
[https://antm-js.gitee.io/vantui/#/uploader](url)，accept="all"

**Comment by rendongsc** [comment]
nutui-react-taro Uploader应该根据accept去选择用Taro.chooseImage还是Taro.chooseMessageFile，现在只有Taro.chooseImage，希望可以改进一下。
