### ISSUE TITLE
Picker 官方demo滚动报错

### ISSUE THREAD

**Issue by Mickxuanyuan** [jdf2e/nutui-react#562]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.0

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.1

### Browser and its version（浏览器及其版本）
Chrome 版本 108.0.5359.124

### System and its version（系统及其版本）
Macos

### Reproduction link（重现链接）
[nutui.jd.com/react/](https://nutui.jd.com/react/#/zh-CN/component/picker)

### Steps to reproduce（重现步骤）
官方demo

### What is expected?（期望的结果是什么？）
不报错

### What is actually happening?（实际的结果是什么？）
Unable to preventDefault inside passive event listener invocation.

**Comment by oasis-cloud** [comment]
如果是网站中的 demo 的话，可以用 https://nutui.jd.com/react/demo.html#/Picker 访问，开启模拟器。目前并未发现报错信息。
可以明确指出是第几个demo 报错吗？
