### ISSUE TITLE
Audio 组件在 Taro 小程序开发环境下不能正常工作

### ISSUE THREAD

**Issue by AnteeHub** [jdf2e/nutui-react#564]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.1

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
Microsoft Edge 版本 108.0.1462.54 (正式版本) (arm64)

### System and its version（系统及其版本）
MacOS(12.6)

### Taro environmental information（taro 环境信息）
```
👽 Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.7 => 3.5.7 
      @tarojs/components: 3.5.7 => 3.5.7 
      @tarojs/helper: 3.5.7 => 3.5.7 
      @tarojs/plugin-framework-react: 3.5.7 => 3.5.7 
      @tarojs/plugin-html: ^3.5.7 => 3.5.8 
      @tarojs/plugin-platform-weapp: 3.5.7 => 3.5.7 
      @tarojs/plugin-react-devtools: ^3.5.7 => 3.5.8 
      @tarojs/react: 3.5.7 => 3.5.7 
      @tarojs/router: 3.5.7 => 3.5.7 
      @tarojs/runtime: 3.5.7 => 3.5.7 
      @tarojs/shared: 3.5.7 => 3.5.7 
      @tarojs/taro: 3.5.7 => 3.5.7 
      @tarojs/taro-h5: 3.5.7 => 3.5.7 
      @tarojs/webpack5-runner: 3.5.7 => 3.5.7 
      babel-preset-taro: 3.5.7 => 3.5.7 
      eslint-config-taro: 3.5.7 => 3.5.7 
      react: ^18.0.0 => 18.2.0 
```

### Reproduction link（重现链接）
[github.com](https://github.com/AnteeHub/nutui-react-taro-present)

### Steps to reproduce（重现步骤）
- 使用 Taro cli 按照官方指引，初始化小程序
- 引入 `@nutui/nutui-react-taro` 的 `<Audio/>` 组件，填入 url，选择 `type="progress"`

### What is expected?（期望的结果是什么？）
1. 点击暂停、播放按钮前后，进度条和时间能够根据音频变化而做出相应改变
2. 播放完成后，进度条和时间能够置零
3. 点击暂停按钮后再点击播放按钮，恢复播放时进度条能够正常变化
4. 组件卸载后音频能够停止播放

### What is actually happening?（实际的结果是什么？）
1. 点击暂停、播放按钮后，进度条偶尔会出现没有变化的情况
2. 播放完成后，会出现类似于 `"21 listeners of event 16723735203950.12147774576404435_onAudioStateChange_pause have been added, possibly causing memory leak."` 的警告提示
3. 切换到其他页面后，组件的音频仍然在后台继续播放，无法控制其停止

**Comment by AnteeHub** [comment]
https://user-images.githubusercontent.com/55703989/210048351-abc16df6-bf68-4afc-ae36-258189d56ca9.mp4

**Comment by oasis-cloud** [comment]
@nutui/nutui-react-taro 的 <Audio/> 组件，不支持选择 type="progress"

**Comment by libin0824** [comment]
您好，实际效果以真机为准，麻烦提供下真机演示的视频。对比看上述问题是否还存在。

**Comment by AnteeHub** [comment]
https://user-images.githubusercontent.com/55703989/210510649-670d27f1-9656-4c9c-aad0-49ab2a8f0586.mp4

这是我在安卓手机上用微信开发者工具进行的真机调试录屏，其表现与在 Mac 上的微信开发者预览工具的表现基本相同。开发调试相关的平台参数如下：

- 微信开发者工具 Stable 1.06.2210310
- 微信小程序调试基础库 2.29.1
- 微信版本 Version 8.0.31
- 安卓手机系统 MIUI 13.0.10 

调试所用的基础代码仓库来自 https://github.com/AnteeHub/nutui-react-taro-present

 @libin0824

**Comment by AnteeHub** [comment]
> @nutui/nutui-react-taro 的 组件，不支持选择 type="progress"

https://github.com/jdf2e/nutui-react/blob/main/src/packages/audio/audio.taro.tsx

**Comment by oasis-cloud** [comment]
推荐使用 Taro 提供的 Audio 进行开发
