### ISSUE TITLE
BackTop返回顶部不显示

### ISSUE THREAD

**Issue by hhy965** [jdf2e/nutui-react#569]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.1

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
MacOS(10.15)

### Reproduction link（重现链接）
[codehouse.jd.com/](https://codehouse.jd.com/?source=share&type=react&mainJs=Ly9pbXBvcnQgVkNvbnNvbGUgZnJvbSAidmPGDyI7Ci8vdmFyIHbIID0gbmV3yS8oKTsKx0JSZWFjdMc/csQMIs4bRE9NzB4tZG9tyiInQG51dHVpL8UGLcUhL2Rpc3Qvc3R5bGUuY3NzJ8grQXBwx0guL2FwcC5qc3jKSMcUc2NzcyI7Csh4LnJlbmRlcigKICA8QXBwLz4sCiAgZG9jdW1lbnQuZ2V0RWxlxAtCeUlkKCJhcHAiKQopOw==&appValue=aW1wb3J0ICBSZWFjdCBmcm9tICJyxAwiOwrHHHsgQmFja1RvcCB9xiEnQG51dHVpL8UGLcUuJzsKCmNvbnN0IEFwcCA9ICgpID0+IHsKICDGFmNlbGxTdHlsZSA9xRYgIGhlaWdodDogJzQ2cHgnLMUUbGluZUjTGG1hcmdpbjogJzE1cHggYXV0byAyMMkecGFkZGluZ0xlZsQ3Mco3YmFja2dyb3VuZENvbG9yOiAnI2ZmZscdY8gTNjY2yDBvcmRlclJhZGl1czogJzfKSW94U2hhZG93OiAnMCAxcHggN3B4ICNlZGVlZjHHJGZvbnRTaXpl5ACDM8c6fQogIHJldHVybiAoxSU8PsYHZGl2IGNsYXNzTmFtZT0iZGVtbyIgaWQ9ImVsSWQixiXUKXRleHQtZGF0YSIgc+QBTj176QFZfT7miJHmmK/mtYvor5XmlbDmja4xPC9kaXbfT99Py08y30/fT9BPM99P30/QTzTfT99P0E8130/fT9BPNt9P30/QTzffT99P0E8430/fT9BPOd9P30/QTzEw31DfUNFQ/wMY31DSUP8DGd9Q0lD/AxrfUNJQ/wMb31DSUP8DHN9Q0lD/Ax3fUNJQ/wMe31DSUP8DH99Q0lD/AyDfUNFQMv8DIN9Q0lD/AyDfUNJQ/wMg31DSUP8DIN9Q0lDxAyDoCPEgL8YVyyA8xRMpOwp9OwpleOUJIWRlZmF1bOUI+zsK&scssValue=)

### Steps to reproduce（重现步骤）
以下为官方文档代码，不会显示返回顶部，返回顶部的功能没有办法使用
import  React from "react";
import { BackTop } from '@nutui/nutui-react';

const App = () => {
  const cellStyle = {
    height: '46px',
    lineHeight: '46px',
    margin: '15px auto 20px',
    paddingLeft: '16px',
    backgroundColor: '#fff',
    color: '#666',
    borderRadius: '7px',
    boxShadow: '0 1px 7px #edeef1',
    fontSize: '13px',
  }
  return (
    <>
    <div className="demo" id="elId">
        <div className="text-data" style={cellStyle}>我是测试数据1</div>
        <div className="text-data" style={cellStyle}>我是测试数据2</div>
        <div className="text-data" style={cellStyle}>我是测试数据3</div>
        <div className="text-data" style={cellStyle}>我是测试数据4</div>
        <div className="text-data" style={cellStyle}>我是测试数据5</div>
        <div className="text-data" style={cellStyle}>我是测试数据6</div>
        <div className="text-data" style={cellStyle}>我是测试数据7</div>
        <div className="text-data" style={cellStyle}>我是测试数据8</div>
        <div className="text-data" style={cellStyle}>我是测试数据9</div>
        <div className="text-data" style={cellStyle}>我是测试数据10</div>
        <div className="text-data" style={cellStyle}>我是测试数据11</div>
        <div className="text-data" style={cellStyle}>我是测试数据12</div>
        <div className="text-data" style={cellStyle}>我是测试数据13</div>
        <div className="text-data" style={cellStyle}>我是测试数据14</div>
        <div className="text-data" style={cellStyle}>我是测试数据15</div>
        <div className="text-data" style={cellStyle}>我是测试数据16</div>
        <div className="text-data" style={cellStyle}>我是测试数据17</div>
        <div className="text-data" style={cellStyle}>我是测试数据18</div>
        <div className="text-data" style={cellStyle}>我是测试数据19</div>
        <div className="text-data" style={cellStyle}>我是测试数据20</div>
        <div className="text-data" style={cellStyle}>我是测试数据21</div>
        <div className="text-data" style={cellStyle}>我是测试数据22</div>
        <div className="text-data" style={cellStyle}>我是测试数据23</div>
        <div className="text-data" style={cellStyle}>我是测试数据24</div>
        <BackTop  />
    </div>
    </>
  );
};
export default App;

### What is expected?（期望的结果是什么？）
尽快修复吧

### What is actually happening?（实际的结果是什么？）
还没修复

**Comment by vickyYE** [comment]
您好，您是在本地起服务看的这个组件失效了吗？还是仅是在网页上查看的线上调试代码？
