### ISSUE TITLE
input onChange方法触发死循环

### ISSUE THREAD

**Issue by YYBT** [jdf2e/nutui-react#579]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.2

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.1

### Browser and its version（浏览器及其版本）
 chrome108.0.5359.124

### System and its version（系统及其版本）
MacOS(12.4)

### Reproduction link（重现链接）
[nutui.jd.com/react/](https://nutui.jd.com/react/#/zh-CN/component/input)

### Steps to reproduce（重现步骤）
const [state, setState] = useState({
    event: ""
  });
  const change = (value, event) => {
    console.log("change: ", value, event);
    setState({
      event:value
    })
  };
  
      <Input
        label="点击"
        placeholder="点击"
        defaultValue={state.event}
        onChange={change}
      />

### What is expected?（期望的结果是什么？）
显示输入值

### What is actually happening?（实际的结果是什么？）
 Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by zouyawen** [comment]
我也碰到这问题
