### ISSUE TITLE
form和tabs功能增加

### ISSUE THREAD

**Issue by Hincex** [jdf2e/nutui-react#585]
### What problem does this feature solve?（这个功能解决的问题）
1. `form`希望能增加`defaultValues`、`useForm`等功能，目前的form功能实在太少了
2. `tabs`增加滑动切换功能，目前我是直接用touch事件来手动修改`Tabs`的`value`来实现的，希望官方能直接支持
3. `<TabPane/>`的title渲染希望能放到`<TabPane/>`上去，在`<Tabs/>`上用`titleNode`这种方式有点太诡异了，而且下面遍历一次，上面也遍历一次，不太美观，其它类似的node写法也希望能优化一下，希望可以和`antd`那种靠拢，相对会舒服一些，也更容易被接受
3. 子组件希望能放到一起，比如`<TabPane/>`希望是`<Tabs.TabPane/>`这种调用方式

### What does the proposed API look like?（期望的 API）
```
const form=Form.useForm();
<Form form={form} defaultValues={{a:1}}/>
```
``` 
<Tabs>
  {tabs.map((tab,tabIndex)=>
      <Tabs.TabPane key={tab.key} paneKey={tab.key} title={tab.title}>
        {tab.children}
      </Tabs.TabPane>)
   }
</Tabs>
```

**Comment by xiaoyatong** [comment]
开发中~

**Comment by Vincehx97** [comment]
> 开发中~



> 开发中~

好的~辛苦了

**Comment by junjun666** [comment]
form 在v1.4.8版本中已经新增defaultValues、useForm等功能

**Comment by junjun666** [comment]
form 在v1.4.8版本中已经新增defaultValues、useForm等功能

**Comment by ljianc** [comment]
1 Tabs 扩展确实很别扭，建议直接参考[antd](https://mobile.ant.design/zh/components/tabs)，同时增加stretch参数表示选项卡头部是否拉伸

2 所有其他组件的可扩展点，也建议尽量接收ReactNode类型的参数，尽量避免接收string类型参数失去可扩展性

**Comment by xiaoyatong** [comment]
问题1.form希望能增加defaultValues、useForm等功能，目前的form功能实在太少了
已支持。

**Comment by xiaoyatong** [comment]
4已完成，1.4.9 版本号。

**Comment by Jairwin-L** [comment]
> 问题1.form希望能增加defaultValues、useForm等功能，目前的form功能实在太少了 已支持。

请问这部分文档更新了嘛？
