### ISSUE TITLE
Tabs 组件体验问题

### ISSUE THREAD

**Issue by Seauning** [jdf2e/nutui-react#591]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.3.11

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
17.9.1

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
windows11

### Taro environmental information（taro 环境信息）
👽 Taro v3.5.7

  Taro CLI 3.5.7 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 17.9.1 - C:\Program Files\nodejs\node.EXE
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[github.com](https://github.com/Seauning/qingting-food-club-fronted/tree/feat-nutui-issue-tabs)

### Steps to reproduce（重现步骤）
1. 微信小程序开启 navigationStyle: 'custom' 配置
2. 切换 tab 需要回到内容区域顶部

### What is expected?（期望的结果是什么？）
1. 仅 Tabs 内容区域滚动
2. 切换 tab 回到内容区域顶部

### What is actually happening?（实际的结果是什么？）
1. 内容溢出时滚动 Tabs 会同步滚动
2. 滚动距离维持不变

**Comment by xiaoyatong** [comment]
帮忙发一下demo，目前demo打开404
