### ISSUE TITLE
Table 组件是否可以增加一个Index的列

### ISSUE THREAD

**Issue by leida1983** [jdf2e/nutui-react#592]
### What problem does this feature solve?（这个功能解决的问题）
自动生成一个序号

### What does the proposed API look like?（期望的 API）
{
							valueType: 'indexBorder',
							dataIndex: 'Index',
							title: '序号',
							fixed: 'left',
							align: 'center',
							width: 50,
							search: false,
						},

可以直接参考antd 的  ProTable

**Comment by libin0824** [comment]
您好，麻烦提供下期望功能的示例截图或者更详细的说明。

**Comment by oasis-cloud** [comment]
序号可以维护在数据层
