### ISSUE TITLE
Overlay 遮罩层 不能锁定背景 lockScroll 设置后无效

### ISSUE THREAD

**Issue by gooddaddy** [jdf2e/nutui-react#610]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.4

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
v16.14.2

### Browser and its version（浏览器及其版本）
ios 端小程序

### System and its version（系统及其版本）
ios 15.3.1

### Reproduction link（重现链接）
[https://nutui.jd.com/react](https://nutui.jd.com/react)

### Steps to reproduce（重现步骤）
官方demo修改 lockScroll={true} ,点击demo的弹出 Overlay 遮罩层 

### What is expected?（期望的结果是什么？）
可以锁定背景

### What is actually happening?（实际的结果是什么？）
背景会滚动

### Remarks（补充说明）
很多有遮罩的组件都存在背景跟随滚动的情况

**Comment by gooddaddy** [comment]
找到临时的解决方法：
```
      <View catchMove>
        <Overlay visible={visible} onClick={onClose} lockScroll={true} />
      </View>
```

**Comment by wanglihuaya** [comment]
> 找到临时的解决方法：
> 
> ```
>       <View catchMove>
>         <Overlay visible={visible} onClick={onClose} lockScroll={true} />
>       </View>
> ```

这就是taro 官方的解决 方案
