### ISSUE TITLE
SearchBar 搜索栏组件中 将padding设置为0，显示错乱

### ISSUE THREAD

**Issue by VanHoth** [jdf2e/nutui-react#612]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.4

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.16

### Browser and its version（浏览器及其版本）
微信1.06

### System and its version（系统及其版本）
window

### Taro environmental information（taro 环境信息）
 Taro v3.5.12

  Taro CLI 3.5.12 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\admin\AppData\Roaming\npm\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[github.com](https://github.com/VanHoth/searchbar_NutUI_issue)

### Steps to reproduce（重现步骤）
直接运行，主界面就是会出现 searchbar ，会看到左边图案和搜索框重叠

### What is expected?（期望的结果是什么？）
左边的图标和搜索框重叠在一起了

### What is actually happening?（实际的结果是什么？）
正确显示

### Remarks（补充说明）
想上传图片却无法上传

**Comment by Ymm0008** [comment]
https://github.com/jdf2e/nutui-react/pull/632  问题已修复 @VanHoth

**Comment by VanHoth** [comment]
你好，我是小范，你的邮件我已经收到了
