### ISSUE TITLE
ellipsis文本省略组件在多列表的情况下会很卡，看了源码，比如有1000个节点的列表，渲染速度会很慢

### ISSUE THREAD

**Issue by PuffMeow** [jdf2e/nutui-react#616]
### What problem does this feature solve?（这个功能解决的问题）
可以尝试一下优化在列表场景下的性能

### What does the proposed API look like?（期望的 API）
内部优化性能

**Comment by oasis-cloud** [comment]
辛苦提供下可复现的 Demo，以便 issue 的跟进处理
