### ISSUE TITLE
Image组件刷新或切换中英文demo中图片展示不正确

### ISSUE THREAD

**Issue by yangjinjun3** [jdf2e/nutui-react#624]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.5

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
MacOS(12.6)

### Reproduction link（重现链接）
[nutui.jd.com/h5/react/1x/](https://nutui.jd.com/h5/react/1x/#/en-US/component/image)

### Steps to reproduce（重现步骤）
1、刷新https://nutui.jd.com/h5/react/1x/#/en-US/component/image
2、切换中英文

### What is expected?（期望的结果是什么？）
执行刷新或切换中英文等动作，图片不变

### What is actually happening?（实际的结果是什么？）
有个loading图片覆盖在了上面

**Comment by oasis-cloud** [comment]
loading 图片无法去除主要是因为 img 的 onload 事件早于 useEffect ，现已更新 onload 的执行时机
