### ISSUE TITLE
Taro版按需加载问题

### ISSUE THREAD

**Issue by ljianc** [jdf2e/nutui-react#629]
### What problem does this feature solve?（这个功能解决的问题）
 问题同 https://github.com/jdf2e/nutui-react/issues/538  ，那个被关闭了

1 watch 模式，依赖预编译正常也是按需加载的，和PreBundle 关系不大
2 build的模式，仅引入一个button也不至于380K左右

### What does the proposed API look like?（期望的 API）
实现按需加载效果

**Comment by oasis-cloud** [comment]
可以查看下面 Demo 仓库的 npm run build:weapp 后的结果。
https://github.com/oasis-cloud/taro-demo.git

**Comment by ljianc** [comment]
你运行后的大小是多少？ 我这有依赖下载不下来

**Comment by oasis-cloud** [comment]
npm run build:weapp 的产物中，dist/vendors.js 15KB, pages/index/index.js 5KB
npm run dev:weapp 的 prebundle 不会进行 tree shaking, taro 的 dev 模式可以查阅 taro 文档。

**Comment by ljianc** [comment]
我又试了一下，禁用掉prebundle确实如你所说   (我之前build模式也显式开启了prebundle)

还有个问题，这个文件占用了100K左右，我看里面很多图标，还可以再优化一下

![1675928275017](https://user-images.githubusercontent.com/10055508/217747685-dfb3a135-c538-4276-8cbd-77f59d76c2f6.png)

**Comment by oasis-cloud** [comment]
icon 这块正在改版开发中

**Comment by ljianc** [comment]
好的，辛苦
