### ISSUE TITLE
video 安卓手机 提示 play() can only be initiated by a user gesture

### ISSUE THREAD

**Issue by duanzb0** [jdf2e/nutui-react#633]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.5

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.17.6

### Browser and its version（浏览器及其版本）
微信浏览器

### System and its version（系统及其版本）
windows

### Reproduction link（重现链接）
[559-aaaa.zwjiandu.cn/](https://559-aaaa.zwjiandu.cn/#/pages/vplay/index?id=10061&eid=100610004)

### Steps to reproduce（重现步骤）
自动播放视频 黑屏不播放

### What is expected?（期望的结果是什么？）
正常播放

### What is actually happening?（实际的结果是什么？）
无法播放

**Comment by junjun666** [comment]
您这边是使用taro开发的么？

**Comment by junjun666** [comment]
<img width="1523" alt="image" src="https://user-images.githubusercontent.com/35680677/217787682-078c8abe-8355-4442-82b2-e20e429f7605.png">
您这边是taro开发的是么，我看标签里也没有引用与nutui相关(比如nut-video-player)的标签呢？
可以方便提供下demo么
