### ISSUE TITLE
Uploader上传图片defaultFileList不生效

### ISSUE THREAD

**Issue by programmerlgs** [jdf2e/nutui-react#645]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.6

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
v14.18.0

### Browser and its version（浏览器及其版本）
109.0.5414.119

### System and its version（系统及其版本）
11.6

### Taro environmental information（taro 环境信息）
 Taro v3.5.5

  Taro CLI 3.5.5 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.19.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.5 => 3.5.5 
      @tarojs/components: 3.5.5 => 3.5.5 
      @tarojs/components-react: ^3.5.6 => 3.5.6 
      @tarojs/helper: 3.5.5 => 3.5.5 
      @tarojs/plugin-framework-react: 3.5.5 => 3.5.5 
      @tarojs/plugin-html: ^3.5.7 => 3.5.11 
      @tarojs/plugin-platform-alipay: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-jd: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-qq: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-swan: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-tt: 3.5.5 => 3.5.5 
      @tarojs/plugin-platform-weapp: 3.5.5 => 3.5.5 
      @tarojs/react: 3.5.5 => 3.5.5 
      @tarojs/router: 3.5.5 => 3.5.5 
      @tarojs/runtime: 3.5.5 => 3.5.5 
      @tarojs/shared: 3.5.5 => 3.5.5 
      @tarojs/taro: 3.5.5 => 3.5.5 
      @tarojs/taro-h5: 3.5.5 => 3.5.5 
      @tarojs/webpack5-runner: 3.5.5 => 3.5.5 
      babel-preset-taro: 3.5.5 => 3.5.5 
      eslint-config-taro: 3.5.5 => 3.5.5 
      react: ^18.0.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 4.8.2

### Reproduction link（重现链接）
[nutui.jd.com/h5/react/1x/](https://nutui.jd.com/h5/react/1x/#/zh-CN/component/uploader)

### Steps to reproduce（重现步骤）
自定义样式，然后defaultFileList给个值

### What is expected?（期望的结果是什么？）
defaultFileList 可以正常显示图片

### What is actually happening?（实际的结果是什么？）
defaultFileList 不生效

**Comment by junjun666** [comment]
经排查，如果想用自定义就不会走到defaultFileList的逻辑中，展示默认图片。
