### ISSUE TITLE
Icon组件line-height属性致向上偏移一个像素

### ISSUE THREAD

**Issue by chrysanthemum** [jdf2e/nutui-react#648]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.6

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
v18.9.0

### Browser and its version（浏览器及其版本）
Chrome 109.0.5414.119

### System and its version（系统及其版本）
MacOS 12.5.1

### Taro environmental information（taro 环境信息）
👽 Taro v3.5.12

  Taro CLI 3.5.12 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.9.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.1 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.5.12 => 3.5.12
      @tarojs/components: 3.5.12 => 3.5.12
      @tarojs/helper: 3.5.12 => 3.5.12
      @tarojs/mini-runner: 3.5.12 => 3.5.12
      @tarojs/plugin-framework-react: 3.5.12 => 3.5.12
      @tarojs/plugin-html: ^3.5.12 => 3.5.12
      @tarojs/plugin-platform-alipay: 3.5.12 => 3.5.12
      @tarojs/plugin-platform-jd: 3.5.12 => 3.5.12
      @tarojs/plugin-platform-qq: 3.5.12 => 3.5.12
      @tarojs/plugin-platform-swan: 3.5.12 => 3.5.12
      @tarojs/plugin-platform-tt: 3.5.12 => 3.5.12
      @tarojs/plugin-platform-weapp: 3.5.12 => 3.5.12
      @tarojs/react: 3.5.12 => 3.5.12
      @tarojs/router: 3.5.12 => 3.5.12
      @tarojs/runtime: 3.5.12 => 3.5.12
      @tarojs/shared: 3.5.12 => 3.5.12
      @tarojs/taro: 3.5.12 => 3.5.12
      @tarojs/taro-h5: 3.5.12 => 3.5.12
      @tarojs/webpack-runner: 3.5.12 => 3.5.12
      babel-preset-taro: 3.5.12 => 3.5.12
      eslint-config-taro: 3.5.12 => 3.5.12
      react: ^18.0.0 => 18.2.0

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/summer-sea-odvnwb)

### Steps to reproduce（重现步骤）
https://codesandbox.io/s/summer-sea-odvnwb

### What is expected?（期望的结果是什么？）
icon不会向上偏移导致被遮挡一个像素，在小程序环境去掉 .nut-icon 的 line-height 属性即可fix
 

### What is actually happening?（实际的结果是什么？）
Icon组件line-height属性致向上偏移一个像素

**Comment by oasis-cloud** [comment]
在 https://github.com/oasis-cloud/taro-demo.git 的 icon 分支上并未复现上面的情况
