### ISSUE TITLE
nutui-react-taro设计尺寸问题

### ISSUE THREAD

**Issue by DaJianWu** [jdf2e/nutui-react#658]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.6

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
14.18

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
windows

### Taro environmental information（taro 环境信息）
Taro v3.5.1

### Reproduction link（重现链接）
[nutui.jd.com/taro/react/1x/](https://nutui.jd.com/taro/react/1x/#/zh-CN/guide/starttaro-react)

### Steps to reproduce（重现步骤）
目前官方文档是建议忽略对nutui-react-taro的px=>rpx的转化，但是nutui-react-taro设计尺寸是375的，项目的设计尺寸是750的，那么怎么在小程序上实现尺寸自适应呢？

### What is expected?（期望的结果是什么？）
nutui-react-taro设计尺寸可配置或可配置为px=>rpx

### What is actually happening?（实际的结果是什么？）
没有相应的配置项

**Comment by eiinu** [comment]
Taro 中支持使用函数配置 designWith：
```
designWidth (input) {
  // 配置 NutUI 375 尺寸
  if (input?.file?.replace(/\\+/g, '/').indexOf('@nutui') > -1) {
    return 375
  }
  // 全局使用 Taro 默认的 750 尺寸
  return 750
},
```

**Comment by DaJianWu** [comment]
> Taro 中支持使用函数配置 designWidth：
> 
> ```
> designWidth (input) {
>   // 配置 NutUI 375 尺寸
>   if (input?.file?.replace(/\\+/g, '/').indexOf('@nutui') > -1) {
>     return 375
>   }
>   // 全局使用 Taro 默认的 750 尺寸
>   return 750
> },
> ```

那这样是不是应该要把自己项目的代码和nutui的代码都转成rpx了

**Comment by DaJianWu** [comment]
我按照上面写法试了下，并且把deviceRatio加上了375的配置，但是发现nutui的代码的px虽然被转成了rpx，但是没有扩大两倍。。。

**Comment by eiinu** [comment]
> > Taro 中支持使用函数配置 designWidth：
> > ```
> > designWidth (input) {
> >   // 配置 NutUI 375 尺寸
> >   if (input?.file?.replace(/\\+/g, '/').indexOf('@nutui') > -1) {
> >     return 375
> >   }
> >   // 全局使用 Taro 默认的 750 尺寸
> >   return 750
> > },
> > ```
> 
> 那这样是不是应该要把自己项目的代码和nutui的代码都转成rpx了

是的，这样配置之后就可以开启对组件库的 pxtransform 了

**Comment by DaJianWu** [comment]
好的 designWidth支持函数是taro新版才支持的 感谢！

**Comment by memory1112** [comment]
> > > Taro 中支持使用函数配置 designWidth：
> > > ```
> > > designWidth (input) {
> > >   // 配置 NutUI 375 尺寸
> > >   if (input?.file?.replace(/\\+/g, '/').indexOf('@nutui') > -1) {
> > >     return 375
> > >   }
> > >   // 全局使用 Taro 默认的 750 尺寸
> > >   return 750
> > > },
> > > ```
> > 
> > 
> > 那这样是不是应该要把自己项目的代码和nutui的代码都转成rpx了
> 
> 是的，这样配置之后就可以开启对组件库的 pxtransform 了

这样设置之后，组件库仍然没有pxtransform呢，还有就是组件库按需引入时，如何实现pxtransform呢

**Comment by MichaelHao25** [comment]
貌似不生效啊。。。。，函数配置，导致现在整体偏小。

**Comment by MichaelHao25** [comment]
我自己写的样式大，但是默认的样式小。

**Comment by MichaelHao25** [comment]
> Taro 中支持使用函数配置 designWidth：
> 
> ```
> designWidth (input) {
>   // 配置 NutUI 375 尺寸
>   if (input?.file?.replace(/\\+/g, '/').indexOf('@nutui') > -1) {
>     return 375
>   }
>   // 全局使用 Taro 默认的 750 尺寸
>   return 750
> },
> ```

没效果啊。亲亲，最新版的

**Comment by MichaelHao25** [comment]
有效果了，两个地方都需要配置才可以。
