### ISSUE TITLE
Dialog 组件在小程序环境下不能使用函数式调用方式

### ISSUE THREAD

**Issue by AnteeHub** [jdf2e/nutui-react#676]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.7

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
微信开发者工具 Stable 1.06.2301040

### System and its version（系统及其版本）
MacOS(12.6)

### Taro environmental information（taro 环境信息）
```sh
👽 Taro v3.5.7


  Taro CLI 3.5.7 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1 
      @tarojs/components: 3.6.1 => 3.6.1 
      @tarojs/helper: 3.6.1 => 3.6.1 
      @tarojs/plugin-framework-react: 3.6.1 => 3.6.1 
      @tarojs/plugin-html: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-alipay: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-jd: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-qq: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-swan: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-tt: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-weapp: 3.6.1 => 3.6.1 
      @tarojs/react: 3.6.1 => 3.6.1 
      @tarojs/router: 3.6.1 => 3.6.1 
      @tarojs/runtime: 3.6.1 => 3.6.1 
      @tarojs/shared: 3.6.1 => 3.6.1 
      @tarojs/taro: 3.6.1 => 3.6.1 
      @tarojs/taro-h5: 3.6.1 => 3.6.1 
      @tarojs/webpack5-runner: 3.6.1 => 3.6.1 
      babel-preset-taro: 3.6.1 => 3.6.1 
      eslint-config-taro: 3.6.1 => 3.6.1 
      react: ^18.0.0 => 18.2.0 
```

### Reproduction link（重现链接）
[github.com](https://github.com/AnteeHub/nutui-react-taro-present/tree/dialog)

### Steps to reproduce（重现步骤）
- 使用 `taro init` 初始化项目
- 选择 `nut-ui` 模板，指定版本为 `1.4.7`
- 引入 `<Dialog/>` 组件，按照文档提示分别使用“组件方式”和“函数式调用”方式使用。

### What is expected?（期望的结果是什么？）
应该像官网文档示例一样，通过“函数式调用”方式的 `Dialog.alert({...})` 调用时，可以打开 `<Dialog />` 组件

### What is actually happening?（实际的结果是什么？）
没有弹出 `<Dialog/>` 组件，控制台报错提示
`TypeError: _nutui_nutui_react_taro_dist_esm_Dialog__WEBPACK_IMPORTED_MODULE_8__.D.alert is not a function`

截图如下：
<img width="593" alt="image" src="https://user-images.githubusercontent.com/55703989/219003378-51a4241a-194c-49ba-9503-ad0258e7e936.png">

**Comment by eiinu** [comment]
小程序对应的文档是这个 [NutUI React-Taro](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/Dialog)，受小程序环境限制，不支持函数方式调用

**Comment by AnteeHub** [comment]
> 小程序对应的文档是这个 [NutUI React-Taro](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/Dialog)，受小程序环境限制，不支持函数方式调用

@eiinu 你附上的是 nutui-taro-vue 的文档，nutui-react-taro 的文档对应的是下面的：
https://nutui.jd.com/taro/react/1x/#/zh-CN/component/dialog

附上截图：

![image](https://user-images.githubusercontent.com/55703989/219252998-7692f2b2-8581-496e-b271-53c64756c93b.png)

**Comment by eiinu** [comment]
> > 小程序对应的文档是这个 [NutUI React-Taro](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/Dialog)，受小程序环境限制，不支持函数方式调用
> 
> @eiinu 你附上的是 nutui-taro-vue 的文档，nutui-react-taro 的文档对应的是下面的： https://nutui.jd.com/taro/react/1x/#/zh-CN/component/dialog
> 
> 附上截图：
> 

哦哦我搞错了，是文档有问题，稍后会修改。在Taro 框架下，组件的函数调用暂时没有合适的实现方法。

**Comment by AnteeHub** [comment]
> > > 小程序对应的文档是这个 [NutUI React-Taro](https://nutui.jd.com/taro/vue/4x/#/zh-CN/component/Dialog)，受小程序环境限制，不支持函数方式调用
> > 
> > 
> > @eiinu 你附上的是 nutui-taro-vue 的文档，nutui-react-taro 的文档对应的是下面的： https://nutui.jd.com/taro/react/1x/#/zh-CN/component/dialog
> > 附上截图：
> 
> 哦哦我搞错了，是文档有问题，稍后会修改。在Taro 框架下，组件的函数调用暂时没有合适的实现方法。

`Dialog` 的 ts 导出类型仍有 `alert` 方法，这里可能也要修改下。一些比较依赖 ts 类型提示的开发者（比如我）也容易被误导。

![image](https://user-images.githubusercontent.com/55703989/219300979-dec5f206-b32b-479d-9155-a6a692770312.png)


![image](https://user-images.githubusercontent.com/55703989/219300932-7c060162-b0c0-41e8-b8ad-1dc61a19cd11.png)
