### ISSUE TITLE
Ellipsis组件点击展开、收起会触发onClick事件，是否合理？

### ISSUE THREAD

**Issue by liujiayii** [jdf2e/nutui-react#692]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.7

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.0

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
macos

### Taro environmental information（taro 环境信息）
  Taro CLI 3.6.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\liuji\AppData\Roaming\npm\yarn.CMD
      npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[github.com/liujiayii/chat-bot](https://github.com/liujiayii/chat-bot)

### Steps to reproduce（重现步骤）
无

### What is expected?（期望的结果是什么？）
不触发onClick

### What is actually happening?（实际的结果是什么？）
触发onClick

![image](https://user-images.githubusercontent.com/38902744/219696868-83ee52e0-1ae4-4b10-ba24-3128f1b819fa.png)

**Comment by oasis-cloud** [comment]
展开和收起操作的事件应该加上阻止冒泡，建议合理
