### ISSUE TITLE
Dialog、Popup等组件显示后，蒙层底部背景仍然可以上下滑动的问题

### ISSUE THREAD

**Issue by jqroom** [jdf2e/nutui-react#694]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.7

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.19.1

### Browser and its version（浏览器及其版本）
Chrome(110.0.5481.83)

### System and its version（系统及其版本）
MacOS(10.15.7)

### Taro environmental information（taro 环境信息）
yarn run v1.22.19
$ taro info
👽 Taro v3.6.1

  Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 16.19.1 - /var/folders/v8/zf64zxj155581bkbwhc0b3c40000gp/T/yarn--1676721197111-0.514750923327403/node
      Yarn: 1.22.19 - /var/folders/v8/zf64zxj155581bkbwhc0b3c40000gp/T/yarn--1676721197111-0.514750923327403/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1 
      @tarojs/components: 3.6.1 => 3.6.1 
      @tarojs/helper: 3.6.1 => 3.6.1 
      @tarojs/plugin-framework-react: 3.6.1 => 3.6.1 
      @tarojs/plugin-html: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-alipay: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-h5: ^3.6.1 => 3.6.1 
      @tarojs/plugin-platform-jd: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-qq: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-swan: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-tt: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-weapp: 3.6.1 => 3.6.1 
      @tarojs/react: 3.6.1 => 3.6.1 
      @tarojs/router: 3.6.1 => 3.6.1 
      @tarojs/runtime: 3.6.1 => 3.6.1 
      @tarojs/shared: 3.6.1 => 3.6.1 
      @tarojs/taro: 3.6.1 => 3.6.1 
      @tarojs/taro-h5: 3.6.1 => 3.6.1 
      @tarojs/webpack5-runner: 3.6.1 => 3.6.1 
      babel-preset-taro: 3.6.1 => 3.6.1 
      eslint-config-taro: 3.6.1 => 3.6.1 
      react: ^18.0.0 => 18.2.0 

✨  Done in 1.10s.

### Reproduction link（重现链接）
[github.com](https://github.com/jqroom/nutui-react-taro-present)

### Steps to reproduce（重现步骤）
yarn install
yarn dev:h5
引入<Dialog />、<Popup />组件，本地启动调试
使用移动端浏览器访问页面

### What is expected?（期望的结果是什么？）
Dialog、Popup等组件显示后，蒙层底部背景不可以上下滑动

### What is actually happening?（实际的结果是什么？）
Dialog、Popup等组件显示后，蒙层底部背景仍然可以上下滑动

### 补充说明
https://user-images.githubusercontent.com/18415185/219866664-e66055c2-0200-48ee-bb2c-e131e3a65cc3.mp4

**Comment by oasis-cloud** [comment]
Popup 组件内部封装的 overlay，可以通过 lockScroll 属性控制

**Comment by jqroom** [comment]
1、Popup组件在文档中（https://nutui.jd.com/h5/react/1x/#/zh-CN/component/popup），lockScroll默认为true。
2、Dialog、Popup等组件，在增加了lockScroll:true的配置后，在移动端浏览器中背景仍然可以滑动。
重新验证，发现问题并没有解决

https://user-images.githubusercontent.com/18415185/220599569-d7364ec5-1773-459d-a850-444c64a55356.mp4

**Comment by fuyunzhishang** [comment]
是没有修复，而且带来了新的样式问题
![image](https://user-images.githubusercontent.com/19215394/220809312-16e74b62-dabd-44db-b516-885d14be916a.png)

**Comment by promiseLC** [comment]
@oasis-cloud 这个可以重新打开么? ios下还是有滚动问题

**Comment by promiseLC** [comment]
@jqroom 解决了么?我们是通过Dialog打开状态手动改样式

**Comment by hooliy** [comment]
为什么关了呀？背景还是会滚动，怎么解决呀？
