### ISSUE TITLE
短密码组件的一些建议

### ISSUE THREAD

**Issue by kasonyang** [jdf2e/nutui-react#696]
### What problem does this feature solve?（这个功能解决的问题）
当前短密码存在的一些问题：
1. 组件内集成了Popup组件，导致组件灵活性不够。比如，当需要使用这个组件来设置短密码时，无法增加一个用于确认密码的短密码输入框。同时，也无法使用软键盘等。
2. 短密码组件利用原生input组件接收输入，当前实现上，原生input不可见，但是在可视区域内，如果用户点击短密码或者长按短密码，是可以移动输入光标或者触发浏览器的“选择文本”功能的，用户可能会非常疑惑。

### What does the proposed API look like?（期望的 API）
1. 短密码组件剥离Popup，封装一个新组件（如ShortPasswordInput）只负责核心部分（输入处理和显示等）。
2. 将input偏移到不可视区域。

**Comment by kasonyang** [comment]
如果有需要，我可以提个PR提供一些帮助

**Comment by oasis-cloud** [comment]
> 如果有需要，我可以提个PR提供一些帮助

可以提交相关 PR，帮助我们优化

**Comment by kasonyang** [comment]
试着实现了一版，针对问题2，试了几个浏览器，发现存在一些兼容性问题，部分浏览器会有input强制移位或者无法使用后退键删除的奇怪表现。看起来，如果想在所有浏览器都能完美呈现，强制使用软键盘是个更好的选择^_^
