### ISSUE TITLE
「Swipe 滑动手势」组件文档描述错误

### ISSUE THREAD

**Issue by AnteeHub** [jdf2e/nutui-react#730]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.8

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
any

### System and its version（系统及其版本）
MacOS(12.6)

### Reproduction link（重现链接）
[nutui.jd.com/h5/react/1x/](https://nutui.jd.com/h5/react/1x/#/zh-CN/component/swipe)

### Steps to reproduce（重现步骤）
见重现链接

### What is expected?（期望的结果是什么？）
Swipe 组件的样式变量应与其组件本身是用的依赖变量相关

### What is actually happening?（实际的结果是什么？）
错将 Swiper 的样式变量错误的引用进来了

### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.8

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
any

### System and its version（系统及其版本）
MacOS(12.6)

### Reproduction link（重现链接）
[nutui.jd.com/h5/react/1x/](https://nutui.jd.com/h5/react/1x/#/zh-CN/component/swipe)

### Steps to reproduce（重现步骤）
见重现链接 [nutui.jd.com/h5/react/1x/](https://nutui.jd.com/h5/react/1x/#/zh-CN/component/swipe)

### What is expected?（期望的结果是什么？）
**Swipe 滑动手势**组件的样式变量应与其组件本身是用的依赖变量相关

### What is actually happening?（实际的结果是什么？）
错将 **Swiper 轮播**的样式变量错误的引用当作 **Swipe 滑动手势**组件的样式变量

![image](https://user-images.githubusercontent.com/55703989/221076729-8279672d-6004-456c-a241-78e89ba23b6b.png)

**Comment by xiaoyatong** [comment]
1.4.9
