### ISSUE TITLE
nutui/nutui-react-taro 的form表单功能希望尽快可以得到开放和应用

### ISSUE THREAD

**Issue by shenyunzhe** [jdf2e/nutui-react#734]
### What problem does this feature solve?（这个功能解决的问题）
在小程序端表单功能可以使用

### What does the proposed API look like?（期望的 API）
参照react版本

**Comment by Jairwin-L** [comment]
form表单校验章节校验好像有问题：https://nutui.jd.com/h5/react/1x/#/zh-CN/component/form

<img width="723" alt="image" src="https://user-images.githubusercontent.com/32570960/225564635-39d84f58-6611-48d1-83e4-7164d942ade9.png">

repo：https://github.com/Jairwin-L/taro-debug

**Comment by LovesLolita** [comment]
支持  没有form 好烦啊 技术不行 >_<  求官方支持!!!!  求求了

**Comment by 5201314999** [comment]
支持

**Comment by 5201314999** [comment]
这么核心的功能怎么能没有。。。

**Comment by hcw2175** [comment]
+1

**Comment by wangyuan0108** [comment]
form2.0版本支持吗？大概还要多久啊，发现没有这个现在

**Comment by dpzxsm** [comment]
推荐 https://github.com/dpzxsm/taro-vform   我自己开源的，兼容nutui，非常轻量，功能也更加强大 @wangyuan0108 @hcw2175 @LovesLolita @5201314999
