### ISSUE TITLE
Elevator 增加行自定义渲染设置

### ISSUE THREAD

**Issue by lkjh3214** [jdf2e/nutui-react#738]
### What problem does this feature solve?（这个功能解决的问题）
支持单行内容 自定义渲染， 当前只能只展示文案， 对于更丰富的单行内容无法展示。类似于vue中的插槽
![image](https://user-images.githubusercontent.com/23164467/221520528-dc0139de-c910-430a-99c2-0b91783ff112.png)

### What does the proposed API look like?（期望的 API）
类似于 
renderItem(itemData) {
  return <div> <Icon /> {itemData}</div>
}

**Comment by irisSong** [comment]
v1.4.7版本已支持，参考 https://nutui.jd.com/h5/react/1x/#/zh-CN/component/Elevator自定义内容demo

**Comment by lkjh3214** [comment]
> v1.4.7版本已支持，参考 [https://nutui.jd.com/h5/react/1x/#/zh-CN/component/Elevator自定义内容demo](https://nutui.jd.com/h5/react/1x/#/zh-CN/component/Elevator%E8%87%AA%E5%AE%9A%E4%B9%89%E5%86%85%E5%AE%B9demo)

找到了。 文档没刷新，看的还是以前的
