### ISSUE TITLE
希望能出一个Form组件？

### ISSUE THREAD

**Issue by strongyc** [jdf2e/nutui-react#74]
Form组件在日常使用中比较常用，希望能出一个Form组件。感谢大佬！

**Comment by wangcode** [comment]
为什么不尝试使用 [React Hook Form](https://react-hook-form.com/)
完全没必要封装一个form组件

**Comment by xiaoyatong** [comment]
都会非常好的建议，Form 我们在计划中~

**Comment by JackFeng7** [comment]
我看vue版本的组件丰富，建议能够跟进。

**Comment by xiaoyatong** [comment]
开发中。

**Comment by xiaoyatong** [comment]
已发布h5版本。
