### ISSUE TITLE
popup渲染问题

### ISSUE THREAD

**Issue by szg2008** [jdf2e/nutui-react#763]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.9

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18

### Browser and its version（浏览器及其版本）
Chrome

### System and its version（系统及其版本）
Mac

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/weathered-glade-956yem?file=/src/App.js)

### Steps to reproduce（重现步骤）
在useEffect中，如果visible为true，那么popup里面的内容获取不到

### What is expected?（期望的结果是什么？）
在useEffect中，如果visible为true，那么popup里面的内容能够正常获取，并且能够正常操作dom

### What is actually happening?（实际的结果是什么？）
在useEffect中，如果visible为true，那么popup里面的内容获取不到

**Comment by oasis-cloud** [comment]
可以通过 setTimeout 或 ref callback 方式实现

setTimeout 方式：
  useEffect(() => {
    setTimeout(() => {
      console.log(visible, contentRef, contentRef.current);
      contentRef.current.innerText = 'Hwll'
    });
  }, [visible, contentRef]);

ref callback 方式：

<div ref={(r) => r.innerText='aaaa'}>xxxxx</div>
