### ISSUE TITLE
A-Input组件不设置placeholder，但是会显示另一个B-Input组件的placeholder值

### ISSUE THREAD

**Issue by nenzo2016** [jdf2e/nutui-react#764]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.9

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.1

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
window11

### What is expected?（期望的结果是什么？）
Input组件不设置placeholder，应不显示

### What is actually happening?（实际的结果是什么？）
Input组件不设置placeholder，显示了另一个Input的placeholder值

**Comment by oasis-cloud** [comment]
提供一份 input 使用的 demo 吧，单独看 issue 中的描述，无法得知应该如何复现

**Comment by CaniceZ** [comment]
小程序端也有这个问题 第一个input的placeholder有值，第二个为空的时候显示异常
![image](https://user-images.githubusercontent.com/23026625/223364529-4c5080e7-79a6-4cf9-8bb1-b1a40ab582ac.png)
`<Input
          name='number'
          label='银行卡'
          placeholder='银行卡'
          defaultValue={state.bankcount}
          inputAlign='right'
          type='digit'
          maxlength={18}
        />
        <Input
          name='tel'
          labelWidth='120'
          label='银行卡预留手机号'
          placeholder=''
          defaultValue={state.tel}
          inputAlign='right'
          type='tel'
          border={false}`

**Comment by sushi-su** [comment]
看了下源码应该是受到多语言配置的影响
![image](https://user-images.githubusercontent.com/50985188/223370516-0c4b58a6-edc1-45a3-b40c-f75563ca42da.png)
<img width="722" alt="image" src="https://user-images.githubusercontent.com/50985188/223370743-74731dab-a38d-4623-b0c3-bfeff2281b6b.png">

**Comment by AnteeHub** [comment]
> 小程序端也有这个问题 第一个input的placeholder有值，第二个为空的时候显示异常 ![image](https://user-images.githubusercontent.com/23026625/223364529-4c5080e7-79a6-4cf9-8bb1-b1a40ab582ac.png) `<Input name='number' label='银行卡' placeholder='银行卡' defaultValue={state.bankcount} inputAlign='right' type='digit' maxlength={18} /> <Input name='tel' labelWidth='120' label='银行卡预留手机号' placeholder='' defaultValue={state.tel} inputAlign='right' type='tel' border={false}`

协助补充了一个复现的 demo：
https://github.com/AnteeHub/nutui-react-taro-present/tree/input-placeholder
