### ISSUE TITLE
Radio组件shape="button"时的背景颜色不对

### ISSUE THREAD

**Issue by yangjinjun3** [jdf2e/nutui-react#768]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.9

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
MacOS(12.6)

### Reproduction link（重现链接）
[nutui.jd.com/h5/react/1x/](https://nutui.jd.com/h5/react/1x/#/zh-CN/component/radio)

### Steps to reproduce（重现步骤）
https://nutui.jd.com/h5/react/1x/#/zh-CN/component/radio

### What is expected?（期望的结果是什么？）
和Vue版本一致

### What is actually happening?（实际的结果是什么？）
和Vue版本不一致。
查看源代码，是这个样式导致的
.nut-radiogroup .nut-radio__button {
    background-color: var(--nutui-gray-4, #f4f4f4);
}

**Comment by AnteeHub** [comment]
补充描述：

vue 版本 radio 按钮默认颜色是 `#f6f7f9`， react 版本 radio 按钮的默认样式覆盖了原来按钮的颜色，变为 `#f4f4f4`

<img width="550" alt="image" src="https://user-images.githubusercontent.com/55703989/223603496-6f311501-435f-4fea-b0b1-05f0f2b1a377.png">
