### ISSUE TITLE
Textarea两个问题

### ISSUE THREAD

**Issue by yangjinjun3** [jdf2e/nutui-react#777]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.9

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
MacOS(12.6)

### Reproduction link（重现链接）
[nutui.jd.com/h5/react/1x/](https://nutui.jd.com/h5/react/1x/#/zh-CN/component/textarea)

### Steps to reproduce（重现步骤）
1、字数统计：输入中文时，按回车键前，一直在计数
2、样式：placeholder距离顶部太高，参考vue版

### What is expected?（期望的结果是什么？）
1、字数统计：输入中文时，按回车键前，不计数
2、样式：placeholder距离顶部和vue版保持一致

### What is actually happening?（实际的结果是什么？）
1、字数统计：输入中文时，按回车键前，一直在计数
2、样式：placeholder距离顶部太高

**Comment by AnteeHub** [comment]
@yangjinjun3

**Comment by AnteeHub** [comment]
> 样式：placeholder距离顶部太高

vue 版本的 textarea 组件默认样式是 `padding: 10px 25px;`
<img width="552" alt="image" src="https://user-images.githubusercontent.com/55703989/223949285-1f169811-be13-4389-acbd-700f2a0b248f.png">


react 版本的 textarea 组件默认样式是 `16px 10px 16px 16px;`
<img width="549" alt="image" src="https://user-images.githubusercontent.com/55703989/223949294-b0fcdd7d-f6ef-4095-af19-8b81c0c95b82.png">

**Comment by oasis-cloud** [comment]
字体数统计功能在中文输入法下会计数，但是在合成后计数是准确的。其他UI组件库的字数统计功能也是如此，交互一致。
