### ISSUE TITLE
Ellipsis组件外层标签超过15层时文本溢出失效且控制台报错

### ISSUE THREAD

**Issue by midday** [jdf2e/nutui-react#786]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.10

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.19.0

### Browser and its version（浏览器及其版本）
微信开发者工具1.06.2303060

### System and its version（系统及其版本）
MaxOS(13.0.1)

### Taro environmental information（taro 环境信息）
Taro v3.6.1

  Taro CLI 3.6.1 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.1 => 3.6.1 
      @tarojs/components: 3.6.1 => 3.6.1 
      @tarojs/helper: 3.6.1 => 3.6.1 
      @tarojs/plugin-framework-react: 3.6.1 => 3.6.1 
      @tarojs/plugin-html: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-alipay: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-h5: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-jd: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-qq: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-swan: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-tt: 3.6.1 => 3.6.1 
      @tarojs/plugin-platform-weapp: 3.6.1 => 3.6.1 
      @tarojs/react: 3.6.1 => 3.6.1 
      @tarojs/runtime: 3.6.1 => 3.6.1 
      @tarojs/shared: 3.6.1 => 3.6.1 
      @tarojs/taro: 3.6.1 => 3.6.1 
      @tarojs/webpack5-runner: 3.6.1 => 3.6.1 
      babel-preset-taro: 3.6.1 => 3.6.1 
      eslint-config-taro: 3.6.1 => 3.6.1 
      react: ^18.0.0 => 18.2.0 

### Reproduction link（重现链接）
[github.com](https://github.com/midday/nutui-problem-feedback/blob/feature/ellipsis-report-error-bug/src/pages/index/index.tsx)

### Steps to reproduce（重现步骤）
运行Demo即可复现

### What is expected?（期望的结果是什么？）
外层标签超过15层文本溢出功能正常

### What is actually happening?（实际的结果是什么？）
外层标签超过15层文本溢出失效且控制台报错

### Remarks（补充说明）
由于业务复杂度高，组件封装颗粒度细，导致Ellipsis外层标签超过15层后报错。

**Comment by oasis-cloud** [comment]
对于 template 模板不支持递归的小程序（如：微信、QQ、京东），Taro 会对所有模板循环 baseLevel 次，以支持同类模板的循环调用。
可通过下面的配置进行修改。
https://nervjs.github.io/taro-docs/docs/config-detail/#minibaselevel
