### ISSUE TITLE
dev 启动报错

### ISSUE THREAD

**Issue by crazyair** [jdf2e/nutui-react#802]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.10

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
mac

### Reproduction link（重现链接）
yarn dev
![image](https://user-images.githubusercontent.com/7971419/224873604-22d4664e-44e6-467a-82d0-ba45d5f0cce9.png)

### Steps to reproduce（重现步骤）
yarn dev

### What is expected?（期望的结果是什么？）
启动起来

### What is actually happening?（实际的结果是什么？）
启动报错

**Comment by eiinu** [comment]
测试了 yarn、npm 安装项目依赖后，没有复现类似问题。
可能是使用了 pnpm 安装项目依赖，其中 `@testing-library/jest-dom` 包的依赖 `@types/testing-library__jest-dom` 无法被自动安装，相关 issue https://github.com/pnpm/pnpm/discussions/4723 https://github.com/testing-library/jest-dom/issues/314
解决办法是手动安装 `@types/testing-library__jest-dom`

**Comment by crazyair** [comment]
> 测试了 yarn、npm 安装项目依赖后，没有复现类似问题。 可能是使用了 pnpm 安装项目依赖，其中 `@testing-library/jest-dom` 包的依赖 `@types/testing-library__jest-dom` 无法被自动安装，相关 issue [pnpm/pnpm#4723](https://github.com/orgs/pnpm/discussions/4723) [testing-library/jest-dom#314](https://github.com/testing-library/jest-dom/issues/314) 解决办法是手动安装 `@types/testing-library__jest-dom`

一开始用 npm install 下载失败，才使用了  pnpm，毕竟 pnpm 下载很快，基本不会出错，希望项目本身把依赖补全。

**Comment by eiinu** [comment]
> > 测试了 yarn、npm 安装项目依赖后，没有复现类似问题。 可能是使用了 pnpm 安装项目依赖，其中 `@testing-library/jest-dom` 包的依赖 `@types/testing-library__jest-dom` 无法被自动安装，相关 issue [pnpm/pnpm#4723](https://github.com/orgs/pnpm/discussions/4723) [testing-library/jest-dom#314](https://github.com/testing-library/jest-dom/issues/314) 解决办法是手动安装 `@types/testing-library__jest-dom`
> 
> 一开始用 npm install 下载失败，才使用了 pnpm，毕竟 pnpm 下载很快，基本不会出错，希望项目本身把依赖补全。

最近在做 pnpm 迁移，会尽快增加该依赖
