### ISSUE TITLE
DatePicker 组件希望能增加点击取消按钮的事件

### ISSUE THREAD

**Issue by zouyawen** [jdf2e/nutui-react#808]
### What problem does this feature solve?（这个功能解决的问题）
现在点击确定按钮和点击取消按钮都会调用onCloseDatePicker方法。想在点击取消的时候做一下其他的判断，但现在在onCloseDatePicker里没有办法区分是点击取消触发的还是点击确定促发的

### What does the proposed API look like?（期望的 API）
DatePicker 组件添加点击取消按钮单独触发的事件

**Comment by xiaoyatong** [comment]
点击确认可以使用：onConfirmDatePicker

**Comment by zouyawen** [comment]
> 点击确认可以使用：onConfirmDatePicker

特殊情况希望在点击取消的时候做一些处理

**Comment by xiaoyatong** [comment]
2.0 增强。

**Comment by xiaoyatong** [comment]
2.0已增加 onClose 方法
