### ISSUE TITLE
希望menu菜单组件添加监听显示和隐藏的方法

### ISSUE THREAD

**Issue by star-xing-code** [jdf2e/nutui-react#815]
### What problem does this feature solve?（这个功能解决的问题）
可以解决用户自定义菜单，菜单数据用户无法手动更新问题。

### What does the proposed API look like?（期望的 API）
const onShow = (value)=>{
  console.log(value)
}

**Comment by hcw2175** [comment]
还有 `value` 值好像不受控，重置 `value` 值后，menu 还是显示之前选中的项。
