### ISSUE TITLE
我将ImagePreview 组件的Images和InitNo设为动态State时，效果异常

### ISSUE THREAD

**Issue by l-light-l** [jdf2e/nutui-react#821]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.11

### React version（react 版本）
17.0.2

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
14.16.1

### Browser and its version（浏览器及其版本）
chrome( 111.0.5563.65)

### System and its version（系统及其版本）
windows 10

### Reproduction link（重现链接）
[codepen.io](https://codepen.io/l-light-l/pen/LYJmXdb?editors=0010)

### Steps to reproduce（重现步骤）
伪代码：
  const [showImg, setShowImg] = useState(0); // 图片索引
  const [showPreview, setShowPreview] = useState(false); // 预览图片
  const [images, setImages] = useState<{src: string}[]>([]); // 图片地址
useEffect(() =>{
     setImages( [
        {
            src: '//m.360buyimg.com/mobilecms/s750x366_jfs/t1/18629/34/3378/144318/5c263f64Ef0e2bff0/0d650e0aa2e852ee.jpg'
        },
        {
            src: '//m.360buyimg.com/mobilecms/s750x366_jfs/t1/26597/30/4870/174583/5c35c5d2Ed55eedc6/50e27870c25e7a82.png'
        },
        {
            src: '//m.360buyimg.com/mobilecms/s750x366_jfs/t1/9542/17/12873/201687/5c3c4362Ea9eb757d/60026b40a9d60d85.jpg'
        },
        {
            src: '//m.360buyimg.com/mobilecms/s750x366_jfs/t1/30042/36/427/82951/5c3bfdabE3faf2f66/9adca782661c988c.jpg'
        }
    ])
}, [])
      <ImagePreview images={images} initNo={showImg + 1} show={showPreview} autoplay={0} onClose={() => setShowPreview(false)} />
      <Image src={images[showImg]?.src} onClick={() => { setShowPreview(true); }} />
      <div style={{ display: 'flex' }}>
        {
          images.map((item: any, index: any) => {
            return <Image src={item?.src} key={item?.src} onClick={() => setShowImg(index)} />;
          })
        }
      </div>

### What is expected?（期望的结果是什么？）
修改initNo，预览该索引对应的图片

### What is actually happening?（实际的结果是什么？）
修改initNo，始终预览的是第一张图片

**Comment by oasis-cloud** [comment]
可以参考 NutUI 官网新增的例子

**Comment by Fancons** [comment]
> 可以参考 NutUI 官网新增的例子

import React, {useState} from 'react';
import {ImagePreview, Cell} from '@nutui/nutui-react-taro';

const App = () => {
  const images = [
    {
      src: '//m.360buyimg.com/mobilecms/s750x366_jfs/t1/18629/34/3378/144318/5c263f64Ef0e2bff0/0d650e0aa2e852ee.jpg'
    },
    {
      src: '//m.360buyimg.com/mobilecms/s750x366_jfs/t1/26597/30/4870/174583/5c35c5d2Ed55eedc6/50e27870c25e7a82.png'
    },
    {
      src: '//m.360buyimg.com/mobilecms/s750x366_jfs/t1/9542/17/12873/201687/5c3c4362Ea9eb757d/60026b40a9d60d85.jpg'
    },
    {
      src: '//m.360buyimg.com/mobilecms/s750x366_jfs/t1/30042/36/427/82951/5c3bfdabE3faf2f66/9adca782661c988c.jpg'
    }
  ];
  const [init, setInit] = useState(0);

  return (
    <>
      <Cell style={{position: 'relative', zIndex: 10000}}>
        {images.map((image, index) =>
          (<span
            key={image.src}
            onClick={() => setInit(index + 1)}
            style={{marginRight: '10px'}}
          >
              <img width={30}
                   height={30}
                   src={image.src}
                   alt={image.src}
              />
            </span>)
        )}
      </Cell>
      <ImagePreview
        images={images}
        show={init}
        initNo={init}
        onClose={hideFn2}
      />
    </>
  );
};
export default App;
官网的例子:点击缩略图切换
hideFn2没有被定义,自己处理了会出现initNo属性始终不对

**Comment by Fancons** [comment]
```tsx
```
