### ISSUE TITLE
Cell右侧文案过多会挤压左侧

### ISSUE THREAD

**Issue by yangjinjun3** [jdf2e/nutui-react#822]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.11

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.18.0

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
MacOS(12.6)

### Reproduction link（重现链接）
[nutui.jd.com](https://nutui.jd.com/h5/react/1x/demo.html#/Cell)

### Steps to reproduce（重现步骤）
增加右侧文案

### What is expected?（期望的结果是什么？）
左侧内容不被挤压

### What is actually happening?（实际的结果是什么？）
左侧内容被挤压了
https://img10.360buyimg.com/imagetools/jfs/t1/50223/33/22648/81198/6413c234F64905d3f/54cedff0ad6b5552.png

**Comment by yangjinjun3** [comment]
右侧输入英文，无法换行
https://img12.360buyimg.com/imagetools/jfs/t1/107404/4/38902/27263/6413d51bFa6ec2c89/045cd4d508a8f839.jpg

**Comment by oasis-cloud** [comment]
英文有空格应该可以换行
