### ISSUE TITLE
建议新增 slider 滑块组件

### ISSUE THREAD

**Issue by midday** [jdf2e/nutui-react#831]
### What problem does this feature solve?（这个功能解决的问题）
滑动输入条，用于在给定的范围内选择一个值。

### What does the proposed API look like?（期望的 API）
可以对标：
vant weapp slider：https://vant-contrib.gitee.io/vant-weapp/#/slider
ant mobile slider：https://mobile.ant.design/zh/components/slider

**Comment by AnteeHub** [comment]
在 nutui-react 中有一个 Range  组件：
https://nutui.jd.com/h5/react/1x/#/zh-CN/component/range
