### ISSUE TITLE
button组件loading没有防重复点击功能

### ISSUE THREAD

**Issue by Jairwin-L** [jdf2e/nutui-react#833]
### What problem does this feature solve?（这个功能解决的问题）
防止表单重复提交，重复的ajax请求

### What does the proposed API look like?（期望的 API）
https://nutui.jd.com/taro/react/1x/#/zh-CN/component/button

可参考antd-mobile：https://mobile.ant.design/zh/components/button

**Comment by Jairwin-L** [comment]
1、就是form提交，button有loading且不能重复点击。如果这个叫auto功能，那就是这个。
2、好的。目前loading和disabled都没这个效果，也就是会在后续版本支持是吧？

**Comment by AnteeHub** [comment]
> 1、就是form提交，button有loading且不能重复点击。如果这个叫auto功能，那就是这个。 2、好的。目前loading和disabled都没这个效果，也就是会在后续版本支持是吧？

一般业务代码中，处于请求未返回的状态时，设置按钮的 `loading` 或者 `disable` 可以简单满足需要；对于一些较快的请求返回，处理逻辑应该自行在业务代码中处理。

**为什么 UI 组件库不提供这样的能力：**

普遍来说说按钮的防抖（也就是防重复提交）的逻辑属于业务逻辑，按钮组件只提供最基本的原子能力，即点击按钮的交互功能。涉及到防抖、节流、延时响应等状态应该由开发者自行实现逻辑。
你可以在自己的项目进行二次封装，但对于通用场景的 UI 组件来说，确实而不会把这些额外的能力耦合在组件中，因为 会让组件变得臃肿。

**Comment by Jairwin-L** [comment]
理解你的意思。
**此外，我也再简单补充下相关个人阐述**：站在其他UI组件库的角度（带点对比性），可能是基于其他UI组件库有这样的能力，例如[antd-mobile](https://mobile.ant.design/zh/components/button)，觉得也是可以提供这样的能力
