### ISSUE TITLE
希望支持node14版本

### ISSUE THREAD

**Issue by longriver1012** [jdf2e/nutui-react#837]
### What problem does this feature solve?（这个功能解决的问题）
最新的版本移除了node14版本的支持，希望可以再支持下node14，目前很多项目还在使用node14的版本

### What does the proposed API look like?（期望的 API）
希望支持node14版本

**Comment by oasis-cloud** [comment]
能描述下具体遇到的问题吗

**Comment by TheWindRest** [comment]
目前使用的node版本是14.21，但是安装的时候报错了，说engine：node版本最少大于16
