### ISSUE TITLE
taro3.0 水印无法使用

### ISSUE THREAD

**Issue by yuhuashi1991** [jdf2e/nutui-react#846]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.11

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.3.0

### Browser and its version（浏览器及其版本）
小程序开发者工具调试器 没有使用chrome调试

### System and its version（系统及其版本）
MacOS13.2.1

### Taro environmental information（taro 环境信息）
Taro 3.5.10

### Reproduction link（重现链接）
[codesandbox.io](https://codesandbox.io/s/romantic-chihiro-0fquyw?file=/src/App.js)

### Steps to reproduce（重现步骤）
import { Watermark } from '@nutui/nutui-react-taro';
官方文档明显Watermark大小写拼写错误

### What is expected?（期望的结果是什么？）
水印正常显示

### What is actually happening?（实际的结果是什么？）
水印不显示

**Comment by junjun666** [comment]
您好，我们这边在taro的3.6版本weapp试了下，没有发现上述问题，不知道是不是你这边taro版本导致的呢？可以提供个demo也方便我们排查下

**Comment by yuhuashi1991** [comment]
我们找到了原因 是小程序开发者工具的调试基础库 版本导致的水印组件有问题，需要将调试基础库调到2.20.3版本以上
