### ISSUE TITLE
picker打开后闪烁，具体表现为在日期选择器中，当前时间和结束时间不停切换

### ISSUE THREAD

**Issue by Aliujiayu** [jdf2e/nutui-react#856]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.12

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
19.7.0

### Browser and its version（浏览器及其版本）
微信开发者工具

### System and its version（系统及其版本）
macOS 10.15.7

### Taro environmental information（taro 环境信息）

👽 Taro v3.6.2

  Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 19.7.0 - /usr/local/bin/node
      Yarn: 1.21.1 - /usr/local/bin/yarn
      npm: 9.5.0 - /usr/local/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2 
      @tarojs/components: 3.6.2 => 3.6.2 
      @tarojs/helper: 3.6.2 => 3.6.2 
      @tarojs/plugin-framework-react: 3.6.2 => 3.6.2 
      @tarojs/plugin-html: ^3.6.2 => 3.6.2 
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2 
      @tarojs/react: 3.6.2 => 3.6.2 
      @tarojs/runtime: 3.6.2 => 3.6.2 
      @tarojs/shared: 3.6.2 => 3.6.2 
      @tarojs/taro: 3.6.2 => 3.6.2 
      @tarojs/taro-h5: ^3.6.2 => 3.6.2 
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2 
      babel-preset-taro: 3.6.2 => 3.6.2 
      eslint-config-taro: 3.6.2 => 3.6.2 
      react: ^18.0.0 => 18.2.0 

### Reproduction link（重现链接）
[github.com/Aliujiayu/demo.git](https://github.com/Aliujiayu/demo.git)

### Steps to reproduce（重现步骤）
滑动选择时速度快点，然后不等他停下来就点确定
重新调起来的时候，就开始闪烁

### What is expected?（期望的结果是什么？）
打开picker组件后可以正常滚动，正常选择，正常复现

### What is actually happening?（实际的结果是什么？）
重新调起来的时候，就开始闪烁

**Comment by AnteeHub** [comment]
> ### NutUI scenes（nutui 场景）
> 小程序（@nutui/nutui-react-taro）
> 
> ### NutUI-react version（nutui-react 版本）
> 1.4.12
> 
> ### React version（react 版本）
> 18.0.0
> 
> ### Operating environment（运行环境）
> dev:weapp
> 
> ### Citation method（引用方式）
> npm
> 
> ### Node version（node 版本）
> 19.7.0
> 
> ### Browser and its version（浏览器及其版本）
> 微信开发者工具
> 
> ### System and its version（系统及其版本）
> macOS 10.15.7
> 
> ### Taro environmental information（taro 环境信息）
> 👽 Taro v3.6.2
> 
> Taro CLI 3.6.2 environment info: System: OS: macOS 10.15.7 Shell: 3.2.57 - /bin/bash Binaries: Node: 19.7.0 - /usr/local/bin/node Yarn: 1.21.1 - /usr/local/bin/yarn npm: 9.5.0 - /usr/local/bin/npm npmPackages: @tarojs/cli: 3.6.2 => 3.6.2 @tarojs/components: 3.6.2 => 3.6.2 @tarojs/helper: 3.6.2 => 3.6.2 @tarojs/plugin-framework-react: 3.6.2 => 3.6.2 @tarojs/plugin-html: ^3.6.2 => 3.6.2 @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2 @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2 @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2 @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2 @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2 @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2 @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2 @tarojs/react: 3.6.2 => 3.6.2 @tarojs/runtime: 3.6.2 => 3.6.2 @tarojs/shared: 3.6.2 => 3.6.2 @tarojs/taro: 3.6.2 => 3.6.2 @tarojs/taro-h5: ^3.6.2 => 3.6.2 @tarojs/webpack5-runner: 3.6.2 => 3.6.2 babel-preset-taro: 3.6.2 => 3.6.2 eslint-config-taro: 3.6.2 => 3.6.2 react: ^18.0.0 => 18.2.0
> 
> ### Reproduction link（重现链接）
> [github.com/Aliujiayu/demo.git](https://github.com/Aliujiayu/demo.git)
> 
> ### Steps to reproduce（重现步骤）
> 滑动选择时速度快点，然后不等他停下来就点确定 重新调起来的时候，就开始闪烁
> 
> ### What is expected?（期望的结果是什么？）
> 打开picker组件后可以正常滚动，正常选择，正常复现
> 
> ### What is actually happening?（实际的结果是什么？）
> 重新调起来的时候，就开始闪烁

用你的示例代码跑了一下测试，发现用了 redux + immutable，滑动 DatePicker 的过程中卡顿感明显，确实有闪烁的情况。但原因应该是你使用 redux dispatch 的计算过程较为复杂，阻塞了 DatePicker 内部的 `updateChooseValueCustmer` 方法导致的。不使用 redux 的情况下并没有出现这个问题。
