### ISSUE TITLE
自定义tabbar 无法显示icon

### ISSUE THREAD

**Issue by ReinhardChen93** [jdf2e/nutui-react#857]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.12

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.0

### Browser and its version（浏览器及其版本）
111.0.5563.111（正式版本） （64 位）

### System and its version（系统及其版本）
win10

### Taro environmental information（taro 环境信息）
  Taro CLI 3.4.13 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Users\60193\AppData\Roaming\npm\yarn.CMD
      npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD

### Reproduction link（重现链接）
[github.com](https://github.com/ReinhardChen93/nuiui-template-taro3.0.git)

### Steps to reproduce（重现步骤）
npm run build:weapp -- --watch

### What is expected?（期望的结果是什么？）
自定义tabbar显示出icon

### What is actually happening?（实际的结果是什么？）
自定义tabbar无法显示出icon

**Comment by oasis-cloud** [comment]
自定义 TabBar 比较特殊，要编译为自定义组件给小程序调用。因此会有样式隔离。

配置一下 addGlobalClass 即可：
<img width="467" alt="image" src="https://user-images.githubusercontent.com/12181600/228404784-d760a742-4c64-4139-83aa-2124bb85965b.png">

https://github.com/NervJS/taro/issues/11060
