### ISSUE TITLE
【样式问题】移动端元素如果添加了 cursor: pointer 属性，点击会产生蓝色色块。

### ISSUE THREAD

**Issue by wanpan11** [jdf2e/nutui-react#862]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.12

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18

### Browser and its version（浏览器及其版本）
 106.0.5231.2

### System and its version（系统及其版本）
win11

### Reproduction link（重现链接）
[nutui.jd.com](https://nutui.jd.com/h5/react/1x/demo.html#/Button)

### Steps to reproduce（重现步骤）
1、开始移动端模式
2、找到 body 标签
3、去掉 -webkit-tap-highlight-color 属性

### What is expected?（期望的结果是什么？）
移动端点击元素不显示异常样式

### What is actually happening?（实际的结果是什么？）
移动端点击元素有 cursor: pointer 属性的显示了异常样式。
官方文档并没有提示这一点，希望可以加个提示 添加 -webkit-tap-highlight-color 可处理该问题。

![image](https://user-images.githubusercontent.com/38714194/228739668-2b1ca878-0366-43ce-ad2f-4df2f7dc5e25.png)
![image](https://user-images.githubusercontent.com/38714194/228740528-673bc217-4385-4331-8903-6a0f260233f6.png)

**Comment by AnteeHub** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/CSS/-webkit-tap-highlight-color

**Comment by wanpan11** [comment]
> 非标准属性需要斟酌一下 https://developer.mozilla.org/zh-CN/docs/Web/CSS/-webkit-tap-highlight-color

好的 我今天用Button Cell 组件时发现了这个问题。点击后会有蓝色的背景色块😂😂
