### ISSUE TITLE
input在dialog中聚焦之后马上失焦，使用原生/taro自带input没有这个问题

### ISSUE THREAD

**Issue by Penguin-Lin** [jdf2e/nutui-react#864]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.13

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.15.0

### Browser and its version（浏览器及其版本）
微信开发者工具

### System and its version（系统及其版本）
win10

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.0

  Taro CLI 3.6.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Node: 16.15.0 - D:\nodejs\16.15.0\node.EXE
      Yarn: 1.22.17 - D:\nodejs\node_global\yarn.CMD
      npm: 8.5.5 - D:\nodejs\16.15.0\npm.CMD

### Reproduction link（重现链接）
[github.com](https://github.com/Penguin-Lin/nutui-react-bug)

### Steps to reproduce（重现步骤）
1、pnpm i  
2、pnpm run dev:weapp
3、打开页面pages/index/index
4、点击获取验证码  出现弹窗  在弹窗内的input输入框中聚焦  但聚焦后马上失焦  原因不明  但是使用原生input和taro提供的input就没有这个问题

### What is expected?（期望的结果是什么？）
弹窗内的input输入框中聚焦  不要自动失焦

### What is actually happening?（实际的结果是什么？）
点击获取验证码  出现弹窗  在弹窗内的input输入框中聚焦  但聚焦后马上失焦  原因不明  但是使用原生input和taro提供的input就没有这个问题

**Comment by oasis-cloud** [comment]
![image](https://user-images.githubusercontent.com/12181600/229404080-3fb41397-0215-460e-9f90-e10bf70c742a.png)
建议你将弹框的封装提取到 Input slotButton 外面，因为它会导致外面的 Input 组件重新渲染，从而导致内部的Input失去焦点。
![image](https://user-images.githubusercontent.com/12181600/229404705-d6884cf2-58a9-4582-9f52-4aafc8fe79a1.png)
