### ISSUE TITLE
Tabbar 组件在微信中用于自定义 tabbar 时，icon不展示

### ISSUE THREAD

**Issue by doujianyu** [jdf2e/nutui-react#879]
**NutUI scenes**（nutui 场景）
weapp（@nutui/nutui-react-taro）

NutUI-react version（nutui-react-taro 版本）
^1.4.7

React version（react 版本）
18.2.0

Operating environment（运行环境）
dev:weapp

Citation method（引用方式）
npm

Node version（node 版本）
16.14.2

Browser and its version（浏览器及其版本）
微信开发者工具 & 微信

System and its version（系统及其版本）
macOS & iOS

Steps to reproduce（重现步骤）

使用 tabbar 组件，做自定义tabbar时不展示icon

What is expected?（期望的结果是什么？）
可以正常展示

What is actually happening?（实际的结果是什么？）
不能展示

**Comment by vinneli** [comment]
> 你好 @doujianyu, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/s/nutui-react-p6ppsm) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

我也遇到同样的问题，在页面中不使用 Icon，自定义tabbar的 Icon 正常，一旦页面中使用 Icon，tabbar 里的 Icon 就不显示了。
