### ISSUE TITLE
图片预览-官方demo问题

### ISSUE THREAD

**Issue by JackYumg** [jdf2e/nutui-react#887]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.4.14

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16

### Browser and its version（浏览器及其版本）
111.0.5563.147

### System and its version（系统及其版本）
window11

### Reproduction link（重现链接）
[nutui.jd.com/taro/react/1x/](https://nutui.jd.com/taro/react/1x/#/zh-CN/component/imagepreview)

### Steps to reproduce（重现步骤）
点击”缩率图切换“里面的小图，小图列表展示在预览的上面了

### What is expected?（期望的结果是什么？）
正常展示

### What is actually happening?（实际的结果是什么？）
非正常

![image](https://user-images.githubusercontent.com/62476270/230341500-934667b8-66a8-486d-8f2f-d8faa9ebf27b.png)

**Comment by oasis-cloud** [comment]
是这样设计的，不然点不到切换的缩略图
