### ISSUE TITLE
Calendar小程序和H5版本中日历增加某些日期不可选的功能，以及开放自定义设置日期选中的样式

### ISSUE THREAD

**Issue by David19910306** [jdf2e/nutui-react#896]
### What problem does this feature solve?（这个功能解决的问题）
能够解决在某些特定时间，日期不可选中的功能，比如在选择快递派送选择日期的时候，节假日不能选择等类似需求。

### What does the proposed API look like?（期望的 API）
开放一个属性【如：format】来允许用户自定义修改日期选中的样式；以及开放设置当前日期是否点击可选的属性。或者是增加beforeSelect的属性让用户来自行判断选中之前的逻辑，符合逻辑则选中，不符合逻辑则设置不可点击或者是不可选中

**Comment by David19910306** [comment]
您的来信已收到，谢谢。。。。

**Comment by JingY7** [comment]
Calendar是否可以不用指定日期，可直接向上滚动，也就是查看并选择历史日期，希望可以加入到props中 @xiaoyatong

**Comment by Me-UserName** [comment]
+1

**Comment by xiaoyatong** [comment]
> https://github.com/jdf2e/nutui-react/issues/896#issuecomment-1506405482

这个能帮忙发一个示意图么

**Comment by David19910306** [comment]
您的来信已收到，谢谢。。。。
