### ISSUE TITLE
希望价格可以加一个划线价格一般这个很常用

### ISSUE THREAD

**Issue by wangyuan0108** [jdf2e/nutui-react#909]
### What problem does this feature solve?（这个功能解决的问题）
直接用多种样式的价格

### What does the proposed API look like?（期望的 API）
taro中使用

**Comment by oasis-cloud** [comment]
规划到 2.0 版本中

**Comment by wangyuan0108** [comment]
> 规划到 2.0 版本中

好的，希望2.0快快到来

**Comment by xiaoyatong** [comment]
> > 规划到 2.0 版本中
> 
> 好的，希望2.0快快到来

已把price的优先级 提高~

**Comment by wangyuan0108** [comment]
> > > 规划到 2.0 版本中
> > 
> > 
> > 好的，希望2.0快快到来
> 
> 已把price的优先级 提高~

ok @xiaoyatong
