### ISSUE TITLE
Dialog h5下onOk onCancel不触发

### ISSUE THREAD

**Issue by xiaof520** [jdf2e/nutui-react#922]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.5.0

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18

### Browser and its version（浏览器及其版本）
edge

### System and its version（系统及其版本）
windows

### Reproduction link（重现链接）
[nutui.jd.com/taro/react/1x/](https://nutui.jd.com/taro/react/1x/#/zh-CN/component/dialog)

### Steps to reproduce（重现步骤）
1

### What is expected?（期望的结果是什么？）
正常

### What is actually happening?（实际的结果是什么？）
异常

**Comment by oasis-cloud** [comment]
你是怎么验证没有触发 onOk 和 onCancel 的？你提供的 nutui 包名和问题复现链接对应不上

**Comment by xiaoyatong** [comment]
升级2.x版本，onOk已变更名
