### ISSUE TITLE
Elevator 快速滑动之后，频繁闪动

### ISSUE THREAD

**Issue by AaronDaiR** [jdf2e/nutui-react#947]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.4.14

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
v16.17.0

### Browser and its version（浏览器及其版本）
正常

### System and its version（系统及其版本）
正常

### Taro environmental information（taro 环境信息）
Taro v3.6.5

### Reproduction link（重现链接）
[codesandbox.io/s/09yj90](https://codesandbox.io/s/09yj90?file=/src/App.vue)

### Steps to reproduce（重现步骤）
正常引入快速滑动

### What is expected?（期望的结果是什么？）
不要频闪

### What is actually happening?（实际的结果是什么？）
频闪

### Remarks（补充说明）
下面放置一个视频

**Comment by AaronDaiR** [comment]
https://user-images.githubusercontent.com/53423109/234178530-16d2111f-ca2c-4199-bbe6-a250c103284c.mp4

**Comment by AaronDaiR** [comment]
<Elevator
        indexList={dataList}
        isSticky
        height={'500px'}
        titleHeight={70}
        spaceHeight={70}
        onClickItem={(key: string, item: any) => onClickItem(key, item)}
        onClickIndex={(key: string) => onClickIndex(key)}
      />

**Comment by AaronDaiR** [comment]
https://user-images.githubusercontent.com/53423109/234179594-82118903-0e1f-492d-adbe-4df80e951e9f.mp4

多重复几次 必现

**Comment by AaronDaiR** [comment]
![image](https://user-images.githubusercontent.com/53423109/234180127-0d599844-c3e6-4c23-9606-8898ddb522e4.png)
 demo也是必现的，麻烦尽快修复一下， 影响用户使用体验了

**Comment by xiaoyatong** [comment]
周三发版。
