### ISSUE TITLE
Elevator 电梯楼层 支持 右侧索引是否需要

### ISSUE THREAD

**Issue by AaronDaiR** [jdf2e/nutui-react#948]
### What problem does this feature solve?（这个功能解决的问题）
如果地址目录比较少的情况下，不希望有右侧索引。

需不需要通过给 用户来 传值使用，可以默认 需要。

### What does the proposed API look like?（期望的 API）
<Elevator 
   isSelect={false | true}
/>
类似这样的。

**Comment by AaronDaiR** [comment]
电梯区域 需不需要 标题栏也可以 支持默认 传入吧， 有些时候 地址少的时候 并不需要 地址栏；

如果不要的话，内部可以处理一下

**Comment by xiaoyatong** [comment]
我们近期在2.0中增加是否展示右侧导航区域的props设置。

**Comment by xiaoyatong** [comment]
https://github.com/jdf2e/nutui-react/pull/1006
