### ISSUE TITLE
CellGroup可以支持不显示下边线的属性

### ISSUE THREAD

**Issue by wangyuan0108** [jdf2e/nutui-react#951]
### What problem does this feature solve?（这个功能解决的问题）
现在是每一个cell下面都有一个边线

### What does the proposed API look like?（期望的 API）
border

**Comment by irisSong** [comment]
后续2.0版本支持

**Comment by wangyuan0108** [comment]
> 后续2.0版本支持

好的期待。2.0版本什么时间上哇

**Comment by xiaoyatong** [comment]
> > 后续2.0版本支持
> 
> 好的期待。2.0版本什么时间上哇

方便同步一下项目中使用的组件吗，现在2.0在发布alpha阶段，目前支持20+组件的升级了。
cell这个会在今日的发版中发布。

**Comment by wangyuan0108** [comment]
> > > 后续2.0版本支持
> > 
> > 
> > 好的期待。2.0版本什么时间上哇
> 
> 方便同步一下项目中使用的组件吗，现在2.0在发布alpha阶段，目前支持20+组件的升级了。 cell这个会在今日的发版中发布。

那我用的是还是1.5.3版本，2.0没有发布稳定版本，项目中没有使用
