### ISSUE TITLE
nutui（小程序）运行H5环境下swiper组件报错

### ISSUE THREAD

**Issue by jiangjin3323** [jdf2e/nutui-react#952]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.5.1

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.16.0

### Browser and its version（浏览器及其版本）
Chrome (112.0.5615.137)

### System and its version（系统及其版本）
MacOS(13.3.1)

### Reproduction link（重现链接）
[github.com](https://github.com/jiangjin3323/nutui-swiper-bug)

### Steps to reproduce（重现步骤）
运行代码即可见到。

### What is expected?（期望的结果是什么？）
无报错信息。

### What is actually happening?（实际的结果是什么？）
https://raw.githubusercontent.com/jiangjin3323/nutui-swiper-bug/main/src/static/WechatIMG59.png
报错

关键词：“ paginationBgColor ” , “ paginationbgcolor ” , “ catchMove`  ”

**Comment by oasis-cloud** [comment]
taro 项目需要使用 @nutui/nutui-react-taro

**Comment by jiangjin3323** [comment]
最新版已解决此问题。

**Comment by CCCzKen** [comment]
> taro 项目需要使用 @nutui/nutui-react-taro

我就是用这个，同样的报错

**Comment by jiangjin3323** [comment]
> > taro 项目需要使用 @nutui/nutui-react-taro
> 
> 我就是用这个，同样的报错

你升级为最新版本就没有此报错了。

**Comment by CCCzKen** [comment]
> > > taro 项目需要使用 @nutui/nutui-react-taro
> > 
> > 
> > 我就是用这个，同样的报错
> 
> 你升级为最新版本就没有此报错了。

现在已经是 "@nutui/nutui-react-taro": "^1.5.5"

**Comment by jiangjin3323** [comment]
> > > > taro 项目需要使用 @nutui/nutui-react-taro
> > > 
> > > 
> > > 我就是用这个，同样的报错
> > 
> > 
> > 你升级为最新版本就没有此报错了。
> 
> 现在已经是 "@nutui/nutui-react-taro": "^1.5.5"

1.5.2无此问题。
