### ISSUE TITLE
button按钮高度和行高不一致

### ISSUE THREAD

**Issue by Tom-front** [jdf2e/nutui-react#954]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
2.0.0-alpha.2

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
v16.20.0

### Browser and its version（浏览器及其版本）
112.0.5615.138

### System and its version（系统及其版本）
window11

### Taro environmental information（taro 环境信息）
 Taro v3.6.2

### Reproduction link（重现链接）
[nutui.jd.com/taro/react/1x/](https://nutui.jd.com/taro/react/1x/#/zh-CN/component/button)

### Steps to reproduce（重现步骤）
应用默认button组件

### What is expected?（期望的结果是什么？）
button按钮中的文字，上下居中

### What is actually happening?（实际的结果是什么？）
button按钮中的文字，上下不居中

### Remarks（补充说明）
–nutui-button-default-height ：默认值为 38px；
–nutui-button-default-line-height：默认值为36px

**Comment by oasis-cloud** [comment]
default 类型的按钮带 2px 的边框，所以行高设置的是 36px
