### ISSUE TITLE
NutUI 1.5.2 Swiper 无法滚动，1.5.1 正常使用

### ISSUE THREAD

**Issue by smithyj** [jdf2e/nutui-react#957]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.5.2

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
微信小程序

### System and its version（系统及其版本）
MacOS(13.4)

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.5

  Taro CLI 3.6.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    npmPackages:
      @tarojs/cli: ^3.6.5 => 3.6.5 
      @tarojs/components: ^3.6.5 => 3.6.5 
      @tarojs/helper: ^3.6.5 => 3.6.5 
      @tarojs/plugin-framework-react: ^3.6.5 => 3.6.5 
      @tarojs/plugin-html: ^3.6.5 => 3.6.5 
      @tarojs/plugin-platform-alipay: ^3.6.5 => 3.6.5 
      @tarojs/plugin-platform-h5: ^3.6.5 => 3.6.5 
      @tarojs/plugin-platform-jd: ^3.6.5 => 3.6.5 
      @tarojs/plugin-platform-qq: ^3.6.5 => 3.6.5 
      @tarojs/plugin-platform-swan: ^3.6.5 => 3.6.5 
      @tarojs/plugin-platform-tt: ^3.6.5 => 3.6.5 
      @tarojs/plugin-platform-weapp: ^3.6.5 => 3.6.5 
      @tarojs/react: ^3.6.5 => 3.6.5 
      @tarojs/runtime: ^3.6.5 => 3.6.5 
      @tarojs/shared: ^3.6.5 => 3.6.5 
      @tarojs/taro: ^3.6.5 => 3.6.5 
      @tarojs/taro-loader: ^3.6.5 => 3.6.5 
      @tarojs/webpack5-runner: ^3.6.5 => 3.6.5 
      babel-preset-taro: ^3.6.5 => 3.6.5 
      eslint-config-taro: ^3.6.5 => 3.6.5 
      react: ^18.2.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 5.0.2

### Reproduction link（重现链接）
[https://github.com/smithyj/zgy-wxapp/tree/feature/bug](https://github.com/smithyj/zgy-wxapp/tree/feature/bug)

### Steps to reproduce（重现步骤）
# 问题描述

- 现在这个项目是可以正常运行
- 但是把版本升级到 nutui 升级到 1.5.2 后就没用了，Swiper 异常
-

# 问题解决

- 无法解决，期望大佬们帮忙看看

### What is expected?（期望的结果是什么？）
正常运行

### What is actually happening?（实际的结果是什么？）
无法正常运行

**Comment by irisSong** [comment]
已修改，可更新到这个版本 @nutui/nutui-react-taro@1.5.3-beta.0
