### ISSUE TITLE
需要 Tabs 支持横向滑动切换 Tab

### ISSUE THREAD

**Issue by hughlv** [jdf2e/nutui-react#965]
### What problem does this feature solve?（这个功能解决的问题）
在手机上常见的 App，比如大众点评等，在有 Tabs 的页面基本都支持左右滑动切换 Tab。希望能够支持以提升使用体验。

### What does the proposed API look like?（期望的 API）
为 Tabs 添加 boolean 类型属性 swipeable，缺省为 true。

**Comment by oasis-cloud** [comment]
可以采用 swiper + tabs 的组合实现

**Comment by David19910306** [comment]
> 可以采用 swiper + tabs 的组合实现

想问下，在swiper + tabs实现tabs界面的手势监听切换时，在手势左右滑动的过程中，能否禁止tab页面的上下滚动监听？

**Comment by David19910306** [comment]
您的来信已收到，谢谢。。。。
