### ISSUE TITLE
Picker DatePicker 显示空白

### ISSUE THREAD

**Issue by ziu96** [jdf2e/nutui-react#966]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.5.3

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
14.21.3

### Browser and its version（浏览器及其版本）
Chrome(106.0.5249.119)

### System and its version（系统及其版本）
win 10

### Taro environmental information（taro 环境信息）
👽 Taro v3.6.5

  Taro CLI 3.6.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD  
    npmPackages:
      @tarojs/cli: 3.6.4 => 3.6.4
      @tarojs/components: 3.6.4 => 3.6.4
      @tarojs/helper: 3.6.4 => 3.6.4
      @tarojs/plugin-framework-react: 3.6.4 => 3.6.4  
      @tarojs/plugin-html: ^3.6.5 => 3.6.5
      @tarojs/plugin-platform-alipay: 3.6.4 => 3.6.4  
      @tarojs/plugin-platform-h5: 3.6.4 => 3.6.4      
      @tarojs/plugin-platform-jd: 3.6.4 => 3.6.4      
      @tarojs/plugin-platform-qq: 3.6.4 => 3.6.4      
      @tarojs/plugin-platform-swan: 3.6.4 => 3.6.4    
      @tarojs/plugin-platform-tt: 3.6.4 => 3.6.4      
      @tarojs/plugin-platform-weapp: 3.6.4 => 3.6.4   
      @tarojs/react: 3.6.4 => 3.6.4
      @tarojs/runtime: 3.6.4 => 3.6.4
      @tarojs/shared: 3.6.4 => 3.6.4
      @tarojs/taro: 3.6.4 => 3.6.4
      @tarojs/webpack5-runner: 3.6.4 => 3.6.4
      babel-preset-taro: 3.6.4 => 3.6.4
      eslint-config-taro: 3.6.4 => 3.6.4
      react: ^18.0.0 => 18.2.0

### Reproduction link（重现链接）
[nutui.jd.com/taro/react/1x/](https://nutui.jd.com/taro/react/1x/#/zh-CN/component/datepicker)

### Steps to reproduce（重现步骤）
连接中的第一个demo
在小程序中 运行
查看编译后代码  picker-view-column  样式宽度为0
小程序版本 2.22.1
![image](https://user-images.githubusercontent.com/52490940/236147019-1dcbf11b-fcab-4790-9c7b-1dbc1b35d9f9.png)

### What is expected?（期望的结果是什么？）
修复该Bug 正常显示

### What is actually happening?（实际的结果是什么？）
显示空白

**Comment by xiaoyatong** [comment]
麻烦您给一下报错的demo，目前链接中的是可以运行的。

**Comment by ziu96** [comment]
> 麻烦您给一下报错的demo，目前链接中的是可以运行的。

找到原因了 是我 app.scss 有一个污染了 这个样式
