### ISSUE TITLE
v1.5.3 textarea 组件报错，导致页面白屏

### ISSUE THREAD

**Issue by smithyj** [jdf2e/nutui-react#976]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.5.3

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.14.2

### Browser and its version（浏览器及其版本）
Chrome(113.0.5672.63)

### System and its version（系统及其版本）
MacOS(13.4)

### Reproduction link（重现链接）
[github.com/smithyj/nutui.git](https://github.com/smithyj/nutui.git)

### Steps to reproduce（重现步骤）
1、`pnpm start`
2、微信小程序开发者工具打开 `dist/weapp`
3、页面报错
4、把 TextArea 组件禁用就恢复正常了

### What is expected?（期望的结果是什么？）
正常渲染

### What is actually happening?（实际的结果是什么？）
报错，页面【pages/home/index]错误:
 TypeError: (0 , r(...).withNaming) is not a function

**Comment by smithyj** [comment]
1.5.1 版本正常

**Comment by smithyj** [comment]
1.5.2 Swiper 组件有问题，所以 1.5.3 解决了 Swiper 组件问题，但是又出现了 TextArea 组件问题

**Comment by smithyj** [comment]
@dushoujun @loveky @snandy @beanlee

**Comment by oasis-cloud** [comment]
可以先在最小的项目上测试一下，比较方便定位问题

**Comment by smithyj** [comment]
> 可以先在最小的项目上测试一下，比较方便定位问题

已经是最小项目了

**Comment by eiinu** [comment]
没能复现错误。
![image](https://user-images.githubusercontent.com/44915689/236984012-41c3af69-59bf-45ef-a2f7-ffb4be65b113.png)
报错提示中的 withNaming 是 `@bem-react/classname` 包中的方法，它在最近更新了 1.6.0 版本，有可能是这个版本导致的问题。
你可以尝试先锁定这个版本号，在 package.json 中添加：
```
"resolutions": {
    "@bem-react/classname": "1.5.12"
  },
```
删除所有依赖和 lock 文件后重新安装依赖。
