### ISSUE TITLE
NutUI组件事件无法触发

### ISSUE THREAD

**Issue by seanlsr** [jdf2e/nutui-react#978]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui-react）

### NutUI-react version（nutui-react 版本）
1.5.3

### React version（react 版本）
18.2.0

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
19.6.0

### Browser and its version（浏览器及其版本）
Google Chrome 版本 113.0.5672.64（正式版本） （64 位）

### System and its version（系统及其版本）
Windows 11 专业工作站版 22621.1555

### Reproduction link（重现链接）
[test.yooetea.com/login/index](https://test.yooetea.com/login/index)

### Steps to reproduce（重现步骤）
组件事件无法触发，如 Button的onClick

### What is expected?（期望的结果是什么？）
组件事件能触发

### What is actually happening?（实际的结果是什么？）
组件事件无法触发，如 Button的onClick

**Comment by seanlsr** [comment]
初充Taro版本信息：
Taro CLI 3.6.6 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 19.6.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @tarojs/cli: 3.6.6 => 3.6.6
      @tarojs/components: 3.6.6 => 3.6.6
      @tarojs/helper: 3.6.6 => 3.6.6
      @tarojs/plugin-framework-react: 3.6.6 => 3.6.6
      @tarojs/plugin-html: ^3.6.6 => 3.6.6
      @tarojs/plugin-platform-h5: 3.6.6 => 3.6.6
      @tarojs/plugin-platform-weapp: 3.6.6 => 3.6.6
      @tarojs/react: 3.6.6 => 3.6.6
      @tarojs/runtime: 3.6.6 => 3.6.6
      @tarojs/shared: 3.6.6 => 3.6.6
      @tarojs/taro: 3.6.6 => 3.6.6
      @tarojs/webpack5-runner: 3.6.6 => 3.6.6
      babel-preset-taro: 3.6.6 => 3.6.6
      eslint-config-taro: 3.6.6 => 3.6.6
      react: ^18.2.0 => 18.2.0

**Comment by oasis-cloud** [comment]
可以提供一下最小可复现 demo

**Comment by seanlsr** [comment]
> test.yooetea.com/login/index

**Comment by oasis-cloud** [comment]
能不能提供一份可复现的源代码？

**Comment by oasis-cloud** [comment]
taro 项目下使用 @nutui/nutui-react-taro ，不要使用 @nutui/nutui-react

**Comment by seanlsr** [comment]
"dependencies": {
    "@babel/runtime": "^7.19.0",
    "@nutui/nutui-biz": "^1.0.0-beta.2",
    "@tarojs/components": "3.6.6",
    "@tarojs/helper": "3.6.6",
    "@tarojs/plugin-framework-react": "3.6.6",
    "@tarojs/plugin-html": "^3.6.6",
    "@tarojs/plugin-platform-h5": "3.6.6",
    "@tarojs/plugin-platform-weapp": "3.6.6",
    "@tarojs/react": "3.6.6",
    "@tarojs/runtime": "3.6.6",
    "@tarojs/shared": "3.6.6",
    "@tarojs/taro": "3.6.6",
    "compressorjs": "^1.1.1",
    "cross-env": "^7.0.3",
    "feign-boot-starter": "^1.2.0",
    "feign-boot-tarojs-starter": "^2.0.1",
    "fengwuxp-common-utils": "^1.0.1",
    "fengwuxp-declarative-command": "^1.0.3",
    "fengwuxp-declarative-router-adapter": "^1.0.4",
    "fengwuxp-declarative-storage-adapter": "^1.0.1",
    "fengwuxp-taro-starter": "^2.0.0",
    "fengwuxp-tarojs-router": "2.0.1",
    "fengwuxp-typescript-feign": "^1.2.3",
    "html2canvas": "^1.4.1",
    "immer": "^9.0.15",
    "oak-common": "^1.0.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.19.1",
    "@craco/craco": "^7.1.0",
    "@nutui/icons-react": "^0.0.1-beta.8",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.7",
    "@tarojs/cli": "3.6.6",
    "@tarojs/webpack5-runner": "3.6.6",
    "@types/react": "^18.0.21",
    "@types/react-dom": "^18.0.6",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "@typescript-eslint/parser": "^5.20.0",
    "babel-loader": "^8.2.5",
    "babel-plugin-import": "^1.13.5",
    "babel-plugin-lodash": "^3.3.4",
    "babel-preset-taro": "3.6.6",
    "eslint": "^8.12.0",
    "eslint-config-taro": "3.6.6",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "react-refresh": "^0.14.0",
    "sass": "^1.62.1",
    "stylelint": "^14.4.0",
    "taro-plugin-string-style": "^1.0.3",
    "typescript": "^4.9.4",
    "vite-plugin-style-import": "^2.0.0",
    "webpack": "^5.75.0"
  }

> taro 项目下使用 @nutui/nutui-react-taro ，不要使用 @nutui/nutui-react
