### ISSUE TITLE
input 组件，设置clearable后，在手机上功能异常，点击清除按钮，并不能清除输入框中的内容

### ISSUE THREAD

**Issue by i-smile** [jdf2e/nutui-react#981]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-react-taro）

### NutUI-react version（nutui-react 版本）
1.5.3

### React version（react 版本）
18.0.0

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.17.0

### Browser and its version（浏览器及其版本）
Chrome(112.0.5615.137)

### System and its version（系统及其版本）
IOS(14.4.1 )

### Taro environmental information（taro 环境信息）
Taro v3.6.4

  Taro CLI 3.6.4 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/components: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/extend: ^3.6.5 => 3.6.5 
      @tarojs/helper: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/plugin-framework-react: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/plugin-html: ^3.6.5-alpha.1 => 3.6.5 
      @tarojs/plugin-platform-alipay: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/plugin-platform-h5: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/plugin-platform-jd: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/plugin-platform-qq: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/plugin-platform-swan: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/plugin-platform-tt: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/plugin-platform-weapp: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/react: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/runtime: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/shared: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/taro: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      @tarojs/webpack5-runner: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      babel-preset-taro: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      eslint-config-taro: 3.6.5-alpha.1 => 3.6.5-alpha.1 
      react: ^18.0.0 => 18.2.0 
    npmGlobalPackages:
      typescript: 4.9.4

### Reproduction link（重现链接）
[codesandbox.io/s/09yj90](https://codesandbox.io/s/09yj90?file=/src/App.vue/地址是假的)

### Steps to reproduce（重现步骤）
给input组件添加 clearable 属性。
点击清除按钮，并不能清除输入框中的内容，而是闪烁一下。

### What is expected?（期望的结果是什么？）
能正常清除输入框中的内容。

### What is actually happening?（实际的结果是什么？）
输入框闪烁，失去焦点，内容并未清除。

### Remarks（补充说明）
我的手机是iPhone12，不知道其他手机表现如何。

在微信开发者工具上是可以清除内容的。

微信版本 8.0.37

**Comment by zmm2tysu** [comment]
@oasis-cloud 
pacakge version: 1.5.7
发现两个新的问题
1. clearSize为20，已经足够大了，但是安卓机上非常难点，苹果机上很好点击触发
2. 苹果机iphonexs ，点击后键盘收起并且好像提交了表单，弹出苹果原生的存储密码，如下

https://github.com/jdf2e/nutui-react/assets/20849786/63f127cd-5364-4f62-8e55-6e874446dab0

**Comment by zmm2tysu** [comment]
这个是安卓的录屏

`<Input clearable clearSize={20} />`

https://github.com/jdf2e/nutui-react/assets/20849786/08e0b018-cf24-4e55-9a27-6c0954e8683b
