### ISSUE TITLE
Tabs组件使用自定义标签栏后Tabs.TabPane数量多不会滚动

### ISSUE THREAD

**Issue by Me-UserName** [jdf2e/nutui-react#998]
### What problem does this feature solve?（这个功能解决的问题）
2.0.0-alpha.7版本中，Tabs组件使用自定义标签栏后Tabs.TabPane数量多不会滚动
Tabs.TabPane的title中文超过4个汉字就会变形，虽然nutui-tabs-horizontal-titles-item-min-width可以设置，但是希望根据title宽度自适应

### What does the proposed API look like?（期望的 API）
No

**Comment by oasis-cloud** [comment]
可以设置 nut-tabs__titles-item 的 min-width 或者是设置 flex:none

**Comment by oasis-cloud** [comment]
通过 title 属性设置自定义的标题，需要自己控制样式，建议不要直接 copy 组件带的样式

**Comment by hopelynd** [comment]
### 解决
查看源码发现如果要让他滚动需要给Tabs 设置一个name。  
### 原因
查看源码，发现如果没有name scrollIntoView 方法会直接返回，不会执行后续的逻辑  
![image](https://github.com/jdf2e/nutui-react/assets/135810028/18c0f68c-515d-4b23-8c56-68e6c87ea35b)
